### ISSUE TITLE
Should QueryResults extend Iterable rather than Iterator?

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/google-cloud-java#101]
If [`QueryResults<T>`](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/datastore/QueryResults.html) extended `Iterable<T>` rather than `Iterator<T>` then it could be used in a for-each loop:

``` java
QueryResults<Entity> results = datastore.run(query);
for (Entity result : results) {...}
```

However, this is potentially confusing, because the `Iterable` interface implies that the result can be iterated more than once, so we would either have to document that an attempt to do so will fail, or make it so that every time you call `iterator()` a new query is issued. Neither of these is very desirable, so perhaps we should just add a note to `QueryResults` that heads off this obvious question that users are going to ask.

**Comment by garrettjonesgoogle** [comment]
No one else seems to have chimed in after a year and a half - closing this out.
