### ISSUE TITLE
Update to the next datastore emulator script version

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#1014]
This emulator uses the same URL structure as the Cloud Datastore.  Because `gcloud-java` depends on the [google-cloud-datastore](https://github.com/GoogleCloudPlatform/google-cloud-datastore/tree/master/java) client, we need to wait until the client updates to use a variable to decide when to append  "/datastore" for localhost URLs. (/cc @pcostell)

There are a couple related changes that need to be made:

* Update the version of the google cloud datastore client we depend on.
* The name of the script & folder will change from `gcd` to `cloud-datastore-emulator`.  We should make the necessary updates to accommodate this change.
* We should also change the logic that checks for a locally-installed emulator to check for major/minor version updates (but not build).  Right now, we do not check version (besides ensuring that the script is for v1beta3).
* Ensure the "gcd-emulator" version will be reported the same way as before by the gcloud SDK.

**Comment by mziccard** [comment]
Fixed in #1169
