### ISSUE TITLE
Support customer-supplied encryption keys in Storage

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#1037]
Support for customer-supplied encryption keys was added in storage and we should support it as well.

How to use such keys is documented [here](https://cloud.google.com/storage/docs/encryption#customer-supplied). Fields added to a blob are documented [here](https://cloud.google.com/storage/docs/json_api/v1/objects#customerEncryption).

**Comment by omaray** [comment]
@mziccard, does this work still need to be done? Or was it covered in a PR?

**Comment by mziccard** [comment]
There's #1236 open to fix this. I want to add more tests before merging it.
