### ISSUE TITLE
We probably don't need both KeyFactory and Key.Builder

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/google-cloud-java#104]
You can make a Key either using [Key.Builder](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/datastore/Key.Builder.html) or using [KeyFactory](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/datastore/KeyFactory.html). KeyFactory can also be used to make an IncompleteKey. I suggest that we don't really need `Key.Builder` or `IncompleteKey.Builder` and we could remove them in favour of just KeyFactory.

**Comment by garrettjonesgoogle** [comment]
This is stale, closing it out.
