### ISSUE TITLE
skipLeadingRows is long for external tables but integer for load jobs

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#1044]
I believe this changed recently.

The `skipLeadingRows` field takes a long value when creating an external table (see [docs](https://cloud.google.com/bigquery/docs/reference/v2/tables#externalDataConfiguration.googleSheetsOptions.skipLeadingRows)). Instead, `skipLeadingRows` in load jobs takes an integer value (see [docs](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load.skipLeadingRows)). Why this difference? Load jobs [can take files up to 5TB](https://cloud.google.com/bigquery/quota-policy#import) so in principle there is the chance that users might want to skip more than Integer.MAX_INT rows.

**Comment by andreamlin** [comment]
Opened an internal changelist #170272287 to switch the API's internal proto definition for the load job skipLeadingRows to type int64.

**Comment by andreamlin** [comment]
The types are defined by the BigQuery API, and the API producer is hesitant to change protobuf field types in case of backwards-compatibility issues.

Closing this issue for now.
