### ISSUE TITLE
Fix logging class names

### ISSUE THREAD

**Issue by shinfan** [GoogleCloudPlatform/google-cloud-java#1047]
The logging class name contains a "v2" suffix which is inconsistent with other APIs (pubsub in particular). We can fix this issue by:
1. Contact the logging team to fix the name in the proto.
2. Override the name in the generation phase.

**Comment by garrettjonesgoogle** [comment]
Provisionally marking as 'blocking GA'.

**Comment by lesv** [comment]
Option 2 is recommended.
