### ISSUE TITLE
Add support for the App Engine Admin API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-java#1052]
We have an Admin API (service management) for App Engine here:
https://cloud.google.com/appengine/docs/admin-api/reference/rest/

It's a pretty basic CRUD / REST style API, but it would be great to have wrappers that make it easier to use.

**Comment by mziccard** [comment]
Thanks for sharing this. Any idea when a `v1` will be available?

**Comment by JustinBeckwith** [comment]
It's coming in the next 2-3 months.  I think it's mostly going to be backwards compatible.

**Comment by garrettjonesgoogle** [comment]
Requests for supporting new clients are tracked internally. I'm going to close out this issue.
