### ISSUE TITLE
Consider adding a fullLogName(String) to LoggingOptions

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#1061]
We could add a `LoggingOptions.fullLogName(String)` method that given a log name like "syslog" returns the fully qualified name "projects/<projectId>/logs/syslog".

This method is of no use in our service calls as our params must be partial names but could be useful to users when building filters like: "logName=projects/<projectId>/logs/syslog".

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
