### ISSUE TITLE
Stackdriver Abstraction

### ISSUE THREAD

**Issue by cornmander** [GoogleCloudPlatform/google-cloud-java#1064]
I'd like to propose a stackdriver abstraction to simplify the process of authoring and publishing metrics. My specific needs are for a monitoring library for a GAE based servlet application but the goal would be to write something that can be helpful for any Java application.

The library should simplify the definition and polling of metrics, especially Gauge metrics which make most sense when polled on a regular periodic basis in the background. The library should also just simplify the API as right now it takes a  lot of bookkeeping to just publish a single metric datapoint.

**Comment by garrettjonesgoogle** [comment]
What is the current API you're referring to?

**Comment by cornmander** [comment]
I mean the autogenerated API documented at https://cloud.google.com/monitoring/api/v3/

**Comment by cornmander** [comment]
I wrote a high-level API on top of the low-level autogenerated API. My API is already open source, located here: https://github.com/google/nomulus/tree/master/java/google/registry/monitoring/metrics . I'd like to work toward getting that included in google-cloud-java.

**Comment by garrettjonesgoogle** [comment]
Of note: the current auto-generated client at https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-monitoring/src/main/java/com/google/cloud/monitoring/spi/v3 is gRPC-only, so it will work on GAE flex but not GAE standard. If you want to port it over, we have a number of conventions in `google-cloud-java` that should be followed.

**Comment by cornmander** [comment]
Hey Garrett, I am indeed interested in porting over my library if you think it can be included in the GoogleCloudPlatform organization somehow.

**Comment by garrettjonesgoogle** [comment]
@cornmander do you think this initiative still needs to be tracked here?

**Comment by danoscarmike** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
