### ISSUE TITLE
Logging Handler Should Have Fluentd Transport

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-java#1130]
This might be a "nice-to-have", but a Java logging handler that logs by writing to the fluentd handler could be helpful. Biggest consideration here is whether it would perform better than the current one. fluentd is installed on App Engine flexible and can be included in GKE clusters with click of a button so it's good to integrate with it.

**Comment by mziccard** [comment]
Hi @waprin, you mean having a JUL handler that logs entries to fluentd? While this is surely a "nice-to-have" (I am surprised it does not exist yet) I doubt that `gcloud-java` is the right place for it.

**Comment by waprin** [comment]
Yep that's what I meant. Both GAE Flexible and GKE install the logging agent and it's one of the main ways we recommend communicating with logging API (though having an option to just use the API directly is also good).

I personally think it does belong in the gcloud-* libraries but opinions in general seemed mixed and might be decided on a per-language basis. Just wanted it on the radar.

**Comment by mziccard** [comment]
> I personally think it does belong in the gcloud-* libraries

If I understood correctly such a handler should serve as a way to direct log entries produced with JUL to fluentd. Even though I see it could be used in both GAE and GKE, such a handler is not directly related to Stackdriver Logging. In fact, it could be also useful in circumstances where fluentd is used with a different target. I would imagine this is something fluentd people might be interested in providing users with.

For this reason I believe that gcloud-java is not the best place for this bridge between JUL and fluentd.

**Comment by waprin** [comment]
> Even though I see it could be used in both GAE and GKE, such a handler is not directly related to Stackdriver Logging.

It is related because on GAE and GKE, there is a special file /var/log/app_engine/app.log.json along with a certain structured format necessary to get logs to show up correctly. Take a look at:

https://github.com/GoogleCloudPlatform/winston-gae/blob/master/lib/winston-gae.js

I understand what you're saying, but I'm not proposing a generic fluentd JUL handler, which doesn't make sense anyway since fluentd is an agent that can read from any file. What I'm proposing is a handler that writes to the files in a way that the default fluentd agent that we direct users to install here:

https://cloud.google.com/logging/docs/agent/installation

will correctly pick up log levels, etc. Currently if you just write to standard out on GAE Flex the fluentd agent does actually pick it up but because of this lack of structure does not capture log levels. 

See pissed off customer here:

http://stackoverflow.com/questions/37420400/how-do-i-map-my-java-app-logging-events-to-corresponding-cloud-logging-event-lev

**Comment by waprin** [comment]
Also if you read the answer to that StackOverflow question, the log levels are captured correctly only in the 'compat' runtime, because someone actually did this work in this runtimes so log work as expected, but really it should work in the vanilla runtime as well, but being 'vanilla' we have to ask users to instrument some sort of client library to do so. As you can see, NodeJS created a whole repo just for that one tiny piece of code, which is an opinion thing as mentioned but I personally think it makes sense to include some of that code here.

**Comment by lesv** [comment]
Bill - would https://github.com/fluent/fluent-logger-java help us in any way?  Or [this](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-examples/src/main/java/com/google/cloud/examples/logging/snippets/AddLoggingHandler.java)

**Comment by lesv** [comment]
BTW - I'm asking that all supported Java Frameworks including logging correctly, like java-compat.

**Comment by danoscarmike** [comment]
@jabubake is this being actively worked on or still in 'nice-to-have' bucket?  If latter, I'd like to move to our feature backlog and close this issue.  Thanks!

**Comment by jabubake** [comment]
@danoscarmike : 'nice-to-have'

**Comment by danoscarmike** [comment]
Thanks @jabubake!

This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
