### ISSUE TITLE
Datastore transactions don't provide read-after-write semantics

### ISSUE THREAD

**Issue by jdimond** [GoogleCloudPlatform/google-cloud-java#1134]
Here is a simple repro to demonstrate the issue. Reads in transactions will not reflect writes from the same transaction:

    // 1. Setup
    Datastore datastore = ...
    KeyFactory keyFactory = datastore.newKeyFactory().kind("test");
    Key key = keyFactory.newKey(1);

    // 1. Set initial value of entity to "old"
    datastore.put(Entity.builder(keyFactory.newKey(1)).set("value", "old").build());

    // 2. Start transaction and make sure value is "old"
    Transaction transaction = datastore.newTransaction();
    Entity entity1 = transaction.get(key);
    if (!entity1.getString("value").equals("old")) {
      throw new IllegalStateException("Unexpected value");
    }

    // 3. Write "new" value
    transaction.put(Entity.builder(entity1).set("value", "new").build());

    // 4. Read entity again, value is still "old"
    Entity entity2 = transaction.get(key);
    if (!entity2.getString("value").equals("new")) {
      throw new IllegalStateException("Unexpected value"); // throws here
    }

AFAIK Datastore v1beta3 makes this explicit by forcing all writes into the commit, making it impossible to read after a write. This behavior should also be reflected in the Java API, perhaps by throwing if there is a read attempt after a write.

**Comment by mziccard** [comment]
Hi @jdimond, thanks for the report!

I am not sure we should throw here or rather document what's going on. @aozarov thoughts?

**Comment by aozarov** [comment]
I think this is already [documented](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/Transaction.java#L28).
I don't think we should throw an exception in this case.

**Comment by jdimond** [comment]
I think this goes beyond documenting (since I also believe most devs only read documentations when they run into errors). It is non-obvious that transactions don't have read-after-write semantics, and developers might run into this without noticing, which seems very dangerous given the nature of transactions. If they are running into this exception they will be made aware of the limitations of Datastore transactions and can decide whether they are fine with missing read-after-write semantics by working around the no reads after writes (similar to what the SDK does automatically today).

**Comment by aozarov** [comment]
Note that this is the same for App Engine Datastore API and [documentation](https://cloud.google.com/appengine/docs/java/datastore/transactions#Java_Isolation_and_consistency) seemed to be sufficient.

**Comment by mziccard** [comment]
I am closing this as documentation seems sufficient in this case.
