### ISSUE TITLE
Pub/Sub unit tests are slow

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1159]
In particular, AckDeadlineRenewerTest and LocalSystemTest take most of the time because of multiple 10 second waits that they do. The overall tests on my machine take 3:13, with 2:32 of it in Pub/Sub. Could these tests be refactored to use a fake clock?

**Comment by mziccard** [comment]
There was a bit of a discussion on this [here](https://github.com/GoogleCloudPlatform/gcloud-java/pull/1031#discussion_r65234170)

**Comment by garrettjonesgoogle** [comment]
It think it would be very helpful for development to separate out slow tests (which I would argue are more like integration tests) from the "mvn test" target, and provide a separate target for the slow tests. We might still want Travis to run the slow tests.

**Comment by mziccard** [comment]
> It think it would be very helpful

I'll consider this, but I don't see a pressing need at the moment

**Comment by garrettjonesgoogle** [comment]
Well, I find it very, very, very annoying when I have to run tests multiple times from the command line.

**Comment by garrettjonesgoogle** [comment]
The time it takes to run these tests probably has a multiplicative effect since there is a limit on the number of concurrent Travis builds per repository. If we speed this up we'll see much shorter queues.

**Comment by garrettjonesgoogle** [comment]
Actually the reason that builds take so long on Travis is because we run integration tests there.

Regardless, I fixed the running time of `AckDeadlineRenewerTest` in https://github.com/GoogleCloudPlatform/google-cloud-java/commit/1a8a438c019a26bdb11baa629323443b8fe56f40 by using a fake Clock and a fake ScheduledExecutorService. I'll resolve this issue now.
