### ISSUE TITLE
Update utilities/add_snippets_to_file.py to have some limits...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1190]
We might wish to stop deleting if more than 25 lines pass w/o a closing `</pre>` tag.

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
