### ISSUE TITLE
FR: Logging Examples

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1196]
Logging needs:
1. To use new updater to maintain Javadocs in sync w/ the snippets & example code.
2. Snippets and examples should be runnable (like datastore), and have tags `// [START section]` & `// [END section]`
3. needs to update_a_log_sink sample

**Comment by mziccard** [comment]
> 2. Snippets and examples should be runnable (like datastore)

They already are runnable

**Comment by mziccard** [comment]
This was fixed in #1204 #1221 and #1222
