### ISSUE TITLE
FR: Storage - Please support managing permissions w/ IAM

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1199]
I don't seem to see support in the 0.2.7 JavaDoc

**Comment by mziccard** [comment]
Storage has no IAM methods that I am aware of. To manage permissions it uses ACLs for both buckets and objects. In `gcloud-java` we already support setting ACLs for both buckets and blobs.

**Comment by lesv** [comment]
I've asked why it's on the tracking spreadsheet.  Looking at https://cloud.google.com/storage/docs/access-control/iam doesn't suggest a separate API.

**Comment by omaray** [comment]
Any updates on this issue @lesv ? Do we need IAM support?

**Comment by jgeewax** [comment]
AFAIK, GCS has access-control lists, so I think that's what we're talking about here.

**Comment by mziccard** [comment]
I consider this closed with #1228 which adds support for all ACL-related methods (get, create, list, delete) for both blobs and buckets. I believe this is what @lesv meant with IAM. Feel free to reopen (possibly with some pointers) in case there is some IAM-related stuff we should support that I am not aware of.

**Comment by lesv** [comment]
Yep - as I said, not sure why it was listed on the tracking spreadsheet.
