### ISSUE TITLE
Add support for DropWizard Metrics

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1209]
[Cloud Bigtable](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/) has recently (0.9.2) adopted [DropWizard Metrics](http://metrics.dropwizard.io/3.1.0/) to help users trying to understand / debug Bigdata issues.  They include a connection to a [Graphite](https://graphiteapp.org/) server as well.

This would probably help users of PubSub, BigQuery, and other large data API's. (Datastore / Task Queues?)

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
