### ISSUE TITLE
Need to ensure we use lower-case gRPC header keys

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1213]
**This might be a no-op, but please double check. Filing this issue just in case.**

We need to ensure that all headers used for gRPC are written in lower-case. Please review this [Pull Request](https://github.com/GoogleCloudPlatform/gcloud-python/pull/2212) for reference of what needs to be updated.

Again, perhaps this doesn't apply to your language. Feel free to comment and close the issue (after you double checking).

**Comment by mziccard** [comment]
We don't explicitly set any gRPC header. @garrettjonesgoogle do you?

**Comment by garrettjonesgoogle** [comment]
Our code doesn't have any uppercase text that it puts in the header. We should probably do a more thorough audit of the headers that are passed.

**Comment by jgeewax** [comment]
Not even user-agent ?

**Comment by mziccard** [comment]
We set the user agent via a call to GAX, not setting the header key directly. I logged the headers of a request to PubSub and the user-agent related headers look fine, keys are: `user-agent` and `x-google-apis-agent`.

**Comment by omaray** [comment]
Can the issue be closed?
