### ISSUE TITLE
400 Bad Request on Storage.copy

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#1237]
I started seeing this today. Sometimes our integration tests fail with the following error:
```java
ITStorageTest.testCopyBlob:683 » Storage 400 Bad Request
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
No file found in request.
```
The code that causes the error is the following:
```java
String sourceBlobName = "test-copy-blob-source";
BlobId source = BlobId.of(BUCKET, sourceBlobName);
ImmutableMap<String, String> metadata = ImmutableMap.of("k", "v");
BlobInfo blob = BlobInfo.builder(source)
    .contentType(CONTENT_TYPE)
    .metadata(metadata)
    .build();
Blob remoteBlob = storage.create(blob, BLOB_BYTE_CONTENT);
assertNotNull(remoteBlob);
String targetBlobName = "test-copy-blob-target";
Storage.CopyRequest req = Storage.CopyRequest.of(source, BlobId.of(BUCKET, targetBlobName));
CopyWriter copyWriter = storage.copy(req); // Exception thrown here
```

What's weird is that we never experienced this error before today and it does not occur systematically. @Capstan any idea?

**Comment by Capstan** [comment]
For issues like this, the service team finds it super helpful if you can also specify one or more example requests' HTTP log, with request and response headers and body, and any timing information. Scrub the `Authorization` header or any OAuth token in the request if posting to public fora.

**Comment by mziccard** [comment]
For reference: the team in charge of this has been informed and the issue is being taken care of.

**Comment by mziccard** [comment]
This was fixed on the service-side. I'll reopen in case we experience again.
