### ISSUE TITLE
Insufficient authentication scopes for Logging

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/google-cloud-java#1253]
I am using the following code from the example:

```
LoggingOptions logginsOptions = LoggingOptions.defaultInstance();
Logging logging = logginsOptions.service();
```

When I run the app on Compute Engine, I get the following error:

`com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes.`

I use similar code to initialize Datastore and Storage, and that codes works fine. There is no mention of scopes in the examples, and I could not find a clear explanation in the documentation what scopes need to be provided, if any.

**Comment by mziccard** [comment]
When you created the instance did you grant it full access to `Logging`?

<img width="470" alt="screen shot 2016-09-16 at 10 53 49 pm" src="https://cloud.githubusercontent.com/assets/450933/18600937/7eb7489e-7c60-11e6-9626-58c670dcdb2c.png">

**Comment by volgin** [comment]
Good point :)  The instance was created long time ago, and Logging API is not enabled.
