### ISSUE TITLE
Bug: BigQuery: Need a way to set JobId...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1257]
There doesn't appear to be a way to set the JobId, making cancel(String JobiD) challenging.

Looking at [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/async_query.py#L34-L37) L35, The query Job takes a JobId.  There doesn't appear to be a similar method for Java. ;(
```
    client = bigquery.Client()
    query_job = client.run_async_query(str(uuid.uuid4()), query)
    query_job.use_legacy_sql = False
    query_job.begin()
```

**Comment by lesv** [comment]
@tswast FYI

**Comment by mziccard** [comment]
> There doesn't appear to be a way to set the JobId

Where? and why is `cancel` challenging?

**Comment by lesv** [comment]
Tim's explanation of the string variant of `cancel(String "id")` is that it is a name provided by the user on create, in the case of the Python samples a UUID.  The `.jobId()` is the other kind.  If you can't ever set / create with a name/id, then what's the point of the string method?

I presume, I could perhaps, use  `.jobId().toString()`, in the snippets, but that just seems weird.

It's also terribly possible that I'm not understanding something, but Tim couldn't find it either, and wrote another issue for it.

**Comment by mziccard** [comment]
But you can create a job passing your own name:
```java
String jobName = "my_job";
JobInfo jobInfo = JobInfo.of(JobId.of(jobName), QueryJobConfiguration.of("SELECT * FROM table"));
```
