### ISSUE TITLE
BigQuery - No way to create a Job from just a Job ID without doing an RPC to create one.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1258]
I wanted to create a Job object for a JobId of a job that doesn't exist. This was to check the Job.exists() method. It also would be useful for an architecture where one process creates a job and then sends the job ID string to another process to check for the status.

It appears that there is no way to create a Job except for BigQuery.create http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/index.html

All the builder constructors and actual constructors are package-private.
http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/Job.html

I tried using some of the `of()` methods inherited from JobInfo but the compiler complained that they returned a JobInfo, not a Job.

CC @lesv

**Comment by mziccard** [comment]
Is this a duplicate of #1257?

This is not a bug. Functional objects are only created via methods called on the service class `BigQuery`, which means that when they are created `Job` objects correspond to existing jobs in the remote service. This is consistent across all the library and was thoroughly discussed when designing.

The use case you mention can be resolved by using `bigquery.getJob(jobId)`.

**Comment by tswast** [comment]
Yeah, they might be the same issue.

Right, but `getJob(jobId)` returns `null` if the job doesn't exist. I'm trying to think when the `exists()` function will be useful. Maybe it's not and should be deleted?

**Comment by mziccard** [comment]
If I am not mistaken job metadata are deleted after a while in bigquery (nothing to do with cancel). You might have a job object (possibly serialized to some kind of datastore) that has been deleted and be interested in checking wether it's metadata are still available. I agree this is not common.

**Comment by tswast** [comment]
It seems to me like we'd want to support other kinds of serialization beside Java serialization (such as writing the Job ID string to a file or database). I think we still need such a constructor to support that use case.

**Comment by tswast** [comment]
I'm closing this issue, since I think my problem was more specific to trying to think of a good snippet to show the use case for `.exists()` than it was actually a problem.
