### ISSUE TITLE
Not obvious what *Options do in create() methods

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-java#1265]
### What:

Add documentation to [create() methods](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQuery.java#L444), explaining that the `*Option`s filter the fields in the results. They do not affect the creation itself.
### Why:

It took me more than an hour to figure this out.

**Comment by mziccard** [comment]
Sorry to hear you had to waste your time.

Isn't the javadoc added to all `*Options` classes enough to explain what they'll do when passed to `create` methods? See for instance [`DatasetOption javadoc`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.DatasetOption.html), [`TableOption javadoc`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.TableOption.html) and [`JobOption`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.JobOption.html).

**Comment by bjwatson** [comment]
If something like the [`fields` description](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.DatasetOption.html#fields-com.google.cloud.bigquery.BigQuery.DatasetField...-) is also stated in the summary for these classes, they I believe that would be sufficient. I did look at these class summaries on Friday, but did not see the more detailed and helpful description under `fields`.

**Comment by lesv** [comment]
@bjwatson Once you looked at the Fields descriptions, was that enough?  (ie. can we close this?)

**Comment by bjwatson** [comment]
My context is stale on this now, but I think what would help is to move/copy the detailed explanation from [`DatasetOptions.fields`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.DatasetOption.html#fields-com.google.cloud.bigquery.BigQuery.DatasetField...-) to the top-level description of [`DatasetOptions`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.DatasetOption.html).

The current description, `Class for specifying dataset get, create and update options.` is not all that helpful. `TableOption` and `JobOption` have a similar issue.

**Comment by lesv** [comment]
Got it, not sure there's an automated way to do that, but:
```
ACCESS 
CREATION_TIME 
DATASET_REFERENCE 
DEFAULT_TABLE_EXPIRATION_MS 
DESCRIPTION 
ETAG 
FRIENDLY_NAME 
ID 
LAST_MODIFIED_TIME 
LOCATION 
SELF_LINK 
```
And some commentary.

**Comment by danoscarmike** [comment]
@lesv @bjwatson any action remaining to be taken here?

**Comment by bjwatson** [comment]
Documenting in http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/bigquery/BigQuery.DatasetOption.html the options that @lesv itemized in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1265#issuecomment-283158294 would be sufficient.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
