### ISSUE TITLE
DatasetInfo could use a static of() method

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-java#1266]
### What:
Add a static `of()` method to `DatasetInfo`, like `JobInfo` and `TableId` have.

### Why:
It looks nicer than explicitly constructing a builder and then calling `build()` on it. See sample I wrote for `create(DatasetInfo)` and how it could be simplified a bit.

**Comment by mziccard** [comment]
Yes, totally, I'll add it.
