### ISSUE TITLE
Support Cloud Storage library on local App Engine development server

### ISSUE THREAD

**Issue by GabiAxel** [GoogleCloudPlatform/google-cloud-java#1276]
This is somewhat related to #684 but not exactly. I would like to use this library with the existing App Engine development server, not a separate server, because I would need Blobstore and Images APIs to have access to the blobs uploaded through GCS API and use GCS API to read blobs uploaded through Blobstore. Currently the GCS App Engine library contains only a subset of the functionality (I guess it was meant to cover only the functionality that's not in Blobstore API). I would like to gradually replace usage of Blobstore API and GCS GAE with this library.

**Comment by mziccard** [comment]
Hi @GabiAxel, thanks for your interest in `google-cloud-java`. This is possibly a duplicate of #216?

Your suggestion make totally sense. In fact we are aware of the problem (see #216) but we haven't had time to work on this yet :( I'll try to have a look but I am a bit overloaded at the moment.

**Comment by GabiAxel** [comment]
Right, it's a duplicate of #216 , I didn't find it on my first search. Thanks.
