### ISSUE TITLE
Google cloud storage class and location

### ISSUE THREAD

**Issue by pditommaso** [GoogleCloudPlatform/google-cloud-java#1285]
Is there any example showing how to set the storage class and location of a bucket with the Google storage API ?

**Comment by mziccard** [comment]
We have a number of examples showing how to create a `bucket` in [`google-cloud-examples`](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage). Examples are not showing all possible configurations that you can set though. However, if you look at the javadoc, you'll see that `BucketInfo.Builder` exposes two setters: [`storageClass`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/storage/BucketInfo.Builder.html#storageClass-java.lang.String-) and [`location`](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/apidocs/com/google/cloud/storage/BucketInfo.Builder.html#location-java.lang.String-).

You can create a bucket with location and storage class:
```java
Storage storage = optionsBuilder.build().service();
BucketInfo bucketInfo = BucketInfo.builder("nearline-eu-bucket")
    .location("eu")
    .storageClass("NEARLINE") // default is "STANDARD"
    .build();
Bucket bucket = storage.create(bucketInfo);
```
Hope this helps!

**Comment by pditommaso** [comment]
Great. Thanks!
