### ISSUE TITLE
Retry ExceptionHandler could be set through ServiceOptions

### ISSUE THREAD

**Issue by Horneth** [GoogleCloudPlatform/google-cloud-java#1289]
The [StorageImpl](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java#L107) class and others use the [EXCEPTION_HANDLER defined in the BaseService class](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/BaseService.java#L47) when invoking [runWithRetries](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/RetryHelper.java#L238). 

The RetryParams and Clock can be set in the [ServiceOptions](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java) and will be used when invoking `runWithRetries`, however the exception handler seems hardcoded.

Is that a definitive decision or would it be possible to have the exception handler also be passed through the options ?

# Why

In order to be particularly resilient to transient errors it would be beneficial to be able to retry on a larger set of exceptions.

**Comment by mziccard** [comment]
> Is that a definitive decision or would it be possible to have the exception handler also be passed through the options ?

We already retry all exceptions that are retryable according to service documentation (see https://cloud.google.com/storage/docs/xml-api/reference-status#standardcodes for Storage). If you believe we are missing some don't hesitate to open an issue.

> In order to be particularly resilient to transient errors it would be beneficial to be able to retry on a larger set of exceptions.

Do you have an example of exceptions you would want to retry?
This is not a good idea in general. Retrying exceptions that are not marked as retryable by the service might just result in more errors (for instance you might be trying to create the same object twice). For such exceptions, I encourage to implement your own retry logic at the application level, that possibly does some checks/cleanup before retrying.

**Comment by Horneth** [comment]
Thanks for the answer.

> I encourage to implement your own retry logic at the application level, that possibly does some checks/cleanup before retrying

That's already what we're doing and it looks a lot like what's already in the exception handler, only with some additional custom logic, so I was wondering if there was a way to leverage that and get rid of our retry layer. But I understand the purpose of the built-in retry now.

As for examples it varies but we are making a lot of requests and we sometimes hit QPS limits, or transient 500s and even 403s at times. We need to be robust to as many transient errors as possible so we need to retry on those.
