### ISSUE TITLE
Datastore upgrade before Sep 30th

### ISSUE THREAD

**Issue by lahirug** [GoogleCloudPlatform/google-cloud-java#1291]
We are using dataflow api with protobuf and google api's like datastore, ads, bigquery and lot more other apis. Now we got an email to update the datastore-api to v1 (currrently using protobuf 2.6.1 and other v1beta2: datastore).

I see lot of different versions of datastore and I'm not sure what exact version to use ?

I just picked one and updated all the places which gave me compilation errors and when I try to run it in GCE I  hit #1239 .

Is there a migration guide for datastore  ? I'm curious even if I migrate datastore would all these work with a new protobuf version suggested in #1239 . If we have other apis working together in dataflow pipeline what is the best way to do this migration ?

**Comment by mziccard** [comment]
Hi @lahirug, thanks for your interest in `google-cloud`.

`google-cloud-datastore` uses datastore `v1` since version `0.2.8` (under the previous name `gcloud-java-datastore`). Issue #1239 is now fixed in `google-cloud-datastore 0.4.0`. I suggest you try our latest version and keep us posted :)

**Comment by lahirug** [comment]
@mziccard Thanks for the response. I tried using and I got the same error as #1239 but the solution/workaround for that issue involves using protobuf-java: 3.0.0 (If I understood correct) and moving to protobuf-java: 3.0.0 is going to be a very big change for us.

Of when you say #1239 is now fixed is it fixed properly in some jar ? If thats the case which jar should I be using ? 
Before posting this issue I tried using datastore-v1-proto-client:1.2.0 and datastore-v1-protos:1.2.0 with protobuf-java: 2.6.1 and I saw some classes are missing which I need to use in datastore (ex: Int32Value), so I gave up that too.

**Comment by mziccard** [comment]
Let's make some order here.

This repository hosts the `google-cloud` project which is a Java-idiomatic client for Google Cloud Platform, amongst which we have `google-cloud-datastore` that supports Datastore. `google-cloud-datastore` depends on `datastore-v1-proto-client` and `datastore-v1-protos` to do its job.

 #1239 is being experienced by people already using `protobuf-java 3.0.0` and depending on `google-cloud < 0.4.0` which required `protobuf-java 3.0.0-beta3`, oddly not compatible with `3.0.0`. If you are stuck to `protobuf-java 2.6.1` you are experiencing a compatibility issue but not the one reported in  #1239.

All `datastore-v1-proto-client` and `datastore-v1-protos` versions that run against Datastore v1 require `protobuf-java 3.0.0-beta3` or `protobuf-java 3.0.0` which are not compatible with your `protobuf-java 2.6.1`.

You could avoid including `datastore-v1-protos` and try generating Datastore v1 protos for your version of `protobuf-java`, but I am not sure whether this is possible. \cc @eddavisson @pcostell

**Comment by eddavisson** [comment]
`datastore-v1-protos` uses proto3 features (e.g. maps), so I don't believe it can be compiled with `protobuf-java 2.6.1`.

**Comment by mziccard** [comment]
I am closing this as it seems there's nothing we can do to help. @lahirug you'll probably have to update your protobuf version.
