### ISSUE TITLE
Add support for RuntimeConfig API

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1305]
There is a RuntimeConfig API, which is useful for storing configuration values.

See:
https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/

I started adding support in Python. https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2485 I'd love to have this for Java, too.

The most important methods for my use cases (and most Cloud samples/applications in general, I believe) are listing variables and getting variable values. I wouldn't expect the watcher API to be supported yet, or even create/update methods, since in general the workflow will be to set variables from the command-line and read the latest value on app start-up.

**Comment by mziccard** [comment]
Hi Tim,

any change you can draft a PR for google-cloud-java as well? :) I'd be happy to review it!

**Comment by tswast** [comment]
Yeah, I think next week I'll have some time to do this.

**Comment by garrettjonesgoogle** [comment]
Can this API be done as SPI-only?

**Comment by garrettjonesgoogle** [comment]
We are tracking requests to support new APIs internally now. Closing this out.
