### ISSUE TITLE
Datastore Viewer

### ISSUE THREAD

**Issue by mitchhentges** [GoogleCloudPlatform/google-cloud-java#1307]
I'm currently migrating from the Google App Engine development environment to a more discrete environment, using the Client Datastore API to manage data. When developing with App Engine, I would be able to start a "Devserver", which would run my app's `war` file and provide helpful tooling, like the Datastore Viewer:

![2016-10-03-162356_1716x282_scrot](https://cloud.githubusercontent.com/assets/7784737/19057620/0fd1d0a6-8986-11e6-8a4e-82326741001e.png)

Does Google Cloud's Datastore Emulator provide a Datastore Viewer? If not, then this is a feature request :smile:

**Comment by mziccard** [comment]
Hi @mitchhentges thanks for your interest in `google-cloud-java`!

We are not the maintainers of the emulators but I believe there's no Datastore Viewer in the emulator. @eddavisson can you confirm this? Do you know whether there are any plans to add a viewer?

**Comment by eddavisson** [comment]
@mitchhentges: We don't currently have plans to do this, but https://github.com/GoogleCloudPlatform/google-cloud-datastore would be a good place to file the feature request.

**Comment by mitchhentges** [comment]
Thanks guys, I opened a feature request at https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/148
