### ISSUE TITLE
Client Datastore API: default consistency of 1.0 when testing

### ISSUE THREAD

**Issue by mitchhentges** [GoogleCloudPlatform/google-cloud-java#1314]
I just spent a few hours debugging flaky tests, and I _finally_ realized that it was due to the "consistency" settings that I was using.

When `LocalDatastoreHelper.create()` is called, perhaps a default consistency of `1.0` should be used? Otherwise, integration tests to verify proper API usage will "randomly" fail, even if the tests are fairly small.

**Comment by mitchhentges** [comment]
For reference, I've made a [minimal reproducible suite of tests](https://github.com/mitchhentges/Google-Client-Datastore-Flaky-Tests)  that would (within a few runs) "randomly" fail. The tests were _fairly_ simple, so I was a little surprised that the default values bit me as they did :wink:

**Comment by mziccard** [comment]
@mitchhentges Thanks for you interest in google-cloud. You are right, `LocalDatastoreHelpe.create()` starts the emulator with a consistency of `0.9`. The `Datastore` service  is not strongly consistent, hence we decided to offer a default method that creates a non-consistent datastore emulator. 

The consistency level used by `LocalDatastoreHelper.create()` is documented in the [javadoc](http://googlecloudplatform.github.io/google-cloud-java/0.4.0/apidocs/com/google/cloud/datastore/testing/LocalDatastoreHelper.html#create()). `LocalDatastoreHelper` also exposes a `create(double)` method that allows you to set your favorite consistency, see the [javadoc](http://googlecloudplatform.github.io/google-cloud-java/0.4.0/apidocs/com/google/cloud/datastore/testing/LocalDatastoreHelper.html#create(double)).

**Comment by mitchhentges** [comment]
Other than having the same behaviour as "production" datastore, what's the point of having a "test" datastore with a default consistency of `0.9`?

IMHO, if someone is using the `LocalDatastoreHelper`, they're using it for tests. Probably, they want to verify that their integration with datastore is working (passing tests if integration is good, failing tests if integration is bad).
Perhaps I'm shortsighted, but I cannot imagine a case where having an inconstent datastore is helpful in unit/integration tests.

Finally, to be honest, I've got everything working on my end, so this isn't an issue for me. I just don't want future consumers of the "Client Datastore API" to run into a similar issue that I did

**Comment by mziccard** [comment]
> Perhaps I'm shortsighted, but I cannot imagine a case where having an inconstent datastore is helpful in unit/integration tests.

Some Datastore operations are eventually consistent, testing against an eventual consistent emulator is useful in all cases you want to verify that your code is not depending on strong consistency when it should not. Having your integration tests pass against a strongly consistent emulator don't necessarily guarantee that your code will also work against the actual Datastore service.

Also notice that `0.9` is the default consistency level used by the `gcloud` command line tool when starting the datastore emulator:
```bash
gcloud beta emulators datastore start
```

> Finally, to be honest, I've got everything working on my end, so this isn't an issue for me. I just don't want future consumers of the "Client Datastore API" to run into a similar issue that I did

I am sorry you spent time on this. Probably our [`TESTING readme`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-datastore) or javadoc could have saved you some time.

**Comment by mitchhentges** [comment]
(fun 4 years update: mziccard was right, it's good to be aware of potential consistency issues in your tests, otherwise you could be surprised in production).
