### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#1320]
Hi, all.

How do we talk about the thread safety of the client library for Pub/Sub specifically?  Are the HTTP2 connections shared in gRPC cases? What about HTTP1 connections in the fallback case? Are there any other cases where thread safety might be an issue?

KIr

**Comment by mziccard** [comment]
gRPC channels are marked as `@ThreadSafe` hence we should be fine. There's [another issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1238) open to better document thread safety.

**Comment by mziccard** [comment]
I am closing this in favor of #1238
