### ISSUE TITLE
remove unneeded dependencies from nio

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/google-cloud-java#1332]
mziccard noticed the following with google-cloud-nio:

1.  org.mockito:mockito-core dependency should have test scope
2.  google-cloud-nio now depends on the whole google-cloud, we should depend just on google-cloud-storage
3.  To make 2. effective we need to also remove google-cloud dependency from google-cloud-contrib main pom.xml, we can let each child module pull its own dependencies.

**Comment by mziccard** [comment]
Fixed with #1333
