### ISSUE TITLE
JavaDoc not clear as it could be, e.g. Datastore.add vs. Datastore.put

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/google-cloud-java#1339]
What's the difference between Datastore.add and Datastore.put?

Am I right in assuming that "add" will **not** clobber existing entities?  

Maybe a quick update to the javadoc to clarify--would be much appreciated!!!

**Comment by mziccard** [comment]
`Datastore.put` performs a Datastore `upsert` (Update or Insert) operation. I believe this is documented in our javadoc.

**Comment by mziccard** [comment]
I have no idea what you mean with "clobber". I thought add behavior was straightforward, it adds an entity, in other words it performs a Datastore insert.

More details on datastore operations can be found at https://cloud.google.com/datastore/docs/concepts/entities.

**Comment by unitydynamics** [comment]
A well "clobber" is an old school computer science term.  Very technical.  It means overwrite existing data.  So... will "add" ever overwrite existing data?  If not is there a way to know which ones were already present?  Will it throw an exception?  Lots of potential questions.  I'm just an API user trying to swim.  I actually need this functionality of "add" that would add only those things not already present... leave existing datastore items alone.  I'm testing.  But I just wish I didn't have to.

**Comment by sai-pullabhotla** [comment]
@unitydynamics, add() is equivalent to insert. If you try to insert an entity and the same key already exists, you will get an exception stating that fact. Your existing entity with the same key will be unaffected.

**Comment by unitydynamics** [comment]
I get that but I still don't see any documentation that defines the behavior for multiple entities being inserted at the same time, some of which are not in the data store yet and some of which already are.  If you don't document the basic behaviors (preferably in JavaDoc) then you'll get clueless people like me asking questions like this.  Let's close this issue.  Thank you for your time and hard work on this API.

**Comment by mziccard** [comment]
@unitydynamics Here are some more details:

1. `add(Entity entity)`
  - if `entity.key()` does not exist `entity` is inserted
  - if `entity.key()` already exists the method throws a `DatastoreException ex` such that `ex.reason() == "ALREADY_EXISTS"` and the entity is not inserted

2. `add(Entity... entities)` - this is syntactic on top of a batch operation (i.e. is not transactional)
  - if none of entities' keys exist, all `entities` are inserted
  - if any of `entities`' keys already exists the method throws a `DatastoreException ex` such that `ex.reason() == "ALREADY_EXISTS"`. All entities in `entities` whose key did not exist are inserted.

You might find strange that `add(Entity... entities)` throws an exception while still inserting non-existing entities. You might also be wondering which entities have been inserted, and which already existed. Unfortunately, the service does not provide us with that information (it just returns an `ALREADY_EXISTS` error) so there's nothing more that we can do with the information we have.

BTW, you are totally right when saying that this must be added to our javadoc. Please keep this issue open until I add more docs.

**Comment by lesv** [comment]
Take a look at: https://cloud.google.com/datastore/docs/concepts/entities#datastore_basic_entity_java

**Comment by unitydynamics** [comment]
Wow.  Above and beyond!  Good clarifications all around, updated Datastore interface, added some good tests.  I like that you can get whatever behavior you want using transactions.  Thanks Marco!
