### ISSUE TITLE
NIO: Using custom options reduces cross-bucket performance

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/google-cloud-java#1343]
`google-cloud-nio` normally uses the default credentials, but there's an "escape hatch" to provide your own:

[`CloudStorageFileSystem.forBucket(String bucket, CloudStorageConfiguration config)`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java#L90). 

An unexpected side effect of the way the code is written is that when using custom credentials, bucket-to-bucket copies are slower.

The reason is that this creates a new `CloudStorageFileSystemProvider`. When asking for a copy across providers, NIO will read from one and write to the other (thus routing all the data via the client's computer). Instead, when it's the same provider, NIO can use the far more efficient copy method (data then don't have to leave the datacenter).

A natural fix would be for our code to check whether the passed `config` was seen before and, if so, reuse the same `CloudStorageFileSystemProvider`. This could be done directly by our users as a workaround, but it makes sense for us to do it transparently.

cc:@mziccard, @jart

**Comment by Horneth** [comment]
Just wanted to add some more information to this. To work around this we create a `CloudStorageFileSystemProvider` that we then re-use to generate `Path`s, as long as we know they share the same credentials.
The `getPath` method in `CloudStorageFileSystemProvider` takes a java `URI`. Which means we need to first turn a string "gs://bucket/path/to/object" into an URI. When calling `URI.create` on a gcs url, the bucket is being parsed as the hostname.
We recently ran into an issue where the bucket name contains an underscore, which is valid for a gcs url. However it's not a valid character for URI hostnames. This makes it not possible (without doing some ugly things like this http://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores) to create a URI from a gcs url where the bucket contains underscores.
I don't know if this fits into this issue or is a separate problem, but I thought I would add this here in case this issue gets fixed to make sure this was taken into consideration.

**Comment by jean-philippe-martin** [comment]
Thanks @Horneth, that is a good point.

For the underscore issue, if you know you're using Google Cloud Storage you can work around the `getPath` limitation by calling `CloudStorageFileSystem.forBucket`, which takes a `String` for the bucket name and allows it to have an underscore.

```
Path path = CloudStorageFileSystem.forBucket("bucket_with_underscore").getPath("myfile.txt");
```

**Comment by Horneth** [comment]
@jean-philippe-martin that does work, the problem is now that it's not possible to get back a gcs path as a `String` (`gs://bucket_with_underscore/myfile.txt`) from this path using `toUri`, indeed it is not a valid URI because of the underscore in the bucket..
Any idea how to work around that ?
It seems like some kind of `toGcsString` method would be very useful to be able to roundtrip `gs://bucket_with_underscore/myfile.txt` -> CloudStoragePath -> `gs://bucket_with_underscore/myfile.txt`

**Comment by jean-philippe-martin** [comment]
@Horneth this functionality is already available, though not packaged in a single function: given a path `p`, you can assemble the GCS path as follows:

    String gcsString = "gs://" + p.bucket() + p.toAbsolutePath();

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by daudn** [comment]
> Thanks @Horneth, that is a good point.
> 
> For the underscore issue, if you know you're using Google Cloud Storage you can work around the `getPath` limitation by calling `CloudStorageFileSystem.forBucket`, which takes a `String` for the bucket name and allows it to have an underscore.
> 
> ```
> Path path = CloudStorageFileSystem.forBucket("bucket_with_underscore").getPath("myfile.txt");
> ```

I tried:
```
Path path = CloudStorageFileSystem.forBucket("pth_with_underscore").getPath("*.tar.bz2");
String gcsString = "gs://" + path.bucket() + "/data" + path.toAbsolutePath();
```

```
java.net.URISyntaxException: Illegal character in hostname at index 8: gs://pth_with_underscore/data/
```

This doesn't work? :/

**Comment by jean-philippe-martin** [comment]
@daudn, this version compiles and works:

```
  CloudStorageFileSystem fs = CloudStorageFileSystem.forBucket("bucket_with_underscore");
  Path p = fs.getPath("*.txt");
  String gcsString = "gs://" + fs.bucket() + p.toAbsolutePath();
```

```
  gs://bucket_with_underscore/*.txt
```
I have fixed my earlier remark so others won't be confused.
