### ISSUE TITLE
Unable to use pubsub and monitoring libraries in same Clojure project

### ISSUE THREAD

**Issue by scampbell7777** [GoogleCloudPlatform/google-cloud-java#1344]
I would like to be able to use both 
com.google.cloud/google-cloud "0.4.0"
and 
com.google.apis/google-api-services-monitoring "v3-rev11-1.22.0" in the same Clojure (Java) project. 

Specifically, I am using PubSub to publish/subscribe messages while I am using the API to monitor the number of messages on the queue. In separate projects, both work fine. 
However, when used in the same project, I get the following error: "NoSuchMethodError com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;  io.grpc.internal.ClientCallImpl.<init> (ClientCallImpl.java:103)"

This seems to be due to (perhaps) conflicting dependencies in the two libraries. Is there an easy way to solve this?

**Comment by mziccard** [comment]
This is strange, seems that an older version of Guava (< 18) is being pulled. Can you share with us the complete stacktrace and your dependency tree?

**Comment by mziccard** [comment]
@scampbell7777 any update?

**Comment by mziccard** [comment]
I am closing this due to the lack of information. Feel free to reopen with more details.
