### ISSUE TITLE
Plans to harmonize authentication?

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/google-cloud-java#1345]
@Horneth reports:

> The class used for authentication in the google.cloud library (`com.google.cloud.AuthCredentials`) is different from the one in google.api.client (`com.google.api.client.auth.oauth2.Credential`). We need to maintain 2 different sets of authentication classes for the same authentication mode. I was wondering if there are any plans to harmonize those in the future.

Do we have some guidance we can share, or plans to harmonize across these projects?

**Comment by mziccard** [comment]
We are in the process of dropping our `AuthCredentials` classes in favor of classes in [google-auth-library-java](https://github.com/google/google-auth-library-java) (we are adding there all the functionality that we need from `AuthCredentials`).

We will not be using the `com.google.api.client.auth.oauth2.Credential` class. I suggest you look at classes in [google-auth-library-java](https://github.com/google/google-auth-library-java) which support a wide range of authentications. Have a look at [`HttpCredentialsAdapter`](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java) which extends `HttpRequestInitializer` and allows you to authenticate API client requests.

**Comment by mziccard** [comment]
With #1375 we dropped our `AuthCredentials` classes and moved to using [google-auth-library-java](https://github.com/google/google-auth-library-java) for authentication (this library also works with the REST client), this will be available in the next release.
