### ISSUE TITLE
ValueBuilder - excludeFromIndexes - Method name consistency 

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1352]
The accessor methods for excludeFromIndexes in ValueBuilder are not consistent. Something to look into. 

`setExcludeFromIndexes(boolean)` is good. 
`excludeFromIndexes(boolean)` is Deprecated per the new conventions, so that is also good. 

The Getter method is the one that is **not** consistent. Perhaps we need to add `isExcludeFromIndexes()` and deprecate `excludeFromIndexes()`? 

```
public interface ValueBuilder<V, P extends Value<V>, B extends ValueBuilder<V, P, B>> {

  @Deprecated
  boolean getExcludeFromIndexes();

  boolean excludeFromIndexes();

  @Deprecated
  B excludeFromIndexes(boolean excludeFromIndexes);

  B setExcludeFromIndexes(boolean excludeFromIndexes);
//...
}

```

**Comment by mziccard** [comment]
Hi @sai-pullabhotla, this was actually done on purpose. We kept all `boolean` getters with their original names (or added the `is` prefix when it made sense) as they feel more as natural language when tested:
```java
if (value.excludeFromIndex()) {
  // do something
}
```
