### ISSUE TITLE
DatastoreOptions.Builder#namespace(String) should be setNamespace 

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1353]
Just like how there is `setProjectId(String)`, `setAuthCredentials(AuthCredentials)`, need `setNamespace(String)` for consistency. Deprecate the `namespace(String)` method.

**Comment by mziccard** [comment]
You are totally right, we missed this. I'll fix ASAP, thanks for the report.
