### ISSUE TITLE
GqlQuery#allowLiteral() - should it be renamed to isAllowLiteral()?

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1354]
`GqlQuery#allowLiteral()` - should it be renamed to `isAllowLiteral()`, for consistency?

**Comment by mziccard** [comment]
Hi @sai-pullabhotla, this was actually done on purpose. We kept all `boolean` getters with their original names (or added the `is` prefix when it made sense) as they feel more as natural language when tested:
```java
if (query.allowLiteral()) {
  // do something
}
```
