### ISSUE TITLE
Datastore: Divergence in failure treatments in add/put with multiples entities

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/google-cloud-java#1356]
I'm using the following code block to generate a big random blob of characters

```
Random r = new Random();

int msgSize = 5200;  // in KB
msgSize = msgSize/2; // Java chars are 2 bytes
msgSize = msgSize * 1024;
StringBuilder sb = new StringBuilder(msgSize);
for (int i=0; i<msgSize; i++) {
    sb.append((char)(r.nextInt(26) + 'a'));
}
```

I find that if I put a blob in an entity and store it...

`entityBuilder.set("myTextBlob", BlobValue.builder(Blob.copyFrom(sb.toString())).excludeFromIndexes(true).build());
`

And then build my entity and save it that it works... and all *other* properties make it into the datastore... but the blob property is silently dropped.  Is there a correct way to validate an entity before inserting it?  Datastore items are max 1MB in size right?

**Comment by sai-pullabhotla** [comment]
@unitydynamics, 

Max entity size is 1 MB, this is the size of all properties in the entity. Attempting to put an entity that is larger than this size should produce a DatastoreException indicating that the entity is too large. 

Can you post the entire code... unless I'm overlooking something, the code you posted most likely won't compile because there is no method to create a Blob from String, . 

BlobValue.builder(Blob.copyFrom(**sb.toString()**))

**Comment by mziccard** [comment]
Hi @unitydynamics, are you sure?
First, your code:
```
entityBuilder.set("myTextBlob", BlobValue.builder(Blob.copyFrom(sb.toString())).excludeFromIndexes(true).build());
```
Does not compile as `Blob` has no `copyFrom` method that takes a `String`.

I tried the following code:

```java
Random random = new Random();
byte[] blobArray = new byte[2_000_000];
random.nextBytes(blobArray);

Key key = datastore.newKeyFactory().setKind("MyKind").newKey("mykey");
Entity entity = Entity.newBuilder(key1)
    .set("stringProperty", "value")
    .set("integerProperty", 1)
    .set("blobProperty",
        BlobValue.builder(Blob.copyFrom(blobArray))
            .setExcludeFromIndexes(true)
            .build())
    .build();

// using datastore
datastore.add(entity);
// or
Transaction transaction = datastore.newTransaction();
transaction.add(entity);
transaction.commit();
// or
datastore.put(entity);
// or 
Transaction transaction = datastore.newTransaction();
transaction.out(entity);
transaction.commit();
```
As you can see I tried to insert the entity in different ways. Regardless of the way I get the following error and the entity is not persisted (none of its properties):
> The value of property "blobProperty" is longer than 1048487 bytes.

This is in line with the limits reported [here](https://cloud.google.com/datastore/docs/concepts/limits):

> Maximum size for an entity = 1,048,572 bytes (1 MiB - 4 bytes)
> Maximum size for an unindexed property = 1,048,487 bytes (1 MiB - 89 bytes)

**Comment by unitydynamics** [comment]
So yes I have lots of code cut out (I'm compressing text before I put it into the property).  I will try to post a short reproducible example tomorrow.  Couple of potentially contributing circumstances.... one is that I'm accessing the datastore from outside AppEngine.  I've got my certificate installed so I can push entities to production Datastore from my local machine (or compute engine).

**Comment by mziccard** [comment]
> one is that I'm accessing the datastore from outside AppEngine.

This corresponds to the setup I used to run my above (and working as expected) code. I doubt this is a Datastore-related issue.

**Comment by unitydynamics** [comment]
So yes this, as originally posted, was a *me* issue... sorry to take up your time.  But I did run into one interesting issue so I changed the title.  Per our last issue... I noticed that "add" makes a best effort to store all good entities (the ones not already inserted).  Well the behavior is slightly different when the entities are too large... the entire operation fails.  I would expect (or hope for) consistent behavior from these methods (i.e.. always best efforts on every individual entity).  Maybe a different way to fail other that exceptions?  Ideally something that allows you to identify the issues (but I recall that may not be possible).

````
Random random = new Random();
byte[] blobArray = new byte[2_000_000];
random.nextBytes(blobArray);

Datastore datastore = DatastoreOptions.defaultInstance().service();
Key key1 = datastore.newKeyFactory().kind("MyKind").newKey("mykey");
Entity entity1 = Entity.builder(key1)
    .set("stringProperty", "value2")
    .set("integerProperty", 1)
    .set("blobProperty",
        BlobValue.builder(Blob.copyFrom("one two three".getBytes()))
            .excludeFromIndexes(true)
            .build())
    .build();

Key key2 = datastore.newKeyFactory().kind("MyKind").newKey("mykey2");
Entity entity2 = Entity.builder(key2)
    .set("stringProperty", "value2")
    .set("integerProperty", 1)
    .set("blobProperty",
        BlobValue.builder(Blob.copyFrom(blobArray))
            .excludeFromIndexes(true)
            .build())
    .build();

Key key3 = datastore.newKeyFactory().kind("MyKind").newKey("mykey3");
Entity entity3 = Entity.builder(key3)
    .set("stringProperty", "value2")
    .set("integerProperty", 1)
    .set("blobProperty",
        BlobValue.builder(Blob.copyFrom("four five six".getBytes()))
            .excludeFromIndexes(true)
            .build())
    .build();

// using datastore
// both of these fail the entire batch
datastore.add(entity1, entity2, entity3);
datastore.put(entity1, entity2, entity3);
````

**Comment by sai-pullabhotla** [comment]
@mziccard, 

Regarding the max size of an unindexed property - 

> Maximum size for an unindexed property = 1,048,487 bytes (1 MiB - 89 bytes)

I was testing the limits the other day and I was not able to store (1 MiB - 89). I was getting Entity too large exception. After a few trial and errors, I was able to store (1 Mib-129), but that was also failing sporadically with the Entity too large message. Since you seem to have a test case now, would you mind validating this?

**Comment by unitydynamics** [comment]
@sai-pullabhotla the exception makes it sound like a field-level limit but it's an entity-as-a-whole size limit right?  Variations in you testing may be due to your other entity attributes?  

Regarding how to handle "too large" in general....  Maybe throw the "too large" exception when build() is called on the entity?  I know I'd rather know right away.  But I know adding size logic isn't necessarily easy.

**Comment by sai-pullabhotla** [comment]
No, my test case was with just one field with Datastore-generated Integer key.

**Comment by mziccard** [comment]
@sai-pullabhotla I managed to successfully create an Entity with blob of 1,048,487 bytes:
```java
Random random = new Random();
byte[] blobArray = new byte[1_048_487];
random.nextBytes(blobArray);

Key key = Key.newBuilder("my-project", "a", "b").build();
Entity entity = Entity.newBuilder(key)
    .set("p", BlobValue.newBuilder(Blob.copyFrom(blobArray)).setExcludeFromIndexes(true).build())
    .build();
datastore.add(entity);
```
Which exception were you getting? That should tell you if you are hitting an entity limit or a blob limit.

**Comment by mziccard** [comment]
@unitydynamics I managed to reproduce what you are seeing. @pcostell could you have a look at [this comment](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1356#issuecomment-257330850)?

**Comment by pcostell** [comment]
Datastore cannot make guarantees about the success/failure of multi-entity puts. If you need an all-or-nothing rule, you need to use transactions.

If a non-transactional commit fails, there is no way to know which, if any, of the entities were successfully written.

**Comment by mziccard** [comment]
@pcostell I think the point here is not achieving an all-or-nothing rule, but rather the *non*-all-or-nothing behavior feeling inconsistent. Let me try to explain:

1. If `entity1.getKey()` already exists `add(entity1, entity2)` fails, but `entity2` is inserted.
2. If `entity1` exceeds the size limit `add(entity1, entity2)` fails, *no entity* is inserted.

From 1. users conclude that on a failure _multi-entity add_ inserts all entities that can be inserted. From 2. users conclude that on a failure _multi-entity add_ does not insert anything. I can see from where this comes, but it can still be confusing.



put(entity1, entity2)

**Comment by pcostell** [comment]
@mziccard you're right, it's definitely inconsistent in non-transactional cases. Really all we can guarantee is all-or-nothing in a transaction. Outside of a transaction the failures can happen at different points in the stack which results in the undefined behavior. I can file some bugs internally to get the documentation to describe this better, but I'm not sure it will be possible to make the behavior itself more well-defined.

**Comment by mziccard** [comment]
> Outside of a transaction the failures can happen at different points in the stack which results in the undefined behavior.

This is what I meant when saying "I can see from where this comes" :)
Documentation at service-level would really help on this!

**Comment by sai-pullabhotla** [comment]
@mziccard, 

I get the below exception when I try to put an entity with datastore allocated key and one Blob property. I tried to set the data of my blob field to 1MiB - 89. 

```
Caused by: com.google.cloud.datastore.DatastoreException: entity is too big
Caused by: com.google.datastore.v1.client.DatastoreException: entity is too big, code=INVALID_ARGUMENT
```
My entity Kind is `UnindexedByteArrayField`. Property name is `junk`. 

Then I changed my Kind to a single letter, 'X', and the insert succeeded. So, I guess the Kind, ID/Name, Property Names also play a role here. Just an FYI.

**Comment by mziccard** [comment]
I believe we answered all the questions in this issue, dedicated internal issues will track the addition of documentation to Datastore pages.

**Comment by Sampath-Lokuge** [comment]
I can see that where I have to face Maximum size for an entity limit mentioned on the doc. Could you tell me what they mean here an entity? Is that `projects`(this is the entity which it shows the above error) `with collections` or `without collections`? How can I avoid this issue? I'm using `firestore`.

![Alt Text](https://i.stack.imgur.com/kSMWD.png)
