### ISSUE TITLE
Upgrade to protobuf 3.1.0?

### ISSUE THREAD

**Issue by rscorer** [GoogleCloudPlatform/google-cloud-java#1363]
Protobuf has been 3.1.0 since September and other projects have adopted it, and it appears google-cloud-java (specifically datastore) is using 3.0.0 which is causing us conflicts. 

Any plans to move to 3.1.0?

**Comment by mziccard** [comment]
@rscorer Can you be more specific? Which conflicts is 3.1.0 causing?

**Comment by rscorer** [comment]
Sorry! Because we're using 3.1.0 in our project, so the datastore request apparently fails... 

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/datastore/v1/Query$Builder.setLimit(Lcom/google/protobuf/Int32Value;)Lcom/google/datastore/v1/Query$Builder; @36: invokevirtual
  Reason:
    Type 'com/google/protobuf/Int32Value' (current frame, stack[1]) is not assignable to 'com/google/protobuf/GeneratedMessage'
  Current Frame:
    bci: @36
    flags: { }
    locals: { 'com/google/datastore/v1/Query$Builder', 'com/google/protobuf/Int32Value' }
    stack: { 'com/google/protobuf/SingleFieldBuilder', 'com/google/protobuf/Int32Value' }
  Bytecode:
    0x0000000: 2ab4 0023 c700 1b2b c700 0bbb 0065 59b7
    0x0000010: 0066 bf2a 2bb5 0012 2ab6 003f a700 0c2a
    0x0000020: b400 232b b600 8557 2ab0               
  Stackmap Table:
    same_frame(@19)
    same_frame(@31)
    same_frame(@40)

```

We have to use 3.1.0 to comply with our colleague's go code.

Does that make better sense?

**Comment by mziccard** [comment]
Mmmm, this is strange. Which version of google-cloud-java are you using?

**Comment by rscorer** [comment]
🙈  transitively we're using 0.1.7 - of com.google.gcloud, we are updating to a more recent version -- will let you know the result!

**Comment by rscorer** [comment]
Problems gone now we're up to date, using com.google.cloud instead of com.google.gcloud 

Thanks

**Comment by mziccard** [comment]
Good news :)
