### ISSUE TITLE
Datastore - Support for OR predicate in GQL/Query Filters 

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1364]
Is there a reason why a datastore query (GQL or otherwise) does not allow OR predicate? I noticed that the AppEngine Datastore supports this - 

(https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/datastore/Query.CompositeFilter). 

I was under the impression that Cloud Datastore is similar (or same) as AppEngine Datastore. 

In any case, is this some thing that can be supported?

**Comment by mziccard** [comment]
@aozarov @ajkannan Any reason we don't support `OR`?

**Comment by ajkannan** [comment]
It looks like "OR" isn't supported in Cloud Datastore yet.

Looking at the [current cloud docs](https://cloud.google.com/datastore/docs/reference/rest/v1/projects/runQuery#Operator) and [previous cloud docs](https://cloud.google.com/datastore/docs/reference/rest/v1beta3/projects/runQuery#Operator), I don't see "or" mentioned under composite filter operators, just "and".  Also, [this page](https://cloud.google.com/datastore/docs/concepts/queries#datastore_composite_filter_java) and [this page](https://cloud.google.com/datastore/docs/reference/gql_reference#clauses) (in the "where" row) affirm that only "and" is supported for now.

/cc @eddavisson are there plans to support "OR" in Cloud Datastore?

**Comment by sai-pullabhotla** [comment]
@ajkannan - This [page](https://cloud.google.com/datastore/docs/concepts/queries#datastore_composite_filter_java) clearly states that - 

**Restrictions on queries**

> The nature of the index query mechanism imposes certain restrictions on what a query can do. Cloud Datastore queries do not support substring matches, case-insensitive matches, or so-called full-text search. **The NOT, OR, and != operators are not natively supported, but some client libraries may add support on top of Cloud Datastore.**

I wonder if any of the client libraries (possibly Python or the AppEngine Java API) do this, and if so, how do they do it? Something to look into.

**Comment by mziccard** [comment]
@sai-pullabhotla I can confirm that `OR` is not supported natively. And yes, some clients (AppEngine SDK and python ndb) support `OR` by issuing multiple queries and then merging the results. Such a feature is out of the scope of our client which is meant to be a java-idiomatic but thin layer on top of Datastore API. AFAIL none of the other `google-cloud-*` libraries supports `OR`.

**Comment by sai-pullabhotla** [comment]
@mziccard - Thanks. I just wanted to make sure if this is something the Datastore supports or not. Now we know the answer. I'm closing this.
