### ISSUE TITLE
Support generic Batch HTTP requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1366]
We got feedback on this page that we don't have any code samples. https://cloud.google.com/bigquery/batch

The API clients support batch requests, https://developers.google.com/api-client-library/java/google-api-java-client/batch but I don't think the Cloud libraries do.

I'm marking as BigQuery, since that's where we got the feedback, but I'm sure it applies to the other products, as well.

**Comment by mziccard** [comment]
We already support batches for Storage and DNS. Support for BigQuery hasn't been a priority as it has never been requested by users.

I agree this is something we should add.

**Comment by tswast** [comment]
Closing this since batch is considered a legacy feature. It is not supported in new gRPC-native APIs.
