### ISSUE TITLE
Support PubSub on AppEngine Standard

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-java#1368]
Pubsub doens't work on GAE standard.  Please add support for GAEStandard.
pubsub-java throws the following error on initialization 
with 
```
      PubSub pubsub = PubSubOptions.getDefaultInstance().getService();
```
```
  error:
   java.lang.NoClassDefFoundError: java.nio.channels.spi.SelectorProvider is a restricted class.
 Please see the Google App Engine developer's guide for more details. at 
```

(i suspect its not supported if the library now is gRPC only)

**Comment by mziccard** [comment]
This is documented in our main README. The reason this is not supported on AppEngine is in fact gRPC not working AE, there is work on the AE side to fix this.

**Comment by salrashid123** [comment]
The other way to look at this is if gcloud-java's pubsub library would support REST (like the datastore implementation or python).  
Is the suggestion to wait for AE to support gRPC (vs this client to support rest)?
