### ISSUE TITLE
Please update README with Alpha->Beta->GA timelines for each library

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-java#1369]
It helpful for customers to easily 'see' when a particular GCP client library will be at GA.

(i'll file one for gcloud-puthon to get the library status add to that README too)

**Comment by lesv** [comment]
@omaray PTAL

**Comment by omaray** [comment]
Not in the plans to add an exact timeline. Would something "more ball parky" make sense?

**Comment by lesv** [comment]
Probably giving folks the following as an estimate would be ok.  Something like should be before 17Q4.

**Comment by oto0** [comment]
Is there any update for providing basic timeline as lesv suggested? For example pubsub went into alpha after 0.8 and now is still alpha as 0.17.2

**Comment by garrettjonesgoogle** [comment]
So I understand the value of this, but in practice, even dates we broadcast internally don't always stick. I'm going to close out this issue now - sorry that we can't be more helpful w.r.t. this!
