### ISSUE TITLE
Error when updating ACL on an object

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/google-cloud-java#1373]
The following code (suggested in documentation) results in an error:

```
Iterator<Blob> it = storage.list(COVER).iterateAll();
while (it.hasNext()) {

    Blob blob = it.next();
    storage.updateAcl(blob.blobId(), Acl.of(User.ofAllUsers(), Role.READER));
    // blob.updateAcl(Acl.of(User.ofAllUsers(), Role.READER));  - results in the same error
}
```

The error message (not very useful):

> Exception in thread "main" com.google.cloud.storage.StorageException: Not Found
> 	at com.google.cloud.storage.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:198)
> 	at com.google.cloud.storage.spi.DefaultStorageRpc.patchAcl(DefaultStorageRpc.java:818)
> 	at com.google.cloud.storage.StorageImpl$33.call(StorageImpl.java:827)
> 	at com.google.cloud.storage.StorageImpl$33.call(StorageImpl.java:824)
> 	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
> 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
> 	at com.google.cloud.storage.StorageImpl.updateAcl(StorageImpl.java:824)
> 	at com.rebelation.ingest.server.VerifyCoverFiles.main(VerifyCoverFiles.java:52)
> Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
> {
>   "code" : 404,
>   "errors" : [ {
>     "domain" : "global",
>     "message" : "Not Found",
>     "reason" : "notFound"
>   } ],
>   "message" : "Not Found"
> }
> 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
> 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
> 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
> 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
> 	at com.google.cloud.storage.spi.DefaultStorageRpc.patchAcl(DefaultStorageRpc.java:813)
> 	... 6 more

**Comment by mziccard** [comment]
Hi @volgin!

Does an ACL for `User.ofAllUsers()` already exist? If that is not the case you must use `createAcl`:
```java
Iterator<Blob> it = storage.list(COVER).iterateAll();
while (it.hasNext()) {

    Blob blob = it.next();
    storage.createAcl(blob.blobId(), Acl.of(User.ofAllUsers(), Role.READER));
}
```

**Comment by volgin** [comment]
createAcl works - thank you!

It would be nice to make a bit more clearer in the documentation that updateAcl applies to an existing individual Acl record, and not to the "Access Control List". Or, at least,  improve an error message.

**Comment by mziccard** [comment]
@volgin The javadoc already states:

> Updates an ACL **entry** on the specified blob.

Any specific suggestion to make it more clear?
