### ISSUE TITLE
pubsub emulator authinterceptor question

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-java#1381]
I get the following when subscribing to a topics subscription locally:
```
...
[pubsub] Nov 09, 2016 1:46:17 PM com.google.cloud.iam.testing.v1.shared.authorization.AuthInterceptor interceptCall
[pubsub] INFO: Authentication interceptor: Header value is null
[pubsub] Nov 09, 2016 1:46:17 PM com.google.cloud.iam.testing.v1.shared.authorization.AuthInterceptor interceptCall
[pubsub] INFO: Authentication interceptor: invalid or missing token
[pubsub] Nov 09, 2016 1:46:17 PM com.google.cloud.iam.testing.v1.shared.authorization.AuthInterceptor interceptCall
[pubsub] INFO: Authentication interceptor: Header value is null
...
```
Given the below information, what could be wrong?

My java code works with the actual cloud service but when using the following code:

```java
PubSubOptions.Builder optionsBuilder = PubSubOptions.newBuilder().setProjectId("project");
optionsBuilder.setAuthCredentials(AuthCredentials.noAuth());
optionsBuilder.setHost("localhost:8989");
PubSub pubsub = optionsBuilder.build().getService();

//then using pubsub.pullAsync(...) for the actual pulling of messages
```

gcloud pubsub emulator started like this:
`gcloud beta emulators pubsub start --host-port=0.0.0.0:8989`

Versions:
gcloud-java-pubsub -> 0.5.1

$ gcloud --version
Google Cloud SDK 133.0.0
alpha 2016.01.12
beta 2016.01.12
bq 2.0.24
bq-nix 2.0.24
core 2016.11.01
core-nix 2016.11.01
gcloud
gsutil 4.22
gsutil-nix 4.22
pubsub-emulator 2016.08.19

**Comment by mziccard** [comment]
Nothing is going wrong. When using the emulator we pass no credentials and this is what the logs are telling you, that no authentication header was provided with the any of the requests.

Code running against the emulator is working as expected right?

**Comment by fonzy2013** [comment]
Oh, it was spitting out soo much that I thought it was wrong. I will test. Maybe a good idea to disable that particular logging (many lines per second)

**Comment by mziccard** [comment]
@fonzy2013 I believe there might be some users interested in that log (the interceptor also logs the header if one is set in the request).

@hbchai could we make the logging level `FINE` for `AuthInterceptor`?

**Comment by fonzy2013** [comment]
Just for knowledge, when running in pull mode in gcloud-java I get more entries then my console can handle... I think it would be great if it could be tuned down or collapsed into 1 line instead of 3

**Comment by hbchai** [comment]
@mziccard Good idea about using `FINE` - will do that.

**Comment by garrettjonesgoogle** [comment]
Looks like nothing more is necessary for this.

**Comment by Ghazgkull** [comment]
@garrettjonesgoogle Would you mind summarizing the resolution of this one? As a user of the emulator, how do I get it to stop logging this warning?

It's particularly a problem when using docker-compose to run a number of containers, as the pubsub container spam consistently scrolls away the output from other containers.

**Comment by asnare** [comment]
It looks like @hbchai said "Great, we'll change it to `FINE`" but @garrettjonesgoogle then closed it before the change was made?

**Comment by garrettjonesgoogle** [comment]
I think I didn't look carefully enough and assumed the message from @hbchai was from a user, but now I see it was from the implementer of the emulator. I will re-open so we can check the log levels in google-cloud-java code.

**Comment by pongad** [comment]
I'll fix the emulator.

**Comment by pongad** [comment]
Emulator fix landed in Google internal repo. I'll leave this open until the change made its way out.

**Comment by pongad** [comment]
Change pushed. Run `gcloud components update` to pick it up!

**Comment by nomcopter** [comment]
@pongad When will the update make it in to https://hub.docker.com/r/google/cloud-sdk/ ? Thanks!

**Comment by pongad** [comment]
@nomcopter I believe a new one has already been pushed.
