### ISSUE TITLE
Query (and possibly other classes) in Datastore library using @Deprecated with no documentation of what to use instead

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-java#1383]
com.google.cloud.datastore.Query:171 is an instance of this, although there are others in that class.

**Comment by mziccard** [comment]
Hi @patflynn!

In `google-cloud 0.5.0` we went through a massing renaming of our methods to meet proto conventions (for a smoother integration of our classes with protos).

We deprecated older methods to make the transition easier to users (no breaks), but all changes fall in the following categories (outlined in our [release notes](https://github.com/GoogleCloudPlatform/google-cloud-java/releases/tag/v0.5.0)):

> * Getters and setters with the `get` and `set` prefix have been added to all classes/builders. Older getters/setters (without `get/set` prefix) have been deprecated
> * Builder factory methods `builder()` have been deprecated, you should use `newBuilder()` instead
> * `defaultInstance()` factory methods have been deprecated, you should use `getDefaultInstance()` instead

Deprecated methods will most likely be removed sooner than we can fix this issue.

**Comment by patflynn** [comment]
Got it. Thanks for letting me know.
