### ISSUE TITLE
Integer Overflow In BaseWriteChannel

### ISSUE THREAD

**Issue by Dima1224** [GoogleCloudPlatform/google-cloud-java#1389]
Hi there. I'm testing out com.google.cloud.storage.Storage.writer() for writing to GCS. It works very well for files smaller than 2GB, but right around the 2GB mark WriteChannel throws an exception indicating that there's something wrong with the Content-Range header.

`com.google.api.client.http.HttpResponseException: 400|Failed to parse Content-Range header.`

I noticed that the Content-Range header is set in com.google.cloud.storage.spi.DefaultStorageRpc.write() and is calculated using com.google.cloud.BaseWriteChannel.position, which is an int. The problem is that at the 2GB mark the position variable overflows and becomes negative, causing panic and mayhem.

Here are some screenshots to paint a fuller picture:

![trace1](https://cloud.githubusercontent.com/assets/8976403/20188491/7cee211e-a73e-11e6-9197-945755142b08.jpg)

![trace2](https://cloud.githubusercontent.com/assets/8976403/20188495/81a45be2-a73e-11e6-91d9-3c5eb1c6a578.png)

Any chance we can get a patch for this? Should I submit a pull request?

**Comment by mziccard** [comment]
Uh very sorry for the panic and mayhem. I believe we have fixed an analogous fix for the reader and this was left behind.

A PR would be awesome, it should be as simple as making `position` in `BaseWriteChannel` a `long` and changing the two getters `position()` and `getPosition()` to long as well. Let me know if you can make it, otherwise I'll kick one out ASAP.

**Comment by Dima1224** [comment]
Can I ask you to do it? I don't have the code base checked out, was debugging against the sources jar.

**Comment by mziccard** [comment]
> Can I ask you to do it?

This is kind of my job so I'll be more than happy :D

**Comment by Dima1224** [comment]
Looks like I'm talking to the right guy :)

**Comment by Dima1224** [comment]
Thanks! Any idea when the fix will be released?

**Comment by mziccard** [comment]
@Dima1224 Beginning of next week the latest!

**Comment by Dima1224** [comment]
Thanks for the lightning fast turnaround once again, @mziccard! Much appreciated.
