### ISSUE TITLE
NoSuchmethodError on pubsub.PubSubOptions.newBuilder()

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#1397]
My code compiles with this clause in pom.xml
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-pubsub</artifactId>
        <version>0.5.0</version>
    </dependency>

But crashes immediately at run time when I attempt to create a new option builder:
   public static void main( String[] args ) throws ParseException, java.io.IOException
    {
        CommandLine cmd = parseCommandLineArgs( args );
        PubSubOptions options = PubSubOptions.newBuilder().build();
     ...
     }

With 
Exception in thread "main" java.lang.NoSuchMethodError: com.google.cloud.pubsub.PubSubOptions.newBuilder()Lcom/google/cloud/pubsub/PubSubOptions$Builder;

1. What am I doing wrong?
2. I modeled this line on the datastore example on the read-the-code front page.  If this is different, that's something to be fixed either in the API or the docs :) 
3. It is super hard to figure out how to actually create a properly authenticated client from the Javadoc. There are not examples and most of the key methods are right in the middle of being deprecated.  I'd love clean documentation on the client creation classes.

**Comment by mziccard** [comment]
How are you running the application? Is the proper version of `google-cloud-pubsub` in the classpath? Can you do a clean build?

**Comment by garrettjonesgoogle** [comment]
@kir-titievsky , could you provide the information that Marco was asking for here? Could you maybe try with 0.8.0?

**Comment by garrettjonesgoogle** [comment]
Closing out due to no response.
