### ISSUE TITLE
BigQuery does not have listProjects method

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1409]
See: https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects#projects
and https://cloud-dot-devsite.googleplex.com/bigquery/docs/reference/rest/v2/projects/list

The BigQuery API provides a way to access the list of projects available. (This is because BigQuery was one of the first Google Cloud APIs and customers may wish to access BigQuery projects without using resource manager.)

See also: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2143

**Comment by mziccard** [comment]
This was done on purpose, listing projects does not belong to BigQuery. Was this a user request?

**Comment by tswast** [comment]
Hold off on making this a beta blocker. We might point users to resources API instead of adding this to this library.

**Comment by tcoffee-google** [comment]
@omaray do we yet have any further guidance on this?

**Comment by garrettjonesgoogle** [comment]
I'm going to close this out because it doesn't seem clear that we know what we want to do. We can file a new issue when we know.
