### ISSUE TITLE
Support for GCS Cloud Pub/Sub Notifications

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-java#1420]
GCS has a new feature (currently in private alpha) wherein buckets can be configured to send object change notifications to Cloud Pub/Sub topics, rather than as push notifications to HTTPS endpoints.

In gcloud-java, I imagine such a feature might look something like this:

    Storage storage = StorageOptions.getDefaultInstance().getService();
    PubSub pubsub = PubSubOptions.getDefaultInstance().getService()

    Bucket bucket = storage.get(BUCKET_NAME);
    Topic topic = pubsub.getTopic(TOPIC_NAME);
    NotificationConfig notificationConfig = bucket.sendNotificationsTo(topic);

**Comment by BrandonY** [comment]
FYI, this feature is now in public beta.

**Comment by b-turk** [comment]
+1 for this enhancement

**Comment by danoscarmike** [comment]
@BrandonY, as we are tracking all GCS feature requests internally I will add it to the feature backlog page in the repo wiki: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
