### ISSUE TITLE
[Datastore question] How to build AllocateIdRequest?

### ISSUE THREAD

**Issue by GabiAxel** [GoogleCloudPlatform/google-cloud-java#1428]
Greetings,

As I understand, a Java `AllocateIdsRequest` instance can be built using `Key`s or `PathElement`s, but according to the API it expects the key to contain incomplete paths. I saw no public way to build a `Key` without an id or name, and I no public way to get the path of an `IncompleteKey`. Can you please provide and example of building an `AllocateIdsRequest` from a string representing the kind? Also, wouldn't it make sense to be able to build `AllocateIdsRequest` from `IncompleteKey`s?

Thanks.

**Comment by garrettjonesgoogle** [comment]
I will try to investigate this question within a few days.

**Comment by sai-pullabhotla** [comment]
@GabiAxel - Are you possibly looking for something like this? 

```java
Datastore ds = DatastoreOptions.newBuilder().build().getService();
//Create an incomplete key for kind, MyKind...
IncompleteKey incompleteKey = ds.newKeyFactory().setKind("MyKind").newKey();
System.out.println(incompleteKey);
//Allocate the ID 
Key completeKey = ds.allocateId(incompleteKey);
System.out.println(completeKey);

```
This would print the below to the console: 

```
IncompleteKey{projectId=my-project-id, namespace=, path=[PathElement{kind=MyKind, id=null, name=null}]}
Key{projectId=my-project-id, namespace=, path=[PathElement{kind=MyKind, id=5640376756994048, name=null}]}

```

**Comment by GabiAxel** [comment]
Yes, that's it. Thanks.

**Comment by garrettjonesgoogle** [comment]
Looks like the question was answered - closing out the issue.
