### ISSUE TITLE
Republish javadocs to show latest (0.7.0)

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1435]
SCENARIO
- Navigate to https://github.com/GoogleCloudPlatform/google-cloud-java
- Click on the doc link at the top: http://googlecloudplatform.github.io/google-cloud-java

EXPECTED RESULTS
- You should navigate to the 0.7.0 docs at http://googlecloudplatform.github.io/google-cloud-java/0.7.0/index.html

ACTUAL RESULTS
- You navigate to the 0.6.0 docs at: http://googlecloudplatform.github.io/google-cloud-java/0.6.0/index.html

(And clicking on "Read The Docs" button takes you to the javadoc of the 0.6.0 as well and it should be 0.7.0)

**Comment by garrettjonesgoogle** [comment]
Docs are now published for 0.7.0.
