### ISSUE TITLE
Logging should support loggers besides JUL

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1439]
http://blog.takipi.com/is-standard-java-logging-dead-log4j-vs-log4j2-vs-logback-vs-java-util-logging/

Most GH projects use logback (aka SLF4J), we should work with that easily.

**Comment by lesv** [comment]
@jabubake We should provide your slf4j adapter here.

**Comment by bbzg** [comment]
How would one go about to log in the correct format using SLF4J, for ingestion through google fluentd on GKE?

I am using spring boot and logging through slf4j (output to stdout and automatically ingested through fluentd that is running in GKE/Kubernetes).

My problem is that the standard logback format does not get ingested properly by fluentd/stackdriver (multiple rows get split, wrong log levels, etc.).

Thanks.

**Comment by jabubake** [comment]
@bbzg : 
If you want to use fluentd directly, https://stackoverflow.com/questions/37420400/how-do-i-map-my-java-app-logging-events-to-corresponding-cloud-logging-event-lev might have the answer to your formatting concern.

You can also log directly to Stackdriver using the google-cloud-logging library. Logback support has just been added.
https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-logging-logback

**Comment by bbzg** [comment]
@jabubake Thank you for your fast reply.

Do you know if there are any pros/cons to logging directly to stackdriver, instead of using kubernetes fluentd?

I took a look at the stackoverflow answer, but I am unsure how to properly configure it, since the example given would log to a file and I guess fluentd is using stdout/stderr, but I will try to read up on some documentation.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
