### ISSUE TITLE
Google Storage parallel upload

### ISSUE THREAD

**Issue by pditommaso** [GoogleCloudPlatform/google-cloud-java#1440]
Does the Google Storage Java SDK provides an API for parallel multi-parts upload? Is there any example out there?

**Comment by garrettjonesgoogle** [comment]
I will take a look but I won't be able to get to this immediately.

**Comment by pditommaso** [comment]
Any update on this? Tx

**Comment by garrettjonesgoogle** [comment]
@lesv or @tswast do either of you know?

**Comment by tswast** [comment]
I don't know.

Only sample for uploading I'm aware of is https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/BucketSnippets.java#L227 linked from https://cloud.google.com/storage/docs/object-basics#storage-upload-object-java which doesn't explicitly do a multi-part upload.

**Comment by pditommaso** [comment]
Plain upload it's quite easy. The [documentation](https://cloud.google.com/storage/docs/composite-objects) suggest that parallel upload can be implemented just splitting the original object in chunks and upload them in parallel, them compose all the chunks in a single object. 

It's not clear how to perform the compose operation by using the Java API.

**Comment by lesv** [comment]
Looking at `Storage.writer`, it doesn't appear that there is a way to get more than one `WriteChannel`.  But I didn't work on that API, @tswast might know more.

**Comment by tswast** [comment]
We don't have any code samples at https://cloud.google.com/storage/docs/composite-objects so my guess is the client libraries don't support it in any language. I'll follow up with Omar.

**Comment by lesv** [comment]
@tswast This seems like it should be a FR, rather than block GA -- thoughts?

**Comment by tswast** [comment]
Yeah, definitely a new feature for the client libraries to support the compose operation. I don't know enough about how people tend to use Cloud Storage to know if it should be a GA blocker.

Seems like it would be a useful feature for large files.

**Comment by frankyn** [comment]
I found this issue in the sample sheet. I reviewed current Storage examples and the compose operation is supported by the Java client.  

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/c3d18ffce9d9895550dd5d2acc1d0ff125305898/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L446

**Comment by pditommaso** [comment]
This is still an open issue on my side. I will give a try to this example. Thanks.

**Comment by garrettjonesgoogle** [comment]
Closing this out because the compose operation is supported in google-cloud-storage.
