### ISSUE TITLE
BigQuery: Add support to FormatOptions for AVRO

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1441]
`configuration.load.sourceFormat` accepts  `CSV`, `DATASTORE_BACKUP`, `NEWLINE_DELIMITED_JSON`, and `AVRO`. See the [API reference docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs).

[FormatOptions](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/FormatOptions.java) is missing an option for Avro.

**Comment by garrettjonesgoogle** [comment]
This is additive - we will work on it after beta is declared.

**Comment by vam-google** [comment]
Resolved.
