### ISSUE TITLE
Fully document supported retry mechanisms

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#1445]
There does not seem to be any documentation for what retry mechanisms are implemented by the clients (except for "Supporting new services" docs -- which are not relevant to most users).  Would be wonderful if this were highlighted, explicitly.  These cases are important in particular for users to decide whether to implement their own error handling:
1.  Re-tryable errors.
2. Non-retryable errors.
3. Prolonged non-retry-able errors (hours).

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
