### ISSUE TITLE
Error reporting library

### ISSUE THREAD

**Issue by karan** [GoogleCloudPlatform/google-cloud-java#1447]
Error Reporting client library seems to be missing implementation (auto gen code?). It would be very useful to have that done along with some instrumentation (handling SIGTERM for example).

I could not find another tracking bug for that.

**Comment by lesv** [comment]
@garrettjonesgoogle @tswast One of us should do this, I'll add you to a doc.

**Comment by steren** [comment]
Note that the Error Reporting client library is available: http://googlecloudplatform.github.io/google-cloud-java/0.5.0/apidocs/com/google/cloud/errorreporting/spi/v1beta1/package-summary.html

What is not available is an idiomatic instrumentation library.

**Comment by lesv** [comment]
Jisha will do this, but she's not yet on this team, so I can't assign her the issue.

**Comment by lesv** [comment]
This got subsumed by using thread dump from @karan 's team.

**Comment by garrettjonesgoogle** [comment]
@lesv what are we currently intending on doing for this issue?

**Comment by lesv** [comment]
We are going to do nothing.  Michael and Karan's team are adding something to get a thread dump to stdout. (kill -3) 

Jisha will be open sourcing her work after Next.
