### ISSUE TITLE
[NIO] Make CloudStorageFileSystem#newFileSystem more lenient in the URIs it accepts

### ISSUE THREAD

**Issue by tomwhite** [GoogleCloudPlatform/google-cloud-java#1450]
Currently the URIs must be of the form `gs://bucket`, and URIs with port, user info, path, query or fragment parts will fail.

This seems to be unnecessarily restrictive, and causes legitimate uses to fail - e.g. if we are [trying to find a FileSystem for a given URI](https://github.com/broadinstitute/gatk/blob/5e17764f74fdf110d4ea09cc0b5508fbad9a1305/src/main/java/org/broadinstitute/hellbender/utils/io/IOUtils.java) then we shouldn't have to know that GS is more restrictive than other providers, and remove everything from the URI except the scheme and host.

I suggest that the implementation accept the extra information in URIs and just ignore it.

**Comment by jean-philippe-martin** [comment]
Fixed in #1470.
