### ISSUE TITLE
How launch many instances at once? 

### ISSUE THREAD

**Issue by pditommaso** [GoogleCloudPlatform/google-cloud-java#1458]
The snippet at [this link](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/compute/snippets/CreateInstance.java) shows how launch a compute instance, however I was unable to find in the API a way to specify the number of instances to run. 

Is that possible or it is needed to invoke the `create` operation as many times as the number of instances to launch ?

**Comment by unitydynamics** [comment]
If you create an InstanceGroup you can size up/down using [resize](https://cloud.google.com/compute/docs/reference/latest/instanceGroupManagers/resize) function with code like this:

`Compute.InstanceGroupManagers.Resize resizeRequest = computeService.instanceGroupManagers().resize(APPLICATION_NAME, COMPUTE_ZONE, COMPUTE_GROUP, myNumberOfDesiredInstances);`
resizeRequest.execute();

**Comment by pditommaso** [comment]
I see. However instance groups and templates are only exposed via `com.google.api.services.compute.Compute` and not (yet?) implemented by the  `com.google.cloud.compute.Compute` interface. 

Quite confusing.

**Comment by pditommaso** [comment]
I'm still struggling with this problem. Stating version `0.8.1-alpha` it looks that there's no API to handle Instance groups and Instance templates. Could you please confirm that and there's any plan to support them?

**Comment by pditommaso** [comment]
Tried version `0.10.0-alpha`. Still no solution to launch more than one instance in a single request.

**Comment by garrettjonesgoogle** [comment]
We are going to be doing some work on the Compute client over the next several months. Unfortunately we won't be addressing anything in the short term, though.

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
