### ISSUE TITLE
Missing READMEs

### ISSUE THREAD

**Issue by michaelbausor** [GoogleCloudPlatform/google-cloud-java#1466]
Some APIs don't have READMEs:
- [ ] Language
- [ ] Speech
- [ ] Vision

**Comment by garrettjonesgoogle** [comment]
Marking as "Blocking GA" because part of the library will be GA soon, so we at least want all of the components minimally documented.

**Comment by garrettjonesgoogle** [comment]
Removed release-blocking label, because this applies to APIs that aren't going 1.0.0 in google-cloud-java.
