### ISSUE TITLE
FR: version numbers

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1471]
Currently our versions are a bit weird.

`0.8.0` designates an alpha version
`0.8.0-beta` designates a beta, and presumably
`1.0.0` will be our first GA

That's well and good for now though a bit confusing.  I'd like to suggest that code that from now on, code that is not beta, be designated `-alpha` and not `0.8.0`.

The real problem is when we go GA however.  We will have a `-SNAPSHOT` which is top of tree Master; we will likely have a Pre-Release (or early release), a Current, and a last release.

Unfortunately, maven doesn't really understand `-alpha` or `-beta` designations in a clear way.  It considers them to be a "[qualifier](http://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-syntax.html)" and sorts them alphabetically.  So while it might allow updating from -alpha to -beta, it is unlikely to update to a GA version. 

For those of us who use automation (like the [versions plugin](http://www.mojohaus.org/versions-maven-plugin/)) this is a bit of a problem.

The auth library chose to go with all release update the major version (first # before the dot).  

I wish I had a clear suggestion to go with your desire to be clear that this is a `beta` release.  I don't.  But I wish you had gone with a the java standard rather that following the path of some of our other teams and making something up that isn't idiomatic.

@omaray @garrettjonesgoogle @tswast

**Comment by garrettjonesgoogle** [comment]
Everything GA and after will follow the path you are describing. We are not going to put "-beta" on 1.x+ releases. For pre-1.x, the plan is to currently not have any package where both 0.x.y and 0.x.y-beta exist.

**Comment by garrettjonesgoogle** [comment]
Plan of record:

Already-existing packages:
* alpha: 0.y.z-alpha-SNAPSHOT and 0.y.z-alpha
* beta: 0.y.z-beta-SNAPSHOT and 0.y.z-beta
* GA: x.y.z-SNAPSHOT and x.y.z

New packages:
* alpha: 0.0.z-SNAPSHOT and 0.0.z
* beta: 0.y.z-SNAPSHOT and 0.y.z
* GA: x.y.z-SNAPSHOT and x.y.z

**Comment by garrettjonesgoogle** [comment]
Closing out this issue because we have put this plan into action already.
