### ISSUE TITLE
FR: Datastore should use gRPC and be Async

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1472]
Perhaps we can incorporate parts of [Spotify's library](https://github.com/spotify/async-datastore-client).

**Comment by lesv** [comment]
Sigh - I should finish reading before writing bugs - Spotify's library is just Async not gRPC based.

**Comment by garrettjonesgoogle** [comment]
Also, this is already tracked in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/493 . Closing this issue in preference to the existing one.
