### ISSUE TITLE
Branding updates required for Translate API veneer libraries

### ISSUE THREAD

**Issue by merla18** [GoogleCloudPlatform/google-cloud-java#1476]
On November 15, 2016, Google launch a rebranding of Google Translate API to Google Cloud Translation API. This does not impact the method names but the URLbase as well as readmes, samples and comments.
URLbase has been already updated to translation.googleapis.com

We need to have now for Client library, the readme, client library docs, samples and code comments updated to use "Google Cloud Translation API" instead of Google Translate API. The short version of the new name is "Cloud Translation API" or "Translation API:"

Note: the product Google Translate still exists. It is the API Google Translate API that has been rebranded.

**Comment by merla18** [comment]
there are still 1 Translate reference in the Readme. See Readme.md https://github.com/GoogleCloudPlatform/google-cloud-java 

And It is not listed in the readme of Go. https://github.com/GoogleCloudPlatform/google-cloud-go#supported-apis

**Comment by garrettjonesgoogle** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1867 .
