### ISSUE TITLE
GAPIC-only client libs missing from ReadMe list

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1478]
SCENARIO
Navigate to the [ReadMe](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/README.md) for google-cloud-java.

EXPECTED
We should see a list of all the Beta and Alpha client libraries.

ACTUAL
We are not seeing the GAPIC-only client libs in that list (e.g. Vision, Speech, Language, Monitoring). We should add them to the Alpha list (for now):

![image](https://cloud.githubusercontent.com/assets/6609430/21211173/28eaf962-c236-11e6-9cbc-6ccf06e875fb.png)

NOTE
We need to chat about how to show an example too for the GAPIC libs. And perhaps also update the individual readmes.

**Comment by garrettjonesgoogle** [comment]
Marking as "Blocking GA" because part of the library will be GA soon, so we at least want all of the components minimally documented.

**Comment by shinfan** [comment]
Fixed with https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1983
