### ISSUE TITLE
BigQuery: Add support for struct query parameters

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1486]
`QueryParameterValue` does not currently support STRUCT parameters.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/0f6a47e19cc51a8baa9e13d9f1bb8d23c105e00a/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java#L58

See the API docs: https://cloud.google.com/bigquery/querying-data#using_structs_in_parameterized_queries for how these work in the API and an example query.

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
