### ISSUE TITLE
Tracking issue for PubSub high-perf client integration

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1493]
This issue tracks items we need to do to go from "the code works" to "we're happy with it"

- [ ] Document explaining migration to HP client
- [ ] Figure out the proper configuration for Publisher and Subscriber
  - Can executors be shared with the rest of the program?
  - Does each connection have its own channel?
  - See https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1487 for context
- Sample code
  - [ ] Publisher
  - [ ] Subscriber
- Code snippets
  - [ ] Publisher
  - [ ] Subscriber

**Comment by davidtorres** [comment]
- I prefer if we keep separate executors for publisher and subscriber (but also give the alternative for the user to provide his own executor). The reason being that it is easier to debug thread starvation problems and thread dumps when the executors are separate (i.e. you don't want the subscriber executor to starve the publisher if having problems to pull, renew-deadlines, etc)

**Comment by davidtorres** [comment]
- In regards to the multiple channels, we need many channels in order to achieve the desired throughput

**Comment by garrettjonesgoogle** [comment]
@pongad we may have taken care of enough of this tracking issue - maybe close it out, and if there are any tail-end tasks, create separate issues for them. I would like to avoid zombie issues.

**Comment by pongad** [comment]
This was a tracking issue for bundling implementation integration. That work is much more long term than I thought previously. Let's close it out.
