### ISSUE TITLE
Failed to import com.google.cloud.bigquery after authentication

### ISSUE THREAD

**Issue by bowen0603** [GoogleCloudPlatform/google-cloud-java#1498]
Hi, I have configured the maven dependency, and been authenticated with the Cloud SDK, but when I am writing the quickstart code in Intellij, it shows me that the bigquery symbol cannot be resolved for some reason in the importing line as below. 

Did I miss something, or did anything improperly? Could anyone help me out? Thanks a lot!

![screen shot 2017-01-02 at 6 19 57 am](https://cloud.githubusercontent.com/assets/22078411/21583249/75761506-d0b3-11e6-8f4f-b6b857fc961e.png)

**Comment by bowen0603** [comment]
Anyone could help me out on this issue?

**Comment by garrettjonesgoogle** [comment]
Sorry I didn't get a chance to look into the issue before you closed it - did you figure it out?

**Comment by bowen0603** [comment]
Yes, I figured it out. For some reason, I still need to import the library into the IDE - Intellij, only have the maven is not enough. So it works now. Thanks! @garrettjonesgoogle
