### ISSUE TITLE
MaxMessageSize too low for Cloud Pub/Sub

### ISSUE THREAD

**Issue by mdietz94** [GoogleCloudPlatform/google-cloud-java#1499]
Cloud Pub/Sub allows responses of up to 20 MB, so the channel default of 4 MB causes deframing errors for users, as can be seen here https://code.google.com/p/cloud-pubsub/issues/detail?id=50 . MaxMessageSize should either be increased to at least 20 MB, or else users should be given the ability to change it themselves.

**Comment by garrettjonesgoogle** [comment]
@pongad : I'm unsure if this is already addressed in the pubsub-hp branch.

**Comment by pongad** [comment]
This issue seems to be alleviated by https://github.com/grpc/grpc-java/issues/2307 . As of GRPC 1.0.3 though, the fix hasn't been merged...

**Comment by pongad** [comment]
@garrettjonesgoogle This is now available [here](http://www.grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize-int-). It is marked experimental though. Are we OK to use this? I'm a little worried about ABI compatibility with later releases. Or do we plan to shade the entire gRPC?

**Comment by garrettjonesgoogle** [comment]
Good catch. I'm trying to get away from dependencies on experimental features. We will need to think about this.

**Comment by garrettjonesgoogle** [comment]
Filed issue https://github.com/grpc/grpc-java/issues/2763 .

**Comment by garrettjonesgoogle** [comment]
Maybe we could mark it as experimental on our own surface too, so that users can make their own choice about whether to depend on it.

**Comment by garrettjonesgoogle** [comment]
Hmm ideally we wouldn't actually want to expose this on our surface, since this can be completely determined by which API is in use.

**Comment by garrettjonesgoogle** [comment]
@pongad  - GAX issue: https://github.com/googleapis/gax-java/issues/149 - please resolve that issue if for some reason no GAX change is necessary to support Pub/Sub.

**Comment by pongad** [comment]
@mdietz94 Sorry it took me so long to get to this. I want to make sure. This is only for Subscriber right? The Publisher is unaffected?

**Comment by mdietz94** [comment]
Yes, this is only inbound message size, so this only affects Subscriber.

**Comment by garrettjonesgoogle** [comment]
This has been fixed for a while. https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1911 moved the grpc call into GAX, so that it's no longer made directly from google-cloud-java. Resolving.
