### ISSUE TITLE
Update the team page on the website

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1503]
http://googlecloudplatform.github.io/google-cloud-java/0.8.0/team-list.html

Is out dated.  We should probably just link to repo team.

**Comment by garrettjonesgoogle** [comment]
Marking "Blocking GA" because this would look silly to have out of date at launch time.

**Comment by lesv** [comment]
This requires changing the root `pom.xml`.  I don't have your team list, so I'm going to assign you @garrettjonesgoogle
