### ISSUE TITLE
Question - How do you rename/move an object in a Storage Bucket?

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/google-cloud-java#1513]
What the efficient way to do a rename or move?  Storage shows update(), delete()... but I didn't find what I was looking for.

**Comment by jskeet** [comment]
There's no single move operation in the Storage API. For .NET, as per https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/398, we decided not to try to fake one in the client library - there's too much that would be app-specific in terms of how to handle failures.

**Comment by garrettjonesgoogle** [comment]
@danoscarmike why is this in the First 4 (GA) project? We don't have it marked Blocking GA.

**Comment by garrettjonesgoogle** [comment]
I am going to resolve this for now because we don't plan to support it in the library as a feature.
