### ISSUE TITLE
Why there are two libraries: com.google.api.services.bigquery and com.google.cloud.bigquery?

### ISSUE THREAD

**Issue by bowen0603** [GoogleCloudPlatform/google-cloud-java#1514]
I am running into this problem, and very confused. It seems there are two different libraries I can use. 

One is com.google.cloud.bigquery where I see it from this source: https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-usage-java

The other one is com.google.api.services.bigquery where I see it from this source: https://github.com/googlearchive/bigquery-samples-java/blob/master/src/main/java/com/google/cloud/bigquery/samples/BigQueryJavaGettingStarted.java

The problem I am trying to solve is to set a destination table for the query. Most online QAs point me to use the second source. I followed the first source to set it up, and I am able to connect to the Bigquery now. The only problem is I cannot find a way to set the destination table. 

I am super confused about these two libraries, and hope to have some explanations. Thanks!

**Comment by polleyg** [comment]
@bowen0603 - the first one is the new client library that Google started rolling out last month. This is the recommended one to use. Although bear in mind it's still in [beta](
https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bigquery).

> Note: This client is a work-in-progress, and may occasionally make backwards-incompatible
   changes.

The second one is the older library. You can still use this of course, but the new libraries are much nicer to use. In fact, the new one simply wraps the old one and abstracts away its nuances, and provides a much more idiomatic API.

More info here: https://cloudplatform.googleblog.com/2016/12/announcing-new-google-cloud-client.html

**Comment by bowen0603** [comment]
Thanks for your reply and clarification! @polleyg It is very helpful :)

**Comment by SampoDev** [comment]
I'm trying to execute apache beam sdk 2.4 and the libraries  com.google.cloud.bigquery but thow exception

Exception in thread main java.lang.NoSuchMethodError com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(LjavalangString;)LcomgoogleapiclientgoogleapisservicesAbstractGoogleClient$Builder;
	at com.google.api.services.bigquery.Bigquery$Builder.setBatchPath(Bigquery.java3519)

import com.google.cloud.bigquery.*;

<dependencies>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-sdks-java-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-runners-direct-java</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.cloud.dataflow</groupId>
            <artifactId>google-cloud-dataflow-java-sdk-all</artifactId>
            <version>[2.4.0, 2.99)</version>
        </dependency>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.14</version>
        </dependency>

       <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.14</version>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquery</artifactId>
            <version>1.35.0</version>
        </dependency>

    </dependencies>


the code example apache beam 2.4 using 
import com.google.api.services.bigquery.model.TableFieldSchema;
import com.google.api.services.bigquery.model.TableRow;
import com.google.api.services.bigquery.model.TableSchema;

If I use the the libraries om.google.api.services.bigquery.  the code example run successfully .

What library is it using internally?

**Comment by bin-shi-exa** [comment]
This com.google.cloud.bigquery is the new API.
