### ISSUE TITLE
Consider using "TimeUnit.<unit>.sleep(x)" for code examples

### ISSUE THREAD

**Issue by polleyg** [GoogleCloudPlatform/google-cloud-java#1518]
In most code examples given (both in GitHub & official docs) where a `sleep` is needed, then `Thread.sleep(x)` is used. For example:

- https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bigquery
- https://cloud.google.com/bigquery/querying-data

For better readability/clarity, then it may be prudent to consider using the `TimeUnit` class instead. Yes, it's all the same as it calls `Thread.sleep(x)` under the hood, but consider the following as an example:

`Thread.sleep(180000)` vs. `TimeUnit.MINUTES.sleep(3)`

More info: http://stackoverflow.com/questions/9587673/thread-sleep-vs-timeunit-seconds-sleep

**Comment by lesv** [comment]
Better not to include sleep in the samples, unless we expect users to use it as well. Instead put them in the tests for those samples.

However, if you really most use sleep, then this probably should be preferred.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1445). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
