### ISSUE TITLE
BigQuery: support labels field of Datasets and Table resources

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1525]
Docs (talks about datasets, but tables can have labels, too):
https://cloud.google.com/bigquery/docs/labeling-datasets

API references:
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#labels
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#labels

If the `patch` request is not yet supported, this will be needed, too.
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets/patch
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch

**Comment by rouzwawi** [comment]
Any update on this issue?

We're looking to use the high-level `BigQuery` client to read labels for datasets. But neither `bigquery.listDatasets(...)` nor `bigquery.getDataset(...)` propagate the labels field from low level protobuf types up to `Dataset`.

I could open a PR as it seems to be a simple fix.

**Comment by garrettjonesgoogle** [comment]
@rouzwawi we would welcome your contribution for this :-)

**Comment by garrettjonesgoogle** [comment]
We have a project to prepare BigQuery for GA, and this feature is part of the list (P0 for dataset labels, P2 for table labels). I'm going to close this out and let the feature be tracked internally.
