### ISSUE TITLE
Deprecate AsyncLoggingHandler?

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/google-cloud-java#1532]
The fix for #1386 has made the normal LoggingHandler asynchronous!  Was this deliberate? If so, should the AsyncLoggingHandler be deprecated as it now no longer changes behaviour.

**Comment by garrettjonesgoogle** [comment]
I think this needs to be cleaned up before GA.

**Comment by garrettjonesgoogle** [comment]
We should delete this altogether, and support a setting for sync v async in the logging config.

**Comment by michaelbausor** [comment]
Closed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1716

**Comment by gregw** [comment]
Could the AsyncLoggingHandler be left as a deprecated extension of LoggingHandler, as that will make transitioning usage easier?
