### ISSUE TITLE
Implement Publisher/Subscriber stats

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1542]

**Comment by garrettjonesgoogle** [comment]
@pongad Is this a blocker for beta or is it post beta?

**Comment by lesv** [comment]
Consider DropWizard #1209

**Comment by pongad** [comment]
@garrettjonesgoogle I don't think this is beta blocking. @davidtorres , what do you think?

**Comment by lesv** [comment]
Definitely not blocking.

**Comment by davidtorres** [comment]
Not blocking from the Pub/Sub side.

**Comment by garrettjonesgoogle** [comment]
I'm going to close this out - I don't see any external demand here; if we feel we need to implement this later, we can track it differently.
