### ISSUE TITLE
GqlQuery - Allow binding of null 

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1559]
The GqlQuery.Builder's addBinding and setBinding methods allow binding of various data types, but not a null. Can the API be enhanced to allow binding of a null/NullValue instead of having to use different GqlSyntax based on the search string (null vs not null)?

**Comment by sai-pullabhotla** [comment]
Looking through the code, I found that when an empty array is passed, it is interpreted as a `NullValue`. However, since there are multiple addBinding/setBinding methods for each type, we cannot just use - 

`builder.addBinding()` 

That causes ambiguity to the compiler. 

so, one could use 

`addBinding(new boolean[0])` or `addBinding(new String[0])` to actually search for a `null`. This is not that intuitive. Perhaps, another method `addNullBinding()` and `setNullBinding()` might be a better option?

**Comment by hzyi-google** [comment]
This is added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
