### ISSUE TITLE
BigQuery: LoadJobConfiguration to support schemaUpdateOptions

### ISSUE THREAD

**Issue by juhoautio** [GoogleCloudPlatform/google-cloud-java#1566]
`configuration.load.schemaUpdateOptions` is documented in the [REST API docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs), but `LoadJobConfiguration` doesn't have a way to set it. Actually the protobuf model class seems to have a setter.

It's not clear in the documentation whether `schemaUpdateOptions` are valid also for partitioned tables or not. Would be nice to get a clarification for that.

**Comment by tcoffee-google** [comment]
Doc issue reported as b/62535154.
