### ISSUE TITLE
Publish the docs for 0.8.1

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1571]
It seems like everything became 0.8.1. The docs are still at 0.8.0:

http://googlecloudplatform.github.io/google-cloud-java/0.8.0/index.html

And in fact, the Monitoring example shown in the current docs failed because the method `formatGroupName` doesn't exist it seems:

```
 try (GroupServiceClient groupServiceClient = GroupServiceClient.create()) {
   String formattedName = GroupServiceClient.formatGroupName("[PROJECT]", "[GROUP]");
   Group response = groupServiceClient.getGroup(formattedName);
 }
```

I had to look at the generated code to find the working sample. Hence, I assume this should be fixed with 0.8.1.

**Comment by garrettjonesgoogle** [comment]
Done.
