### ISSUE TITLE
Convert from Maven to Gradle

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1587]
Reasons:

1. We can migrate the release process out of bash and into build scripts
2. We can migrate the snippet update process out of python and into build scripts
3. The rest of the team's Java repositories are in Gradle (`toolkit`, `gax-java`)

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here.
