### ISSUE TITLE
Feature Request: Discourage use of API_KEY in translate

### ISSUE THREAD

**Issue by gguuss** [GoogleCloudPlatform/google-cloud-java#1594]
At the request of @puneith, we should remove, deprecate, or otherwise discourage using the API_KEY form of authorization favoring the GOOGLE_APPLICATION_CREDENTIALS for Cloud APIs to make the library consistent with the Python client library for Translate.

The affected method is [setApiKey](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/60270261fa763131f6cd6b9aacfc7819e0af1c3d/google-cloud-translate/src/main/java/com/google/cloud/translate/TranslateOptions.java#L118) in the **TranslateOptions** builder.

**Comment by tcoffee-google** [comment]
Fixed by #2147.
