### ISSUE TITLE
remove pubsub Mockito dependency

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1596]
maybe use easymock instead

**Comment by pongad** [comment]
@garrettjonesgoogle I just realized that mockito is also used in google-cloud-contrib and google-cloud-spanner. Do we want to allow use to Mockito? Or do we want to rip it out from those too?

**Comment by vkedia** [comment]
Whats the concern with Mockito?

**Comment by pongad** [comment]
Most of the libraries uses Easy Mock. It's probably better if we can use just one instead of two, though I'm not sure if using both is necessarily a bad thing.

**Comment by garrettjonesgoogle** [comment]
google-cloud-contrib is a "side artifact", so it doesn't affect google-cloud. I think we should rip it out of google-cloud-spanner.

@pongad is correct, we want to use only one mocking system instead of two.
