### ISSUE TITLE
Custom log enhancers prevented due to visibility of LoggingHandler.Enhancer interface

### ISSUE THREAD

**Issue by jscinoz** [GoogleCloudPlatform/google-cloud-java#1597]
com.google.cloud.logging.LoggingHandler allows enhancer classes to be configured to augment created LogEntry & MonitoredResource instances.

The Enhancer interface is package-private, preventing the implementation of custom Enhancers (unless one resorts to putting their third-party Enhancer implementation in the com.google.cloud.logging package). As there's only a single Enhancer implementation shipped with the library (GaeFlexLoggingEnhancer), this makes the entire Enhancer functionality not terribly useful.

Is this intentional or simply an oversight?

**Comment by garrettjonesgoogle** [comment]
Yeah that seems like a mistake, since the constructor that takes `Enhancer`s is public.
