### ISSUE TITLE
Storage: add support for Per-Object Storage Class

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1602]
We need to add support for Per-Object Storage Class (POSC).

Here some extra information to help:

- [POSC info from Cloud Storage documentation](https://cloud.google.com/storage/docs/per-object-storage-class)
- [POSC example with JSON API](https://cloud.google.com/storage/docs/changing-storage-classes)
- [Storage Class info from Cloud Storage documentation](https://cloud.google.com/storage/docs/storage-classes)

On top of that, google-cloud-dotnet has made an implementation which can be used as reference. 

- [Please view the Pull Request to understand the changes](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/766)

If you have any implementation questions, please direct them at jskeet

/cc @jskeet @danoscarmike

**Comment by lesv** [comment]
@omaray Someone suggested this should block GA - since I was getting it 3rd hand, I'm going to defer to your judgment on this one.
