### ISSUE TITLE
BigQuery: insertAll should help convert a byte[] array to base64.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1603]
See the snippet for insertAll:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/fa0720c65576ed68419772b04b463176bc8061d7/google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java#L405

The example shows a base64 string. I would love to have a feature where a byte array could be entered and the library handles the conversion.

Marked as "triaged for GA" because this is not a blocker.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
