### ISSUE TITLE
Which Java client library to use?

### ISSUE THREAD

**Issue by jatins** [GoogleCloudPlatform/google-cloud-java#1605]
The entire Java API situation seems a bit confusing. 

A google search for "Google compute Java api" brings up this as the first result: [**Google API Client Libraries - Compute**](https://developers.google.com/api-client-library/java/apis/compute/v1)

However, the recommended way to work with GCP seems to be [**google-cloud**](http://googlecloudplatform.github.io/google-cloud-java/0.8.3/index.html) .

> google-cloud is built specifically for the Google Cloud Platform and is the recommended way to integrate Google Cloud APIs into your Java applications

which would have been fine if the docs had a link to it but the [**compute engine docs**](https://cloud.google.com/compute/docs/api/libraries) for client libraries makes no mention of `google-cloud`, but rather links to [Google APIs Java Client Library](https://cloud.google.com/compute/docs/api/libraries#google_apis_java_client_library) (the maven version mentioned there did not resolve for me)

I think it'd be great if the documentation clearly mentioned which was the recommended way forward. 

--
This [**image**](https://lh3.googleusercontent.com/FRQQdZAvn7lk1UdlnnTNe_QvOc5EdMiHYB_Dy2xdP7Ut28X6TkDJ5RwrxejKHdJ_8wbgx2fd7SK4mCDSQLh0JnN4lOwUvQY=s1600) on the [Google API Client Libraries | Java](https://developers.google.com/api-client-library/java/) home page is the only thing that gives the  "not recommended" vibe.

**Comment by steve1337** [comment]
As far as I know you can find the current Java client libs here:

https://mvnrepository.com/artifact/com.google.cloud/google-cloud-storage

**Comment by jatins** [comment]
@steve1337 That's correct. I just meant that the discoverability of that is hard. For example, as I mentioned, the [compute engine docs for client libraries](https://cloud.google.com/compute/docs/api/libraries) makes no mention of `google-cloud` Java client.

**Comment by omaray** [comment]
Hi Jatins. Thanks for the message. 

So the reason why you don't see support for the Compute Engine API with google-cloud is because it hasn't been implemented yet. So indeed, the Google API Client Library is the recommended way for now.

As feedback to us, how could have this been clearer to you?

**Comment by jatins** [comment]
@omaray Aren't these [official examples](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/compute/ComputeExample.java) using the `google-cloud` compute api ?

And in these [docs](http://googlecloudplatform.github.io/google-cloud-java/0.8.3/apidocs/index.html) for `google-cloud`, I do see a package for `com.google.cloud.compute` (can't link to it, but here's a [screenshot](https://cloud.githubusercontent.com/assets/1556536/23100385/752fa7f2-f6a5-11e6-909e-765cd06ea4c5.png))

**Comment by omaray** [comment]
Hey Jatins. So sorry for such the long delay. So there might have been a side manual effort to indeed add support. 

However, it's such a big APIs that doing it by hand is not the right approach here. We have a better automated approach that we hope will come soon. The automated approach allows for many advantages: (1) the surface is pretty simple (though large) and is easier to automate (2) if compute changes then everyone gets the updates quickly with a regeneration.

**Comment by jatins** [comment]
@omaray Thanks for the update.

I ended up using [Google API Client Libraries | Java](https://developers.google.com/api-client-library/java/).
