### ISSUE TITLE
Fill out integration tests for BigQuery

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1609]

**Comment by garrettjonesgoogle** [comment]
Feature hole discovered: Date, Time, and DateTime are not supported as query outputs yet. Filed issue: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1792

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
