### ISSUE TITLE
Add support for table.externalDataConfiguration

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1610]
Add support for table.externalDataConfiguration, at a minimum with sourceFormat = "CSV", sourceUris = valid GCS URIs, and the csvOptions.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
