### ISSUE TITLE
More support for DATE, TIME, and DATETIME schema types

### ISSUE THREAD

**Issue by mtagle** [GoogleCloudPlatform/google-cloud-java#1617]
At present you cannot create new fields with types DATE, TIME, and DATETIME.

To do so, you need access to a com.google.cloud.bigquery.Field.Type of that type, and though there are enums of DATE, TIME, and DATETIME, they are never passed to the Type constructor (which is private).

**Comment by garrettjonesgoogle** [comment]
@tswast can you triage?

**Comment by tswast** [comment]
Yes, is the sort of thing that would go under the "create a table" column of the integration tests I requested.

Even though this is for updating a table with a new column, I think the same resource is used.

**Comment by criccomini** [comment]
Out of curiosity, is there a timeline on when this might get addressed?

**Comment by garrettjonesgoogle** [comment]
@criccomini , this is currently marked as a GA release-blocking issue, so we intend to work on it relatively soon. It's hard to give a hard date, though.
