### ISSUE TITLE
com.google.protobuf.GeneratedMessageV3$Builder cannot be resolved

### ISSUE THREAD

**Issue by sAbakumoff** [GoogleCloudPlatform/google-cloud-java#1618]
I am trying to follow the guidelines at
https://cloud.google.com/natural-language/docs/reference/libraries#client-libraries-install-java
The only extra step is adding google-cloud-language dependency in pom.xml file.
But once it's done the following errors are reported:

> The project was not built since its build path is incomplete. Cannot find the class file for com.google.protobuf.GeneratedMessageV3$Builder. Fix the build path then try building this project
> The type com.google.protobuf.GeneratedMessageV3$Builder cannot be resolved. It is indirectly referenced from required .class files

How to fix it?

**Comment by garrettjonesgoogle** [comment]
You are likely mixing different versions of protobuf. `google-cloud` requires 3.0.0, and is incompatible with using beta versions of protobuf (e.g. 3.0.0-beta-3).

**Comment by garrettjonesgoogle** [comment]
No more comments after a week, so I'm going to close this out.
