### ISSUE TITLE
Adding SSH keys via client

### ISSUE THREAD

**Issue by vania-pooh** [GoogleCloudPlatform/google-cloud-java#1619]
Can't get how to add SSH keypairs to cloud. According to these docs: https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#instance-only there's an API project metadata method for that. Is there any example of this action?

**Comment by garrettjonesgoogle** [comment]
This repository (`google-cloud-java`) isn't really the right place for this question; this repository is for java client libraries, not the command line `gcloud`. I would recommend clicking on the pink button in the lower right corner of the page you referenced in order to file a bug.

**Comment by vania-pooh** [comment]
@garrettjonesgoogle no, my question is about Java client. It seems this action is not yet supported in client... or is hidden somewhere in the API. My question is how to add SSH key with client method calls.

**Comment by garrettjonesgoogle** [comment]
Ahh ok. (reopening)

**Comment by tcoffee-google** [comment]
@vania-pooh I believe the methods you need are documented here: http://googlecloudplatform.github.io/google-cloud-java/0.19.0/apidocs/?com/google/cloud/compute/package-summary.html

The first form of `setMetadata` should make it easy to provide arguments in the form in the docs you linked to (under the 'API' tab).

Please re-open this issue if you experience problems using these methods.
