### ISSUE TITLE
pubsub test flakes

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1626]
- [x] https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-java/build/609 (testModifyAckDeadline)
- [ ] https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/builds/215825641

**Comment by pongad** [comment]
This seems to not be flaking anymore. Closing this for the time being.

**Comment by pongad** [comment]
We have new flakes :frowning_face: . Reopening.

**Comment by garrettjonesgoogle** [comment]
Can you give links to the new failures we are seeing?

**Comment by pongad** [comment]
@garrettjonesgoogle It's the unchecked box in the issue description.

**Comment by garrettjonesgoogle** [comment]
Fixed by #1898
