### ISSUE TITLE
Batch copy for storage API

### ISSUE THREAD

**Issue by Horneth** [GoogleCloudPlatform/google-cloud-java#1628]
The storage API implements `delete`, `get`, and `update` methods to add requests to a batch. A `copy` method would be valuable as well. Is it something that can be considered ?

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
