### ISSUE TITLE
google-cloud-spanner: Request ReadOption for descending result order

### ISSUE THREAD

**Issue by archiecobbs** [GoogleCloudPlatform/google-cloud-java#1632]
It's nice to be able to use the `ReadContext.read()` method instead of `ReadContext.executeQuery()` because it's so much more efficient (no SQL parsing, query plan, etc).

To make `ReadContext.read()` more generally useful, this is a request to add a new `ReadOption`  to specify descending sort order (presumably, ascending sort order is the default so no option is needed for that).

Thanks.

**Comment by vkedia** [comment]
ReadContext.read would return the rows in the order of primary key as specified in the schema. By default the primary keys are stored in ascending order but you can [mark any key column as descending](https://cloud.google.com/spanner/docs/data-definition-language#create_table) to store it in descending order. In that case read would return the rows in the descending order of the key. There is no way to change/specify the order of rows returned by read at runtime.
Also we believe that performance characteristics of query and read should be [similar](http://stackoverflow.com/questions/42303190/cloud-spanner-read-vs-cloud-spanner-sql-api). I would advise you to use executeQuery unless there is a compelling reason to use read.

**Comment by archiecobbs** [comment]
> Also we believe that performance characteristics of query and read should be similar. I would advise you to use executeQuery unless there is a compelling reason to use read.

Great, if so then my fears are unfounded and you may close this issue.

However I am still puzzled by something:
> There is no way to change/specify the order of rows returned by read at runtime.

Yes, but don't you agree that this is due simply to a limitation of the API, and not of the underlying capability? After all, I can query `SELECT key, value FROM KeyValue ORDER BY key DESC` so clearly the underlying capability to return results in reverse order exists... in which case, it seems like a silly limitation that you can't get at that functionality via `read()`.

**Comment by vkedia** [comment]
Yes thats a valid point. In theory we should be able to sort order to the API. But given that similar effect can be achieved using query api, we do not have any plans to do so.

**Comment by saturnism** [comment]
the ReadOption has ability to filter, limit, and set page size. it does make sense to provide sort via this as well. It'd make some ORM a bit easier to implement.

**Comment by vkedia** [comment]
@saturnism can you explain the impact of this on ORM? I thought ORMs would just use the query API and not the read API. Also note that this is not really about the Java client. Underlying api does not provide this functionality so this would need to be first added to that.
