### ISSUE TITLE
Spanner: add snippets/samples to all top level methods of main classes

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-java#1637]
We want to ensure that all the methods that represent the interface of an API have samples/snippets to show our users the intended use. Spanner doesn't have such samples/snippets at the moment.

As examples, [BigQuery](http://googlecloudplatform.github.io/google-cloud-java/0.9.2/apidocs/index.html?com/google/cloud/bigquery/BigQuery.html), [Storage](http://googlecloudplatform.github.io/google-cloud-java/0.9.2/apidocs/index.html?com/google/cloud/storage/Storage.html), and [Datastore](http://googlecloudplatform.github.io/google-cloud-java/0.9.2/apidocs/index.html?com/google/cloud/datastore/Datastore.html) all have these snippets that show up in the Javadoc. 

In the case of Spanner, we should also make sure that all the main interfaces have such samples/snippets in their top level methods (e.g. Spanner, DatabaseClient, DatabaseClientAdmin, ...).

There is also an infrastructure in place to write these snippets and to then test them automatically. Please see how other APIs are doing it (or ask @garrettjonesgoogle for guidance).

**Comment by vkedia** [comment]
@garrettjonesgoogle Can you please point me to the infrastructure that @omaray is alluding to?

**Comment by pongad** [comment]
@vkedia You can write the snippets in separate Java files like [this](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1613/files). Generally snippets for one class together form one file.

Then `utilities/add_snippets_to_file.py` is the script to auto-inject the snippets into the javadoc.

**Comment by vkedia** [comment]
@snehashah16 will work on this. @garrettjonesgoogle I am not able to assign this issue to her. Can you please make her a collaborator.

**Comment by garrettjonesgoogle** [comment]
I have made @snehashah16  a collaborator.

**Comment by vkedia** [comment]
Thanks!

**Comment by vkedia** [comment]
Added snippets to `DatabaseClient` in #2217

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
