### ISSUE TITLE
Enable compression for pubsub library

### ISSUE THREAD

**Issue by lucmult** [GoogleCloudPlatform/google-cloud-java#1639]
As a customer I would like to have communication compressed from pubsub client to pubsub service.

This allows saving on network bandwidth when running it from other Cloud providers for example.

**Comment by garrettjonesgoogle** [comment]
Fixed in #1645 ; it will be included in the next release.

**Comment by ryankillory** [comment]
Given that https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1645 appears to have been reverted, I was wondering whether this should be reopened.

Thanks!

**Comment by georgespalding** [comment]
Seeing that it was a year ago someone asked about this, I'd like to ask again:
We would like to use compression at the Pub/Sub level to avoid doing it at application level.

The pull request and this issue mentions nothing to motivate why it was reverted. 
If there is a good reason for not allowing compression it would be nice to understand

**Comment by ostlerc** [comment]
Adding this for posterity. the revert commit says grpc [doesn't support compression yet](https://github.com/googleapis/google-cloud-java/commit/e1ca0d55cbc7da58cc1310698beb7ea40fdf7129).

> Compression is not fully supported in gRPC, can't have it in the library
yet.

**Comment by georgespalding** [comment]
The lack of this functionality does really hurt now that Google Cloud started charging for inter region pubsub egress network usage.
