### ISSUE TITLE
List subscriptions by topic

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1641]
Listing subscriptions by topic was possible with the prior version of the API as
com.google.cloud.pubsub : Page<SubscriptionId> listSubscriptions(String topic, ListOption... options);
 I don't see a way to do that anymore with com.google.pubsub.v1.ListSubscriptionsRequest.
Is this a known deprecation or is there a way to achieve topic subscription filtering that is not exposed clearly ?

**Comment by garrettjonesgoogle** [comment]
It is located at `PublisherClient.listTopicSubscriptions`.
