### ISSUE TITLE
Have getIamPolicy accept TopicName, SubscriptionName as input

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1643]
Given a lot of the new code uses TopicName/SubscriptionName class : constructed from projectId, topic-name/sub-name : it would be good if getIamPolicy on PublisherClient and SubscriberClient took in a TopicName, SubscriptionName respectively as opposed to just String : so there's no confusion to whether just topic/subscription-name alone works or the project-id needs to be specified as well.

**Comment by garrettjonesgoogle** [comment]
The String variant may be necessary to keep in case there are new resources in the future. It may be worth adding an overload that takes the currently-known resource types, though.

**Comment by garrettjonesgoogle** [comment]
@michaelbausor looks like someone else has already asked for resource name classes on the IAM methods :-)

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
