### ISSUE TITLE
Support default project for Pubsub

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1646]
All the veneer libraries support picking up the default project id if an explicit one is not provided.
See Spanner , Datastore, Storage  : 
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java

The deprecreated PubSub api supported it as well, v0.9.2-alpha does not.

**Comment by lesv** [comment]
I know this doesn't block GA, but it should block BETA - I don't see such a tag.

**Comment by garrettjonesgoogle** [comment]
We are using "Status: Release Blocking", and the API it applies to disambiguates between GA blocking and beta blocking.

**Comment by garrettjonesgoogle** [comment]
Renamed title - this is for default project, not default auth (which is already supported).

**Comment by garrettjonesgoogle** [comment]
As a workaround for Beta, could we have the samples use `ServiceOptions.getDefaultProjectId()`? This would just be one extra line. 

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L339

**Comment by jabubake** [comment]
Looks like that's not part of 0.9.3, I can try that out once available.

**Comment by garrettjonesgoogle** [comment]
Since this is for samples within this repository, I don't think an artifact is necessary. I'm going to remove the beta-blocking label, and we can consider making this more automatic later.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
