### ISSUE TITLE
Subscriber implements Service interface

### ISSUE THREAD

**Issue by piotrpolatowski** [GoogleCloudPlatform/google-cloud-java#1650]
Why new `Subscriber` implementation is a decorator for `AbstractService` and not implement `Service` interface directly? 

It makes it harder to use with `com.google.common.util.concurrent.ServiceManager`

**Comment by garrettjonesgoogle** [comment]
Because we don't want to expose Guava on our surface. We want to be able to create a variant of google-cloud-java with Guava shaded for those who are using older versions of Guava that aren't compatible with our version.

**Comment by garrettjonesgoogle** [comment]
I'm going to close this out now. Re-open if you have more concerns.
