### ISSUE TITLE
PubSub, Logging, Datastore, BigQuery testing on GAE Std J7 & GAE Std J8

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1653]
Veener libraries need to be tested (ie. deployed) to GAE Standard using Java 7 and Java 8.

@ludoch can WL you.

**Comment by lesv** [comment]
We've been told this shouldn't block GA, as gRPC on GAE 7 gVisor isn't ready yet.  DevRel will take GAE 8 for Q2

**Comment by garrettjonesgoogle** [comment]
Java 7 is not going to be supported, and Java 8 has been tested, with known issues documented in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1918 . Closing the present issue.
