### ISSUE TITLE
JUL - Logging should be zero-conf for most users.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1654]
1. JUL `java.util.logging` should be zero configuration for most users.
1. Work on all platforms: GAE Std 8 / Flex / GKE / GCE without modification.
1. See #1130 for fluentd support as well. (in GAE Flex env)

(Java 7 GAE Std / Dataproc / Dataflow is NOT Release Blocking;)

I've asked @jabubake to help you with this.

**Comment by lesv** [comment]
Also it doesn't buffer in most cases; work in a fluentd environment; etc.

**Comment by garrettjonesgoogle** [comment]
@lesv Can you edit the title to be in command form instead of problem-description form?

**Comment by garrettjonesgoogle** [comment]
I can't quite tell from the description what needs to be done.

**Comment by jabubake** [comment]
FYI, @meltsufin and team have worked on JUL support for App Engine Flex.
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/GaeFlexLoggingEnhancer.java

**Comment by jabubake** [comment]
Fluentd support needs to be better understood and scoped,  JUL is now auto-configured on GCE, GKE, Flex, Standard. Will be tracked separately in #1130
