### ISSUE TITLE
Async APIs for Spanner

### ISSUE THREAD

**Issue by danielcompton** [GoogleCloudPlatform/google-cloud-java#1657]
It would be great if the Java library had asynchronous APIs for Cloud Spanner so that I don't need to tie up a request serving thread while I'm waiting for a response to a queries and writes. I had a look around the Javadoc and couldn't see anything about this, apologies if I've missed it.

**Comment by vkedia** [comment]
Thanks for filing this request. We don't currently have an async api. We will consider adding it based on demand.

**Comment by vkedia** [comment]
@shinfan I don't think this is needed for Spanner GA?

**Comment by shinfan** [comment]
Okay I was adding everything spanner without a "triaged for GA" label to Spanner GA milestone. Feel free to remove and add "triaged for GA" label if it is not a part of GA.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by igor-bbm** [comment]
Is there any ETA for this feature?

**Comment by hzyi-google** [comment]
Spanner Java library now supports async calls for creating and [updating databases](https://github.com/googleapis/google-cloud-java/blob/7fc4b3b2973faa23292b4f92f49ef1445d19934d/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java#L103) and instances. There don't seem to be async methods for read and write.
cc/ @nithinsujir and @snehashah16 who own Spanner library.
