### ISSUE TITLE
More distinct exception handling when getting GAE ProjectID in ServiceOptions

### ISSUE THREAD

**Issue by aschults** [GoogleCloudPlatform/google-cloud-java#1666]
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/e5f90467fe7490759482e6a8bc62b1246318a7f0/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L437

In case of quota exhaustion,  Exception is thrown from RPC. Catch doesn't distinguish and thus assumes it's not running on GAE.

Would it be sufficient to catch ClassNotFoundException and related (e.g. NoSuchMethodException) to detect if we're on GAE? Like this, RPC-related exceptions (from within the called method) could bubble up properly.

**Comment by garrettjonesgoogle** [comment]
@shinfan can you see if this is resolved with your latest change?

**Comment by garrettjonesgoogle** [comment]
@shinfan ping - I suspect this is fixed and I'd like to close it out if that is true.

**Comment by shinfan** [comment]
No this is not resolved. I will send a separate fix.

**Comment by pongad** [comment]
I believe this is closed by #2304. At the very least, we're not dynamically loading classes anymore.
