### ISSUE TITLE
`ListTopicSubscriptionsPagedResponse.iterateAllElements()` should return `Iterable<Subscription>`

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1668]
`ListTopicSubscriptionsPagedResponse.iterateAllElements` currently returns `Iterable<String>`.
It feels inconsistent with `ListTopicsPagedResponse.iterateAllElements` that returns `Iterable<Topic>`
and `ListSubscriptionsPagedResponse.iterateAllElements` returns `Iterable<Subscription>`.

**Comment by garrettjonesgoogle** [comment]
This could get tricksy because of templating. Assigning to @michaelbausor to take a look at viability.

**Comment by garrettjonesgoogle** [comment]
We now have a `ListTopicSubscriptionsPagedResponse.iterateAllAsSubscriptionName` method which returns `Iterable<SubscriptionName>`. I think this satisfies the issue. 

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/d476ef7904467233e83168b8d1f5a934a0aae711/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1/PagedResponseWrappers.java#L150
