### ISSUE TITLE
`MonitoredResource.newBuilder` accepts arbitrary input, but does not log if invalid resource

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1676]
Supported resource types @ https://cloud.google.com/monitoring/api/resources
`MonitoredResource.newBuilder` currently accepts a free string. Logging backend validates against supported resource types and does not log if it is not a supported log type.

We should have a cleaner way for the user to provide the resource type : be inferred from environment (GCE vs GAE ?) or have a custom resource type be used by default when user logs via the API.

**Comment by lesv** [comment]
Doesn't block Release, but @waprin is looking into this.

**Comment by garrettjonesgoogle** [comment]
So @lesv, should it be release blocking or no?

**Comment by lesv** [comment]
While I like the idea of validation and it would help users debug, I see Resources just increasing and it would be easy for the Veneer team to get out of sync.  (And we'd probably start leaking things during EAP, if we validated).

An option would be to warn when a resource isn't defined in a list, but still accept a String, another approach would to have an enum list of resources and a newBuilder that accepts from that list (changes things to a String), and a newBuilder that takes the string for exceptions and customer created Resources.  (Assuming I'm understanding things correctly)

**Comment by waprin** [comment]
The issue in Python is that there is no way to write to the resource at all using the documented API. Java situation is a bit better since at least it's possible.

I think both of @lesv ideas sound like solid improvements.

**Comment by jabubake** [comment]
I agree, validation is hard on construction and can get messy to keep up with. Another option :can we not fail silently, and expose the exception/validation done by the logging backend to state that it is an unsupported resource type ?  We can at least let the user know what they setup is not working.

**Comment by garrettjonesgoogle** [comment]
@jabubake how would we implement the validation? Duplicate the code from the backend?

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
