### ISSUE TITLE
google/google-auth-library-java #89 needs to be fixed

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1679]
https://github.com/google/google-auth-library-java/issues/89
Blocks GAE Standard (java 7 & J8)

Summary: on App Engine Compat, GCE credentials need to be used instead of GAE credentials.

**Comment by lesv** [comment]
We've asked for additional info.

**Comment by garrettjonesgoogle** [comment]
This is blocked on an internal decision.

**Comment by garrettjonesgoogle** [comment]
Since we aren't blocking anything on this any more, I'm going to close it out, since the real resolution will be tracked on https://github.com/google/google-auth-library-java/issues/89 itself.
