### ISSUE TITLE
google-oauth-java-client/issues/145

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1680]
https://github.com/google/google-oauth-java-client/issues/145

Blocks testing on GAE Standard (J7)

**Comment by saturnism** [comment]
This literally prevents using the client lib in any servlet environment. Verified w/ Spring Boot as well.

Work around is to explicitly exclude servlet-api.

**Comment by lesv** [comment]
I've put several comments on Google/google-oauth-java-client#145 In two pom.xml, the servlet dependency MUST be marked `<scope>provided</scope>`.  This is always the case for all uses except if you are writing a container engine like Jetty or Tomcat.

**Comment by garrettjonesgoogle** [comment]
So I looked into why google-cloud-core depends on google-api-client-appengine, and found that I could narrow the dependencies and avoid pulling in servlet-api transitively, even without changing google-api-client-appengine. See https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1766 .
