### ISSUE TITLE
Publisher.setupDurationBasedPublishAlarm - log does not replace %d, potentially reduce log level

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#1682]
See screenshot.  Also, should alarm setup be INFO level log? Reduce level if appropriate.

![log](https://cloud.githubusercontent.com/assets/1998883/23518275/e9eabcb4-ff40-11e6-8584-f482a6567a85.png)

**Comment by garrettjonesgoogle** [comment]
This will be fixed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1675 .

**Comment by pongad** [comment]
Yes, it should be `{0}` instead of `%d`. Sorry about this silly mistake.

**Comment by pongad** [comment]
Closed by #1675 .
