### ISSUE TITLE
Requests from this Android client application <empty> are blocked

### ISSUE THREAD

**Issue by thanhlv93** [GoogleCloudPlatform/google-cloud-java#1697]
Hi all,
When i tried to translate the text with Google Cloud API but i got a message :
{
  "error": {
    "code": 403,
    "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
    "errors": [
      {
        "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

I don't know how to fix this issue , plz tell me if you have any solution.
Thanks

**Comment by garrettjonesgoogle** [comment]
It looks like you aren't doing auth correctly. Are you setting an API key?

**Comment by thanhlv93** [comment]
I setting and using Android key then got above message . I tried public key then ok . I don't know why Android key i can't use it.

**Comment by tcoffee-google** [comment]
@thanhlv93 are you still experiencing this problem? If so, could you share the code you're using for authentication to help us diagnose the issue? Thanks!

**Comment by thanhlv93** [comment]
@tcoffee-google yeah , i still this problem and i'm using public key instead private key.

**Comment by tcoffee-google** [comment]
@thanhlv93 it would help us to see the code you were using for authentication that was producing the error message.

**Comment by tcoffee-google** [comment]
Closing this issue due to lack of context --- @thanhlv93 please re-open if you can provide additional information. Thanks!

**Comment by sss-hnguyen** [comment]
I'm running into this issue as well, and am using cordova to wrap an application. I created a bug about this for cordova, but I'll link the item here as well.

https://github.com/apache/cordova-cli/issues/429

**Comment by PijushManna** [comment]
I'm also getting this. I have used REST api call with my API key 
https://www.googleapis.com/blogger/v3/blogs/2965410073933068533?key=xxxxxx<my API key >

**Comment by CloudAktsk** [comment]
Same here using Unity3D + C# calling Google Cloud Translate API by REST.
I got exactly 100% the same error message, any idea?

**Comment by suculent** [comment]
I have similar problem, however it seems we're doing various mistakes... One is using public key instead of private key, most of us however use Android API Key for Web app, which seems odd.

**Comment by rchamara** [comment]
same issues here 
working perfectly in my local emulator when restricted as None in google console
But if I changed it into Android same error got

1. add debug key and package name correctly (100% sure) in google console save and wait more than 5 minutes to update 
2. debug key and package name is ok and i double-check with my android code is with getting its programmatically
3. use com.google.apis:google-api-services-youtube lib (java) for call services from android side
4. API key also double check and its correct

```
E/ServiceRequestTask: mLastError: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
    GET https://www.googleapis.com/youtube/v3/videos?chart=mostPopular&key=***********************&maxResults=10&part=snippet,contentDetails,statistics&regionCode=US
    {
      "code" : 403,
      "errors" : [ {
        "domain" : "global",
        "message" : "Requests from this Android client application <empty> are blocked.",
        "reason" : "forbidden"
      } ],
      "message" : "Requests from this Android client application <empty> are blocked.",
      "status" : "PERMISSION_DENIED"
    }
E/MainActivity: error: 400
```

**Comment by 0wwafa** [comment]
how to specify the requesting application?
