### ISSUE TITLE
What's third party?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#1699]
Supporting new services says not to expose third party libraries in the API. Who's a third party in this context? E.g. would exposing a Guava class such as ImmutableSet be OK or not?

**Comment by garrettjonesgoogle** [comment]
For the purposes of google-cloud-java, Guava is considered third party, so we don't expose any Guava types on the surface.

**Comment by garrettjonesgoogle** [comment]
I'm closing out this issue now - re-open if you have more questions.
