### ISSUE TITLE
Direct users to use https://github.com/GoogleCloudPlatform/cloud-trace-java

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/google-cloud-java#1700]
Would be nice if the README for google-cloud-trace package directed users use the Stackdriver provided libraries at https://github.com/GoogleCloudPlatform/cloud-trace-java. Also a pointer showed up in the Maven artifacts generated so someone searching for and viewing the maven artifact 

https://mvnrepository.com/artifact/com.google.cloud/google-cloud-trace

would be directed to use Stackdriver SDK instead

https://mvnrepository.com/artifact/com.google.cloud.trace/core

Thanks

**Comment by garrettjonesgoogle** [comment]
cc @omaray

**Comment by lesv** [comment]
I'd like to follow this conversation.

**Comment by garrettjonesgoogle** [comment]
The short response to this issue is that I don't think we want to simply do a redirect. We have an internal discussion on how to reduce the confusion of multiple client libraries for trace. I'm going to close out this issue for now; when we come to a decision, we'll get it sorted out on github.

**Comment by danielcompton** [comment]
Just wanted to say that this is all very confusing from the perspective of someone trying to setup tracing. The docs all seem to put in different directions, with varying amounts of guidance on actually using this to capture traces.
