### ISSUE TITLE
We need a way to set traceId or RequestId on all requests.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1727]
It would be nice to know what request generated this API call.  (RequestID) -- this s.b. for Cloud Trace

**Comment by lesv** [comment]
StackDriver Trace needs this -- @rakyll is interested in this as well.

**Comment by garrettjonesgoogle** [comment]
@lesv is this still needed, or is it being done at a lower level?

**Comment by lesv** [comment]
The claim was that we'll get this for free in our runtimes. (Std / Flex) Using [gRPC interceptors](https://github.com/GoogleCloudPlatform/cloud-trace-java-instrumentation).  I don't know that it's really true for GAE Std.
