### ISSUE TITLE
PubSub pullAsync redelivery question

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-java#1729]
Is there a way to get the redelivery of the message to not be instant if the messageProcesser throws an exception (nack) when using 
```java
PubSub.MessageConsumer pullAsync(String subscription,
                                 PubSub.MessageProcessor callback,
                                 PubSub.PullOption... options)
```

I have tried setting the ack-deadline to several minutes but the message is redelivered immediately if the processor throws an exception.

**Comment by fonzy2013** [comment]
Any news on this question?

**Comment by garrettjonesgoogle** [comment]
@pongad could you investigate for the new code?

**Comment by pongad** [comment]
Sorry for the late reply. The `PubSub` class is deprecated; I recommend migrating to `com.google.cloud.pubsub.spi.v1.Subscriber` instead.

In `Subscriber`, there is a 100ms delay. This is for optimization though: if you ack/nack a bunch of messages, we try to batch them together to save time.

Could you briefly describe why you need to delay the redelivery? As far as I know, the library sees the exception as an inability to process a message. By making the message immediately available again, it can be delivered to other machines to be processed and keep the latency low.

**Comment by fonzy2013** [comment]
Sorry for the late reply. In our case we want the message to be redelivered after some time due to reasons of backing off from other systems that in rare occasions need extra time to be ready for the requests.

That means we need the possibility but not always.

**Comment by pongad** [comment]
If the situation is rare, would it be possible for you to catch the exception and use a `ScheduledExecutorService`? It's a little roundabout but probably works for your use case.

```java
ScheduledExecutorService executor = ...;
AckReplyConsumer reply = ...;
executor.schedule(new Runnable(){
  @Override
  public void run() {
    reply.nack();
  }
}, time, timeUnit);
```

**Comment by fonzy2013** [comment]
ok, thanks

**Comment by pongad** [comment]
I'll close this for now. Please reopen if you have more questions.
