### ISSUE TITLE
pubsub deprecated?

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-java#1730]
It seems the entire pubsub namespace is deprecated. What will it be replaced with?

**Comment by garrettjonesgoogle** [comment]
Closing out issue.

**Comment by fonzy2013** [comment]
When will the documentation and examples be updated with the new API?

**Comment by garrettjonesgoogle** [comment]
We have an issue for cleaning up the docs: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1789
