### ISSUE TITLE
Change signature of RPCFuture.addCallback to allow lambdas as arguments

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/google-cloud-java#1732]
Hi, it's nice to have a callback mechanism on the latest pubsub client library, but it would be even better if the RPCFuture.addCallback supported functional interfaces instead of an interface with two methods to process errors and success.

so if instead of addCallback(RpcFutureCallback)

public void subscribe(Consumer<T> success, Consumer<? super Throwable> error){

One could just invoke the subscribe with lambdas expressions.

I know Consumer is Java 8 construct, but any functional interface with an interface like

Foo<T>{

void apply(T t)

}

would work

**Comment by garrettjonesgoogle** [comment]
Unfortunately, we probably aren't going to do this. We are trying to match the patterns of `ListenableFuture` from Guava, which is well-established and widely understood. When we migrate to Java 8, we will fully use the available Java 8 constructs.

**Comment by garrettjonesgoogle** [comment]
Closing out issue now - we appreciate your suggestions, keep them coming!
