### ISSUE TITLE
Rename PublisherClient to TopicAdminClient, and SubscriberClient to SubscriptionAdminClient

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1733]
This will require adding a config in pubsub_gapic.yaml and regenerating the client. 

https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1734 might be doable at the same time; it also requires a config modification.

**Comment by garrettjonesgoogle** [comment]
Being implemented in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1818

**Comment by pongad** [comment]
Closed by #1818
