### ISSUE TITLE
google-auth-library-java/issues/91 retry refreshAccessToken failures

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1735]
https://github.com/google/google-auth-library-java/issues/91

**Comment by garrettjonesgoogle** [comment]
@lesv Do you think this should be release blocking? (I have provisionally marked it as such)

**Comment by lesv** [comment]
Oh, yes - lots of users run into this kind of failure.  Their access just stops after an hour - it's very hard to find and debug.

**Comment by garrettjonesgoogle** [comment]
Switching to Post GA P1 - it doesn't affect the surface

**Comment by tcoffee-google** [comment]
Closed in https://github.com/google/google-auth-library-java/issues/91.
