### ISSUE TITLE
Support configuration of base severity level

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1740]
Currently there is no way to modify base severity level of a `LoggingHandler`. Logs with the same severity with the base could be more efficiently sent to Stackdriver.

Some ideas:
1. Do nothing.
The level the handler is set to is probably the most chatty anyway.
2. Give it its own config param.
3. Create `setBaseLevel` method.
This [requires](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1721#issuecomment-285529950) us to make bundling a little more resilient first.

**Comment by garrettjonesgoogle** [comment]
@pongad , this was completed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1721 , right?

**Comment by pongad** [comment]
@garrettjonesgoogle The base severity level was implemented like you said. Right now you can't change the base severity level, but we should allow this eventually. This issue exists so we don't forget about it. I'll add priority P2+

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
