### ISSUE TITLE
Create a sample app setup that runs on GAE

### ISSUE THREAD

**Issue by shinfan** [GoogleCloudPlatform/google-cloud-java#1742]
It would be helpful if we have a complete setup for a sample app (e.g. Storage) that users can grab and deploy directly without any editing effort. 

Ideally the structure would look like this:
--- pom.xml
--- README.md
--- src/paths/to/main/StorageSample.java
--- src/main/webapp/WEB_INF/appengine-web.xml
--- src/main/webapp/WEB_INF/web.xml

so the user just need to clone the folder and run: `mvn appengine:deploy` and deploy the app onto their GAE host.

**Comment by ludoch** [comment]
Some are in
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/flexible
and java8 branch:
https://github.com/GoogleCloudPlatform/java-docs-samples/tree/java8-master/java8-appengine

**Comment by shinfan** [comment]
Those samples are not using google-cloud-java. It would be good to have at least one sample that runs with google-cloud-java clients.

**Comment by lesv** [comment]
https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/bookshelf-standard
uses GCS, I'll get something into java-docs-samples next week.

**Comment by garrettjonesgoogle** [comment]
I think https://github.com/GoogleCloudPlatform/java-docs-samples/issues/558 is the right place to track this request; I will close out the present issue.
