### ISSUE TITLE
GCS - "Invalid Credentials" error when debugging locally

### ISSUE THREAD

**Issue by jakeam** [GoogleCloudPlatform/google-cloud-java#1744]
When trying to upload a file to GCS I get the following error.

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "com.google.cloud.storage.StorageException: Invalid Credentials"
   }
  ],
  "code": 503,
  "message": "com.google.cloud.storage.StorageException: Invalid Credentials"
 }
}
```

I have authenticated using the CLI and am able to list all buckets using 'gsutil ls', however any code that interacts with GCS returns this error when debugging locally.

Please let me know if you require any more details.

**Comment by lesv** [comment]
See #1500 You may need to add 1.9.50 or better of the api to your classpath.
