### ISSUE TITLE
getNextPageToken returns Object, setPageToken taking String

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-java#1764]
This is using the Monitoring VTK. This causes a lot of ugly code since casting a null to a String is an exception.

**Comment by waprin** [comment]
lesv says it blocks release

**Comment by garrettjonesgoogle** [comment]
Monitoring isn't part of the 4 GA APIs, so this issue shouldn't block GA.

**Comment by garrettjonesgoogle** [comment]
@lesv since the marking of this issue as release-blocking involves a second-hand report from a statement by you, could you clarify here?

**Comment by lesv** [comment]
Yea - it doesn't block GA - it should, however get fixed at some point.

(I was at his desk when it wrote this up.)  (I thought this tag was block next release of Monitoring)

**Comment by garrettjonesgoogle** [comment]
It's "future release blocking" I guess, but to make the next release easier to track, I removed the label.

**Comment by waprin** [comment]
It's also not quite as bad as I realized since the Object returned isn't null, it's just the empty String, so it's safe to cast to String. Still a pretty weird API inconsistency.

**Comment by michaelbausor** [comment]
Fixed in https://github.com/googleapis/toolkit/pull/1139 and https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1894
