### ISSUE TITLE
No syncRecognize response (DEADLINE_EXCEEDED) using Java speech client library

### ISSUE THREAD

**Issue by henryjcee** [GoogleCloudPlatform/google-cloud-java#1772]
As Requested in https://groups.google.com/forum/#!msg/cloud-speech-discuss/ I'm opening a ticket on here.

Using both the sample and a bare Java 8/Spring/Tomcat 8 stack with Java speech client versions 0.8.0 / 0.9.4-alpha / 0.10.0-alpha I get no response when I make a syncRecognise request. The request future doesn't resolve until I eventually get a com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED error.

I am authorising via service account and have tried using both the application default json creds and via the command line tools. Happy to fill in more details about my setup if needed.

**Comment by garrettjonesgoogle** [comment]
This is likely to be the same general class of root cause as https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1430 , which is that there is likely to be a problem loading netty-tcnative. 

To be sure, you need to set your logging level to FINE to see if you see logs that say `Unable to load the library: netty-tcnative-linux-x86_64`.

**Comment by henryjcee** [comment]
This is correct, moronic tcnative config error on my part. Thanks for your time and I'll report back to the groups convo.

**Comment by kilaka** [comment]
Happening to me as well with google-cloud-speech v0.8.1-alpha and v0.8.0 on tomcat v8.5.8 on Ubuntu 16.04 64bit.
Any idea how to fix it?

**Comment by garrettjonesgoogle** [comment]
@kilaka Could you change your logging level to FINE as instructed above, and come back with what you see?

**Comment by garrettjonesgoogle** [comment]
I'm going to close out this issue because there has been no response. Feel free to reopen if there are more issues.
