### ISSUE TITLE
Implement NoCredentials.refreshAccessToken()

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#1778]
This credential is used in tests. This method will be called somewhere downstream and will expect to be implemented and return an `AccessToken`.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
