### ISSUE TITLE
TRANSLATE: Are the supported languages documented in the API Docs?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-java#1779]
I'm trying to use the translate API Docs: http://googlecloudplatform.github.io/google-cloud-java/0.10.0/apidocs/?com/google/cloud/translate/package-summary.html

I can't find anywhere that lists the set of valid language options.  Should this be an enum somewhere?

**Comment by garrettjonesgoogle** [comment]
There is a link from https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-translate/src/main/java/com/google/cloud/translate/Language.java#L32 to https://cloud.google.com/translate/v2/translate-reference#supported_languages , but it appears that this link isn't really valid any more. The link should be https://cloud.google.com/translate/docs/languages .

This list seems like it might be too long to be an enum.
