### ISSUE TITLE
pom - parent POM - artifact not found

### ISSUE THREAD

**Issue by ppatihsb** [GoogleCloudPlatform/google-cloud-java#1781]
Project build error: Non-resolvable parent POM for com.google.cloud:google-cloud-bigquery:${beta.version}: Could not find artifact com.google.cloud:google-cloud-pom:pom:0.10.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM

irrespective of the version.

**Comment by garrettjonesgoogle** [comment]
What command are you running and where are you running it?

**Comment by ppatihsb** [comment]
I just tried to import the google-cloud-bigquery project into my eclipse
workspace.
There it showed the pom error.

Not any command.

Regards.

**Comment by garrettjonesgoogle** [comment]
the google-cloud-core project also needs to be imported for it to work.

**Comment by garrettjonesgoogle** [comment]
@ppatihsb have you tried my suggestion yet to see if it helps?

**Comment by shinfan** [comment]
Close the question for now. Please feel free to reopen if the solution does not work.
