### ISSUE TITLE
Translate: service factory method seems oddly placed

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-java#1785]
Is it me or is TranslateOptions an odd place to expect a method to get a Translation Service instance?

`TranslateOptions.getDefaultInstance().getService();`

**Comment by garrettjonesgoogle** [comment]
It's not just you... It's a longstanding pattern for all services in google-cloud-java though, and would be really disruptive to change.

**Comment by garrettjonesgoogle** [comment]
We probably aren't going to change this in the foreseeable future.
