### ISSUE TITLE
ServiceOptions should allow the path of credentials file to be passed in.

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-java#1786]
Currently we can supply the credentials by parsing the Credentials ourselves from the credentials file and then calling setCredentials. One concern with this is that we also have to call setProjectId even though the credentials file has the project id. When we set the GOOGLE_APPLICATION_CREDENTIALS variable, the library is smart enough to pick the project id from that.
Similarly if we had a method setGoogleApplicationCredentialsFile(String filePath or InputStream credentialsStream), the library would then pick up both credentials as well as project id from there.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
