### ISSUE TITLE
Consider trimming the dependencies of google-cloud-spanner

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-java#1788]
Currently google-cloud-spanner pulls in lot of dependencies most of which it does not need. We should consider if it is possible to refactor the dependency chain in such a way as to reduce the number:
Here is the current tree:
```
[INFO] com.google.cloud:google-cloud-spanner:jar:0.10.1-beta-SNAPSHOT
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:1.1.33.Fork19:compile
[INFO] +- com.google.cloud:google-cloud-core:jar:0.10.1-alpha-SNAPSHOT:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.21.0:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.21.0:compile
[INFO] |  +- com.google.http-client:google-http-client-appengine:jar:1.21.0:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson:jar:1.21.0:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.0.0:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.0.3:compile
[INFO] |  |  \- io.grpc:grpc-protobuf-lite:jar:1.0.3:compile
[INFO] |  +- com.google.api.grpc:grpc-google-common-protos:jar:0.1.5:compile
[INFO] |  \- com.google.api.grpc:grpc-google-iam-v1:jar:0.1.5:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-v1:jar:0.1.5:compile
[INFO] |  \- com.google.api:api-common:jar:0.0.2:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:jar:0.1.5:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:jar:0.1.5:compile
[INFO] +- io.grpc:grpc-netty:jar:1.0.3:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.0.3:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.0.3:compile
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.6.Final:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.6.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-common:jar:4.1.6.Final:compile
[INFO] |  |  |  \- io.netty:netty-resolver:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-codec-socks:jar:4.1.6.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.6.Final:compile
[INFO] |  |  \- io.netty:netty-codec-http:jar:4.1.6.Final:compile
[INFO] |  \- io.netty:netty-codec-http2:jar:4.1.6.Final:compile
[INFO] |     \- io.netty:netty-handler:jar:4.1.6.Final:compile
[INFO] +- io.grpc:grpc-auth:jar:1.0.3:compile
[INFO] +- io.grpc:grpc-stub:jar:1.0.3:compile
[INFO] +- com.google.api:gax:jar:0.5.0:compile
[INFO] |  +- com.google.inject:guice:jar:4.0:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] +- com.google.protobuf:protobuf-java-util:jar:3.0.0:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.3:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- com.google.guava:guava:jar:19.0:compile
[INFO] +- joda-time:joda-time:jar:2.9.2:compile
[INFO] +- com.google.auth:google-auth-library-credentials:jar:0.4.0:compile
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:0.4.0:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  \- com.google.guava:guava-jdk5:jar:13.0:compile
[INFO] +- com.google.api-client:google-api-client:jar:1.20.0:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- com.google.truth:truth:jar:0.30:test
[INFO] |  \- com.google.errorprone:error_prone_annotations:jar:2.0.8:test
[INFO] +- org.mockito:mockito-all:jar:1.9.5:test
[INFO] +- com.google.guava:guava-testlib:jar:19.0:test
[INFO] \- org.json:json:jar:20151123:test (scope not updated to compile)
```

**Comment by garrettjonesgoogle** [comment]
I'm guessing it is the `com.google.*-client` dependencies that you take issue with, which are necessary for old-platform APIs (BigQuery, Compute, Storage, etc) but not grpc-based APIs. I agree that this should be trimmed down for grpc-based APIs. 

There is one dependency I found that nothing needs, which is `guice`, which seems to have been added a while back to `gax-java` and `api-common` but which simply isn't needed anywhere.

**Comment by vkedia** [comment]
Yeah those were the glaring ones. They also end up pulling bit of other cruft.

**Comment by garrettjonesgoogle** [comment]
@vkedia could you check over the latest dependency tree to see how it looks?

**Comment by garrettjonesgoogle** [comment]
@vkedia ping

**Comment by vkedia** [comment]
This is the latest tree.
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Cloud Spanner 0.18.1-beta-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:tree (default-cli) @ google-cloud-spanner ---
[INFO] com.google.cloud:google-cloud-spanner:jar:0.18.1-beta-SNAPSHOT
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:1.1.33.Fork26:compile
[INFO] +- com.google.cloud:google-cloud-core:jar:1.0.3-SNAPSHOT:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- org.json:json:jar:20160810:compile
[INFO] |  +- com.google.api:api-common:jar:1.1.0:compile
[INFO] |  +- com.google.api:gax:jar:1.1.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.2.0:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.11:compile
[INFO] |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.11:compile
[INFO] +- com.google.cloud:google-cloud-core-grpc:jar:1.0.3-SNAPSHOT:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.2.0:compile
[INFO] |  \- io.grpc:grpc-protobuf:jar:1.2.0:compile
[INFO] |     \- io.grpc:grpc-protobuf-lite:jar:1.2.0:compile
[INFO] +- com.google.api:gax-grpc:jar:0.17.0:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.6.1:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.21.0:compile (version managed from 1.19.0)
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.21.0:compile (version managed from 1.19.0)
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] +- com.google.api.grpc:proto-google-cloud-spanner-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:jar:0.1.11:compile
[INFO] +- com.google.api.grpc:grpc-google-longrunning-v1:jar:0.1.11:compile
[INFO] |  \- com.google.api.grpc:proto-google-longrunning-v1:jar:0.1.11:compile
[INFO] +- io.grpc:grpc-netty:jar:1.2.0:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.2.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.8:compile (version managed from 2.0.11)
[INFO] |  |  +- io.grpc:grpc-context:jar:1.2.0:compile
[INFO] |  |  \- com.google.instrumentation:instrumentation-api:jar:0.3.0:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.8.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.8.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.8.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.8.Final:compile
[INFO] |  |     \- io.netty:netty-buffer:jar:4.1.8.Final:compile
[INFO] |  |        \- io.netty:netty-common:jar:4.1.8.Final:compile
[INFO] |  \- io.netty:netty-handler-proxy:jar:4.1.8.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.8.Final:compile
[INFO] |     |  \- io.netty:netty-resolver:jar:4.1.8.Final:compile
[INFO] |     \- io.netty:netty-codec-socks:jar:4.1.8.Final:compile
[INFO] +- io.grpc:grpc-auth:jar:1.2.0:compile
[INFO] |  \- com.google.auth:google-auth-library-credentials:jar:0.6.1:compile (version managed from 0.4.0)
[INFO] +- io.grpc:grpc-stub:jar:1.2.0:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- joda-time:joda-time:jar:2.9.2:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- com.google.truth:truth:jar:0.30:test
[INFO] +- org.mockito:mockito-all:jar:1.9.5:test
[INFO] \- com.google.guava:guava-testlib:jar:19.0:test

**Comment by garrettjonesgoogle** [comment]
What are the dependencies that you consider unnecessary?

**Comment by vkedia** [comment]
I think this is fine. Closing this.

**Comment by ericandrewschmidt** [comment]
I'd like you to reconsider re-opening to  specifically upgrade your **Apache HTTP client reference**. 4.0.1 is 8 years old.  This is stomping over the latest version  of the client which includes URIBuilder which is a super common reference.  Help prevent dependency hell in maven :-) 

     <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency> 

[INFO] +- com.google.api:gax-grpc:jar:0.17.0:compile
[INFO] |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.6.1:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.21.0:compile (version managed from 1.19.0)
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |     \- commons-codec:commons-codec:jar:1.3:compile

**Comment by garrettjonesgoogle** [comment]
@ericandrewschmidt , the Apache HTTP version is unrelated to the present issue (trimming dependencies) - could you file a new issue?
