### ISSUE TITLE
BigQuery: Support Date, Time, and DateTime types in FieldValue

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1792]
Use types from threetenbp.

**Comment by shinfan** [comment]
@garrettjonesgoogle  Can we close this issue now?

**Comment by garrettjonesgoogle** [comment]
No, https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1819 was closed out because we decided to use threetenbp types instead of handrolled types. The support for threetenbp types still needs to be implemented.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
