### ISSUE TITLE
Fix LoggingHandler flush

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#1795]
Logging handler's `flush()` calls `LoggingImpl.write` which eventually calls `LoggingClient.writeLogEntries` which uses bundling. So, handler flushing just moves messages from one buffer to another without actually making any RPC call.

## Proposed fix
LoggingHandler should keep a count of pending messages. The count increments with calls to publish and decrements when RPC returns.

Flush should force batcher to issue all buffered messages and just wait for the count to reach zero. No call to publish may succeed when flush is "in flight" otherwise flush could wait forever.

Encountering a log above the configured flush level should also force a flush.

**Comment by garrettjonesgoogle** [comment]
@pongad could you reword the description in terms of a command instead of a problem? (e.g. "Fix logging flush")

**Comment by pongad** [comment]
@garrettjonesgoogle I never seem to be able to remember. Done.

**Comment by garrettjonesgoogle** [comment]
Also reword the extended description, recommending a course of action to take.

**Comment by garrettjonesgoogle** [comment]
This properly waits for the RPCs to finish with @pongad 's last change; the triggering of RPCs by the call can be done after GA. Removing the release-blocking label.

**Comment by pongad** [comment]
@garrettjonesgoogle I think I need to send this back to you. The generated client must expose a way to flush. I don't think this is possible at the moment.

**Comment by pongad** [comment]
I'll resolve this as duplicate of #2796.
