### ISSUE TITLE
Spanner - Expose transaction protocol

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#1810]
Currently, transaction is wrapped around a single run block. Typically, there is a begin transaction & commit semantic where we can get a tx ID and tie operation to the tx ID. According to @vkedia, there is the wire protocol for this, that can be exposed. This could help significantly in tying better w/ JTA standards. 

Currently, the [community jdbc driver](https://github.com/olavloite/spanner-jdbc/blob/master/src/main/java/nl/topicus/jdbc/transaction/TransactionThread.java) is trying to work around this by having a single runnable thread that listens/pulls from a queue of requests.

/cc @emmanuelbernard to see if this will be helpful & what the JTA needs are.

**Comment by emmanuelbernard** [comment]
Yes that would be very helpful to Hibernate as well.
We would be able to tie the Spanner transaction to our wrapper and put all of Hibernate's operations in a single tx. At the moment we can only treat Spanner as a non transactional store most of the time.

**Comment by vkedia** [comment]
/cc @tomayles
@emmanuelbernard This sounds reasonable. But even with this in place, without read-your-writes semantics and DML, can spanner be made to work with Hibernate?

**Comment by emmanuelbernard** [comment]
@vkedia we need DML for Hibernate ORM proper. But I'm working on a Hibernate OGM dialect to use the native Spanner APIs for DML ops.
As for read your writes, I need to think deeper but the notion of persistence context protects you from a lot of read-your-write problems.

**Comment by archiecobbs** [comment]
FWIW, I'm using Spanner in a [project](http://archiecobbs.github.io/jsimpledb/site/apidocs/index.html?org/jsimpledb/kv/spanner/SpannerKVDatabase.html) that also needs the ability to manually open/commit/rollback transactions, and also has built-in read-your-writes support. See also issue #1627 for additional background and motivation.

**Comment by saturnism** [comment]
we also opened #2063 to track adding support to JTA where applicable, and sounds like the original ask of #1627.

**Comment by aandreakis** [comment]
+1 for this change request

We are integrating Spanner into our code base and it would be very convenient if we are able to start a Spanner read-write transaction and commit / rollback explicitly and without relying on the current callback approach.

**Comment by olavloite** [comment]
As mentioned earlier in this thread: [This JDBC driver for Google Cloud Spanner](https://github.com/olavloite/spanner-jdbc) supports 'normal' transactions and other standard JDBC functionality (including DDL- and DML-statements).
This sample project shows a (simple) example how you could use it in combination with JPA/Hibernate: https://github.com/olavloite/spanner-jpa-example

**Comment by vkedia** [comment]
@aandreakis Do you care if we implement a standard interface like [UserTransaction](http://docs.oracle.com/javaee/6/api/javax/transaction/UserTransaction.html) or it does not really matter for you as long as we have some way of doing explicit commit/rollback?

**Comment by Ronpgo** [comment]
Hi, any updates on this?
We would love to use it soon.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by vkedia** [comment]
I am working this now so reopening. Sent an initial #2776 for the interface. Anyone interested feel free to leave comments on that.

**Comment by vkedia** [comment]
Closed by #2776
