### ISSUE TITLE
JavaDoc's - we need to find a way to move autogen'd API's up to API packages.

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#1811]
Looking at the 0.10.0 [javadoc](http://googlecloudplatform.github.io/google-cloud-java/0.10.0/apidocs/), pubsub appears to be deprecated.

It would be nice if we could have autogen'd api's show up under **API Packages**.

Or we need to figure out how to train developers to look under SPI.

@garrettjonesgoogle 
@omaray FYI

**Comment by lesv** [comment]
Also, should spaner.spi be listed up there?

**Comment by garrettjonesgoogle** [comment]
This has been fixed - all clients are now in the API Packages sections.
