### ISSUE TITLE
No getService method in google-cloud-storage

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#1813]
README.MD for google-cloud-storage refers to

```
Storage storage = StorageOptions.getDefaultInstance().getService();
```

and a few other times. It appears this is no longer accurate at 0.10.alpha.

I.e. the `StorageOptions` class does not have a `getService` method. I'm not sure what it should be replaced with.

**Comment by garrettjonesgoogle** [comment]
`getService()` is present on `ServiceOptions` which `StorageOptions` extends. It was never changed. The code you pasted here should work fine.

**Comment by elharo** [comment]
OK, I must be doing something wrong. I'll dig into this further.

**Comment by elharo** [comment]
```
Multiple markers at this line
	- The method getService() is undefined for the type StorageOptions
	- The type com.google.cloud.HttpServiceOptions cannot be resolved. It is indirectly referenced 
	 from required .class files
```

**Comment by elharo** [comment]
Digging into my jar I do see the `getService` method. I don't see `com.google.cloud.HttpServiceOptions` in google-cloud-core-0.10.0-alpha.jar. What jar should that be in?

**Comment by garrettjonesgoogle** [comment]
I think you are out of sync somehow. If you build both -core and -storage fresh, or make sure that they are both at 0.10.0, it should all work. It looks like you might have the old version of -storage pointing to the new version of -core. (`HttpServiceOptions` was taken out of the hierarchy and is now a standalone class, `HttpTransportOptions`)

**Comment by elharo** [comment]
This appears to be the problem. Thanks. Closing.
