### ISSUE TITLE
Old pubsub API which is the latest version?

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-java#1814]
Which version of the library has the latest of the "old" pubsub api?
We need to upgrade to the latest without breaking the api as the new api is not backwards compatible.

**Comment by garrettjonesgoogle** [comment]
0.10.0-alpha still has it. The next release (0.11.0-alpha) won't have it.

**Comment by fonzy2013** [comment]
ok thanks. I couldn't see it on that tag unless you moved the namespace to deprecated.
I really hope there will be some good migration docs

**Comment by garrettjonesgoogle** [comment]
Closing out this issue because the question was answered. Please let us know if you have more questions.
