### ISSUE TITLE
Make sure Publisher/Subscriber use same channel customization as TopicAdminClient/SubscriptionAdminClient

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1830]

**Comment by pongad** [comment]
By "same channel customization", do you only mean that they should accept ChannelProvider?

Right now Publisher and Subscriber follow
```java
Publisher.newBuilder(...).foo(bar).build();
```
while the admins follow
```java
TopicAdminClient.create(settings);
```
do you want this pattern changed as well?

**Comment by garrettjonesgoogle** [comment]
This issue is just about the channels - Subscriber currently accepts a `ChannelBuilder` instead of a `ChannelProvider`.

**Comment by pongad** [comment]
@garrettjonesgoogle Is this beta-blocking?

**Comment by garrettjonesgoogle** [comment]
Pub/Sub was willing to go without it, but it would be very nice to work it in though.

**Comment by garrettjonesgoogle** [comment]
We have decided to go ahead and remove any usage of flow control settings for now. Go ahead and remove the usage.

**Comment by pongad** [comment]
This is currently blocked on grpc 1.2.0. Once we migrate, we can properly set the maxInboundMessageSize.
