### ISSUE TITLE
Handle new values in API responses gracefully (for almost-GA clients)

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-java#1832]
There was [a bug][] in the Node.js Vision client which was effectively that the client raised an exception if it ever got a key that it did not expect. This is relatively easy to do for any number of reasons:

```python
# `raw_response` is a dict that came back from the API.
key_map = {
    'alphaObject': 'alpha_object',
    'betaObject': 'beta_object',
}
new_response = {}
for k, v in raw_response.iteritems():
    new_response[key_map[k]] = v
```

This is an anti-pattern, because it strongly assumes that you will never get a new key that is not already in your key map. If the API adds a `gammaObject` key and this (Python) code were to run, suddenly what used to work now raises `KeyError`.

The solution: Add unit tests in each spot where we transform an API response into a custom object to ensure that unexpected key-value pairs are either passed through or dropped.

  [a bug]: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2034

**Comment by garrettjonesgoogle** [comment]
This repo is littered with cases like this - it throws exceptions when a value can't be mapped to an enum. 

See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1833 for an example just from today.
