### ISSUE TITLE
Ensure no normalization is done on Storage file names

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1837]
Use the following C# integration test as a basis for writing the equivalent in Java:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/pull/933/files

If it fails, fix the problem (remove the normalization). If it succeeds, then yay.

**Comment by garrettjonesgoogle** [comment]
Removing the release-blocking label because the code already does no normalization. We will get the PR for the test submitted when it can be reviewed by @jskeet .

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
