### ISSUE TITLE
Spanner - Allow set/get of com.google.cloud.spanner.Value

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1838]
Is it possible to add methods to respective interfaces and classes to get/set instances of com.google.cloud.spanner.Value in addition to the distinct types that are currently supported? 

For example - `ResultSet.getValue()` and `ValueBinder.to(Value v)`

**Comment by vkedia** [comment]
@sai-pullabhotla Can you please describe you use case. Why do you need these methods?

**Comment by sai-pullabhotla** [comment]
@vkedia - the purpose is to have a generic way to set/get data using an interface or generic type. I'm in the process of developing a ORM framework similar to the one I did for Cloud Datastore ([Catatumbo](https://github.com/sai-pullabhotla/catatumbo)), and having these methods would help with mapping types defined in the domain model to Spanner and vice versa. See [Mapper](https://github.com/sai-pullabhotla/catatumbo/blob/master/src/main/java/com/jmethods/catatumbo/Mapper.java)  for more info on how the mapping was done in Catatumbo, hoping to do the same for Spanner and having these methods would help. I also see another issue, #1805, which appears to be similar to what I'm asking for. 

Moreover, the API already does this internally to convert the distinct types to Value objects, so just need to expose a public method. Snippet from ValueBinder is below: 

```
  public R to(@Nullable String value) {
    return handle(Value.string(value));
  }

```

**Comment by vkedia** [comment]
@sai-pullabhotla Thanks. This sounds interesting. So if we had a to(Value) you would still need to figure out what type of Value to create, right? So it is not complete generic?

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
