### ISSUE TITLE
Add a flattened method for SubscriptionAdminClient.seek (requires oneof support)

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1839]
Requires https://github.com/googleapis/toolkit/issues/1057 .

**Comment by pongad** [comment]
This is codegen feature, reassigning back to Garrett

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
