### ISSUE TITLE
Front page has outdated API

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/google-cloud-java#1854]
http://googlecloudplatform.github.io/google-cloud-java/0.11.0/index.html has a code snippet:
```
DatastoreOptions options = DatastoreOptions.newBuilder()
  .setProjectId(PROJECT_ID)
  .setAuthCredentials(AuthCredentials.createForJson(
    new FileInputStream(PATH_TO_JSON_KEY))).build();
```

However, `setAuthCredentials` isn't a method on `DatastoreOptions.Builder`- it's `setCredentials`: http://googlecloudplatform.github.io/google-cloud-java/0.11.0/apidocs/com/google/cloud/datastore/DatastoreOptions.Builder.html. It also has it taking an `AuthCredentials` object- `GoogleCredentials` is probably the correct substitute here.

**Comment by neozwu** [comment]
The example code is now updated.
