### ISSUE TITLE
Replace consumer.accept by consumer.ack & consumer.nack in Pub/Sub

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#1864]
Attempting to tie together some offline discussion to get to a concrete resolution.   The Pub/Sub ack ReplyConsumer [1] uses an enum for reply type. There seems to  consensus that explicit .ack() and .nack() methods would be cleaner.  Could we make this change before beta or disagree, @pongad @davidtorres @garrettjonesgoogle ?  

[1] http://googlecloudplatform.github.io/google-cloud-java/0.11.1/apidocs/com/google/cloud/pubsub/spi/v1/AckReplyConsumer.html

**Comment by davidtorres** [comment]
The argument for flattening the enum into separate methods, was for future proofing the API for when implementing deadletter queues, with the idea that we would just add a new method (e.g. fail(String|Enum reason) ) which will serve to us for taking the decision to whether move the message to the deadletter queue or not.

However I'd argue that in the current interface we can still add such method while leaving the accept(AckReply) method as is.

But I honestly don't have a very strong argument but I vote for leaving it as is.

**Comment by garrettjonesgoogle** [comment]
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1899
