### ISSUE TITLE
Raise static addresses quota on Travis testing account?

### ISSUE THREAD

**Issue by danielcompton** [GoogleCloudPlatform/google-cloud-java#1866]
One of the causes of flaky tests in this repo appears to be exceeding a quota of global static IP addresses. A representative failure is at https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/jobs/218519105. It looks like any individual test is fine, but if there are enough concurrent tests running, then the account runs out of quota. The test is failing at [ITComputeTest.java#L783](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/8b1009916cbd0c0c5e5c2de40d96d49e69e92457/google-cloud-compute/src/test/java/com/google/cloud/compute/it/ITComputeTest.java#L783)

Two options I can see to improve this:

1. Limit concurrent builds to some number (maybe 7?) https://docs.travis-ci.com/user/customizing-the-build#Limiting-Concurrent-Builds
2. Raise the quota on the testing account to have a much larger number of global static IP's available.

**Comment by garrettjonesgoogle** [comment]
@michaelbausor could you raise the quota?

**Comment by garrettjonesgoogle** [comment]
I went ahead and:

* deleted the static addresses that had accumulated (15-ish of them)
* raised the quota from 30 to 60

Also, a recent commit by Neo to ensure compute resources are cleaned up on test failure should help prevent this in the future.
