### ISSUE TITLE
Serializing Spanner Mutations 

### ISSUE THREAD

**Issue by mairbek** [GoogleCloudPlatform/google-cloud-java#1871]
For Apache Beam support we need to serialize/deserialize Mutations. See https://github.com/apache/beam/pull/2166

Few options

- Make Mutation#toProto public https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/Mutation.java#L337  and add corresponding fromProto method.
- Make Mutation serializable and implement writeObject/readObject
- Introduce a new class, move Mutation#toProto code there and implement fromProto.

**Comment by vkedia** [comment]
I would prefer making Mutation serializable. That seems more idiomatic to me.
@garrettjonesgoogle is there any precedence for this? Do you have any preference?

**Comment by garrettjonesgoogle** [comment]
Serialization is used widely in google-cloud-java, so it seems like a good idea here.

**Comment by mairbek** [comment]
I've opened a PR https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1939.

This turned out to be harder than I've expected, because type information is lost once spanner Mutation is converted to the Mutation proto.

**Comment by vkedia** [comment]
Closed by PR #1952
