### ISSUE TITLE
`SubscriptionAdminClient` : Make creating a pull subscription more explicit than `PushConfig.getDefaultInstance()`

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#1874]
Currently if a user intends to create a pull configuration, he or she has to call `SubscriptionAdminClient.createSubscription` with an instance of `PushConfig` (`PushConfig.getDefaultInstance() `or construct a `PushConfig` object). Its confusing that the default instance leads to it being a pull subscription.

The semantics  of the `ackDeadlineInSeconds` are slightly different too for the pull vs push configuration and it is not clear whether the bounds are different between pull vs push in the java docs.
In the java docs, we state that `ackDeadlineInSeconds` has to be atleast 10 seconds for the pull and that if a user provides 0 as input, we use the default. Given the same parameter is used to configure the push endpoint deadline, its not clear if users can provide >0, < 10 values.

Can we provide users a way to create a pull subscription without providing a boilerplate PushConfig object  ?  This might also make it easier to document the `ackDeadlineInSeconds`better.

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
