### ISSUE TITLE
google cloud api java client on Raspberry pi (DEADLINE_EXCEEDED)

### ISSUE THREAD

**Issue by vtvttech** [GoogleCloudPlatform/google-cloud-java#1881]
Is it possible to run the java google cloud api in raspberry pi. When i tried cloud speech and cloud pubsub client in raspberry pi it is having io.grpc.status runtimeexception DEADLINE_EXCEEDED.
The code is running fine in ubuntu desktop.
I searched and found that netty is probably not supported in arm cores.
Is there any fix for this.

**Comment by shinfan** [comment]
I don't think Netty supports ARM. We probably need to update README files of the supported env.

**Comment by garrettjonesgoogle** [comment]
I have updated the README to note that Raspberry Pi is not supported. Closing out this issue.
