### ISSUE TITLE
Versionless redirects to specific javadocs pages

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1883]
I see that @michaelbausor added https://github.com/GoogleCloudPlatform/google-cloud-java/blob/gh-pages/apidocs/index.html which allows for a link to versionless API docs at http://googlecloudplatform.github.io/google-cloud-java/apidocs/

Would we be able to add a similar redirect for each of the class & package pages? I'd like to start linking to the API docs from cloud.google.com docs, but it's a pain if I have to keep updating the version number.

Somewhat related (and maybe worth a separate issue): what are we going to do when the individual packages are versioned separately? I guess this version corresponds to the version of the root meta package?

**Comment by jabubake** [comment]
@omaray FYI

**Comment by garrettjonesgoogle** [comment]
We should switch to just using a path with /latest/ instead of /${version}/.

**Comment by omaray** [comment]
Yes, once the path to the javadoc has 'latest' in it, we'll be able to make the updates.

**Comment by garrettjonesgoogle** [comment]
This was implemented in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2267 . If there are problems, we can open a new issue to track it.
