### ISSUE TITLE
JSON serialization assumes Maps aren't iterable

### ISSUE THREAD

**Issue by mikekap** [GoogleCloudPlatform/google-cloud-java#1890]
I'm using the java libraries from Clojure. Clojure native types (maps, vectors, etc) follow all normal java interfaces, except the built-in maps implement `Iterable`. When using these with BigQuery streaming, the JSON serializer thinks these are collections rather than maps and serializes them incorrectly. It would be nice if it didn't make that assumption and just directly checked for a `x instanceof Map`.

**Comment by garrettjonesgoogle** [comment]
* Is the following an accurate way of describing the issue?: "JSON serialization doesn't check to see if Iterables are Maps"
* Is this considered to be a flaw of Clojure that is going to be fixed, or is it permanently baked in?

**Comment by garrettjonesgoogle** [comment]
No response from filer, so closing this out. Please re-open if you still need a resolution to this problem.

**Comment by lvh** [comment]
Hi! I filed an identical issue here: #2432 .

It is definitely not a flaw of Clojure's builtin maps, they are simply both Iterable (producing their pairs) and java.util.Map; so Clojure won't be fixing that. 

I have a totally gross workaround that creates a proxy type: an object that holds the object implementing multiple interfaces and instead exposing only one. It's awful but it works. I've added a link to that code to the other ticket. Still a very nasty surprise for people using the SDK from Clojure. I also filed #3150 which is a different but possibly related bug where things fail in very obscure ways for people using Clojure.

**Comment by mikekap** [comment]
@garrettjonesgoogle Sorry I missed the request for information. To answer:
 - Yes - "JSON serialization doesn't check to see if Iterables are Maps" is a valid way of describing the issue.
 - This is not considered a flaw in Clojure. It's arguable whether a Map should be iterable or not, Java certainly doesn't prevent you from doing so. Unfortunately even if we all agreed that a Map shouldn't be iterable, it's infeasible at this point to change Clojure maps - a lot of libraries assume maps are iterable as entries.
