### ISSUE TITLE
BigQuery: include query parameters in QueryJobConfiguration

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#1892]
I notice that [QueryRequest.Builder](http://googlecloudplatform.github.io/google-cloud-java/0.12.0/apidocs/com/google/cloud/bigquery/QueryRequest.Builder.html) has methods to add positional and named parameters, but [QueryJobConfiguration.Builder](http://googlecloudplatform.github.io/google-cloud-java/0.12.0/apidocs/com/google/cloud/bigquery/QueryJobConfiguration.Builder.html#setUseQueryCache-java.lang.Boolean-) does not.

After a discussion with the BigQuery engineering team, I'm updating all the Java samples to create a job directly (jobs.insert) rather than use the query method (jobs.query). I won't be able to update the samples that use query parameters until these methods are included in the QueryJobConfiguration class.

**Comment by garrettjonesgoogle** [comment]
This was incidentally completed as part of https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2323 .
