### ISSUE TITLE
Sample code incorrect in com.google.cloud.pubsub.spi.v1.AckReply.java

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-java#1897]
Sample has an incorrect call to `consumer.accept()` in lines [37](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1/MessageReceiver.java#L37) and [39](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/spi/v1/MessageReceiver.java#L39). The `null` parameter shouldn't be there.

**Comment by garrettjonesgoogle** [comment]
This will be fixed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1899 .

**Comment by garrettjonesgoogle** [comment]
The fix was merged. Closing this issue.
