### ISSUE TITLE
Fix large memory usage

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1907]

**Comment by garrettjonesgoogle** [comment]
@vam-google : for this, we want to at least figure out what the cause might be before GA; after we figure out the cause, we can then decide if we want to actually fix it before GA or not.

**Comment by meltsufin** [comment]
@vam-google Can you also look into the breakdown between heap and off-heap memory usage as part of this?

**Comment by vam-google** [comment]
Profiling is completed.
@meltsufin the results are sent to your mailbox, including the non-heap usage results.

**Comment by vam-google** [comment]
The found memory issues are test-related and are not present in the actual clients code.

**Comment by vam-google** [comment]
Closing as the memory issues are caused by testing code only.
