### ISSUE TITLE
0.13.0-alpha not detected in Android Studio gradle

### ISSUE THREAD

**Issue by grantespo** [GoogleCloudPlatform/google-cloud-java#1924]
The latest available version is compile 'com.google.cloud:google-cloud-translate:0.11.0-alpha'

Can you please update this?

**Comment by garrettjonesgoogle** [comment]
The correct version is 0.13.0-beta; there was a mistake in the README for google-cloud-translate. I will correct the README shortly.

**Comment by garrettjonesgoogle** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1926 .
