### ISSUE TITLE
Conflict with dependency 'com.google.code.findbugs:jsr305' when importing pubsub in Android gradle

### ISSUE THREAD

**Issue by dariosalviwork** [GoogleCloudPlatform/google-cloud-java#1936]
I have a bare empty Android project, I am following [this guide](https://cloud.google.com/pubsub/docs/reference/libraries) for PubSub java client.
 So basically:

`compile group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '0.11.0-alpha'`

My gradle file is [here](https://gist.github.com/dariosalviwork/f03e3b58b54f597ba2ccbea7a21c0afa).

The error I get is:

> Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.0) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

There are also 2 warnings:

> Warning:WARNING: Dependency org.json:json:20151123 is ignored for release as it may be conflicting with the internal version provided by Android.

> Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.

I think this is related to #1319 but I can't make those suggested solutions work out.

Any suggestions?

**Comment by dariosalviwork** [comment]
Hi again, it seems that excluding those replicated dependencies may fix it:

so, instead of `compile group: 'com.google.cloud', name: 'google-cloud-pubsub', version: '0.11.0-alpha'`, this would produce no errors nor warnings:

```
 compile ('com.google.cloud:google-cloud-pubsub:0.11.0-alpha') {
        exclude group: 'com.google.code.findbugs'
        exclude group: 'org.apache.httpcomponents'
        exclude group: 'org.json'
 }
```

I'll leave the issue open in case there are any better suggestions, or feel free to close it.

**Comment by shinfan** [comment]
Excluding the conflicting dependencies looks appropriate to me.
