### ISSUE TITLE
Handle new values in API responses gracefully (not-almost-GA clients)

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1944]
Corresponds to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1832 but for clients that aren't almost GA.

**Comment by tcoffee-google** [comment]
Removing translation, as it appears to contain no instances of this issue.

**Comment by tcoffee-google** [comment]
Removing pubsub and spanner, as they do not appear to do protobuf conversion in this way.

**Comment by tcoffee-google** [comment]
I believe the above PRs have covered the only remaining instances of this issue.
