### ISSUE TITLE
update gRPC with a version which solves tcnative collisions

### ISSUE THREAD

**Issue by frko** [GoogleCloudPlatform/google-cloud-java#1958]
The issue I am encountering is already fixed in the netty.tcnative fork 2.0.0.Final which is nbot yet included in gRPC master. Upgrading gRPC to fix https://github.com/netty/netty-tcnative/issues/151 and depending on that in google-cloud-java would relieve us from any issues with multiple tcnative usages within the same jvm.

**Comment by garrettjonesgoogle** [comment]
We have upgraded gRPC to 1.4 and are using the 2.x series of tcnative now, so I'm going to close this out.
