### ISSUE TITLE
[Storage] Question about download object sample

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-java#1962]
Hi, 

I'm trying to understand why the [download object](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L361-L390) sample has a condition for an object size of 1 mb and larger objects. Why not just simplify the simplify it down to:

```
  Blob blob = storage.get(blobId);
  if (blob == null) {
    System.out.println("No such object");
    return;
  }

  PrintStream writeTo = System.out;
  if (downloadTo != null) {
    writeTo = new PrintStream(new FileOutputStream(downloadTo.toFile()));
  }
      
  // Blob is small read all its content in one request
  byte[] content = blob.getContent();
  writeTo.write(content);
      
  if (downloadTo == null) {
    writeTo.println();
  } else {
    writeTo.close();
  }
```

Thank you.

**Comment by vam-google** [comment]
This is to demonstrate the recommended way of handling [small objects](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L370) and handling [large objects](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L374)

This is an example code and its goal is to demonstrate how the libraries should be used, ideally showing the best practices. 

Theoretically an object can become bigger, than available memory so the "easy way" of calling `byte[] content = blob.getContent()` will just crush the program.

**Comment by shinfan** [comment]
@frankyn Does @vam-google answer your question? (If yes I will close this issue)

**Comment by frankyn** [comment]
Thanks @vam-google, is there reason for using exactly 1mb as the threshold?

**Comment by vam-google** [comment]
I don't think so, it is just a "rasonable" round number, good for examples. Strictly speaking, it is not even a 1MB, as it is 1,000,000, while 1MB = 2^20 = 1,048,576.

**Comment by frankyn** [comment]
Mebibyte versus Megabyte. Thank you! I just wanted to make sure, because it's a magic number in the sample code and can be confusing.

Is there a rational to use the magic number `1_000_000` instead of a variable?

**Comment by vam-google** [comment]
I don't think there is any specific rational behind that, probably it was just simpler to write the sample in this way. 
Closing the issue.
