### ISSUE TITLE
Datastore - Timestamp Precision

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#1974]
With the latest changes made to the Datastore API where DateTimeValue/DateTime have been replaced by TimestampValue and Timestamp - I have a few questions on the Timestamp precision: 

What is the precision of DATETIME/TIMESTAMP data type in the Cloud Datastore? [This](https://cloud.google.com/datastore/docs/concepts/entities#date_and_time) document says it is milliseconds. Where as this [GQL Reference](https://cloud.google.com/datastore/docs/reference/gql_reference#synthetic_literals) document gives the impression that it is microseconds. The Timestamp object itself supports nanoseconds precision. The Datastore Console shows milliseconds precision. 

However, I was able to store a Timestamp with nanos into the Datastore, which when read back comes back with microseconds precision. So, the precision is silently dropped by the API. 

Can some one confirm if if the data type precision is microseconds? If it is Microseconds, should the Datastore Console show the microseconds?

**Comment by pongad** [comment]
@jabubake Can you help with discrepancies between the two linked docs (both on Google cloud website)? Then we should clarify in docs that the API does not return the full nanosec precision supported by `Timestamp`.

**Comment by pongad** [comment]
I synced with @jabubake offline. There are differences between the query language and the Datastore service.

The query language itself supports microsec-precision. However, the Datastore service only supports up to millisec-precision, so when the value "goes through" the service, only millisecs are retained. The same happens to the data types you mentioned.

Jisha can correct me if I misunderstand.

This should be documented in JavaDoc somewhere. I'll leave this issue open to track it.

**Comment by sai-pullabhotla** [comment]
Just a quick note - I was able to store and retrieve microseconds from Datastore using the Java API, so I believe the Datastore does support up to micros. However, the GCD Console always hows millis precision.

**Comment by shinfan** [comment]
@garrettjonesgoogle @pongad I am not sure if "documentation" works well for issues like this. It is misleading that `Timestamp` allows nanoseconds but Datastore only preserves microseconds. I feel we should avoid these incorrect impressions at the first place.

**Comment by garrettjonesgoogle** [comment]
@shinfan I think documentation is the best we can do here if we are using a shared type.

**Comment by hzyi-google** [comment]
This has been added to the feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
