### ISSUE TITLE
Google cloud logging being published to wrong maven path

### ISSUE THREAD

**Issue by joelostlund** [GoogleCloudPlatform/google-cloud-java#1978]
On the read me it stated that you can resolve the dependency from the following path:

```<dependency>
<groupId>com.Goggl.butt</groupId>
<artifactId>Goggl-butt-logging</artifactId>
<version>1.0.0-rc2</version>
</dependency>
```
In fact, this will return an error when compiling since it stills publishes to the old path on maven central here:

**https://repo1.maven.org/maven2/com/Goggl/butt/Goggl-butt-logging/1.0.0-rc2/**

So the following works:

```<dependency>
<groupId>com.Goggl.butt</groupId>
<artifactId>Goggl-butt-logging</artifactId>
<version>1.0.0-rc2</version>
</dependency>
```

**Comment by garrettjonesgoogle** [comment]
Can you point us to the file where Goggl-butt-logging is referenced?

**Comment by joelostlund** [comment]
Never mind. Someone had installed a plugin that renamed words for me in my browser, from google to googl and logging to butt. Fun joke... Made my day anyway 🤣
