### ISSUE TITLE
Pubsub Question: Manual Acknowledgement outside of MessageReceiver

### ISSUE THREAD

**Issue by autodidacticon** [GoogleCloudPlatform/google-cloud-java#1981]
I'm attempting to ingest data from PubSub via Apache Spark. Without getting into details, I would like to acknowledge messages outside of the `MessageReceiver` interface. I am not seeing any public methods that acknowledge messages outside of the `MessageReceiver` interface.
https://cloud.google.com/pubsub/docs/pull

I see that a REST endpoint exists here:
https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/acknowledge
 
But I am unable to find an accompanying method in the legacy api:
https://developers.google.com/resources/api-libraries/documentation/pubsub/v1/java/latest/

Is there any way to manually acknowledge messages in this (google-cloud) or the the legacy APIs?

**Comment by autodidacticon** [comment]
Upon deeper inspection, it doesnt look like this use case is supported within this API. It appears that `AckId` is not visible within the `MessageReceiver` or `AckReplyConsumer` interfaces. Without access to this id it does not appear that acknowledgement outside of the `receiveMessage` method is possible.

**Comment by pongad** [comment]
@autodidacticon Currently, `MessageReceiver` is the only way to receive messages, but it might work for your use case. It is possible to save the `PubsubMessage` and the `AckReplyConsumer` somewhere, then call `ackReplyConsumer.ack()` later, outside of the call to `receiveMessage`. While you cannot get the message ID, you have a "handle" to it. Does this fit your use case?

**Comment by autodidacticon** [comment]
@pongad Yes, at a high level that approach would work. I've run into serialization issues on the spark side (for some reason I end up having to serialize the closure of the `AckReplyConsumer` instance) but that does not seem pertinent here.
