### ISSUE TITLE
Add Canonicalized_Extension_Headers for signedURL builder

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-java#2000]
Cloud Storage SignedURLs allows for custom headers you can set to define metadata:

* [https://cloud.google.com/storage/docs/access-control/signed-urls#string-components](https://cloud.google.com/storage/docs/access-control/signed-urls#string-components)

It doesn't look like you can add this in now during signURL construction:

* [StorageImpl.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/337ca2f234755453e04e2915880520bb6bcbd4c3/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java#L494)

note BlobInfo has metadata defined in it already so maybe use that:
  * [BlobInfo.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/337ca2f234755453e04e2915880520bb6bcbd4c3/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobInfo.java#L255)

the following shows how to manually construct the signed URL with canonical headers outside of this library

```java
ServiceAccountCredentials creds = ServiceAccountCredentials.fromStream(new FileInputStream("YOUR_CERT.json")); 

String BUCKET_NAME = "your_bucket"; 
String OBJECT_NAME = "a.txt"; 
String SERVICE_ACCOUNT_EMAIL = "svc-2-429@your_project.iam.gserviceaccount.com"; 
String verb = "PUT"; 
long expiration = System.currentTimeMillis()/1000 + 60; 
String Canonicalized_Extension_Headers = "x-goog-meta-icecreamflavor:vanilla"; 


byte[] sr = creds.sign( (verb + "\n\n\n" + expiration + "\n" + Canonicalized_Extension_Headers + 
"\n" + "/" + BUCKET_NAME + "/" + OBJECT_NAME ).getBytes() ); 
String url_signature = new String(Base64.encodeBase64( sr )); 
String signed_url = "https://storage.googleapis.com/" + BUCKET_NAME + "/" + OBJECT_NAME + 
"?GoogleAccessId=" + SERVICE_ACCOUNT_EMAIL + 
"&Expires=" + expiration + 
"&Signature=" + URLEncoder.encode(url_signature, "UTF-8"); 

System.out.println(signed_url); 
```

Just to note, you'll need to post the headers too but thats outside of this FR:
```
curl -v -H "x-goog-meta-icecreamflavor:vanilla" -X PUT "https://storage.googleapis.com/.....&Signature=Ol1zLbXd0W%2B3q....3D%3D" --upload-file a.txt 
```

**Comment by frantello** [comment]
Kindly see pull request #2422

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by hzyi-google** [comment]
This feature request is finished.
