### ISSUE TITLE
We are writing "trace_id" label, but when searching for request log lines, Stackdriver sends requests looking for "appengine.googleapis.com/trace_id". 

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/google-cloud-java#2009]
The com.google.cloud.logging.TraceLoggingEnhancer class adds the label "trace_id" , but when looking up log lines for the selected request by trace ID the Stackdriver wen UI sends a query for "appengine.googleapis.com/trace_id" .   The mismatch causes request logs to NOT show when selecting the log line from the nginx.request  request log.   

Can we resolve this discrepancy by using "appengine.googleapis.com/trace_id"  or work with Stackdriver to use the field we are writing? 

Here is the filter query sent by the Stackdriver API when viewing an Nginx request log: 

resource.type="gae_app"
resource.labels.project_id="bmenasha-1"
resource.labels.version_id="20170426t115924"
resource.labels.module_id="default"
labels."appengine.googleapis.com/trace_id"="be90be962109bc6d4fa4c2cbd42d0d6a"
logName!="projects/bmenasha-1/logs/appengine.googleapis.com%2Fnginx.request"
timestamp>="2017-04-26T16:46:45.230867286Z"
timestamp<="2017-04-26T16:47:48.290867286Z"

Thanks

**Comment by jabubake** [comment]
FYI, https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2011 addresses this. I've decided to take up the possible renaming to "trace_id" in a separate CL.
