### ISSUE TITLE
Javadoc links to gRPC resources broken

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#2010]
See http://googlecloudplatform.github.io/google-cloud-java/0.17.1/apidocs/com/google/cloud/pubsub/spi/v1/SubscriptionAdminClient.html  

Click on "Snapshot" or "Subscription" types in the "method summary" and get 404s.  Note that these types are also not listed in the top level hierarchy so finding is a broken UX.  This also seems to be a systematic problem beyond Pub/Sub based on offline discussion with @garrettjonesgoogle.

Rendered, broken link;
http://googleapis.github.io/googleapis/java/grpc-google-cloud-pubsub-v1/0.1.9/apidocs/com/google/pubsub/v1/Snapshot.html?is-external=true

Correct link:
http://googleapis.github.io/googleapis/java/proto-google-cloud-pubsub-v1/0.1.9/apidocs/com/google/pubsub/v1/Snapshot.html?is-external=true

**Comment by garrettjonesgoogle** [comment]
cc @michaelbausor this is a result of splitting the packages.
