### ISSUE TITLE
Wrong version in top level pom

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/google-cloud-java#2016]
The top level pom has version of 0.17.2-alpha-SNAPSHOT, while all the module poms are at 1.0.1-SNAPSHOT
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/pom.xml#L7

**Comment by garrettjonesgoogle** [comment]
This is intentional. Only some module poms are at 1.0.1-SNAPSHOT: core, core-http, core-grpc, datastore, logging, and storage. Everything else is 0.17.2-{alpha|beta}-SNAPSHOT.

**Comment by gregw** [comment]
Ah OK - caused some minor confusion, but now that I know....
