### ISSUE TITLE
Move credential provider up from ChannelProvider to ClientSettings

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2034]
Currently in GAPIC clients, credentials have to be set on the channel. We should improve the credential customization experience because it's now possible to add credentials on a call-by-call basis in a non-experimental way through `CallOptions` in grpc. We should do the following:

- [x] Create a future callable type in gax which adds the credentials to the call
- [x] Add credentials provider to `ClientSettings`
- [x] Deprecate credentials provider on `ChannelProvider`
- [x] Make it work in streaming callable too
- [x] Add `setCredentialProvider` to `Publisher`/`Subscriber` in Pub/Sub
- [x] Regenerate GCJ

**Comment by garrettjonesgoogle** [comment]
@pongad is this all done?

**Comment by pongad** [comment]
We'll need to release gax and regen GCJ. The "manual code change" part is done though. Are we good releasing gax?

**Comment by tcoffee-google** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2114

**Comment by garrettjonesgoogle** [comment]
The final closing of this issue depends on https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2116 being completed - reopening.

**Comment by garrettjonesgoogle** [comment]
Done fully in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2116 .
