### ISSUE TITLE
Add a README section on supported runtime environments & workarounds

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2039]
gRPC currently don't work well in embedded Tomcat or embedded Netty envs. Document what we know works and don't work and work arounds.

Specifically, if someone uses the client lib in Spring Boot, they need to exclude tomcat starter and use jetty starter instead.

Corollary to this, in each module's README, refer to this section for supported envs.

**Comment by shinfan** [comment]
@saturnism Can you be more specific what did not work well in Tomcat or Netty?

**Comment by tswast** [comment]
I encountered this issue today with the Cloud Pub/Sub client library.

With Spring Boot, I got the error "Jetty ALPN/NPN has not been properly configured" at runtime. These were my dependencies:

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>1.5.3.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-core</artifactId>
      <version>4.2.2.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>0.17.2-alpha</version>
    </dependency>
```

The code worked without modification after I [made Spring Boot use Jetty instead of Tomcat](https://www.mkyong.com/spring-boot/spring-boot-jetty-as-embedded-server/).

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>1.5.3.RELEASE</version>
      <exclusions>
        <exclusion>
          <!-- Use Jetty instead of Tomcat
               https://www.mkyong.com/spring-boot/spring-boot-jetty-as-embedded-server/ -->
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jetty</artifactId>
      <version>1.5.3.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-core</artifactId>
      <version>4.2.2.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>0.17.2-alpha</version>
    </dependency>
```

**Comment by jabubake** [comment]
Note has been added in the main README. We still need to add links to Supported environments on each module.

**Comment by joaoandremartins** [comment]
Yes, I just started using the PubSub API within a Spring Boot app and I'm getting this too.

**Comment by shinfan** [comment]
@jabubake Can we close the issue now since the notes has been added?

**Comment by joaoandremartins** [comment]
Ideally, we would want gRPC to work with Tomcat seamlessly too.

**Comment by joaoandremartins** [comment]
Seems like a fix for this is coming out on a next release of the grpc-java library.
https://github.com/grpc/grpc-java/issues/2996

**Comment by Mistic92** [comment]
Yesterday I have encountered the same problem with spring boot and pubsub lib. Even when I'm using Jetty I'm still getting "Jetty ALPN/NPN has not been properly configured."
When can we expect fix? 
I see there is new version of grpc (1.3.0) so now we are waiting for pubsub?

**Comment by garrettjonesgoogle** [comment]
We have upgraded to grpc 1.4 which removes the conflict with Tomcat. Since the underlying issue should be fixed, I'm going to close this out.
