### ISSUE TITLE
Async API for Cloud Compute

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/google-cloud-java#2043]
Currently API suggests to use blocking method call `Operation#waitFor`, but we need to use async APIs for that.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
