### ISSUE TITLE
Write correlation-id with log entry metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-java#2057]
By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon. See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.

**Comment by arouzrokh** [comment]
@meltsufin Mike is this part of the Jetty work already? I think we merged this in for Java right?

**Comment by garrettjonesgoogle** [comment]
@JustinBeckwith your gist link is broken...

**Comment by meltsufin** [comment]
There's support through a [JUL Logging Appender](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-logging-logback/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java) and [Logback Appender](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-logging-logback). Currently, we [document](https://github.com/GoogleCloudPlatform/jetty-runtime#enhanced-stackdriver-logging-beta) the JUL Logging Appender for Jetty.

**Comment by garrettjonesgoogle** [comment]
@meltsufin It isn't clear to me - is the requested functionality supported?

**Comment by meltsufin** [comment]
Yes it's supported now. You can close this issue.

**Comment by garrettjonesgoogle** [comment]
Thanks!
