### ISSUE TITLE
Expose setNullMarker option in BigQuery Java API Format Options

### ISSUE THREAD

**Issue by marco-tranquillin** [GoogleCloudPlatform/google-cloud-java#2061]
Our customer needs to be able to access the ability to set customer **NullMarkers** that are available in the Rest API v2
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs
while using the Java API CSV Options
http://googlecloudplatform.github.io/google-cloud-java/0.15.0/apidocs/index.html

Also interested in potentially workarounds that will allow them to complete the project.

Use case below:

Customer is moving from AWS to GCP, and our very first step is to move from Redshift to BQ. There are multiple production processes waiting for this, including moving our reporting tool to Tableau and deploying our Advertising prediction tool (business critical).
We were developing a tool that could load data from S3 (AWS storage) to BQ. Most of our data has "\N" as the null marker (coming from Hive or MR processes) and we need to be able to load with this one.

**Comment by tcoffee-google** [comment]
Closing for now --- please re-open if this change doesn't meet your needs.
