### ISSUE TITLE
Many of our API's would benefit if we designed to use JTA transactions API

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2063]
We should consider this for Spanner, PubSub, and other API's, however, it might need updating the product API's to support this, so it may be a moot ask.

RayT recently wrote wrote:

> That's a good start. In short, a hook would at least have begin transaction, commit, and abort/recover semantics.
> 
> To be true distributed transactional, it'll need a [XA resource adapter](http://docs.oracle.com/javaee/5/api/javax/transaction/xa/XAResource.html).
> 
> Otherwise, another pattern would be temporarily writing the pub/sub message into a transactional store (e.g., via JDBC into a database), and have another background process that can guarantee delivery and do all the retries, etc.
> 
> That being said, how does Google deal w/ similar cases? Perhaps we recommend people not to do this (that's my guess), but we need to recommend alternatives.

**Comment by saturnism** [comment]
If not XA, start w/ just JTA

**Comment by lesv** [comment]
I sent an email about this recommending JTA with some specs.

**Comment by lesv** [comment]
I know of two customers who would like this - who asked in the last 30 days.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by vkedia** [comment]
@saturnism I was looking at the JTA [transaction](https://docs.oracle.com/javaee/7/api/javax/transaction/Transaction.html) interface. There are methods there which are needed for supporting distributed transactions which Spanner does not support.

Does it still make sense to implement this interface and just implement the commit and rollback functionality and throw UnsupportedException for other methods? Are there other databases which do this? Without XA support, is implementing this still useful?

**Comment by lesv** [comment]
Odds are that if we don't do a bunch of other stuff, this isn't helpful by itself.  In looking at SpringBoot, it appears to support jta w/ XA in a [few](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-jta-jndi) [cases](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-jta-atomikos) [more](https://stackoverflow.com/questions/36129364/spring-boot-with-jpa-repositories-using-jta-transaction-manager-using-jboss-6)

@meltsufin may have thoughts.

**Comment by meltsufin** [comment]
@lesv I'm not sure what you mean by "if we don't do a bunch of other stuff, this isn't helpful by itself". Distributed transactions are very commonly used in the enterprise, especially for things like read a message from a queue (think Pub/Sub) and update a database (think Cloud SQL). I think Cloud SQL is covered with the JDBC driver, but I don't think there is currently a way for Pub/Sub to participate in a distributed transaction. It doesn't even seem to have a concept of a transaction. At least once delivery, is all you get. Providing something on top of Pub/Sub to simulate transactional semantics, would be a lot of work. Maybe that's what you mean by "a bunch of other stuff".

You can read about Spring support for distributed transactions here: https://spring.io/blog/2011/08/15/configuring-spring-and-jta-without-full-java-ee/

**Comment by olavloite** [comment]
I have added support for XADataSource and XAResource to my [open source JDBC driver for Google Cloud Spanner](https://github.com/olavloite/spanner-jdbc), and also made a small sample application by [modifying the example from Spring Boot](https://github.com/olavloite/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-jta-atomikos).
