### ISSUE TITLE
GAPIC auto generated code should allow manual flow control

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-java#2072]
In cloud spanner Java client, we use manual flow control for the streaming rpcs here:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GrpcSpannerRpc.java#L519

We would need this support in GAPIC code as well before we can change to use that. Specifically we want to manually request for more messages from the stream rather than the client automatically getting the next message.

**Comment by garrettjonesgoogle** [comment]
@vkedia , it turns out that manual flow control in grpc is experimental:

https://github.com/grpc/grpc-java/issues/1788

So unfortunately we can't add a dependency on that until the `@ExperimentalApi` is removed. Otherwise, users could get broken when we upgrade the version of grpc in use.

**Comment by garrettjonesgoogle** [comment]
Additionally, google-cloud-spanner's direct usage of this `@ExperimentalApi` feature will prevent it from going to 1.0 even if it is never added to GAX.

**Comment by vkedia** [comment]
I see. Thanks for bringing this to my attention. I will talk to gRPC team and see if they have any plans to make this non experiemental.
