### ISSUE TITLE
Support publishing to dynamic topics

### ISSUE THREAD

**Issue by viniciusccarvalho** [GoogleCloudPlatform/google-cloud-java#2080]
The current client model, which creates a Publisher for each topic `Publisher.defaultBuilder("TOPIC_NAME")`, which becomes a  bit prohibitive in use cases where the consumers could publish messages to multiple topics. 

In that scenario we would need to create one publisher for each topic, and since those publishers seem to consume some resources (like connections to the server) we could end up with unbounded number of those objects lying around.

What's odd is that the gRPC api that is defined for pubsub actually does not follow this pattern since one could have different PublishRequests objects while sending to the server.

Other brokers such as Kafka or RabbitMQ allows users to specify topics or exchanges just as simple Strings while the publisher that has the connection factory is shared amongst users of the library.

Such model would help us designing a more intuitive Spring MessagingTemplate for google pubsub as we would not need to take care of the control of Publisher instances

**Comment by meltsufin** [comment]
@garrettjonesgoogle WDYT?

**Comment by garrettjonesgoogle** [comment]
@pongad @davidtorres @saturnism take a look

**Comment by garrettjonesgoogle** [comment]
Also @kir-titievsky take a look

**Comment by kir-titievsky** [comment]
@viniciusccarvalho Vinicius, what are you thoughts on using the gRPC interface directly? Our general thinking has been that the client library is for end users and the gRPC service APIs are for client library developers. You are a client library developer in this case.

**Comment by meltsufin** [comment]
@kir-titievsky Using gRPC interface directly has definitely come up, but we thought using the library would avoid rewriting some of the features of the library, and would also benefit the library from additional battle testing.

**Comment by viniciusccarvalho** [comment]
@kir-titievsky I'd rather not use it to be honest. My question is around the use for end users too, at least I believe sending data to multiple topics (let's put aside the partitioning ideas we discussed before) it's something that most users would want to.

And in our specific use case, we would like to write a Spring Message Template. A Message template within Spring mostly follows a pattern of send(String destination, Message<T> message)

There are nuances and overloaded methods, but for JMS/AMQP/Kafka they all follow that pattern. The template usually holds one connection factory to those brokers (which could have 1-* pooled connections)

The current pubsub client (unlike the version prior to 0.8) does not follow this pattern. And it's just a question around the feasibility of this signature be also supported:

`Publiser.defaultBuilder().build()` and perhaps have a publish(PublishRequest) instead of publish(PubSubMessage)

**Comment by kir-titievsky** [comment]
@meltsufin Makes sense.  

Technical question for the benefit of the ignorant (me): can you not share an executor among multiple clients to achieve most of this result?  If true, I recognize this is not the most polished solution, but at least workable.

**Comment by meltsufin** [comment]
We might be able to set the `executorProvider` on the `Publisher` to avoid creating too many threads per topic.

I think part of the reason the library doesn't let you change the topic on the `Publisher` is that there is some kind of message batching that it's doing, and that would have to change to batch by topic within a single `Publisher`.

**Comment by pongad** [comment]
> there is some kind of message batching that it's doing

This is correct. In our testing, this has increased the throughput of Publisher easily by an order of magnitude on a single core machine.

How "bounded" are these topics? Do you have a few known topics you need to publish to? Or is this something like reading topic name from user input?

**Comment by meltsufin** [comment]
> How "bounded" are these topics? Do you have a few known topics you need to publish to? Or is this something like reading topic name from user input?

Since we're using it in framework code, we couldn't really know how many topics the app might want to write to. Presumably, it's a small set.

Perhaps, a viable approach would be to create a `MultiTopicPublisher` that just uses the simple `Publisher` under the hood and shares the thread pool.

**Comment by viniciusccarvalho** [comment]
Yes I understand the need for batching. On the previous version of the client I had to batch myself. But it was basically a map of <string,pubsummessage> that was sent in batches either when a timeout happened or a maximum number of messages.

The approach described by @meltsufin is what we ended up doing for now. There's a PublisherFactory that return Publishers by topic and creates them sharing the same executor, and stores them on a Map

**Comment by pongad** [comment]
I understand the use case. I think I have a reasonable solution in mind, but I want to play with it a little more. I'll keep this thread posted.

**Comment by pongad** [comment]
At the moment, we'd like to focus on stabilizing our current feature set. We will loop back to this when we prioritize additional features.

In the meantime, can I suggest [Guava's Cache](https://github.com/google/guava/wiki/CachesExplained)?

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by wikp** [comment]
Hi there!

Omitting courtesy ;) 

Is there any chance for this to be developed? My use case is mirroring Kafka cluster to PubSub using 
[linkedin/Brooklin](https://github.com/linkedin/Brooklin). I have pretty large number of topics (let's say 1k per cluster). I don't know exact number but even 100 topics could be assigned to single brooklin worker at the same time. It obviously could lead us to some performance issues.

If you don't plan to deliver such a feature any time soon, could you recommend us some workaround?

**Comment by meltsufin** [comment]
@wikp The workaround is to essentially create a separate publisher per topic dynamically. We do this in [Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp).
See [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/publisher/PubSubPublisherTemplate.java#L93).

**Comment by wikp** [comment]
@meltsufin thanks, I do it the same way, we'll see how it performs later this week :)
