### ISSUE TITLE
PubSub - Missing JavaDocs 

### ISSUE THREAD

**Issue by sai-pullabhotla** [GoogleCloudPlatform/google-cloud-java#2081]
The published Java Docs at http://googlecloudplatform.github.io/google-cloud-java/0.18.0/apidocs/ - seem to be missing some classes such as `PubsubMessage`, `TopicName`, `SubscriberName`, `ApiFuture`, etc. Since these are public APIs that developers would be using, can we include the JavaDocs for these?

**Comment by tcoffee-google** [comment]
This also seems to impair readability in other JavaDocs, e.g.: http://googlecloudplatform.github.io/google-cloud-java/0.18.0/apidocs/com/google/cloud/logging/spi/v2/LoggingClient.html

**Comment by jabubake** [comment]
Vision as well : http://googlecloudplatform.github.io/google-cloud-java/0.18.0/apidocs/com/google/cloud/vision/spi/v1/ImageAnnotatorClient.html#batchAnnotateImages-java.util.List-

**Comment by pongad** [comment]
I'm working on this. Ran into a little issue but should resolve soon

**Comment by omaray** [comment]
Thanks for your efforts on this @pongad! We're totally excited about this!!

**Comment by pongad** [comment]
This should have been resolved as of `0.20.1-alpha`. Please reopen if the problem persists.
