### ISSUE TITLE
Version Numbers and Backward Incompatibility Question

### ISSUE THREAD

**Issue by dankirkd** [GoogleCloudPlatform/google-cloud-java#2082]
The version history for this library went from "0.8.0" and never being an "alpha" version to "0.8.1-alpha", and always since being an "alpha" release.

I believe that this explains that: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1471

However, can you confirm that when you talk about backward incompatibility you are just talking about the evolving library, class and package name, and not that a message produced using 0.18.0-alpha cannot be read by a client that uses 0.8.0, for example?  That would seem unlikely since I cannot pin Google PubSub topics to a given version, right?

**Comment by tcoffee-google** [comment]
Yes, these version numbers refer only to the client library.
