### ISSUE TITLE
google-cloud-logging relies on Netty version that conflicts with Tomcat

### ISSUE THREAD

**Issue by grnadav** [GoogleCloudPlatform/google-cloud-java#2092]
Hello

google-cloud-logging 1.0.2 relies on netty-codec-http2 and netty-handler-proxy at version 4.1.8.Final,
which has a bug that causes APR to not load the classes from the bundled tcnative.

This was solved in 4.1.9+

SO issue: https://stackoverflow.com/questions/41909764/io-netty-handler-ssl-openssl-uses-tomcat-classes-instead-of-self

**Comment by garrettjonesgoogle** [comment]
The version of Netty used by google-cloud-java has to match the version that grpc uses exactly, and grpc 1.3 is on Netty 4.1.8.Final. We will be able to get a newer version of Netty when grpc 1.4 is released. Marking as blocked.

**Comment by garrettjonesgoogle** [comment]
It should be noted that the dependency is not broken in isolation; it just causes conflicts with Tomcat.

**Comment by grnadav** [comment]
Is there any way to contribute to assist in resolving this issue? (this this repo or grace's or otherwise)

This blocks an important feature we're due to ship in our application (monitoring GCP audit), and we'd really want to avoid falling back to GCP's REST API just because of this :/

**Comment by Evegen55** [comment]
Exactly the same problem with PubSub API.

**Comment by grnadav** [comment]
@garrettjonesgoogle 
grpc released version 1.4 18 days ago.
any chance this will be merged ?

**Comment by garrettjonesgoogle** [comment]
We are really close: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2171

**Comment by grnadav** [comment]
I can confirm this is now working since the merge of #2171 (using the version that followed 1.2.1).
Closing.
