### ISSUE TITLE
[Feature Request] Add downloadTo to Storage Client

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-java#2107]
# Feature Request
The Java Cloud Storage client `google-cloud-storage` has a [sample to download a Blob](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/StorageExample.java#L358) (shown below). The feature request is to add this functionality into the sample shown into an additional method `downloadTo` for [Class Blob](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Blob.java) to reduce complexity of downloading a blob using the Java Storage client. At the moment [other clients](https://cloud.google.com/storage/docs/object-basics#download) use this approach and allow a user to download a given Blob to a specified file.
 
![xxnxbgjccop](https://cloud.githubusercontent.com/assets/1907648/26698438/d092c64a-46ca-11e7-9d3e-b3aa3d4e109a.png)
 
# Language Comparison:
In other [client libraries](https://cloud.google.com/storage/docs/object-basics#download) (google-cloud-ruby) there exists a method to download a Blob to a specified file. 

![h4q4mswiyt0](https://cloud.githubusercontent.com/assets/1907648/26698442/db486ad6-46ca-11e7-910d-4c21822d875c.png)
 
Another example using .NET:
 
![bbfhutvhz08](https://cloud.githubusercontent.com/assets/1907648/26698449/e15d975c-46ca-11e7-84f0-3c5ecdc09dca.png)
 
# Example of usage
 
```
try {
  String bucketName = ”BUCKET_NAME”;
  String blobName = ”BLOB_NAME”;
 
  Blob blob = BlobId.of(bucketName, blobName);
  Path path = FileSystems.getDefault().getPath("output.ext”);
 
  blob.downloadTo(path);
} catch (IOException io) {
   //...
}
```

**Comment by frankyn** [comment]
@garrettjonesgoogle is this being prioritized this quarter?

**Comment by garrettjonesgoogle** [comment]
@frankyn i'm not sure if you are asking whether we will decide on the prioritization this quarter (maybe) or whether we are scheduling it for this quarter (not yet).

**Comment by frankyn** [comment]
I mean, is it scheduled for this quarter. This issue will help the developer experience when using the Java Client library to download a blob. Thanks @garrettjonesgoogle
