### ISSUE TITLE
Pull should set return_immediately to false

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#2108]
This came out of a discussion with Pubsub team.

cc @haakonringberg

**Comment by garrettjonesgoogle** [comment]
@pongad can you provide more context?

**Comment by pongad** [comment]
Slightly edited the description. IIUC, it saves RPC calls, but @haakonringberg can probably provide better details than I can.

**Comment by haakonringberg** [comment]
We now always discourage the use of return_immediately (it's an option we shouldn't have provided in the API). It's misleading (e.g., what does "immediately" mean in the context of a backlog?) and hurts throughput.
