### ISSUE TITLE
Date for next release?

### ISSUE THREAD

**Issue by droazen** [GoogleCloudPlatform/google-cloud-java#2110]
Just wanted to ask if a date for the next release had been scheduled, since it's been a few weeks since the last one, and there's a patch (https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2083) that we're eagerly awaiting over in https://github.com/broadinstitute/gatk

Thanks!

**Comment by garrettjonesgoogle** [comment]
We will do one within the next few business days.

**Comment by droazen** [comment]
Resolved! Thank you!
