### ISSUE TITLE
StorageOptions.getService() javaDoc could be clearer

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2115]
A customer has asked:
`Storage storage = StorageOptions.getDefaultInstance().getService();` from [storage quickstart](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/storage/cloud-client/src/main/java/com/example/storage/QuickstartSample.java)

getService() is not defined.

Having looked at the JavaDocs, it could say that it returns a Service object for the current service, for example, if you are using Google Cloud Storage, it returns a `Storage` object. b/62208662

**Comment by tcoffee-google** [comment]
Just to be clear, is the issue that we lack a doc string [here](http://googlecloudplatform.github.io/google-cloud-java/0.7.0/apidocs/com/google/cloud/ServiceOptions.html#getService--)?

**Comment by lesv** [comment]
I think so.  That's how I read the issue.
