### ISSUE TITLE
Cloud Spanner Client should prevent nested transactions

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-java#2117]
Cloud Spanner does not support [nested transactions](https://en.wikipedia.org/wiki/Nested_transaction). But the client library does allow users to call `DatabaseClient.readWriteTransaction().run()` inside of the callback that is provided to an outer `DatabaseClient.readWriteTransaction().run()`. This is misleading since users might believe that this will behave like a nested transaction but in reality these will be two independent transactions. This is confusing and a source of bugs. Specifically the inner transaction might succeed while the outer might ABORT, in which case the callback will be rerun thus rerunning the inner transaction. 
We should prevent this from happening by detecting and raising an error if someone calls `DatabaseClient.readWriteTransaction().run()` inside the callback provided to `DatabaseClient.readWriteTransaction().run()`.  Note that this needs to be done before GA since this is a known breaking change.
Also note that if we come across a use case where we do want to allow calling a nested `run`, we should be able to enable that in future without making a breaking change. 

cc @jgeewax @bjwatson

**Comment by garrettjonesgoogle** [comment]
GA-blocking issues shouldn't be marked P0; P0 is for issues where the latest release is DOA. Downgrading to P1.

**Comment by bjwatson** [comment]
@vkedia @garrettjonesgoogle I added the `Release Blocking` label to ensure this is fixed before GA.

**Comment by bjwatson** [comment]
FYI @anthmgoogle and @lukesneeringer

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
