### ISSUE TITLE
Use of System ClassLoader didn't find custom logging enhancer

### ISSUE THREAD

**Issue by dclements** [GoogleCloudPlatform/google-cloud-java#2123]
When using the logback appender I tried adding my own `LoggingEnhancer`, but it failed to load with a ClassNotFound exception (which was swallowed).

Investigation revealed that the problem was that the logback appender was loading it using the system classloader. Switching this to the thread context classloader (with `ch.qos.logback.core.util.Loader#loadClass`) worked fine. 

Label: logging-logback

**Comment by tcoffee-google** [comment]
@jabubake would you mind taking a look at this?

**Comment by jabubake** [comment]
@dclements : I'll take a look and patch, if this is the case. Thanks for the suggested fix.

**Comment by jabubake** [comment]
@dclements, can you also provide  the version of JDK you used ?

**Comment by dclements** [comment]
Java 1.8.0_131
Scala 2.12.2
akka-http 10.0.7
akka 2.5.2

Executed using `java -jar`.

Thanks for taking a look!
