### ISSUE TITLE
Release copies project properties file to incorrect location

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#2125]
```
Copying 1 file to /usr/local/google/home/pongad/github/google-cloud-java/google-cloud-video-intelligence/target/classes/com/google/cloud/trace
```

**Comment by Solen-Win** [comment]
I will point out that the first sentence of the page you link

**Comment by garrettjonesgoogle** [comment]
Problem line:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/80f916c2e2f5c8755d1ea689f97c724c1e910021/google-cloud-video-intelligence/pom.xml#L108

This should be fixed ASAP - we won't be reporting library usage correctly until this is fixed.
