### ISSUE TITLE
Copy objects from bucket to other bucket (request 400)

### ISSUE THREAD

**Issue by mensurdurakovic** [GoogleCloudPlatform/google-cloud-java#2126]
I have explained issue here: 

[https://stackoverflow.com/questions/44413977/groovy-java-google-storage-auth-and-request](url)

Anyone knows why this doesn't work as expected?

**Comment by tcoffee-google** [comment]
The choice of authentication method will depend upon where and how you intend to run the code. 

This page provides an overview of the different types of environments in which you might be running and the typical authentication methods for each: https://cloud.google.com/storage/docs/authentication#storage-authentication-java.

Please re-open this issue if you encounter further problems --- thanks!
