### ISSUE TITLE
Storage: support signed URL on GAE and GCE

### ISSUE THREAD

**Issue by neozwu** [GoogleCloudPlatform/google-cloud-java#2142]
Today signed url requires a service account with a signer.  GAE and GCE use their built-in service account, which cannot sign blob.  Our current impl only retrieves signer from service account.  Therefore, it is not working on GAE and GCE. GAE has `appIdentity.signForApp` API that can be used to sign blob. It seems there's ongoing [work](https://github.com/google/oauth2client/issues/471) to support GCE to sign blob. We should make GAE ( and GCE once it's ready) blob signing available in client lib as well.

**Comment by garrettjonesgoogle** [comment]
@neozwu there are two tasks in here: 1) GAE, 2) GCE. Could you split this apart?

**Comment by neozwu** [comment]
GAE & GCE now both use metadata server. Close this issue since supporting signing URL is tracked in #2629
