### ISSUE TITLE
State Java version required

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#2163]
From the pom.xml I think this requires Java 7 or later. However I don't see that anywhere in the docs. Please make this very explicit and obvious.

**Comment by garrettjonesgoogle** [comment]
It's stated here: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/README.md#java-versions

**Comment by elharo** [comment]
1. I read that as applying to the Google Cloud Video Intelligence (Alpha) specifically. We should probably move that and several other sections above the individual APIs. 

2. This also belongs on the home page https://googlecloudplatform.github.io/google-cloud-java/ perhaps in the FAQ (though current cloud tech writer policy is no FAQs)

**Comment by pongad** [comment]
@elharo I'm not sure I follow (1). The link @garrettjonesgoogle posted is not specific to Video Intelligence; it's at the root of `google-cloud-java` repository. Each individual API has similar doc in the API-specific readme though.

**Comment by elharo** [comment]
Here's what it looks like to me:

https://screenshot.googleplex.com/X16FeWarsRS.png
![image](https://user-images.githubusercontent.com/1005544/27439658-79cedffc-5736-11e7-9ba4-328f1870a1f1.png)

It was not immediately obvious to me that  the info such as Java version did not belong to video client. It would be more obvious if all the sections from Troulbeshooting on dopwn moved above the information about specific libraries such as video client.

Furthermore user information such as required version should be on http://googlecloudplatform.github.io/google-cloud-java/ as well.

**Comment by shinfan** [comment]
I think the word 'for this client' is confusing. Maybe we should change it to 'for all clients'

**Comment by pongad** [comment]
Sorry I lost track of this. I'm thinking "for clients in this repository" will make clear we're not just talking about one client.
