### ISSUE TITLE
Client Library performance

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2181]
I'm working with a customer who is moving from MVM's using Objectify and the GAE Bridge to Flex using google-cloud-java Datastore API's.

The customer is reporting that using Objectify on MVM takes about 6-10sec and doing the same thing with google-cloud-java takes 40+seconds.

**Comment by lesv** [comment]
@garrettjonesgoogle @omaray FYI @GoogleCloudPlatform/cloud-datastore FYI

**Comment by garrettjonesgoogle** [comment]
A 6x performance degradation is pretty large, marking P1. 

cc @pongad

**Comment by pongad** [comment]
@lesv Do we know what operations are involved? I can try looking into benchmarking this, but it's difficult to do in the abstract.

**Comment by lesv** [comment]
gRPC Java 1.5 library was released claiming a 2x performance improvement.  Not sure if it a disappointment that Datastore isn't gRPC or not.

Reading a lot of data.  (i'll find something and send it to you.)

**Comment by vam-google** [comment]
Hi @lesv, do you have any update on this (i.e.whic operations are involved)?

**Comment by lesv** [comment]
I will forward you the conversation.

**Comment by hzyi-google** [comment]
This has been added to the feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by davidhardwickbc** [comment]
What's the number of the issue in the backlog?
