### ISSUE TITLE
Add Datastore mapping between POJO and Entity

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2182]
Customers would like a way to easily convert from a POJO to / from a Datastore Entity.

@jabubake FYI
@garrettjonesgoogle FYI

**Comment by sai-pullabhotla** [comment]
I would recommend taking a look at [Catatumbo](http://catatumbo.io), which is an open source ORM framework for Google Cloud Datastore. GitHub project is located at https://github.com/sai-pullabhotla/catatumbo.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
