### ISSUE TITLE
translate: Integration Tests Failing

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#2191]
[Example](https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/jobs/247366554)

I assume this isn't a huge deal since we're discouraging the use of API keys, but I think we should either fix or disable the test.

**Comment by tcoffee-google** [comment]
Fixed in #2186, #2194, #2197, and #2198.

Translate IT success exhibited in https://travis-ci.org/GoogleCloudPlatform/google-cloud-java/builds/247757474.
