### ISSUE TITLE
google-cloud-logging should allow user to set all fields in the LogEntry

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/google-cloud-java#2201]
Currently the interface of `com.google.cloud.logging.LogEntry` does not let me specify the `sourceLocation` among other fields. It would be very nice to be able to set them.

**Comment by shinfan** [comment]
FYI @lesv @garrettjonesgoogle Currently sourceLocation field is not supported by the client.

**Comment by lesv** [comment]
@jabubake FYI
