### ISSUE TITLE
Spanner: Jetty ALPN/NPN has not been properly configured if spark dependencies are added 

### ISSUE THREAD

**Issue by vaiju12p** [GoogleCloudPlatform/google-cloud-java#2211]
My requirement was to write a Spark DataFrame to the Spanner Table, when I tried to run application it end up with "Jetty ALPN/NPN has not been properly configured" even I run spanner application without spark code it was giving this error.
When I run the same application by removing spark dependencies it ran! so, I am on conclusion that, Spanner application is not running with spark dependencies.
here is the spark and Spanner dependencies by putting together it is failing:
 ```
compile group: 'com.google.cloud', name: 'google-cloud', version: '0.20.0-alpha'
 compile group: 'com.google.cloud', name: 'google-cloud-spanner', version: '0.20.0-beta'
 compile group: 'org.apache.hadoop', name: 'hadoop-mapreduce-client-core', version: '2.7.2'
 compile (group: 'org.apache.spark', name: 'spark-core_2.11', version: '2.0.2'){
        exclude group: 'org.apache.hadoop', module:'hadoop-mapreduce-client-core'
    }
 compile group: 'org.apache.spark', name: 'spark-sql_2.11', version: '2.0.2'
 compile group: 'org.apache.hadoop', name: 'hadoop-aws', version: '2.7.2' 

```

**Comment by michaelbausor** [comment]
Hi @vaiju12p! I was able to reproduce the problem using a very simple Spanner application and the dependencies you listed. I found that including the following exclusion in my build.gradle file resolved the issue:
```
configurations {
    compile.exclude module: 'netty-all'
}
```

Let me know if this fixes the problem for you. If it is not an option for you to exclude this dependency, then you may want to investigate the compatibility of different versions of netty that are being used by Spark and by the `io.grpc:grpc-netty` package. You can use `gradle dependencies` to view the dependencies that are being used.

Hopefully that helps!

**Comment by vaiju12p** [comment]
great!! It is working thanks you very much @michaelbausor .
