### ISSUE TITLE
Natural Language API in .20.2 - Missing Types

### ISSUE THREAD

**Issue by tsondreal** [GoogleCloudPlatform/google-cloud-java#2214]
The most current NL API (.20.2) does not have the basic types like Document, Sentiment, AnalyzeSentimentRequest, AnalyzeSentimentResponse, etc.   Where did they get moved to?

**Comment by michaelbausor** [comment]
These protobuf types are distributed as part of the `proto-google-cloud-language-v1` and `proto-google-cloud-language-v1beta2` packages (for versions `v1` and `v1beta2` of the API).

These packages are available [from Maven Central](https://search.maven.org/#search%7Cga%7C1%7Cproto-google-cloud-language-). You can also check the dependency in our pom.xml here: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.20.1/google-cloud-language/pom.xml#L37

**Comment by michaelbausor** [comment]
Hopefully that answered your question, so I've closed out the issue. If not, please feel free to reopen and follow up. Thanks!
