### ISSUE TITLE
Works in App Engine Standard Java 7 (or not)?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#2215]
There's some confusion on my team as to whether we can expect these libraries to work in a white listed App Engine Standard Java 7 environment. 

Is it the intention that all these libraries work there?

**Comment by michaelbausor** [comment]
Currently we don't expect the google-cloud-java libraries to work for App Engine Standard Java 7, based on availability of gRPC support and restrictions in networking I/O and threading.

GAE Standard Java 8 does work, and we are currently working towards an official release of google-cloud-java for which we can be confident that GAE Standard Java 8 is fully supported.

Hopefully that helps! Let me know if you have any additional questions.

cc @neozwu

**Comment by garrettjonesgoogle** [comment]
Looks like there are no follow-up questions, so I'll close this out now.
