### ISSUE TITLE
compile 'com.google.cloud:google-cloud-translate:0.20.1-beta' error

### ISSUE THREAD

**Issue by rrwiyatn** [GoogleCloudPlatform/google-cloud-java#2221]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK project.properties
  	File1: /Users/rrwiyatn/.gradle/caches/modules-2/files-2.1/com.google.cloud/google-cloud-translate/0.20.1-beta/f1aa85cc82b61e174338d8c45304d6d9d37b0962/google-cloud-translate-0.20.1-beta.jar
  	File2: /Users/rrwiyatn/.gradle/caches/modules-2/files-2.1/com.google.cloud/google-cloud-core/1.2.1/19160044568ccfaf002a78a8c2434744cecbb0d1/google-cloud-core-1.2.1.jar

Any thoughts?

**Comment by vam-google** [comment]
Can you be more specific on what you are trying to do? Is it happening on build phase? I see `com.android` in your output. Please note that Android is not an officially supported platform for google-cloud-java clients.

**Comment by garrettjonesgoogle** [comment]
Closing out because there was no response. Feel free to re-open if you are still seeing an issue and have more details to provide!
