### ISSUE TITLE
Move google-api-services-storagetransfer to the new com.google.cloud library

### ISSUE THREAD

**Issue by danagu** [GoogleCloudPlatform/google-cloud-java#2222]
Current api jar is:

com.google.apis:google-api-services-storagetransfer

In order to manage GCP "JOBS" in a better way, moving to some mutual interface of jobs (such as in BigQuery and com.google.cloud) can be very helpful.

**Comment by vam-google** [comment]
[Cloud Storage Transfer Service](https://cloud.google.com/storage/transfer/) is essentially a separate service and is not part of our current [Storage Client](https://github.com/GoogleCloudPlatform/google-cloud-java#google-cloud-storage-ga). 

I agree that the storage and storage transfer clients are tightly related and it would be nice to have them in same place, but as of now (mostly for historical reasons) they are two very different things and merging them in a proper manner would require significant amount of work (just putting jars together is not an option here).

**Comment by garrettjonesgoogle** [comment]
We are handling requests for supporting additional APIs with an internal mechanism. Closing out this issue.
