### ISSUE TITLE
Provide sample code for overriding endpoints in GAPIC clients

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2224]
Currently we have sample code for overriding credentials, e.g.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/0e4ed46f8dfdc48bac0dba00f4bb50ed7b39b42d/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/TopicAdminClient.java#L97

This task is to show how to override the endpoint, e.g. by calling `setEndpoint`:

https://github.com/googleapis/gax-java/blob/6b7f587ca283a7126be9b1e0f49821808dfc5380/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingChannelProvider.java#L255

**Comment by saicheems** [comment]
So... this is a change to the templates in toolkit?

Is changing the sample you linked to from

```
 * <code>
 * TopicAdminSettings topicAdminSettings =
 *     TopicAdminSettings.defaultBuilder()
 *         .setCredentialsProvider(FixedCredentialsProvider.create(myCredentials))
 *         .build();
 * TopicAdminClient topicAdminClient =
 *     TopicAdminClient.create(topicAdminSettings);
 * </code>
```
to
```
 * <code>
 * TopicAdminSettings topicAdminSettings =
 *     TopicAdminSettings.defaultBuilder()
 *         .setCredentialsProvider(FixedCredentialsProvider.create(myCredentials))
 *         .setEndpoint("localhost:8000")
 *         .build();
 * TopicAdminClient topicAdminClient =
 *     TopicAdminClient.create(topicAdminSettings);
 * </code>
```
enough to resolve this?

**Comment by garrettjonesgoogle** [comment]
That won't work, because the Builder for https://github.com/googleapis/gax-java/blob/master/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcTransportProvider.java doesn't have a `setEndpoint` method. 

And anyway, since setting credentials and setting endpoints are somewhat independent, I might like to have both as self-contained samples.

**Comment by garrettjonesgoogle** [comment]
This can't be closed until the clients have been regenerated.

**Comment by hzyi-google** [comment]
Move this feature request to [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. The issue can continue to be used for comment and discussion.
