### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by kirankumar-mahi** [GoogleCloudPlatform/google-cloud-java#2229]
Hi,

I am using latest aws-java-sdk-s3', version: '1.11.158'. I am getting SignatureDoesNotMatch error. I am using below code.

The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null

        ClientConfiguration clientConfiguration = new ClientConfiguration();
        AWSCredentials awsCredentials = new BasicAWSCredentials("XXX","XXX");
        AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard().withCredentials(new  AWSStaticCredentialsProvider(awsCredentials)).withClientConfiguration(clientConfiguration)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("https://storage.googleapis.com","Multi-Regional")).build();

        String keyName = UUID.randomUUID().toString();
        FileInputStream f = new FileInputStream(new File(filePath));
        TransferManager tx =  TransferManagerBuilder.standard().withS3Client(amazonS3Client).build();

        // Request server-side encryption.
        ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
        objectMetadata.setContentType("application/octet-stream");

        tx.upload("XX", keyName, f,objectMetadata);

**Comment by frankyn** [comment]
Hi @kirankumar-mahi!

Thanks for filing an issue! I'm trying to understand the context for your issue. What is your end goal for using `aws-java-sdk-s3` with Google Cloud Storage?

**Comment by frankyn** [comment]
I missed the last line in your script. IIUC, you're uploading a file to Google Cloud Storage using the aws-java-sdk-s3 client library and you're seeing the `SignatureDoesNotMatch` error?

**Comment by frankyn** [comment]
@kirankumar-mahi, I was able to get passed this issue by using a different version of the signature. I added the solution below, please let me know if you have any trouble.  I tested this with version `1.11.158` and `1.11.160` for `aws-java-sdk-s3`. 

```java
  ClientConfiguration clientConfiguration = new ClientConfiguration();
  // Solution is update the Signer Version. 
  clientConfiguration.setSignerOverride("S3SignerType"); 

  AWSCredentials awsCredentials = new BasicAWSCredentials("XXX","XXX");
  AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard()
    .withCredentials(new  AWSStaticCredentialsProvider(awsCredentials))
    .withClientConfiguration(clientConfiguration)
    .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("https://storage.googleapis.com","Multi-Regional")).build();

  String bucketName = "bucket_name";
  String keyName = UUID.randomUUID().toString();
  String filePath = "path/to/file.ext"

  // I uploaded the file differently as `TransferManager` would hang after it completed
  amazonS3Client.putObject(new PutObjectRequest(bucketName, keyName, new File(filePath)));
```

**Comment by kirankumar-mahi** [comment]
It got resolved. Thanks. Closing this

**Comment by gnanamalarvizhi** [comment]
@kirankumar-mahi  I have some issues with listObjects. Created new issues [here](https://github.com/aws/aws-sdk-java/issues/1372)

**Comment by allpereira** [comment]
@frankyn I found this same error in the version 1.11.602 of SDK.

**Comment by frankyn** [comment]
Could you provide more context on the issue you're experiencing @allpereira?
