### ISSUE TITLE
Provide Voice Activity Detector in SDKs

### ISSUE THREAD

**Issue by nalbion** [GoogleCloudPlatform/google-cloud-java#2236]
To conserve bandwidth (and Google resources) clients featuring ambient listening should use a VAD to avoid sending GBs of silence and background noise to Google.

Creating a good VAD is a lot of work, so it should be built into each SDK.

**Comment by garrettjonesgoogle** [comment]
cc @shinfan here is an interesting feature request for the Speech client.

**Comment by omaray** [comment]
Hello @nalbion . Thanks for using the Speech API. I'm the PM for the SDKs and I would love to ask you a couple of questions. Would you be willing to chat offline?

**Comment by nalbion** [comment]
@omaray sure

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
