### ISSUE TITLE
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by vscatarino** [GoogleCloudPlatform/google-cloud-java#2240]
I'm trying run a code that use a cloud-vision.
Everything works normally when I use my desktop(ubuntu / windows10). But when I use a raspberry appear the following error:

> Jul 16, 2017 5:52:39 PM io.grpc.internal.ChannelExecutor drain
> WARNING: Runnable threw exception in ChannelExecutor
> java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
> 	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:174)
> 	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:151)
> 	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:139)
> 	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:109)
> 	at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiatorByType(NettyChannelBuilder.java:335)
> 	at io.grpc.netty.NettyChannelBuilder.createProtocolNegotiator(NettyChannelBuilder.java:308)
> 	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DynamicNettyTransportParams.getProtocolNegotiator(NettyChannelBuilder.java:499)
> 	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(NettyChannelBuilder.java:448)
> 	at io.grpc.internal.CallCredentialsApplyingTransportFactory.newClientTransport(CallCredentialsApplyingTransportFactory.java:61)
> 	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:209)
> 	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:186)
> 	at io.grpc.internal.ManagedChannelImpl$SubchannelImplImpl.obtainActiveTransport(ManagedChannelImpl.java:806)
> 	at io.grpc.internal.GrpcUtil.getTransportFromPickResult(GrpcUtil.java:568)
> 	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:296)
> 	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$5.run(ManagedChannelImpl.java:724)
> 	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:87)
> 	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:715)
> 	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onUpdate(ManagedChannelImpl.java:752)
> 	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:174)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> Exception in thread "main" com.google.api.gax.grpc.ApiException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
> 	at com.google.api.gax.grpc.ExceptionTransformingCallable$ExceptionTransformingFuture.onFailure(ExceptionTransformingCallable.java:108)
> 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:52)
> 	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1764)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
> 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
> 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
> 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
> 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:463)
> 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
> 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
> 	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
> 	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
> 	at io.grpc.Status.asRuntimeException(Status.java:540)
> 	... 15 more

My pom.xml : 

```
<dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-vision</artifactId>
            <version>0.17.2-beta</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
            <version>1.22.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.5.Final</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
            </plugin>
        </plugins>
    </build>
</project>

```

Anyone can help me please?

**Comment by garrettjonesgoogle** [comment]
Unfortunately, Raspberry Pi runs on ARM, but ARM is not a supported architecture for the tcnative dependency of grpc yet. Thus, you won't be able to use any of the clients in this repo based on gRPC.

**Comment by garrettjonesgoogle** [comment]
@vscatarino I don't understand your question, could you elaborate?

**Comment by vscatarino** [comment]
Ok! 
I need to use Cloud Vision on Raspeberry.
Is there any way to do this?

**Comment by garrettjonesgoogle** [comment]
There is not a known way to do this, unfortunately.

**Comment by garrettjonesgoogle** [comment]
I am going to add a special comment about Raspberry in the README (since this has been asked more than once), then I'll close out this issue. Sorry that we can't be of more help in the near future!

**Comment by garrettjonesgoogle** [comment]
Note added to the README, so closing this issue now.

**Comment by vscatarino** [comment]
thanks!
