### ISSUE TITLE
Pubsub: Get AckId outside of MessageReceiver

### ISSUE THREAD

**Issue by Habitats** [GoogleCloudPlatform/google-cloud-java#2241]
I'm basically having an issue very much like https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1981. I need to receive the message on one machine, and ack it on another (Spark). Serializing the `AckReplyConsumer` isn't straight forward, and not really a neat approach. I've managed to ack messages outside the scope of `receiveMessage` using the REST API, but I cannot figure out a way to generate the `ackId` for messages.

Is this possible?

**Comment by garrettjonesgoogle** [comment]
I think this touches on some fundamental design decisions - I will talk to some people and get back to you.

**Comment by Habitats** [comment]
I can understand that this conflicts with the design, but I think it's unfortunate if it's impossible circumvent it. 

Is the design aimed at actor based systems where the same node both receives and handles the message? I would assume the Spark Streaming context, where you receive at a master, and process on another node, isn't that unique.

Looking forward to feedback!

**Comment by haakonringberg** [comment]
@Habitats is it possible to have every node subscribe?

**Comment by Habitats** [comment]
That doesn't make much sense in my context. The thing is that I'm pulling it from pubsub, and putting it on the Spark Streaming queue.

I managed to workaround this issue by just using the REST API for both subscriptions and acking -- all the other client libraries seems to inherit this functionality as well though. What is the reasoning behind this for the Java library?

**Comment by pmkc** [comment]
I think there are valid reasons to want to ACK a message at a later point, and that this client may not easily support that.

However I believe the suggested pattern of a [Reliable Receiver](https://spark.apache.org/docs/latest/streaming-custom-receivers.html#receiver-reliability) in Spark Streaming is to ACK the message immediately after storing it, which seems to get around serializing the `AckReplyConsumer`.

**Comment by Habitats** [comment]
Acking messages immediately after storing it does not fit in our case, as the Spark processing bit may or may not complete for a number of reasons. I could solve this by republishing failed messages on another topic (original format is lost so I cannot use the same), but this seems like an unnecessary complication.

But, the REST API seems to be working fine, so I'll just stick to that for now.

**Comment by garrettjonesgoogle** [comment]
@Habitats you could also consider using the new stub classes that have been added for Pub/Sub, which allow you to access all API methods. See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1661 for example code.

Since this seems to be resolved for the requester, I'm going to close it out.
