### ISSUE TITLE
Provide a ChannelProvider which can connect to the PubSub emulator

### ISSUE THREAD

**Issue by sarelp** [GoogleCloudPlatform/google-cloud-java#2248]
With the rest api it was possible to connect to the PubSub emulator by specifying the address
of the emulator with no additional configuration.

With the gRPC api it is no longer possible. It can be done by creating a PlainText negotiated 
channel but that requires us to create our own `ChannelProvider`.
  
The gax libraries provide a `LocalChannelProvider` which creates a PlainText channel but it is unfortunately limited to local jvm addresses only (for in-memory gRPC service)

It would be handy to provide a `PlainTextChannelProvider` which can connect to PubSub emulator as part of the api.

As reference the following is a workable implementation

```
public final class PlainTextChannelProvider implements ChannelProvider {
    private final String endpoint;

    private PlainTextChannelProvider(String endpoint) {
        this.endpoint = endpoint;
    }

    @Override
    public boolean shouldAutoClose() {
        return false;
    }

    @Override
    public boolean needsExecutor() {
        return false;
    }

    @Override
    public ManagedChannel getChannel() throws IOException {
        return ManagedChannelBuilder.forTarget(endpoint).usePlaintext(true).build();
    }

    @Override
    public ManagedChannel getChannel(Executor executor) throws IOException {
        return getChannel();
    }

    public static PlainTextChannelProvider create(String endpoint) {
        return new PlainTextChannelProvider(endpoint);
    }
}
```

**Comment by evmin** [comment]
+1

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
