### ISSUE TITLE
Please support multiple network interfaces for compute instances

### ISSUE THREAD

**Issue by mpartel** [GoogleCloudPlatform/google-cloud-java#2250]
If I try to attach multiple network interfaces to a compute instance, I get an `Invalid value for field 'resource': ''. Expected one network interface.`. Please add support for this.

This was already mentioned in #915 (#916 is also related), but those were closed after filing a bug (internally I assume) about documenting the limitation.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
