### ISSUE TITLE
Spanner: Convenient way to read Object/Objects from db.

### ISSUE THREAD

**Issue by bullet-tooth** [GoogleCloudPlatform/google-cloud-java#2270]
It would be great to have a convenient way to retrieve the data as pojos from Spanner database. 
For example `com.google.cloud.spanner.ReadContext` interface could be expanded with such methods for this purpose: 

```
<T> T readRow(String table, StructMapper<T> mapper, Key key, Iterable<String> columns);
<T> List<T> read(String table, StructMapper<T> mapper, KeySet keys, Iterable<String> columns, ReadOption... options);
```
Where `StructMapper` is an interface that can be implemented by users for custom pojos. Also it is a reason to create default implementation that covers conversion for common types, as example `org.springframework.jdbc.core.BeanPropertyRowMapper`.

If you're ok with that I would be pleasant to make pull request.

**Comment by tcoffee-google** [comment]
@bjwatson can you comment on including a feature like this in the Spanner client?

**Comment by bjwatson** [comment]
@vkedia What do you think?

**Comment by vkedia** [comment]
@bullet-tooth You can always invoke the mapper yourself on the returned Structs. So I am not convinced that adding this shortcut gives that much value.

**Comment by vkedia** [comment]
I am closing this since I am not convinced of the value of this feature. Please reopen if you disagree.
