### ISSUE TITLE
Auth: stop reading gcloud's configuration directly

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-cloud-java#2272]
Instead, use `gcloud config config-helper`:

Instead, we should subprocess out to `gcloud config config-helper --format json`

Example output:

```
{
  "configuration": {
    "active_configuration": "default",
    "properties": {
      "core": {
        "account": "[ELIDED]",
        "disable_usage_reporting": "False",
        "project": "[ELIDED]"
      }
    }
  },
  "credential": {
    "access_token": "[ELIDED]",
    "token_expiry": "2017-03-23T23:09:49Z"
  },
  "sentinels": {
    "config_sentinel": "/Users/jonwayne/.config/gcloud/config_sentinel"
  }
}
```

Context: https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/146

**Comment by tcoffee-google** [comment]
Looks like we should change [this method](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/313a16ca610b822d750b8c02255fdac985e37b0b/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L330).

**Comment by neozwu** [comment]
@jonparrot, thank you for pointing this out.  I agree that the current approach is not elegant. But I have some concerns about relying on `gcloud`: 
* Google-cloud-java is not supposed to have any dependency on gcloud sdk. 
* "Subprocess" may not be feasible when running in some sandbox JVM environment.

**Comment by jonparrott** [comment]
In both of those cases the Python library just returns `None` for the project. That's totally fine.

**Comment by neozwu** [comment]
Google-cloud-java checks project-id following a sequence of steps. One step is to check "gcloud sdk project-id". This is different from "calling gcloud sdk to get project-id".

**Comment by jonparrott** [comment]
I'm not sure I understand what you mean.

**Comment by garrettjonesgoogle** [comment]
I think it's preferable to not execute other processes from google-cloud-java. @jonparrott why is it necessary to make this change?

**Comment by jonparrott** [comment]
Because gcloud's configuration files are considered implementation details and are not subject to any deprecation policy - essentially, reading them is dangerous as there's no guarantee they'll be there or in the format you expect. `gcloud config config-helper` is a GA surface and is subject to their deprecation policy. It's also what they told us to use. :)

**Comment by hzyi-google** [comment]
Move this to the feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
