### ISSUE TITLE
BigQuery: Can't create a table with a expirationtime

### ISSUE THREAD

**Issue by joelostlund** [GoogleCloudPlatform/google-cloud-java#2274]
Hello,
I am trying to create a table using the bigquery API in the following way:

```
final Long expirationTime = getExpirationTimeMillis(dateString);
      final TableInfo tableInfo = TableInfo.newBuilder(TableId.of(project, dataset, tableId), NEW_TABLE_DEF)
          .setExpirationTime(expirationTime)
          .build();
      LOG.info(String.format("Creating table: %s.%s.%s", project, dataset, tableId));
      return bigQuery.create(tableInfo);
```
This gives me the following message:
com.google.cloud.bigquery.BigQueryException: Not found: Table entity-dev:joel_daily.user_daily_20170718

Doing the same without .setExpirationTime(expirationTime) works fine. I don't see why I should get an issue Not found when setting the ExpirationTime.

Can you please help me with this issue?

**Comment by tcoffee-google** [comment]
@joelostlund can you check to make sure the expiration time you're passing is not in the past?

**Comment by joelostlund** [comment]
@tcoffee-google yeah it worked, thanks. Must say that this is a little bit confusing this you specify the days from now when you create a dataset and now+the days from now when creating a table.

**Comment by tcoffee-google** [comment]
@joelostlund I agree that in the context of an "expiration time" that is a bit confusing. I'll pass this along to the API team.
