### ISSUE TITLE
Google Translate api ClassNotFoundException/NoClassDefFoundError errors 

### ISSUE THREAD

**Issue by TheSkripterDK** [GoogleCloudPlatform/google-cloud-java#2289]
Hello so when i try using the google translate api i get this errors 

java.lang.ClassNotFoundException: com.google.cloud.ServiceOptions
java.lang.NoClassDefFoundError: com/google/cloud/translate/TranslateOptions
java.lang.NoClassDefFoundError: com/google/cloud/ServiceOptions

i use 
google-cloud-translate-1.2.3.jar
![screenshot_18](https://user-images.githubusercontent.com/29629145/28713734-a71513b6-7390-11e7-9f17-41a2da1fe63a.png)

**Comment by tcoffee-google** [comment]
@TheSkripterDK this sounds like a dependency issue --- can you provide more detail about your development environment and the steps you took?

**Comment by TheSkripterDK** [comment]
@tcoffee-google I use IntelliJ and i added the code 
`Translate translate = TranslateOptions.newBuilder().setApiKey("myKey").build().getService();
        Translation translation = translate.translate("World",
                TranslateOption.sourceLanguage("en"),
                TranslateOption.targetLanguage("da"));
        
        Bukkit.getLogger().info(translation.getTranslatedText());
        return new String[]{translation.getTranslatedText()};`

and then i just build the artifact u see above 
here is the jar in a zip folder
[google.zip](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1187064/google.zip)

**Comment by tcoffee-google** [comment]
As I'm away, I'll pass this off to @neozwu who's supporting new issues this week.

**Comment by neozwu** [comment]
Hi, @TheSkripterDK,  google-cloud-translate depends on other libs. What build tool do you use ?  You can use maven or gradle to pull in transitive dependency, or you need to put all dependency jars in your classpath.

**Comment by danielkp1234** [comment]
@neozwu i use Gradle here is my build.gradle https://pastebin.com/X2hERqRv
i use the build artifact button in IntelliJ i posted above a screenshot of what is in my build artifact

**Comment by TheSkripterDK** [comment]
@neozwu i use Gradle here is my build.gradle https://pastebin.com/X2hERqRv
i use the build artifact button in IntelliJ i posted above a screenshot of what is in my build artifact

**Comment by garrettjonesgoogle** [comment]
@TheSkripterDK , one example dependency that @neozwu means is com.google.cloud:google-cloud-core:0.20.3-alpha . This dependency should automatically be cached by gradle when you do a gradle build. It will not be part of the google-cloud-translate jar. If you only add the google-cloud-translate jar, you will be missing google-cloud-core, along with many other jars. You have to add the entire set of dependencies to your classpath somehow.

**Comment by TheSkripterDK** [comment]
@garrettjonesgoogle added compile group: 'com.google.cloud', name: 'google-cloud', version: '0.20.3-alpha' to the build.gradle and added the google-cloud-0.20.3-alpha extracted jar to build artifact it still does not work

**Comment by garrettjonesgoogle** [comment]
This is in the realm of standard java stuff and outside of anything specific to google-cloud-java.

I recommend you create a "fat jar", which is a jar that contains your code plus all of your dependencies in a single jar. One gradle plugin that can help with this is the `shadow` plugin. Add the following to your build.gradle file:

```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
  }
}

apply plugin: 'com.github.johnrengelman.shadow'
```

Then on the command line, use the following command:

```
./gradlew shadowJar
```

Then you'll have a jar in your build directory that contains everything you need.

See http://imperceptiblethoughts.com/shadow/ for more documentation.

**Comment by TheSkripterDK** [comment]
@garrettjonesgoogle I know that does not work for me but is there a way i can do it the way i do and why won't i get the same error

**Comment by garrettjonesgoogle** [comment]
Add this to your build.gradle:

```
task printClasspath {
  doLast {
    configurations.runtime.each { println it }
  }
}
```

Then run this from the command line:

```
./gradlew printClassPath
```

Then add every jar from the output into your classpath.

**Comment by TheSkripterDK** [comment]
@garrettjonesgoogle made it maven 
pom.xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.danilkp1234</groupId>
    <artifactId>aquask</artifactId>
    <version>1.0.0</version>
    <build>
    <finalName>AquaSK</finalName>
    <sourceDirectory>src/main/java</sourceDirectory>
    <defaultGoal>clean install</defaultGoal>
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            
            <filtering>true</filtering>
            <includes>
                <include>plugin.yml</include>
            </includes>
        </resource>
        <resource>
            <directory>src/main/resources</directory>
            
            <filtering>false</filtering>
            <excludes>
                <exclude>**/*.java</exclude>
                <exclude>plugin.yml</exclude>
            </excludes>
        </resource>
    </resources>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.1</version>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
            </configuration>
        </plugin>
    </plugins>
</build>
        <repositories>
            <repository>
                <id>spigot-repo</id>
                <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
            </repository>
            <repository>
                <id>lib</id>
                <url>file://${project.basedir}/lib</url>
            </repository>
        </repositories>
        <dependencies>
             
            <dependency>
                <groupId>org.spigotmc</groupId>
                <artifactId>spigot-api</artifactId>
                <version>1.8.8-R0.1-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
            
            <dependency>
                <groupId>org.bukkit</groupId>
                <artifactId>bukkit</artifactId>
                <version>1.8.8-R0.1-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>ch.njol</groupId>
                <artifactId>Skript</artifactId>
                <version>1.0</version>
                <scope>system</scope>
                <systemPath>${project.basedir}/lib/Skript.jar</systemPath>
            </dependency>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>google-cloud-translate</artifactId>
                <version>1.4.0</version>
            </dependency>
        </dependencies>

    </project>


Caused by: java.lang.NoClassDefFoundError: com/google/cloud/translate/TranslateOptions

**Comment by pongad** [comment]
I tried out the `pom.xml` you pasted. The exception is `java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects`.

This is caused by Spigot and Bukkit import Guava version 17, but Translate requiring 19. If a newer version of Spitgot/Bukkit that uses newer Guava is available, using that should solve the problem. Otherwise, you could try adding

```
<dependency>
  <groupId>com.google.guava</groupId>
  <artifactId>guava</artifactId>
  <version>19.0</version>
</dependency>
```
