### ISSUE TITLE
Make `google-cloud-java` API exception handling easier

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2295]
Users should have clear access to exceptions and their status codes in a transport (gRPC/HTTP) agnostic way, so that they may be handled appropriately in the client.

Currently, there is an inconsistent surface.
Libraries like Spanner provide [SpannerException](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerException.java) while others return [BaseGrpcServiceException](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/BaseGrpcServiceException.java)
@lesv

**Comment by remi** [comment]
Could you provide code snippets demonstrating the friction currently encountered when handling exceptions?

It would be useful to provide at least 2 samples showing how to currently handle different common exceptions users want to catch. For each snippet, provide a second snippet with your *ideal* interface.

This will really help to define changes the generated exception interface

**Comment by jabubake** [comment]
Here is an example on the current friction : 
Example : User tries to create a Pub/Sub topic using a topic ID that already exists.
```java
// Your Google Cloud Platform project ID
    String projectId = ServiceOptions.getDefaultProjectId();

    // Your topic ID
    String topicId = "my-new-topic";
    try {
      // Create a new topic
      TopicName topic = TopicName.create(projectId, topicId);
      try (TopicAdminClient topicAdminClient = TopicAdminClient.create()) {
        topicAdminClient.createTopic(topic);
      }

      System.out.printf("Topic %s:%s created.\n", topic.getProject(), topic.getTopic());
    } catch (Exception e) {
      if (e instanceof ApiException) {
        System.out.println(((ApiException) e).getStatusCode();
        System.out.println(((ApiException) e).isRetryable());
        System.out.println(e.getMessage());
      }
    }
  }
```

Currently, the output of
- `e.getStatusCode()` is `com.google.api.gax.grpc.GrpcStatusCode@43e8b753`
- `e.isRetryable()` false
- `e.getMessage()` : io.grpc.StatusRuntimeException: ALREADY_EXISTS: Resource already exists in the project (resource=my-new-topic).

The ALREADY_EXISTS should be clearly exposed as a status code that the user can choose to handle in the client.

**Comment by jabubake** [comment]
@remi I believe the interface correctly exists, its just not been hooked up to deliver the right status codes to the client in case of an API exception.

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
