### ISSUE TITLE
Add Support for Specifying Min CPU Platform

### ISSUE THREAD

**Issue by theotheradam** [GoogleCloudPlatform/google-cloud-java#2296]
Hi, 

I would like to be able to specify the [minimum CPU platform](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform) (e.g. Intel Skylake) for a VM, but I don't see where I can specify it. I would expect a method like `setMinCpuPlatform` on `InstanceInfo`. If it is not supported, do you plan on supporting it?

Thanks

**Comment by neozwu** [comment]
Hi @theotheradam , I think this is what you can use: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-compute/src/main/java/com/google/cloud/compute/Instance.java#L169 .

**Comment by theotheradam** [comment]
Hi @neozwu, thanks for the quick reply. That method isn't public, so I don't see how I could use it to set the minimum CPU platform. Looks like it is used to set the actual platform that was used when the instance was created.

**Comment by neozwu** [comment]
@theotheradam , I think you are right - you cannot use it, plus it appears to be used to set actual platform (although the doc suggests one can only set minimum cpu: https://cloud.google.com/compute/docs/cpu-platforms) .

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
