### ISSUE TITLE
google-cloud-storage README example is incorrect

### ISSUE THREAD

**Issue by ifigotin** [GoogleCloudPlatform/google-cloud-java#2301]
We have the following example:
`Iterator<Bucket> bucketIterator = storage.list().iterateAll();`

However, storage.list().iterateAll() does not return java.util.Iterator<Bucket>, instead 
java.lang.Iterable<Bucket> is returned. 

Consider changing the example to a 'for' loop, e.g.:
```
      Storage storage = StorageOptions.getDefaultInstance().getService();
      for(Bucket bucket : storage.list().iterateAll()) {
        ...
      }
```

**Comment by vam-google** [comment]
Documentation updated, closing.
