### ISSUE TITLE
Reading the logs from StackDriver Logging

### ISSUE THREAD

**Issue by NagarajP** [GoogleCloudPlatform/google-cloud-java#2302]
Hi All,

I am using  following dependency to interact with GCP StackDriver Logging.
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-logging</artifactId>
    <version>1.0.1</version>
</dependency>

Java Code:
Page<LogEntry> entries = logging.listLogEntries(EntryListOption.filter(filter));
		    for (LogEntry entry : entries.iterateAll()) { 
		      System.out.println("entry:::"+entry.toString());
		    }
However getting following exception:
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:105)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:560)
	at com.google.api.gax.grpc.AuthInterceptor.interceptCall(AuthInterceptor.java:52)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
	at com.google.api.gax.grpc.HeaderInterceptor.interceptCall(HeaderInterceptor.java:57)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:536)

Is there any fix available for this issue in any other version of gc logging jars? Your input is highly appreciated. Thanks

**Comment by garrettjonesgoogle** [comment]
Could you provide your dependency tree? (If you are running maven, run `mvn dependency:tree`). I suspect that you are using a version of Guava that is too old.

**Comment by NagarajP** [comment]
Thanks for your response @garrettjonesgoogle .
Here is the dependency tree from my app

`
C:\mycompany\SourceCode\GoogleStackDriver\StackDriver>mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building StackDriver 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml (2 KB at 0.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml (2 KB at 14.1 KB/sec)
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ StackDriver ---
[INFO] com.mycompany.googlecomponents.example:StackDriver:jar:1.0-SNAPSHOT
[INFO] +- com.google.cloud:google-cloud-logging:jar:1.0.1:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:1.1.33.Fork26:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- org.json:json:jar:20160810:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.0.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.0.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.2.0:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.9:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.9:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.0.1:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.2.0:compile
[INFO] |  |  \- io.grpc:grpc-protobuf:jar:1.2.0:compile
[INFO] |  |     \- io.grpc:grpc-protobuf-lite:jar:1.2.0:compile
[INFO] |  +- com.google.api:gax-grpc:jar:0.16.0:compile
[INFO] |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.4.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client:jar:1.19.0:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-logging-v2:jar:0.1.9:compile
[INFO] |  +- io.grpc:grpc-netty:jar:1.2.0:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.2.0:compile (version selected from constraint [1.2.0,1.2.0])
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.11:compile
[INFO] |  |  |  +- io.grpc:grpc-context:jar:1.2.0:compile
[INFO] |  |  |  \- com.google.instrumentation:instrumentation-api:jar:0.3.0:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.8.Final:compile (version selected from constraint [4.1.8.Final,4.1.8.Final])
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.8.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec:jar:4.1.8.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler:jar:4.1.8.Final:compile
[INFO] |  |  |     \- io.netty:netty-buffer:jar:4.1.8.Final:compile
[INFO] |  |  |        \- io.netty:netty-common:jar:4.1.8.Final:compile
[INFO] |  |  \- io.netty:netty-handler-proxy:jar:4.1.8.Final:compile
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.8.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver:jar:4.1.8.Final:compile
[INFO] |  |     \- io.netty:netty-codec-socks:jar:4.1.8.Final:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.2.0:compile
[INFO] |  \- io.grpc:grpc-auth:jar:1.2.0:compile
[INFO] |     \- com.google.auth:google-auth-library-credentials:jar:0.4.0:compile
[INFO] \- junit:junit:jar:3.8.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.944 s
[INFO] Finished at: 2017-08-07T15:20:13-04:00
[INFO] Final Memory: 14M/96M
[INFO] ------------------------------------------------------------------------`

**Comment by garrettjonesgoogle** [comment]
This is honestly a little perplexing - you seem to have the minimum version of Guava required for the missing method (which is 18.0, you have 19.0) . Can you check what version of Guava you're actually loading in your VM somehow?

Also, you are a few versions behind - maybe consider upgrading to 1.3.1 of google-cloud-logging.

**Comment by NagarajP** [comment]
Thanks for your comments @garrettjonesgoogle . When i upgrade google-cloud-logging version to 1.3.1, then ending up with "java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured." problem #2310  ( Now I noticed your comments also that it is duplicate of #2266. As per your suggestion , changed the version number of netty-tcnative-boringssl-static -2.0.3.Final, still same error). Please advise.
For your reference, i have added the dependency tree also

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ StackDriver ---
[INFO] com.mycompany.googlecomponents.example:StackDriver:jar:1.0-SNAPSHOT
[INFO] +- com.google.cloud:google-cloud-logging:jar:1.3.1:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.3.1:compile
[INFO] |  |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- org.json:json:jar:20160810:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.1.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.5.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.3.1:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.15:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.15:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.3.1:compile
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:0.7.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.3.1:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.4.0:compile
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.4.0:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.4.0:compile
[INFO] |  +- com.google.api:gax-grpc:jar:0.22.0:compile
[INFO] |  |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  \- com.google.auth:google-auth-library-oauth2-http:jar:0.7.0:compile
[INFO] |  |     +- com.google.http-client:google-http-client:jar:1.19.0:compile
[INFO] |  |     |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |     |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |     |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |     |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |     \- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |  |        \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-logging-v2:jar:0.1.15:compile
[INFO] |  +- io.grpc:grpc-netty:jar:1.4.0:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.4.0:compile (version selected from constraint [1.4.0,1.4.0])
[INFO] |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.19:compile
[INFO] |  |  |  \- com.google.instrumentation:instrumentation-api:jar:0.4.2:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.11.Final:compile (version selected from constraint [4.1.11.Final,4.1.11.Final])
[INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.11.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec:jar:4.1.11.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler:jar:4.1.11.Final:compile
[INFO] |  |  |     \- io.netty:netty-buffer:jar:4.1.11.Final:compile
[INFO] |  |  |        \- io.netty:netty-common:jar:4.1.11.Final:compile
[INFO] |  |  \- io.netty:netty-handler-proxy:jar:4.1.11.Final:compile
[INFO] |  |     +- io.netty:netty-transport:jar:4.1.11.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver:jar:4.1.11.Final:compile
[INFO] |  |     \- io.netty:netty-codec-socks:jar:4.1.11.Final:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.4.0:compile
[INFO] |  \- io.grpc:grpc-auth:jar:1.4.0:compile
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
[INFO] \- junit:junit:jar:3.8.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by garrettjonesgoogle** [comment]
Well I think you have indeed ended up in the same state as https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2266 , so I'm going to close this out and direct you over there so that we can track the resolution in one place.
