### ISSUE TITLE
Launch GCE instance with GPU support

### ISSUE THREAD

**Issue by irwen** [GoogleCloudPlatform/google-cloud-java#2303]
Seems like specifying `AcceleratorConfig` is supported in the latest version of _google-api-services-compute_ [version: _v1-rev151-1.22.0_]. Any plans of enabling this SDK to utilize that and launch a GCE instance with _K80_ or P100 GPUs? Thanks.

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
