### ISSUE TITLE
Create BOM for google-cloud-java

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2307]
Example BOM:

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml

Here is how Spring Cloud uses the BOM for their dependencies:

https://spring.io/blog/2016/09/26/spring-cloud-camden-release-and-brixton-sr6-are-available

The work for us is the following:

1. Extract dependencyManagement and pluginManagement to a dedicated pom.xml (e.g., artifact: google-cloud-java-bom)
2. In the parent pom.xml, import the BOM

Then consumers can import the BOM too, instead of specifying individual versions.

**Comment by saturnism** [comment]
@meltsufin @joaoandremartins who's implemented for spring-cloud-gcp

**Comment by vam-google** [comment]
`google-cloud-pom ` itself can be used as BOM. Added documentation in main README.md about how it can be done. Closing this issue.

**Comment by saturnism** [comment]
i know it can _also_ be used as a BOM, but it's not necessarily the best practice. I don't feel we should ask people to import from a parent POM.  Parent POM is meant to be the parent of our projects.

**Comment by saturnism** [comment]
@garrettjonesgoogle can we reopen this issue to track?
