### ISSUE TITLE
Provide a way to create a TableDefinition from a schema file

### ISSUE THREAD

**Issue by esanchezros** [GoogleCloudPlatform/google-cloud-java#2308]
It would be useful to have a way to create a TableDefinition from a schema file. For example something like:

```
Schema schema = Schema.fromFile(schemaFile);
TableDefinition tableDefinition = StandardTableDefinition.of(schema);
```

**Comment by NicolaSpreafico** [comment]
While the question seems to be unchanged since 7 Aug, I wrote a custom deserializer which allow to deserialize a json schema to` com.google.cloud.bigquery.Schema` object

You can find the source here
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2753

**Comment by vam-google** [comment]
Closing this as a duplicate of https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2553 (which was created later, but has a wider scope, that is why keeping it).
