### ISSUE TITLE
Datastore Cloud Emulator refuses connections

### ISSUE THREAD

**Issue by JoshuaFox** [GoogleCloudPlatform/google-cloud-java#2309]
Running unit tests from Maven, my code starts `DatastoreCloudOnTestHelper`. All connections to the Datastore emulator are refused. Stacktrace below.

Notes:
- Everything works OK when running tests from TestNG plugin in Eclipse. 
-- Using detailed logs in the Google Cloud code, I learned that the reason is this: In Eclipse, `GcloudEmulatorRunner`  silently fails to start, so that the test-helper falls back to an emulator which it downloads from Google Cloud Storage. This downloaded emulator allow connections. In contrast, when running from Maven, the `GcloudEmulatorRunner` completes its starts up "successfully," so that `GcloudEmulatorRunner`  is used -- but it refuses connections. Ironically, then, it is the fallback to the less-preferred emulator  which allows the tests  to proceed in Eclipse.
- On a colleague's machine, even running from Maven, everything works OK.
- Simply running the emulator  from the command line (`gcloud beta emulators datastore start ...`) allows connections -- everything works OK.
- My gcloud is fully up to date : `gcloud components list, Your current Cloud SDK version is: 164.0.0.
The latest available version is: 164.0.0`.
- I checked  whether the Windows Firewall is blocking this `java.exe` --  it is not.

How can I get this to work?

 ```

INFO: Initialized Google Cloud Datastore with options gcloud-java/1.2.0:localhost:51321
 
SEVERE:  ``java.net.ConnectException: Connection refused: connect  Connection refused: connect
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:87)
        at com.google.datastore.v1.client.Datastore.commit(Datastore.java:84)
        at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:152)
        at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:418)
        at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:415)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:93)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:49)
        at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:414)
        at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:408)
        at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:368)
        at com.google.cloud.datastore.DatastoreHelper.put(DatastoreHelper.java:55)
        at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:343)

**Comment by vam-google** [comment]
Hi @JoshuaFox, can you be more specific on what you are trying to do?

What is `DatastoreCloudOnTestHelper` class? I cannot find it neither in google-cloud-java nor in its dependencies. Is it from gcloud tool? The only other place I could find DatastoreCloudOnTestHelper on the internet was this other [post](https://groups.google.com/forum/#!topic/gcd-discuss/IPT7tLqgdX0). It mentions in stacktrace `org.gails.infrastructure.google.DatastoreCloudOnTestHelper`. Note, it is `org.gails`, not `org.grails`, the http://gails.org/ domain is not active, so it looks like something private. 

You say that on colleague's machine everything works ok. Can you please compare your and colleague's setups? Specifically maven version, google-cloud-java version, gcloud version etc.

Thanks

**Comment by JoshuaFox** [comment]
Nothing special about `gails` -- it is simply an internal library at my company (despite the `org`) prefix.  My mistake in mentioning the `DatastoreCloudOnTestHelper`. That's just our class that launches the emulator and in the stack comes above the stacktrace you see.

**Comment by JoshuaFox** [comment]
For both me and my colleage 
- Google Cloud SDK 164.0.0
- Apache Maven 3.3.9 
- Also 
`<dependency>
<groupId>com.google.cloud</groupId>
<artifactId>google-cloud-datastore</artifactId>
<version>1.3.1</version>
</dependency>`
- and this plugin for launching
`<groupId>com.google.cloud.tools</groupId> <artifactId>appengine-maven-plugin</artifactId>`

**Comment by JoshuaFox** [comment]
`gcloud 166` just came out. Upgraded and bug still occurs.

Note the difference between `GcloudEmulatorRunner` and  the downloaded runner as in the body of the ticket. I believe that the problem lies there.

**Comment by JoshuaFox** [comment]
It just got worse.  Failure now occurs not only in Maven but even in Eclipse, 90% of the time. 

Yet there is success 10% of the time in Eclipse, there is success. In these cases , I note `DownloadableEmulatorRunner downloadZipFile...  Using cached emulator... Unzipping emulator` in the logs. On August 2, this apparently succeeded every tme (in Eclipse).

I now have gcloud 168.0.0 instead of 164.0.0 as I did  on August 2. 

I  have attached the reattached logs from August 2 for clarity; also logs from from today, August 30. THe logs show Maven, and Eclipse, with both the with ok and not-ok cases.

 
[not ok 2017-08-02.maven.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1264001/not.ok.2017-08-02.maven.txt)
[not ok 2017-08-30.eclipse.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1264004/not.ok.2017-08-30.eclipse.txt)
[not ok 2017-08-30.maven.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1264002/not.ok.2017-08-30.maven.txt)
[ok 2017-08-02.eclipse.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1264003/ok.2017-08-02.eclipse.txt)
[ok 2017-08-30.eclipse.txt](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1264000/ok.2017-08-30.eclipse.txt)

**Comment by shinfan** [comment]
@JoshuaFox 

As you mentioned the setup works okay on the other machine so it looks like an environment issue.

You also mentioned that running emulator directly from command line works which indicates the emulator itself has no problem running on your machine. On the other hand, things failed with your custom Java test runner class (`DatastoreCloudOnTestHelper`) and Maven setup. It would be helpful if we can look at that code for further investigation.

**Comment by JoshuaFox** [comment]
`DatastoreCloudOnTestHelper` is nothing special. It just launches the test helper. Here is the essential code.  I will mail you this and the `pom.xml`, though there is not much of interest there.

`helper = LocalDatastoreHelper.create(0.77d);
helper.start();
DatastoreOptions dsOptions = DatastoreCloudOnTestHelper.helper.getOptions();
CrossAppKeysGCloud.getInstance().setOrigAppId(proj);
ds = dsOptions.getService();`
return ds;`

**Comment by shinfan** [comment]
Thanks for the code, I think the `DatastoreCloudOnTestHelper` looks fine.

The `GcloudEmulatorRunner` does not do anything special other than executing the exact command `gcloud beta emulators datastore start` so it should not cause the issue here.

The only difference between a downloaded emulator and the emulator from the gcloud command is the minor version --- the downloaded emulator is `1.2.0` and the gcloud command is `1.2.1`, so the problem may go there. 

To verify if this is the case, I think you can:

1) Uninstall the gcloud emulator component (which is `1.2.1`): https://cloud.google.com/sdk/gcloud/reference/components/remove
2) After the gcloud component is removed, it will always fall back to use the downloaded emulator (which is `1.2.0`)
3) Run your test and see if the problem is solved.

**Comment by JoshuaFox** [comment]
Thank you, running 
   `gcloud components remove cloud-datastore-emulator`

allows the unit-tests to pass. 

But then, I cannot run our application on the dev machine.   Although our unit tests use the unit-test-oriented `com.google.cloud.datastore.testing.LocalDatastoreHelper`, our application in development runs the command  `gcloud beta emulators datastore start` .

I see this message
`You need the [cloud-datastore-emulator] component to use the Google Cloud Datastore emulator.`

So I let it (re)install the Emulator. And then unit tests again fail.

But I notice something strange. You ask us  to uninstall the `cloud-datastore-emulator` , without the beta `designation`,  allowing unit tests to pass; but we use the `beta` to launch the dev version of the emulator, following [guidance on the Cloud  Datastore Google Group.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gcd-discuss/51xsAReJnOE/nX8p5xFqDQAJ) Is there some sort of conflict here? I can use either one -- so long as it works. 

How can I do that?

**Comment by shinfan** [comment]
@JoshuaFox I don't think the `beta` does anything here. Both beta and non-beta use the same emulator which is `1.2.1`.

@vam-google @michaelbausor  Can anyone of you take a look at this customer issue? It looks like the 1.2.1 emulator has some regression which caused the connection refused exception. Thank you!

**Comment by pcostell** [comment]
@shinfan @JoshuaFox 

Can we test this using the downloaded emulator but on version `1.2.1`? This could be done by changing the version constant in the `LocalDatastoreHelper`. The `1.2.1` version of the emulator has been released for almost a year, so I'd like to make sure this isn't a `gcloud` vs downloaded issue, rather than a `1.2.0` vs `1.2.1` issue.

**Comment by JoshuaFox** [comment]
How do I make it use the downloaded emulator? It always tries gcloud and
then reverts to the downloaded emulator -- I do not know how to control
that.

Moreover (as shown by diffing the logs, as attached  earlier), in the
failure case (Maven), apparently the problem is that the gcloud emulator
DOES start up, but then doesn't work, whereas in the success case
(Eclipse), the gcloud fails to start up and then the downloaded emulator
has a chance to go ahead.

> This could be done by changing the version constant in the
LocalDatastoreHelper.

How do I do that? Examining the code of LocalDatastoreHelper shows nothing
relevant to that.

**Comment by pcostell** [comment]
You can change the version of the downloaded emulator by changing the [`MIN_VERSION` in `LocalDatastoreHelper`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java#L60) from `"1.2.0"` to `"1.2.1"`. 

You can force it to use the downloaded version by uninstalling the gcloud version: https://cloud.google.com/sdk/gcloud/reference/components/remove

**Comment by JoshuaFox** [comment]
I'll see about that code edit.

On Sep 18, 2017 9:54 PM, "Patrick Costello" <notifications@github.com>
wrote:

You can change the version of the downloaded emulator by changing the
MIN_VERSION in LocalDatastoreHelper
<https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java#L60>
from "1.2.0" to "1.2.1".

You can force it to use the downloaded version by uninstalling the gcloud
version: https://cloud.google.com/sdk/gcloud/reference/components/remove

I did that. See above. That makes unit tests pass, but then I can't use the
emulator for development.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2309#issuecomment-330321122>,
or mute the thread

**Comment by JoshuaFox** [comment]
@pcostell 
>  changing the MIN_VERSION in LocalDatastoreHelper

I copied the `LocalDatastoreHelper` source code as class `LocalDatastoreHelper121` in a new package, changed `MIN_VERSION` to `1.2.1`, then used this class.

Unit tests still fail in the same way.
 
>You can force it to use the downloaded version by uninstalling the gcloud

I did that already. See comment above (from 2017-9-17 12:24 UTC). That indeed makes unit tests pass in Maven, but then I can't use the Datastore Emulator for ordinary development.

**Comment by pcostell** [comment]
Thanks @JoshuaFox.

I definitely don't want you to have to not have gcloud installed, but this helps confirm that this seems to be something wrong with trying to kick off the tests using gcloud, as opposed to a regression in the Cloud Datastore emulator.

@shinfan What are the next steps here?

**Comment by sai-pullabhotla** [comment]
@JoshuaFox - 

The LocalDatastoreHelper works as outlined below: 

- Gets the `PATH` environment variable and checks to see if it contains `google-cloud-sdk`. If the string is found, it runs `gcloud version` command and ensures that the installed emulator version is `>=` to the `MIN_VERSION`. If both these conditions satisfy, it will run the emulator from the pre-installed google-cloud-sdk. 
- Otherwise, it falls back to downloading the emulator and unzipping it and running the emulator from there. 

> How do I make it use the downloaded emulator? It always tries gcloud and
> then reverts to the downloaded emulator -- I do not know how to control
> that.

When you kick off the tests, you can set the `PATH `to **NOT** have `google-cloud-sdk`, to force the downloaded version of the emulator. 

When running from Eclipse, you said that it ends up not using the pre-installed emulator, but downloads a new one. This means, the launcher configuration in Eclipse is not using the **native environment** or the **native environment** is missing `google-cloud-sdk` from the PATH. You might want to check into your System's environment variables, especially PATH and see if it looks good. Also, ensure that your Launcher in Eclipse is not overriding the environment. 

When running from Maven, it uses the pre-installed emulator, but connections are rejected. This means, Maven launcher is finding the `google-cloud-sdk` in the path, but failing to start the emulator. This means, the `gcloud beta emulators datastore start` command was executed, but it did not really start the emulator, instead there was some kind of error. I think there is a slight issue with the code in `com.google.cloud.testing.BlockingProcessStreamReader`. This checks the stdout from `gcloud` command for a String `Dev App Server is now running`. But it does not do anything (e.g. throw an exception) when the String is not found and end of Stream is reached/process is terminated. If you could debug, set a break point in the above class where it reads the stdout and see what gcloud is complaining about.

**Comment by JoshuaFox** [comment]
@sai-pullabhotla  -- you hit it! 

Buried in my `PATH` was `D:\Program Files\eclipse\plugins\com.google.appengine.eclipse.sdkbundle_1.9.40\appengine-java-sdk-1.9.40\bin\`. After that in the `PATH`, there's a since-uninstalled Google-SDK, and after that there is my real Google SDK installation `d:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin`.

When I set `PATH` to exclude that first one, `mvn test` runs OK.
Perhaps the `gcloud` installer should add itself at the beginning of the `PATH`

**Comment by sai-pullabhotla** [comment]
Glad the issue is resolved!

**Comment by vam-google** [comment]
@shinfan, @pcostell, @sai-pullabhotla thank you for all you help with this issue! Great job!

**Comment by JoshuaFox** [comment]
@vam-google  @shinfan, @pcostell, @sai-pullabhotla  Thank you!

Probably not relevant now, but note  that  the old SDK in my path was *not* the one from the Eclipse that I used to run the unit tests. Also, note the strangeness that in Eclipse, `gcloud` emulator did *not* start up, so the downloaded one was successfully used, while in Maven, `gcloud` emulator *did* start up (and so was used, but it was refusing to accept connections).

**Comment by JoshuaFox** [comment]
I narrowed this down to minimal differences.

This batch file works.
```
set PATH=c:\ProgramData\Oracle\Java\javapath;d:\maven-3.3.9\bin
mvn install 
```

The `javapath`  must be in the `PATH` if we want to avoid the connection error. 
Strangely, with or without this `javapath`  entry, the same JDK 8 is used by Maven.

`gcloud` must *not* be in the path if we want to avoid the connection error: `d:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;`
