### ISSUE TITLE
MVM GAE Compat -> Flex conversion Datastore w/ Objectify faster than g-c-j API's

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2316]
Customer is doing a single read:
* Task: read 20,000+ entities
* Using Objectify on MVM-Java-Compat: 6 seconds to fetch (old api's)
* Using google-cloud-storage on Flex: 40 seconds to fetch

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
