### ISSUE TITLE
DLP should use default Java `java.awt.Color` class and not redefine a `Color` class with limited functionalities

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2321]
```
ImageRedactionConfig imageRedactionConfig = ImageRedactionConfig.newBuilder()
          .setInfoType(infoType)
          .setRedactionColor(Color.newBuilder().setBlue())
          .build();
```

`setRedactionColor` takes in a custom `com.google.privacy.dlp.v2beta1.Color.class` : requiring the use of builders to set RGB values : 
This is a painful user experience.

**Comment by garrettjonesgoogle** [comment]
This this defined at a language-independent level (proto), this isn't surprising to me. Would it be sufficient to provide a converter utility method?

**Comment by jabubake** [comment]
I guess that would suffice

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by jadekler** [comment]
Hi @jabubake. You can now do `Color.asDlpColor(<some awt color>)`.

**Comment by jabubake** [comment]
Woot :)
