### ISSUE TITLE
Add code sample to Publisher for customizing credentials

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2322]
This should work:

```
Publisher
  .defaultBuilder(topic)
  .setCredentialsProvider(FixedCredentialsProvider.create(yourCredentialsHere))
  .build();
```

**Comment by vam-google** [comment]
The sample is already present in google-cloud-examples module: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java#L136
