### ISSUE TITLE
chatty API

### ISSUE THREAD

**Issue by balopat** [GoogleCloudPlatform/google-cloud-java#2331]
Why is the python code so much smaller than the Java/C#? We should have similar (small) verbosity on all the platforms. I see no good reason not to create a nice DSL on top of the more verbose builders.

Example: 
[python code to read timeseries](https://cloud-dot-devsite.googleplex.com/monitoring/custom-metrics/reading-metrics#monitoring-read-timeseries-fields-python): 
```
client = monitoring.Client()
metric = 'compute.googleapis.com/instance/cpu/utilization'
query_results = client.query(metric, minutes=5).iter(headers_only=True)
for result in query_results:
    print(result)
```
vs
[java code to read timeseries](https://cloud-dot-devsite.googleplex.com/monitoring/custom-metrics/reading-metrics#monitoring-read-timeseries-fields-java)
```
MetricServiceClient metricServiceClient = MetricServiceClient.create();
String projectId = System.getProperty("projectId");
ProjectName name = ProjectName.create(projectId);

// Restrict time to last 20 minutes
long startMillis = System.currentTimeMillis() - ((60 * 20) * 1000);
TimeInterval interval = TimeInterval.newBuilder()
    .setStartTime(Timestamps.fromMillis(startMillis))
    .setEndTime(Timestamps.fromMillis(System.currentTimeMillis()))
    .build();

ListTimeSeriesRequest.Builder requestBuilder = ListTimeSeriesRequest.newBuilder()
    .setNameWithProjectName(name)
    .setFilter("metric.type=\"compute.googleapis.com/instance/cpu/utilization\"")
    .setInterval(interval)
    .setView(ListTimeSeriesRequest.TimeSeriesView.HEADERS);

ListTimeSeriesRequest request = requestBuilder.build();

PagedResponseWrappers.ListTimeSeriesPagedResponse response = metricServiceClient
    .listTimeSeries(request);

System.out.println("Got timeseries headers: ");
for (TimeSeries ts : response.iterateAll()) {
  System.out.println(ts);
}
```

**Comment by meltsufin** [comment]
@garrettjonesgoogle @jabubake PTAL

**Comment by garrettjonesgoogle** [comment]
@balopat this is a matter of trade-offs. The Python client here has hand-written code to make common tasks easier. The Java client is purely auto-generated with no such helpers. The Python client is more expensive to maintain; the Java client is much cheaper - we just have to regenerate anytime the protos change. So that's the basic reason: available resources to work on it.

**Comment by jabubake** [comment]
That being said : I still think its worth thinking of how we could simplify some of the generic statements here, which might be applicable across multiple libraries.

Constructing a resource  `ProjectName` with the projectId : comes up for Pub/Sub as well.
It would be good to users to provide projectId if required, and allow for the generated code to autodetect projectId with `ServiceOptions.getDefaultProjectId()`.
```
String projectId = System.getProperty("projectId");
ProjectName name = ProjectName.create(projectId);
```

A `TimeInterval` helper which can possibly provide a start/end time and duration, so this amount of code does n't become necessary.
Java users are used to simpler ways of building time intervals like [here](http://www.joda.org/joda-time/apidocs/org/joda/time/Interval.html).
```
// Restrict time to last 20 minutes
long startMillis = System.currentTimeMillis() - ((60 * 20) * 1000);
TimeInterval interval = TimeInterval.newBuilder()
    .setStartTime(Timestamps.fromMillis(startMillis))
    .setEndTime(Timestamps.fromMillis(System.currentTimeMillis()))
    .build();
```

**Comment by balopat** [comment]
@garrettjonesgoogle thank you for the response. I think that it would be very beneficial to invest into this extra layer: 
* we can fine tune for better user experience and achieve greater adoption
* if the protos change, that doesn't necessarily mean that the API has to change! the current way means that introducing a typo change or rename in a proto field will definitely generate breaking changes in client code, whilst with an extra layer we can protect against that too to a certain extent

**Comment by garrettjonesgoogle** [comment]
* It is true that we can fine tune APIs, but the maintenance burden is 10x that of auto-generated libraries. I'd rather look at what kind of specialized code generation we could do to reduce the pain some, even if it isn't completely solved.
* Our policy is to count proto field renames as breaking changes. API owners need to take that into account and not rename fields after their API has become GA.

**Comment by jabubake** [comment]
@garrettjonesgoogle : I agree, that's why I think its worth investing into efforts that span multiple APIs (possibly @ code generation) : time interval concept should not be so complicated to the end user, user's code should n't have to be littered with project-name based resource objects. See issue on Color [here](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2321).

**Comment by balopat** [comment]
Okay, thanks for the input, I'll try to think about it in automation ways then when I run into inconvenient APIs. I put in another example issue #2333 where the protobuf driven API is a bit confusing for a new user.

**Comment by garrettjonesgoogle** [comment]
So with there being two issues now (the present one and #2333 ), what should be the focus of the present one?

**Comment by garrettjonesgoogle** [comment]
I looked at the Java code in more detail, and there are some places where the sample itself is more verbose than necessary, which exaggerates the differences between Python and Java. I think the following Java sample makes a fairer comparison:

```
MetricServiceClient metricServiceClient = MetricServiceClient.create();
String projectId = System.getProperty("projectId");
ProjectName name = ProjectName.create(projectId);

// Restrict time to last 20 minutes
long startMillis = System.currentTimeMillis() - ((60 * 20) * 1000);
TimeInterval interval = TimeInterval.newBuilder()
    .setStartTime(Timestamps.fromMillis(startMillis))
    .setEndTime(Timestamps.fromMillis(System.currentTimeMillis()))
    .build();

ListTimeSeriesRequest request = ListTimeSeriesRequest.newBuilder()
    .setNameWithProjectName(name)
    .setFilter("metric.type=\"compute.googleapis.com/instance/cpu/utilization\"")
    .setInterval(interval)
    .setView(ListTimeSeriesRequest.TimeSeriesView.HEADERS)
    .build();

for (TimeSeries ts : metricServiceClient.listTimeSeries(request).iterateAll()) {
  System.out.println(ts);
}
```

**Comment by anthmgoogle** [comment]
It looks like this has answered the original question, acknowledging that it is still not as concise the as the Python. Please reopen or create a new issue if there is further iteration required.
