### ISSUE TITLE
Error build gradle for Android Project

### ISSUE THREAD

**Issue by BondolTuon** [GoogleCloudPlatform/google-cloud-java#2340]
![screen shot 2017-08-15 at 1 21 37 pm](https://user-images.githubusercontent.com/4638285/29304367-c958166e-81bc-11e7-9f03-e1020d9e9d8e.png)

**Comment by garrettjonesgoogle** [comment]
Android is not currently supported by google-cloud-java.

**Comment by BondolTuon** [comment]
Ohhh! I see. thank you for your answer.

**Comment by garrettjonesgoogle** [comment]
No problem. I'm going to close out this issue now. Thank you for your interest in google-cloud-java!
