### ISSUE TITLE
Storage::writer() provides no way to see metadata after writing.

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-java#2343]
Here's an example of using the Storage::writer method to write a blob from the documentation:

```
BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType("text/plain").build();
try (WriteChannel writer = storage.writer(blobInfo)) {
   try {
      writer.write(ByteBuffer.wrap(content, 0, content.length));
   } catch (Exception ex) {
     // handle exception
   }
}
```
This works well and makes it easy to write data to a GCS object with a WriteChannel. However, when the operation finishes, GCS returns the metadata of the new object, most importantly including the generation number of the newly-created object. The writer() method provides no way of accessing this metadata.

We need a way of accessing the metadata of the new object upon success. Perhaps a Blob accessor could be added to the WriteChannel, or some assignable reference could be passed to the writer() method, or some other mechanism.

**Comment by shinfan** [comment]
cc/ @garrettjonesgoogle

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
