### ISSUE TITLE
Make exception more informative when using FACE_DETECTION in `Feature` list for Video Intelligence API

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2348]
v0.21.1-alpha

```java
java.util.concurrent.ExecutionException: com.google.api.gax.grpc.GrpcApiException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
```

is the  non-informative response.
[Here](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/patch-video/video/cloud-client/src/test/java/com/example/video/DetectIT.java#L58) is the code used to test.

I noticed [REST API reference](https://cloud.google.com/video-intelligence/docs/reference/rest/v1beta1/videos) does not list FACE_DETECTION.

@lesv @gguuss

**Comment by jabubake** [comment]
It seems this feature requires being whitelisted. It would be great if we could provide a more informative exception here or document this given `Feature.FACE_DETECTION` is in the library.

**Comment by garrettjonesgoogle** [comment]
So is the server itself returning INVALID_ARGUMENT with the message "Request contains an invalid argument."? If so, we don't have much information to work with at the client library level.

**Comment by jabubake** [comment]
That is unfortunate, should I move this issue to googleapis ?

**Comment by garrettjonesgoogle** [comment]
googleapis probably isn't quite the right place - we may have a platform-wide issue with out whitelisted features are treated. I've seen other whitelisted APIs throw uninformative exceptions too.

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
