### ISSUE TITLE
Release notes : no easy way for users to find latest versions @ a glance

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2349]
Given the alpha/beta/GA status, it would be good to provide a way to clearly state the client libraries part of a release.

Right now [pom.xml](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/pom.xml#L146) lists versions of libraries and dependencies like `gax` without any consistent prefix to distinguish them from client libraries.

**Comment by garrettjonesgoogle** [comment]
Could you make your request more specific?

**Comment by jabubake** [comment]
```
<api-client.version>1.22.0</api-client.version>

    <api-common.version>1.1.0</api-common.version>
    <gax.version>1.5.0</gax.version>
    <gax-grpc.version>0.22.0</gax-grpc.version>
    <generatedProto.version>0.1.15</generatedProto.version>
    <google.auth.version>0.7.0</google.auth.version>
    <grpc.version>1.4.0</grpc.version>
    <guava.version>20.0</guava.version>
    <http-client.version>1.22.0</http-client.version>
    <protobuf.version>3.3.1</protobuf.version>

    <easymock.version>3.4</easymock.version>
    <objenesis.version>2.6</objenesis.version>

    <cloud.version>0.21.2-alpha-SNAPSHOT</cloud.version>
    <bigquery.version>0.21.2-beta-SNAPSHOT</bigquery.version>
    <compute.version>0.21.2-alpha-SNAPSHOT</compute.version>
    <contrib.version>0.21.2-alpha-SNAPSHOT</contrib.version>
    <core.version>1.3.2-SNAPSHOT</core.version>
    <core-http.version>1.3.2-SNAPSHOT</core-http.version>
    <core-grpc.version>1.3.2-SNAPSHOT</core-grpc.version>
    <datastore.version>1.3.2-SNAPSHOT</datastore.version>
    <dlp.version>0.21.2-alpha-SNAPSHOT</dlp.version>
    <dns.version>0.21.2-alpha-SNAPSHOT</dns.version>
    <errorreporting.version>0.21.2-alpha-SNAPSHOT</errorreporting.version>
    <examples.version>0.21.2-alpha-SNAPSHOT</examples.version>
    <language.version>0.21.2-beta-SNAPSHOT</language.version>
    <logging.version>1.3.2-SNAPSHOT</logging.version>
    <monitoring.version>0.21.2-alpha-SNAPSHOT</monitoring.version>
    <pubsub.version>0.21.2-beta-SNAPSHOT</pubsub.version>
    <resourcemanager.version>0.21.2-alpha-SNAPSHOT</resourcemanager.version>
    <spanner.version>0.21.2-beta-SNAPSHOT</spanner.version>
    <speech.version>0.21.2-alpha-SNAPSHOT</speech.version>
    <storage.version>1.3.2-SNAPSHOT</storage.version>
    <trace.version>0.21.2-alpha-SNAPSHOT</trace.version>
    <translate.version>1.3.2-SNAPSHOT</translate.version>
    <vision.version>0.21.2-beta-SNAPSHOT</vision.version>
    <video-intelligence.version>0.21.2-alpha-SNAPSHOT</video-intelligence.version>
```

No distinction from core dependencies and client libraries. Some kind of parseable prefix would be useful. We talked of creating a separate file for releases,  but if this is already available in the `pom.xml`, it might be worth just cleaning up to include a prefix tag on client libraries ?

**Comment by garrettjonesgoogle** [comment]
But these will almost always be SNAPSHOT versions, and we want to publish non-SNAPSHOT versions that people can use in their own pom.xml files. So, we would need to generate some content off of these versions at release time. In a way, we do that already - there are maven/gradle snippets all over the place with the current version in them (updated during the release process). Do you want a file containing these snippets for all of the APIs for easy reference?

**Comment by jabubake** [comment]
Wrong paste there, I meant picking them up from the release tagged version from the [Release Notes](https://github.com/GoogleCloudPlatform/google-cloud-java/releases), so they will not have the `-SNAPSHOT`.
https://github.com/GoogleCloudPlatform/google-cloud-java/releases/tag/v0.21.1

**Comment by jabubake** [comment]
But to your question :  Do you want a file containing these snippets for all of the APIs for easy reference? 

I think that would be really useful.

**Comment by jabubake** [comment]
That would actually be really great, we could easily embed that in the cloud docs just like we do for snippets.

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
