### ISSUE TITLE
Add ability to batch Storage.create() requests

### ISSUE THREAD

**Issue by chamikaramj** [GoogleCloudPlatform/google-cloud-java#2351]
Seems like current batching API [1] does not support batching create [2] requests. Batching create requests might be needed for some use cases; for example, if a user needs to create a large number of small files.

If this is already supported it might be good to add an example.

[1] https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageBatch.java#L55
[2] https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L1427

**Comment by chamikaramj** [comment]
cc: @garrettjonesgoogle

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by aditya730** [comment]
Any timeline for this feature?We have a use case where we have to upload a number of small files to GCS and could do way better on throughput if this feature was available.

**Comment by PadrePadrone** [comment]
This feature would significantly imrove our application performance. 
Any timeline for it?

**Comment by janaton** [comment]
> This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

 @yihanzhen please, is there any new ticket we could watch? I can not find any reference to this closed ticket in the reference Feature-backlog document and also no new ticket that could be related to this topic. We would also greatly appropriate this batched feature to radically speed up upload of several thousands small files. Thanks a lot

**Comment by yihanzhen** [comment]
Hey I no longer work on java libraries. I filed ^^^^ in the java storage's repo for current project owners to triage. Please follow it there for updates.

**Comment by janaton** [comment]
Thank you very much for forwarding this issue to the correct place
