### ISSUE TITLE
Subscription processes hangs forever

### ISSUE THREAD

**Issue by bisws007** [GoogleCloudPlatform/google-cloud-java#2353]
Hi,
Publish process publishes only 2 messages. Ran subscription process on my local and messaged processed successfully. 2nd time I ran the subscription process once again on my local and there is no messages but the subscription process hangs forever. Can you please explain why?
I am using google pub-sub version 0.21.1-beta.

**Comment by GEverding** [comment]
I think I've been seeing this issue in production as well. Same version as above. However it's only in one of our services. How can I help debug this issue? I've seen similar behaviour? And it happens 1-5 times per day.

**Comment by nbrinks** [comment]
Similar issue on 0.22.0-beta. As a test I set up a job to publish messages to a topic every 30 seconds. Subscription will receive messages, every 30 seconds, for a period of time and then suddenly stop receiving messages for hours. Subscriber.Listener does not trigger any callbacks when this occurs. Sometimes it recovers sometimes it does not. Spring Boot app hosted on GKE.

**Comment by anthmgoogle** [comment]
Need to verify if this is a reliability bug or not.

**Comment by pongad** [comment]
@bisws007 Could you share the code you're using to subscribe? Generally the subscriber won't stop until you call `subscriber.stopAsync()`.

In v0.21, there was a bug that could cause messages to be stuck in the subscriber that prevents termination. That bug has been fixed now. Do you think you can try again with v0.26?

**Comment by pongad** [comment]
I'll close this for now due to age. Please reopen if required.
