### ISSUE TITLE
PubSub Subscriber requires pubsub.subscriptions.get permission

### ISSUE THREAD

**Issue by trebon** [GoogleCloudPlatform/google-cloud-java#2358]
The current IAM role for Subscriber only gives the following permissions:
- pubsub.subscriptions.consume
- pubsub.topics.attachSubscription

This library uses pubsub.subscriptions.get when [constructing the subscriber](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.21.0/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java#L302). This causes a permission denied exception to be thrown. 

It is not documented anywhere that the Java client library requires this permission. My assumption as a user is that the IAM role for subscriber gives me all the required permissions to subscribe. For Java Publisher, the publisher role has all the needed permissions using the IAM publisher role. For Python Subscriber, Subscriber IAM role has sufficient permissions.

**Comment by pongad** [comment]
Polling subscription has already been deprecated. Streaming pull, landed in v0.21, should not need this permission anymore.
