### ISSUE TITLE
Does there exist a function to parse gs url into a bucket part and a blob part?

### ISSUE THREAD

**Issue by derekhh** [GoogleCloudPlatform/google-cloud-java#2363]
If I understand correctly, the way to fetch blob content from Google Cloud Storage, as suggested by the [google-cloud-java](http://googlecloudplatform.github.io/google-cloud-java/0.21.1/apidocs/index.html) API, right now is using something like:

```
Storage storage = StorageOptions.getDefaultInstance().getService();
BlobId blobId = BlobId.of("bucket", "blob_name");
Blob blob = storage.get(blobId);
byte[] content = blob.getContent();
```

This requires us to pass in two arguments: `bucket` and `blob_name`, but normally what we would want to pass in, originally, would be a `gs://` url. 

I want to know whether there exists a function that can parse a gs URL and return the bucket and blob parts, like the [parseGlob](https://chromium.googlesource.com/external/googleappengine/python/+/78bd635e7b42b5a8105e19b6f83aed5bbf5a6732/google/appengine/api/files/gs.py#70) function here. I feel this might be something that exists in the google-cloud-java library already so I don't need to reinvent the wheel.

**Comment by michaelbausor** [comment]
I am not aware of this existing currently, and a quick search of the code didn't turn anything up.

It seems to me that [`BlobId`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobId.java) would benefit from having `fromStorageUrl` and `toStorageUrl` methods - would that address the use case you are looking at?

**Comment by derekhh** [comment]
@michaelbausor - Thanks for your reply! That would definitely help. :)

Sorry if you don't mind me asking another question that is relevant to this topic. While reading the JavaDoc, I've also found something like [CloudStoragePath](http://googlecloudplatform.github.io/google-cloud-java/0.21.1/apidocs/com/google/cloud/storage/contrib/nio/CloudStoragePath.html) that appears to be relevant but then I found it belongs to [google-cloud-nio](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/0db14b7c72ab534ae7109688302858a2cb3b9ec2/google-cloud-contrib/google-cloud-nio). Can I assume this google-cloud-nio thing is not the recommended approach to interact with Cloud Storage?

**Comment by michaelbausor** [comment]
The google-cloud-nio package is not the recommended approach, the [google-cloud-storage](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-storage) package is the best place to start.

But it is possible that the google-cloud-nio package might be useful for you - it is an implementation of the Java 7 java.nio.file.FileSystem for storage, see the [README](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-nio) for more info.

**Comment by michaelbausor** [comment]
I am going to close this out - I have opened a new issue to track creating fromStorageUrl and toStorageUrl methods here: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2397
