### ISSUE TITLE
SQLAdmin.Builder wants application name

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-java#2371]
If you create a `SQLAdmin` with the builder, without setting application name by calling `SQL.Builder(...).setApplicationName("app-name")`, you'll see a warning coming from `AbstractGoogleClient` saying:

"Application name is not set. Call Builder#setApplicationName."

What's the purpose of setting application name? I don't see it being documented? If it's not needed, the warning should be removed.

**Comment by michaelbausor** [comment]
Do you mean this code: https://github.com/google/google-api-java-client/blob/dev/google-api-client/src/main/java/com/google/api/client/googleapis/services/AbstractGoogleClient.java#L86

If so, this issue should be moved to https://github.com/google/google-api-java-client

**Comment by meltsufin** [comment]
The warning is coming from the file you pointed to, but part of the problem is that it's not clear what is the purpose of `SQL.Builder#setApplicationName`, which is a method provided by this project. That's why I posted it here initially.
@jabubake @lesv

**Comment by michaelbausor** [comment]
AFAICT the SQLAdmin class is coming from this package, which isn't part of this library: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22google-api-services-sqladmin%22

Is this the right class?
https://developers.google.com/resources/api-libraries/documentation/sqladmin/v1beta4/java/latest/com/google/api/services/sqladmin/SQLAdmin.html

**Comment by meltsufin** [comment]
Ah you're right! I thought the code was hosted in this project. My mistake, sorry.
Thanks for pointing to the right place to post this issue.

**Comment by meltsufin** [comment]
https://github.com/google/google-api-java-client/issues/1062
