### ISSUE TITLE
Write unit tests for the CloudStorageRetryHandler class

### ISSUE THREAD

**Issue by droazen** [GoogleCloudPlatform/google-cloud-java#2375]
We recently extracted a simple `CloudStorageRetryHandler` class to keep track of retries/reopens in `google-cloud-nio`. This class needs unit tests, as per the discussion in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2281

**Comment by droazen** [comment]
@jean-philippe-martin or myself can take this on when we have time.

**Comment by anthmgoogle** [comment]
There is a merged PR. Does that mean this can be closed now?
