### ISSUE TITLE
TESTING.md refers to non-existant method setChannelProvider for PubSub

### ISSUE THREAD

**Issue by monofuel** [GoogleCloudPlatform/google-cloud-java#2378]
TESTING.md refers to a method that no longer exists in 0.22.0-beta.

The example for creating a pubsub topic admin client:
```
TopicAdminClient topicClient = TopicAdminClient.create(
    TopicAdminSettings
      .defaultBuilder()
      .setChannelProvider(channelProvider)
      .setCredentialsProvider(credentialsProvider)
      .build());
```

uses `.setChannelProvider()`, which no longer exists. It's not clear what the new approach for testing is.

**Comment by vam-google** [comment]
Merged

**Comment by monofuel** [comment]
Sweet! thanks a bunch!
