### ISSUE TITLE
Add `RequesterPays` as `BucketField` entry

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2391]
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L95

Currently, if I retrieve by `ID`, I receive null on `requesterPays` even when it has been enabled on a bucket.
Please add `RequesterPays` as `BucketField` entry (unless there is another recommended approach to querying `requesterPays` status of a bucket)

**Comment by jabubake** [comment]
@garrettjonesgoogle : this blocks the samples, unless there is another preferred way to retrieve the `requesterPays` status.

**Comment by vam-google** [comment]
Fix merged, closing.
