### ISSUE TITLE
Add fromStorageUrl and toStorageUrl methods to BlobId

### ISSUE THREAD

**Issue by michaelbausor** [GoogleCloudPlatform/google-cloud-java#2397]
See this issue for context: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2363

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by etsrepo** [comment]
why its not yet developed.

**Comment by danielbraun89** [comment]
Past second quarter of 2019 and still not implemented

**Comment by jadn123** [comment]
This issue seems to have been removed from the feature backlog 18 days ago with comment `Clean up: Moving Cloud Storage requests to respective backlogs.`.

However I am unable to find the "feature backlog" for Cloud Storage and hence any reference to this issue.

**Comment by mixermt** [comment]
Middle of 2021 ... was it implemented?

**Comment by yihanzhen** [comment]
Opened ^^^ in the new repository. I'm no longer working on the libraries but please follow the issue above for updates.
