### ISSUE TITLE
googlecloudplatform.github.io/google-cloud-java seems badly formatted

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2400]
![screen shot 2017-09-01 at 11 09 12 am](https://user-images.githubusercontent.com/1136014/29982369-4385acca-8f06-11e7-9c0b-3407c6c987cd.png)

**Comment by vam-google** [comment]
I think it is a screeen width problem (I can reproduce it only when I make my browser window very narrow).

**Comment by samtstern** [comment]
@vam-google confirmed from #2475 that 960px is the line at which things start getting wonky.

**Comment by garrettjonesgoogle** [comment]
Fixed in #2711
