### ISSUE TITLE
How to get the names of all accessible Datasets?

### ISSUE THREAD

**Issue by Electricks94** [GoogleCloudPlatform/google-cloud-java#2404]
Hello,
I got a small problem. Basically, I just want to receive the names of all the datasets which I can access. My code looks like BigQuery API described how to do it:

```

import java.util.Iterator;
import java.util.List;

import com.google.api.gax.paging.Page;
//import com.google.appengine.repackaged.org.apache.lucene.analysis.compound.hyphenation.TernaryTree.Iterator;
import com.google.cloud.bigquery.*;
import com.google.cloud.bigquery.BigQuery.DatasetListOption;

public class GetBQInfo {
	public static void getinfo (){
	BigQuery bigquery = BigQueryOptions.getDefaultInstance()
		    .toBuilder()
		    .setProjectId("testprojekt-175408")
		    .build()
		    .getService();
	 String projectId = "testprojekt-175408";
	 Page<Dataset> datasets = bigquery.listDatasets(projectId, DatasetListOption.pageSize(100));
	 Iterator<Dataset> datasetIterator = datasets.iterateAll();
	 while (datasetIterator.hasNext()) {
	   Dataset dataset = datasetIterator.next();
	   // do something with the dataset
	 }
	 }
}
```
But I cannot compile the code because I get this message from eclipse:
`Type mismatch: cannot convert from Iterable<Dataset> to Iterator<Dataset>`
I tried a lot of things but nothing worked for me yet. Does anyone know how I can solve this?

**Comment by michaelbausor** [comment]
`Iterator` and `Iterable` are two different Java interfaces, so they cannot be used interchangeably. In particular, you cannot assign the return value of `iterateAll` (an `Iterable`) to your variable, which is an `Iterator`. Try changing the line:
`Iterator<Dataset> datasetIterator = datasets.iterateAll();`
to:
`Iterable<Dataset> datasetIterator = datasets.iterateAll();`

**Comment by Electricks94** [comment]
Thank you for your answer. It works fine now!

**Comment by michaelbausor** [comment]
Great! I'll close this out.
