### ISSUE TITLE
Pub/Sub give problem in AppEngine with Standard Environment with Java 7

### ISSUE THREAD

**Issue by ahzamfarhan** [GoogleCloudPlatform/google-cloud-java#2405]
Pub/Sub give problem in AppEngine with Standard Environment with Java 7

Hi, I have created Google PUB/SUB using topic. I get error in my Subscriber code. my code works on my local tomcat server but when I deployed it on Google cloud AppEngine with standard environment. It gives following error.
**Could not initialize class com.google.cloud.pubsub.v1.Subscriber**

Initialization of Subscriber instance is failed on Google cloud AppEngine whereas Subscriber is initialized in local tomcat
com.google.cloud.pubsub.v1.Subscriber subscriber = Subscriber.defaultBuilder(subscription,receiver).build();	

I have used following Maven dependencies 
<dependency>
  <groupId>com.google.appengine</groupId>
  <artifactId>appengine-api-1.0-sdk</artifactId>
  <version>1.9.54</version>
</dependency>

<dependency>
 <groupId>com.google.api-client</groupId>
 <artifactId>google-api-client-appengine</artifactId>
 <version>1.21.0</version>
 <exclusions>
  <exclusion>
   <groupId>javax.servlet</groupId>
   <artifactId>servlet-api</artifactId>
  </exclusion>
  <exclusion>
   <groupId>javax.servlet</groupId>
   <artifactId>servlet-api</artifactId>
  </exclusion>
  <exclusion>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-jdk5</artifactId>
  </exclusion>
 </exclusions>
</dependency>

<dependency>
 <groupId>com.google.apis</groupId>
 <artifactId>google-api-services-pubsub</artifactId>
  <version>v1-rev8-1.21.0</version>
</dependency>

<dependency>
 <groupId>com.google.cloud</groupId>
 <artifactId>google-cloud-examples</artifactId>
 <version>0.22.0-alpha</version>
</dependency>

<dependency>
 <groupId>com.google.appengine.tools</groupId>
 <artifactId>appengine-gcs-client</artifactId>
 <version>0.5</version>
 <exclusions>
  <exclusion>    
    <groupId>com.google.http-client</groupId>
    <artifactId>google-http-client</artifactId>
  </exclusion>
 </exclusions>
</dependency>

<dependency>
 <groupId>com.google.appengine</groupId>
 <artifactId>appengine-remote-api</artifactId>
  <version>1.9.32</version>
</dependency>

**Comment by michaelbausor** [comment]
@neozwu can you comment on this?

**Comment by ahzamfarhan** [comment]
I did not get the answer of my question. I once again describe  my problem in short. I have AppEngine with Standard Environment. Whenever I deploy my web app on AppEngine on standard environment. It  gives me as Error "java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.pubsub.v1.Subscriber". But same webapp application run fine on my local tomcat server. I want to know if AppEngine with Standard Environment does not support com.google.cloud.pubsub.v1.Subscriber initialization?

**Comment by michaelbausor** [comment]
We do not expect PubSub (or other gRPC-based APIs) to work with Java 7 on AppEngine Standard. (See for example [this comment](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1807#issuecomment-304998685)).

It should work using Java 8 on AppEngine Standard.

It doesn't look like you have a direct dependency on the google-cloud-pubsub package (see here on github: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-pubsub). If you are using Java 8 and seeing this problem, you could try adding this dependency.

**Comment by ahzamfarhan** [comment]
Thanks michaelbauso, 
AppEngine Standard by default uses jdk 7. I want to know to change AppEngine Standard to use jdk 8.

**Comment by michaelbausor** [comment]
No worries! For Java 8, take a look at the documentation here: https://cloud.google.com/appengine/docs/standard/java/runtime-java8

**Comment by ahzamfarhan** [comment]
I have followed the steps specified on URL  https://cloud.google.com/appengine/docs/standard/java/runtime-java8. I am getting following error file fire 'mvn appengine:update command.

java.io.IOException: Cannot run program "C:\jdk1.8.0_144\jre\bin\java.exe": Crea
teProcess error=206, The filename or extension is too long
Unable to update app: Cannot run program "C:\jdk1.8.0_144\jre\bin\java.exe": Cre
ateProcess error=206, The filename or extension is too long
Please see the logs [C:\Users\farhanm\AppData\Local\Temp\appcfg16888316327372592
11.log] for further information.

**Comment by lesv** [comment]
@ahzamfarhan Can you post a copy of your log?  (if it doesn't have any confidential info in it)

**Comment by lesv** [comment]
@ahzamfarhan Also, take a look at https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8
for migration info.

**Comment by anthmgoogle** [comment]
Looks like the original issue has been clarified. If there are issues with moving to Java8 it may be best to create a new issue.
