### ISSUE TITLE
Reconsider project.properties and META-INF

### ISSUE THREAD

**Issue by michaelbausor** [GoogleCloudPlatform/google-cloud-java#2412]
Our current use of project.properties is the cause of this issue: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2411

It seems like the way we are using project.properties may be unnecessary, or otherwise we may be able to use `META-INF`, which would be a cleaner/more idiomatic solution.

**Comment by garrettjonesgoogle** [comment]
Closing this issue because https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2411 is closed - we aren't using project.properties any more.
