### ISSUE TITLE
Adding Snippets has errors

### ISSUE THREAD

**Issue by michaelbausor** [GoogleCloudPlatform/google-cloud-java#2413]
script: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/utilities/add_snippets_to_file.py

1. Method signature with @Nullable does not work.
Fix:
At this line in add_snippets_to_file.py#L99, replace the existing:
    ',\s+'.join(['(final\s+)?{}\s+{}'.format(
with this:
    ',\s+'.join(['(@Nullable\s+)?(final\s+)?{}\s+{}'.format(

2. for all single line comments, the script either fails (when its the last method in the file) or appends javadocs to the successive method.

example:
/** some javadoc */
public String method ( String args );

**Comment by hzyi-google** [comment]
@pongad It seems your PR will resolve this issue, so I am giving this to you.

**Comment by pongad** [comment]
Should be fixed by #2838.
