### ISSUE TITLE
Clarify requirement instructions for App Engine

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-java#2419]
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/APPENGINE.md

says to add appengine-api-1.0-sdk for App Engine. This should emphasize that it is only needed for local dev appserver1 (not sure about dev appserver2). The instructions mislead people to believe the dependency is required on prod too.

Also, it says

> **Note: the following instructions are not required for App Engine Flex and Java 8 standard environment.**

However, I verified that dev appserver emulating the Java 8 runtime still needs the dependency. Also, mentioning flex here is confusing, because there is no dev appserver for flex.

(BTW, "Flex" should be "flexible environment" in docs.)

**Comment by hzyi-google** [comment]
Fixed by #2948
