### ISSUE TITLE
GCStorage - Handle extension headers on signUrl generation

### ISSUE THREAD

**Issue by frantello** [GoogleCloudPlatform/google-cloud-java#2421]
More advance configuration and validations of sign URLs require extension headers [https://cloud.google.com/storage/docs/xml-api/reference-headers](extension headers).

Opened this ticket to track my commits.

I'm working on a pull request that will coming soon.

**Comment by hzyi-google** [comment]
@frantello it seems the PR this issue tracks is merged. Can I close it now?

**Comment by frantello** [comment]
@hzyi-google yes, job is done. Thanks!
