### ISSUE TITLE
Logging Structs should prefer map over iterable when serializing

### ISSUE THREAD

**Issue by lvh** [GoogleCloudPlatform/google-cloud-java#2432]
The [current serialization code](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java#L142) looks like this at time of writing:

```java
  private static Value objectToValue(final Object obj) {
    Value.Builder builder = Value.newBuilder();
    if (obj == null) {
      builder.setNullValue(NullValue.NULL_VALUE);
      return builder.build();
    }
    Class<?> objClass = obj.getClass();
    if (obj instanceof String) {
      builder.setStringValue((String) obj);
    } else if (obj instanceof Number) {
      builder.setNumberValue(((Number) obj).doubleValue());
    } else if (obj instanceof Boolean) {
      builder.setBoolValue((Boolean) obj);
    } else if (obj instanceof Iterable<?> || objClass.isArray()) {
      builder.setListValue(ListValue.newBuilder()
          .addAllValues(Iterables.transform(Types.iterableOf(obj), OBJECT_TO_VALUE)));
    } else if (objClass.isEnum()) {
      builder.setStringValue(((Enum<?>) obj).name());
    } else if (obj instanceof Map) {
      Map<String, Object> map = (Map<String, Object>) obj;
      builder.setStructValue(newStruct(map));
    } else {
      throw new IllegalArgumentException(String.format("Unsupported protobuf value %s", obj));
    }
    return builder.build();
  }
```

I think it would be better if the check for `instanceof Map` happened before `instanceof Iterable<?>`. It's true that Maps in the stdlib are generally not iterable, but third party ones can be. For example, Clojure's PersistentHashMap and PersistentArrayMap are both Iterable. If something is both a Map and Iterable, Map seems the most desirable behavior.

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by lvh** [comment]
FWIW, it's not clear why this is marked as a feature request. I'm asking for the code to work correctly with the standard data structures of at least Clojure and possibly Scala -- but it's not a Clojure/Scala specific issue, that's just an obvious place where you'd hit it. See also #1890, #3150 (unrelated except "nasty surprise for people using Clojure data structures").

**Comment by lvh** [comment]
FWIW I used this gross hack to get around the problem: https://github.com/latacora/unsiemly/blob/master/src/unsiemly/xforms.clj#L97

Basically I had to create a proxy type that implements Map but no other interfaces, takes a Map that is also e.g. Iterable, and then only exposes a Map interface.
