### ISSUE TITLE
"High performance" is incorrect.

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#2433]
The Javadoc for the compute API says: "A client for Google Compute Engine – High-performance, scalable virtual machines."

"High performance" is incorrect. The point of scalable here is that you may choose low performance VMs for less cost if that suits your needs better.

**Comment by andreamlin** [comment]
That line reflects the general Compute documentation at https://cloud.google.com/compute/ that says Google offers "High-Performance, Scalable VMs". 

@elharo How would you see the Javadocs phrased?

**Comment by anthmgoogle** [comment]
Please reactivate if there is a concrete suggestion here.

**Comment by elharo** [comment]
My suggestion is to delete "high performance". It's a meaningless buzzword that adds no useful information. In this case, it is also actively misleading. It actively contradicts the next word, "Scalable". GCE scales from low performance to high performance. Users pick and pay for what they need. 

It should probably be deleted from https://cloud.google.com/compute/ as well, though I'll have to file an internal bug for that.

**Comment by anthmgoogle** [comment]
We really need to follow the lead of the API from the client side. If the GCE team agrees to remove this wording from their main reference documentation, we will can change this corresponding documentation here.
