### ISSUE TITLE
Add BigQuery API for labelling datasets and tables 

### ISSUE THREAD

**Issue by kvncp** [GoogleCloudPlatform/google-cloud-java#2444]
The BigQuery interface currently lacks support for adding labels to datasets and tables:
https://cloud.google.com/bigquery/docs/labels#bigquery-dataset-set-label-java

**Comment by hzyi-google** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
