### ISSUE TITLE
Is there a repository for 'appengine-api-1.0-sdk'?

### ISSUE THREAD

**Issue by derekhh** [GoogleCloudPlatform/google-cloud-java#2454]
This [Use Google Cloud Java Client with Google App Engine](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/APPENGINE.md) suggests that we should use `appengine-api-1.0-sdk` for Java 7 GAE standard environments.

Is there a repository for this `appengine-api-1.0-sdk` somewhere? Or is there something like release notes for each version? The closest thing I can find is this: https://cloud.google.com/appengine/docs/standard/java/release-notes but it seems it only says something like "Updated Java SDK to version 1.9.xx" and no other information is provided.

**Comment by derekhh** [comment]
Another question that is quite relevant to the above one: what's the recommended way to use Pub/Sub in Java 7 GAE Standard environment? I found this: https://developers.google.com/api-client-library/java/ but I'm not sure whether this is still the recommended library to use.

**Comment by lesv** [comment]
These libraries need Java 8 to use. [migration](https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8)

For Java 7, take a look at https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-java/tree/master/appengine-push - it uses an older GAE specific library.  You'll want to check the versions w/ maven central and use the most recent.
