### ISSUE TITLE
Ability to set custom headers for outbond calls

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2467]
Some users can only make callout to external services via a proxy that may require authentication headers. Need a way (and doc) to set headers for outbound calls for REST and gRPC services.

**Comment by hzyi-google** [comment]
Move this feature request to [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
