### ISSUE TITLE
Getting labels from InstanceInfo class

### ISSUE THREAD

**Issue by asuresh4** [GoogleCloudPlatform/google-cloud-java#2468]
Like MetaData, Tags and other information about the instance is available through [InstanceInfo.java] (https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-compute/src/main/java/com/google/cloud/compute/InstanceInfo.java) would it be possible to get Labels of an instance from this class. I don't see a direct method that I could use. Also, if this method is left out intentionally what's reason? Thanks!

**Comment by asuresh4** [comment]
I wonder if this has got to do something with the fact that both tags and labels were in sync in previously, which is not the case anymore.

**Comment by hzyi-google** [comment]
Move this to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). This place can continue to be used for discussion.
