### ISSUE TITLE
Add more convenient methods to com.google.cloud.Timestamp

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2472]
`com.google.cloud.Timestamp` exposes some convenient method to convert a common Java type to protobuffer timestamp. But it doesn't the same convenient methods to convert a proto timestamp back to the common Java type.

Timestamp can take in `java.util.Date`, `java.sql.Timestamp`, and `long` in microseconds.  It should also take in `long` for typical timestamp in milliseconds.

You can convert Timestamp to other types w/ `toSqlTimestamp`, but we should also have common types like `toDate` (`java.util.Date`), and `toTime` (`long` for milliseconds)

**Comment by hzyi-google** [comment]
Move this issue to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog)and close it here. This place can continue to be used for discussion.
