### ISSUE TITLE
Docs site has strange text wrapping

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/google-cloud-java#2475]
<img width="1433" alt="google-cloud-java" src="https://user-images.githubusercontent.com/8466666/31109779-0e5cd96e-a7b7-11e7-9f73-979a318f4f3b.png">

That's on my 13" Macbook Pro.  From playing with Chrome Dev Tools it happens when the width crosses 960px.

**Comment by andreamlin** [comment]
Duplicate of #2400.

**Comment by pongad** [comment]
I'll close this as duplicate. Please reopen if required.
