### ISSUE TITLE
Organize packages better in `google-cloud-java` reference docs

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2476]
https://googlecloudplatform.github.io/google-cloud-java/0.25.0/apidocs/index.html

: it is confusing to the `.spi`,` .stub` , hand-written layer / auto-gen layer all listed together eg for `firestore`. The top category should only list the packages that the user is expected to use.

**Comment by pongad** [comment]
@garrettjonesgoogle You told me on IM that `.spi` should be removed from firestore right? Should `.spi.v1beta1` be merged into `.v1beta1`?

I don't actually think we ever decided on what to do with `.stub` packages. Should they have their own section in the overview?

**Comment by garrettjonesgoogle** [comment]
`.spi` is removed from auto-generated clients, but it's still used for the internals of manual clients. Thus, `.spi.v1beta` should stay where it is.

We should probably make a new section for `.stub` packages.
