### ISSUE TITLE
Pub/Sub : Subscriber Exceptions

### ISSUE THREAD

**Issue by hmigneron** [GoogleCloudPlatform/google-cloud-java#2480]
Using version `0.20.1-beta` of the google-cloud-pubsub lib.

We use `com.google.cloud.pubsub.v1.Subscriber` objects that live for a long time (multiple hours / days). Our logs are filled with the same errors that occur over and over : 

```
 
at java.lang.Thread.run(Thread.java:748)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
at io.grpc.Status.asRuntimeException(Status.java:543)
 
max_age
Received Goaway
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
WARNING: Failed to pull messages (recoverable): 
Oct 04, 2017 2:36:02 PM com.google.cloud.pubsub.v1.PollingSubscriberConnection$1 onFailure
```

From what I can tell, this is fine. The errors are recoverable and we do get all the messages. The problem really is that it fills up our logs and triggers a bunch of alerts and we can't seem to catch the exceptions ourselves to lower the logging level. The format is weird too, we use StackDriver and in this case, it seems like every single line becomes its own log entry (all at the error level) : 

![screen shot 2017-10-04 at 11 12 37 am](https://user-images.githubusercontent.com/1261812/31183575-fb91bac2-a8f4-11e7-8526-d29741898a2b.png)

How can we keep the library from logging so many messages are the error level ? Any way to catch the exceptions ourselves and / or change the logging level ?

Our subscribers are created this way (if it makes a difference) : 

```java
SubscriptionName subscription = SubscriptionName.create(Configurations.getGoogleCloudProjectId(), getSubscriptionName());

MessageReceiver receiver = (message, consumer) -> {
    try {
        // ... handle message
        consumer.ack();
    }
    catch(Exception ex) {
        // Not the one getting logged
        logger.error(new LogEntry().setMessage("An unhandled exception occured in the pubsub receiver. Message will be acked and dropped. " + Helper.getStackTrace(ex)));
        consumer.ack();
    }
};

ExecutorProvider executorProvider = InstantiatingExecutorProvider.newBuilder()
        .setExecutorThreadCount(4)
        .build();

subscriber = Subscriber.defaultBuilder(subscription, receiver)
        .setExecutorProvider(executorProvider)
        .setCredentialsProvider(FixedCredentialsProvider.create(
                ServiceAccountCredentials.fromStream(new FileInputStream(Configurations.getGoogleCloudCredentials())))
        )
        .build();

// PubsubListener extends Subscriber.Listener and doesn't do much besides logging 
// but the logs we see in stack driver aren't coming from our implementation there either
subscriber.addListener(new PubsubListener(), MoreExecutors.directExecutor());

subscriber.startAsync();
```

**Comment by pongad** [comment]
I believe you can do something like this
```java
Logger.getLogger("com.google.cloud.pubsub").setLevel(Level.OFF);
```
to disable logging from package right? You should be able to set it to other levels as well.

FWIW, newer versions should, I think, spam a little less since streaming pull makes fewer calls.

How are you setting the logging to stackdriver. Did you register stackdriver as logging handler or something?

**Comment by hmigneron** [comment]
Thanks for your answer. Ideally we would not want to set them off completely as we wouldn't want to miss important messages if they ever occur (do they ?). I will try different levels, though I imagine this means all messages are logged with the same severity. 

The example I gave is meant to be a `WARNING` from the looks of it. I would like it to be logged as such if at all possible but am ready to live with limitations. I am trying with a different logging level at the moment but it sometimes takes a long time before it starts giving error messages.

> How are you setting the logging to stackdriver. Did you register stackdriver as logging handler?

We run on a google cloud container with logging enabled so we didn't have to setup the agent or anything else really. We simply log using log4j using the following Appender : 

```
<Appenders>
    <Console name="STDOUT" target="SYSTEM_OUT">
        <GCloudLayout />
    </Console>
</Appenders>
```

`GCloudLayout` extends `AbstractStringLayout` and doesn't do anything exotic. Simply serializes our in-house LogEntry objects to JSON. I can provide details if needed.

**Comment by hmigneron** [comment]
Just ran a few tests and unfortunately adding the initializer in the entry point of the app doesn't work.

```java
static {
        Logger.getLogger("com.google.cloud.pubsub").setLevel(Level.INFO);
    }
```

The message still gets logged at the error level in the console.

**Comment by pongad** [comment]
@hmigneron I posted [PR](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2492) that should make new versions spam you less.

I think the reason you're still seeing the logs is that `setLevel` means the logger will only generate logs that that level *or higher*. Since the logger is set to `INFO`, it will continue to log `WARNING` since warnings are considered higher level than infos. In the linked PR, I made retryable errors `FINE` so that loggers set at `INFO` won't pick them up.

@jabubake I'm not sure why logging is picking up each level of stack trace separately though. Do you have any context here?

**Comment by jabubake** [comment]
Given these logs are being directed to stdout, it is picking up individual lines as log entries.
I believe there is a way to structure the log via appender as JSON to avoid this problem. @saturnism may be able to help.

Another option is to use the [Stackdriver logback appender](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/logging/logback) / [java.util.logging handler](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/logging/jul).

**Comment by hmigneron** [comment]
Thanks to both of you for the PR and for your help.

It took me a while, but I ultimately understood that in our case the logs were being direct to stderr (not sure if this is a default but I don't think we configured anything for that) which is why every single line was considered an error on stack driver.

The solution I came up with is to replace the default ConsoleHandler with a custom one : 

```java
Logger globalLogger = Logger.getLogger("");
for (Handler handler : handlers) {
    if (handler instanceof ConsoleHandler) {
        globalLogger.removeHandler(handler);
    }
}
globalLogger.addHandler(new CustomHandler());
```

The `CustomHandler` derives from `Handler` and only really "translates" the message to the format we use with stack driver. Something like : 

```java
@Override
public void publish(LogRecord record)
{
    String message = record.getMessage();
    if (record.getThrown() != null) {
        message += System.lineSeparator() + Helper.getStackTrace(record.getThrown());
    }
    LogManager.getLogger(record.getLoggerName()).log(getLog4jLevel(record), logEntry);
}
```

Probably not the cleanest solution but it does work for me because I get to keep the logging level of the messages which I definitely prefer.

Would be curious to hear about the appender solution.

This solution works for us right now, so unless there is something really wrong with it you can probably close this ticket. Thanks again !

**Comment by jabubake** [comment]
Hope this helps : https://cloud.google.com/solutions/customizing-stackdriver-logs-fluentd
