### ISSUE TITLE
FR: Expose GrpcForestoreRpc.close() via Firestore

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-cloud-java#2497]
`GrpcForestoreRpc` class has a [`close()`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/spi/v1beta1/GrpcFirestoreRpc.java#L134) method, which cleans up any allocated resources (client stubs, threads pools etc) and terminates the client. This should be exposed via `Firestore` interface so the users can gracefully terminate the client. For example:

```
Firestore fs;
try {
  fs = initMyFirestore();
  // Do stuff with fs
} finally {
  // On application shutdown or at any other suitable lifecycle handler
  fs.close();
}
```

**Comment by pongad** [comment]
Closed by #2807.
