### ISSUE TITLE
Strange subscriber behavior - long delays between message delivery

### ISSUE THREAD

**Issue by rdmoore** [GoogleCloudPlatform/google-cloud-java#2501]
I recently got back to working on a project that incorporates pub/sub that had been on the shelf for a couple of months. I switched to 0.24.0-beta of the pub/sub client and I'm now seeing strangeness on the subscriber side: my subscriber often does not receive messages (for a long time). In the most recent experiment, I published a single message and the subscribe received it 20+ minutes later. Sometime the subscriber gets messages right away; often not.

 I would expect all published messages to get delivered in a "reasonable" timeframe - when I used the old client a few months again, I receive them "promptly". Notes that may be pertinent:
* outstanding-element-count is one as the client can handle only one pub/sub message at a time
* there is currently only one subscription, with a single subscriber pulling from it (in the future there will be many)
* publishing may be infrequent - it is expected that over time, there will eventually have many messages posted regularly but for now, there will often be minutes or hours between publish events.
* it _seems_ that publishing another message (or starting another client) helps get messages delivered sooner.

The setup of the client looks like this:
```scala
    val flowControl = FlowControlSettings.newBuilder
      .setMaxOutstandingElementCount(1L)
      .setLimitExceededBehavior(LimitExceededBehavior.Block)
      .build
    val name = SubscriptionName.newBuilder().setProject(project).setSubscription(subscription).build
    Subscriber.defaultBuilder(name, receiver)
      .setExecutorProvider(pubsubThreadPool)
      .setFlowControlSettings(flowControl)
      .setCredentialsProvider(credentialProvider)
//        .setAckExpirationPadding()
//        .setMaxAckExtensionPeriod()
      .build()
```

**Comment by lukasz-szewc** [comment]
Related to #2502

**Comment by pongad** [comment]
I'm sorry I didn't see this issue. I think this is related to #2502 and #2506.

The short version is that a firewall sees an idle connection and closes it without notifying the client, so it takes the client a long time to realize the connection is bad and reconnect.

I'll close this for now as duplicate; please reopen if you think the issues are unrelated.
