### ISSUE TITLE
Latest Datastore + Pubsub clients libraries conflict

### ISSUE THREAD

**Issue by brunovieira7** [GoogleCloudPlatform/google-cloud-java#2503]
I had a project with the latest datastore client (1.7.0) and added the pubsub client (0.25.0-beta).
When I tried to publish a message, it would not publish my message and hang forever with no error

after making some tests I found out those two clients had a conflict in their dependencies.
Datastore uses **com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0** that depends on **com.google.protobuf:protobuf-java:jar:3.0.0** while PubSub uses **com.google.cloud:google-cloud-core-grpc:jar:1.7.0** that depends on **com.google.protobuf:protobuf-java:jar:3.3.1**

I made it work excluding **protobuf-java** from the datastore dependency:

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-datastore</artifactId>
            <version>1.7.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by jabubake** [comment]
@garrettjonesgoogle, @vam-google  FYI, should n't this have been caught prior ?

**Comment by vam-google** [comment]
@jabubake Yes it should have been. The problem here is that there are many various dependencies in google-cloud-java and unfortunately sometimes things like this happen. We have a task of creating BOM (bill of materials) artifact, which should fix issues like this.

**Comment by danoscarmike** [comment]
Ping @vam-google @garrettjonesgoogle have we at least fixed the pubsub/datastore conflict?

**Comment by anthmgoogle** [comment]
Classifying as P1 bug since it is at the scope of individual APIs. This seems important to fix quickly.

**Comment by danoscarmike** [comment]
@garrettjonesgoogle ping.  What's the strategy here?  do we need to update Datastore dependencies?  Or perhaps we have already?

**Comment by garrettjonesgoogle** [comment]
An update will be coming today.

**Comment by garrettjonesgoogle** [comment]
The update was merged yesterday: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2770 

We still need to publish a release to include it.

**Comment by pongad** [comment]
The release was cut yesterday and this issue should be resolved. Please reopen if you continue to see this problem with latest release.
