### ISSUE TITLE
How to support insert NULL values in bigquery.insertAll

### ISSUE THREAD

**Issue by BorisB-Tradair** [GoogleCloudPlatform/google-cloud-java#2505]
I followed the official example of [Streaming insert examples](https://cloud.google.com/bigquery/streaming-data-into-bigquery), and came across with a problem:
the _insertAll_ command, does not accept **a null value** in the Map I pass it.

**Code example:**
        Map<String, Object> rowContent = new HashMap<>();
        rowContent.put("fname","David");
        rowContent.put("lname",null); //here's the problem

        TableId tableId = TableId.of(dataSetName, tableName);
        InsertAllResponse response = bigquery.insertAll(InsertAllRequest.newBuilder(tableId)
                .addRow( rowContent)
                .build());

        // If any of the insertions failed, this lets you inspect the errors
        if (response.hasErrors()) {
            for (Map.Entry<Long, List<BigQueryError>> entry : response.getInsertErrors().entrySet()) {
                logger.error(entry.toString());
            }
        }

I investigated the libraries the code is using, and I saw there're several checks regarding NULL. 
For example:

@GwtCompatible
final class CollectPreconditions {
    CollectPreconditions() {
    }

    static void checkEntryNotNull(Object key, Object value) {
        if (key == null) {
            throw new NullPointerException("null key in entry: null=" + value);
        } else if (value == null) {
            throw new NullPointerException("null value in entry: " + key + "=null");
        }
    }
...
}

**Question:**
How/What can can I do in order to insert records, which some of the values might be NULL.
**I'm using the Java client.

**Comment by dhoard-papajohns** [comment]
Any update on this issue?  We have ETL processes that are being blocked by this issue.
