### ISSUE TITLE
Spanner: LIKE with bound parameter ignoring index

### ISSUE THREAD

**Issue by clettenberg** [GoogleCloudPlatform/google-cloud-java#2507]
I have a query that uses `LIKE` and has a bound parameter with a tailing wildcard. 

The index (IX_USERS_TYPE) has both the `TYPE` and `ADDRESS` columns. I would expect the amount of rows scanned to equal the amount of matches to the string preceding the `%`.

When I run the following query, I expect it to only scan 1 row based on the address I am using. It _actually_ does a full table scan of all 14 million rows.

```sql
SELECT S.NAME, S.EMAIL
FROM USERS@{FORCE_INDEX=IX_USERS_TYPE} S
WHERE S.TYPE='ADMIN'
AND S.ADDRESS LIKE CONCAT(@userAddress,'%')
```

When I hard code the value of *@userAddress* from the previous example directly into the SQL (instead of binding), it behaves as expected and only does an index scan of 1 row.

```sql
SELECT S.NAME, S.EMAIL
FROM USERS@{FORCE_INDEX=IX_USERS_TYPE} S
WHERE S.TYPE='ADMIN'
AND S.ADDRESS LIKE CONCAT('1234 Oak Dr','%')
```

**Comment by vkedia** [comment]
I would recommend to use `STARTS_WITH(S.ADDRESS, @userAddress)` instead of `CONCAT`. Then even with query parameters, you would see that only the matching rows are scanned and not the full table.
