### ISSUE TITLE
google-cloud-datastore Entity.isUnindexedProperty API

### ISSUE THREAD

**Issue by mihania** [GoogleCloudPlatform/google-cloud-java#2509]
In com.google.appengine.api.datastore.Entity we had an API to get whether an entity is indexed by callling com.google.appengine.api.datastore.Entity.isUnindexedProperty(String propertyName) during the read time.

Is there an API in google-cloud-datastore that provides the same capability during the read?

**Comment by sai-pullabhotla** [comment]
@mihania  - The below should work. 

```java
boolean unindexed = entity.getValue("myProperty").excludeFromIndexes();
```

**Comment by mihania** [comment]
thank you, @sai-pullabhotla! That's exactly what I needed.
