### ISSUE TITLE
Pub/Sub on failures must return `ApiException` and not `io.grpc.StatusRuntimeException`

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2512]
Currently, the following code on publishing to a non-existent topic returns `io.grpc.StatusRuntimeException` instead of an `ApiException`.
```
ApiFuture<String> future = publishMessage(publisher, "message");
ApiFutures.addCallback(future, new ApiFutureCallback<String>() {
    @Override
    public void onFailure(Throwable throwable) {
        if (throwable instanceof ApiException) {
         ApiException apiException = (ApiException) throwable;
         System.out.println("Error publishing message : " + apiException.getStatusCode());
       }
   }

   @Override
   public void onSuccess(String s) {
       System.out.println("Message published with ID : " + s);
   }
 });
```

**Comment by garrettjonesgoogle** [comment]
This needs to be fixed before GA. BTW, switching to the GAPIC client would fix this.

**Comment by jabubake** [comment]
What do you mean switching to GAPIC clients though ?
I thought the `Publisher` / `Subscriber` is what we expect users to always use to publish / subscribe ?

**Comment by garrettjonesgoogle** [comment]
I mean using the GAPIC client in the implementation instead of the generated grpc stub.

**Comment by jabubake** [comment]
Closing, realized the issue I wanted to file is related but is a GAX bug.
