### ISSUE TITLE
API report for Google Cloud Storage

### ISSUE THREAD

**Issue by lvc** [GoogleCloudPlatform/google-cloud-java#2514]
Hi,

Here is the report on API changes and backward binary compatibility for the Google Cloud Storage library: https://abi-laboratory.pro/java/tracker/timeline/google-cloud-storage/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars at http://central.maven.org/maven2/com/google/cloud/google-cloud-storage/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library. Feel free to request other Google Cloud modules to be included to the tracker if you are interested.

Thank you.

![google-cloud-storage-1](https://user-images.githubusercontent.com/1517837/31481172-aa9e2588-af2a-11e7-9e19-26454b912db4.png)

**Comment by jabubake** [comment]
@frankyn FYI

**Comment by garrettjonesgoogle** [comment]
No need to keep this open.
