### ISSUE TITLE
Method for assigning custom metadata missing

### ISSUE THREAD

**Issue by PRMEDIASTORE** [GoogleCloudPlatform/google-cloud-java#2517]
I'm trying to pass custom metadata like uid ('x-goog-meta-uid') in the header, but I can't find an option to sign the url with this additional piece of information. Is this available on the java library? I've got below so far..  

URL uploadUrl = storage.signUrl(
                blobInfo,
                5,
                TimeUnit.MINUTES,
                Storage.SignUrlOption.httpMethod(HttpMethod.PUT),
                Storage.SignUrlOption.withContentType());

**Comment by neozwu** [comment]
@PRMEDIASTORE It seems to me client library in this repo does not support signing url with header yet. However, you maybe able to use `ServiceAccountCredentials.sign()` to sign a "signature string", then base64 encode the string and assemble the URL.  Here's reference: https://cloud.google.com/storage/docs/access-control/create-signed-urls-program

**Comment by PRMEDIASTORE** [comment]
@neozwu you're right - someone else found the same issue, and have submitted a PR for this. 
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2000

**Comment by hzyi-google** [comment]
Close this issue since #2000 is fixed.
