### ISSUE TITLE
com.google.cloud.RetryParams not found in google-cloud-core jar

### ISSUE THREAD

**Issue by jmtiong** [GoogleCloudPlatform/google-cloud-java#2520]
Hi! I am trying to implement my own `RetryParams` to alter the maximum number of reattempts made by my storage service. However, I could not import `RetryParams` and it could not be found anywhere even though it is stated in the docs, [RetryParams](http://googlecloudplatform.github.io/google-cloud-java/0.7.0/apidocs/com/google/cloud/RetryParams.html). 

Am I missing something or am I implementing the whole thing wrongly?

This is my code snippet:
```
storage = StorageOptions.newBuilder()
                .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream(credentialsPath)))
                .setRetryParams(RetryParams.newBuilder().retryMaxAttempts(3).build())
                .build()
                .getService();
```

**Comment by neozwu** [comment]
hi @jmtiong `RetryParams` has been renamed to `RetrySettings`. The method is here: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L212
