### ISSUE TITLE
Provide libraries compatible with 'io.netty:netty-tcnative-boringssl-static:2.0.6.Final'

### ISSUE THREAD

**Issue by tafypz** [GoogleCloudPlatform/google-cloud-java#2528]
Spring Boot as of version 2.0.0.M4 is not compatible with ```io.netty:netty-tcnative-boringssl-static:1.1.33.Fork26``` it requires ```io.netty:netty-tcnative-boringssl-static:2.0.6.Final``` especially for the reactive spring-boot-starter-webflux package. This causes google java api to not be usable with the newest version of spring boot.
It would be great if you could either shade the dependency on ```1.1.33.Fork26``` or upgrade to the ```2.0.6.Final```.

**Comment by vam-google** [comment]
All newer versions of google-cloud java are configured to work with `netty-tcnative-boringssl-static:2.0.3.Final`. 

1) Which version of google-cloud-java are you using? Doesn't the newest (`> 0.25.0`) work for you? 
2) Does the minor version difference between 2.0.3.Fork and 2.0.6.Fork break it for you?
3) Do you still have `1.1.33.Fork26` in your dependency tree even when you use the newest `google-cloud-jav`a library i your project?

**Comment by garrettjonesgoogle** [comment]
We bumped netty-tcnative-boringssl-static to 2.0.6.Final in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2549 , which will be included in the next release. Closing this issue.
