### ISSUE TITLE
Large number of duplicate messages when small delay is added before message ack

### ISSUE THREAD

**Issue by atilelliCSS** [GoogleCloudPlatform/google-cloud-java#2534]
The customer is experiencing a large number of duplicate messages from pubsub when adding a delay before the `consumer.ack` The customer supplies code with sleep thread to simulate process on the process on a message before ack. This sleep time is below the ack timeout threshold for messages, However there is still a large number of duplicate messages. 

-> In the back end charts, it shows a large spike in ModifyAckDeadlineRequest in the customer's project.  I saw about 238k  ModifyAckDeadlineRequest[1] at peak and  about 30-40k messages successes. 

https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.ModifyAckDeadlineRequest.description

Log/Graph data: Customer numbers:
  Total consumed:
  126709
  Unique messages:
  30000

My tests:
1
)~~~
Total consumed:
75294
Unique messages:
30000
~~~
2)
~~~
Total consumed:
142131
Unique messages:
30000
~~~
3)
~~~
Total consumed:
55764
Unique messages:
30000
~~~

Reproduction steps: 1) Create topic and subscription in your project 
2) Modify Consume.java to your project and subscription (line 13 and 14)
3) Modify Publish.java to your project and topic  (line 12)
4) run "run.sh" 
 See the large number of duplicates 
5) REMOVE Lines 27 to 33 
 There are significantly fewer duplications

[pubsub-explosion-master.zip](https://github.com/GoogleCloudPlatform/google-cloud-java/files/1396154/pubsub-explosion-master.zip)

Internal tracking error is bug 67854080

**Comment by pongad** [comment]
This is a known issue. See #2534. I'll close this as duplicate. Please reopen if you believe it is a separate issue.
