### ISSUE TITLE
What is the rate limiting on Cloud Monitoring calls

### ISSUE THREAD

**Issue by ardias** [GoogleCloudPlatform/google-cloud-java#2536]
Hi,
I haven't been able to find in the documentation what is the current rate limit, in calls/sec, for calls to cloud monitoring, specifically to "listTimeseries". Also, i haven't been able to see waht is the current limit for returned data for this same call.

Any pointers would be really appreciated!

**Comment by vam-google** [comment]
I believe things like this are configurable by quotas. In your https://console.cloud.google.com go to `IAM & Admin -> Quotas`, then search for "Monitoring" in the list of APIs. There you should be able to edit your quota and see the maximum possible quota.

**Comment by garrettjonesgoogle** [comment]
@ardias did that help?

**Comment by ardias** [comment]
Yes it did @garrettjonesgoogle , thank you.

**Comment by garrettjonesgoogle** [comment]
Great to hear!
