### ISSUE TITLE
Google Cloud Logging PERMISSION_DENIED when running in docker

### ISSUE THREAD

**Issue by gridcellcoder** [GoogleCloudPlatform/google-cloud-java#2537]
I have an application that uses cloud logging

   ```java
logger = LoggingOptions.newBuilder().setCredentials(
                ServiceAccountCredentials.fromStream(new FileInputStream(EnvUtils.getString(EnvUtils.GOOGLE_APPLICATION_CREDENTIALS)))
        ).build().getService();
```

using
```xml
<dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-core-grpc</artifactId>
        <version>${gcp.version}</version>
    </dependency>
<dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-core</artifactId>
        <version>${gcp.version}</version>
    </dependency>
```

where ${gcp.version} =1.7.0

When I run this Java application from command line, maven logger works fine and I can see the output in cloud logging.

When I run this in gitlab-ci or docker I get:  Caused by: 

```console
 com.google.cloud.logging.LoggingException:io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
    at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:162)
    at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:156)
    at com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction.apply(ApiFutures.java:140)
    at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:205)
    at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:193)
    at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:132)
```

I am quadruple sure (using lots of debugging and printing) that the logger is being initiated with a service account json file that has permissions works in command line, maven but not in docker/gitlab-ci.

Is this a docker specific issue with grpc or something else? The docker image does not have default credentials or use glcoud cli installed.

**Comment by vam-google** [comment]
Hi @gridcellcoder,

There should be no any problems with running `google-cloud-java` from docker image (should work even better than without it, as a docker image is usually a clean environment where less thing can go wrong). 

1) Are you talking about running in a docker in general or in a specific docker image? 
2) I see you are using `GOOGLE_APPLICATION_CREDENTIALS` env variable to access your `key.json` file, but at the same time you are reading it manually (i.e. combining 2 approaches in one). You usually want to have either just `GOOGLE_APPLICATION_CREDENTIALS` pointing to a correct key.json **OR** specify it manually via `setCredentials()`.
3) Does any other google-cloud-java client work in your setup? (for example Storage, which does not use grpc at all; it should be enabled first)
4) Can you please confirm that:
- you are using a service account which has proper role (the `Owner` role should allow full access).
- created a new JSON key for exactly that service account, included it int your docker image and set path to it in GOOGLE_APPLICATION_CREDENTIALS (in your docker image as well).

In general, you should be able to do anything you can do on your machine within a docker image (including installing gcloud, maven and running that like on your machine but within a docker image).

**Comment by saicheems** [comment]
Please reopen if the above comment didn't provide enough information.

**Comment by averikitsch** [comment]
The service account of the Google Cloud service (for example Cloud Run) needs to be updated to have role `Logs Writer`,`roles/logging.logWriter`.
