### ISSUE TITLE
Spanner java client + service account without write permission causes high error rate (403)

### ISSUE THREAD

**Issue by maxqch** [GoogleCloudPlatform/google-cloud-java#2540]
Steps to reproduce:

1. Create a service account without write permission.
2. Initialize an instance of DatabaseClient with default options and credentials from above.
3. Check the API dashboard (console.cloud.google.com/apis/dashboard), there will be a bunch of 403 errors.

I dug into this a bit and found out that it is due to the default settings of 

    com.google.cloud.spanner.SessionPoolOptions 

Which sets write session fraction to 0.2. These sessions will repeatedly try to make begin transaction API calls but fail since the service account does not have permission.

**Comment by vkedia** [comment]
Closing this in favor of #2624
