### ISSUE TITLE
Java 9 - protobuf-java 3.0.0 warnings

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2545]
In running something with latest Datastore client, I see the following:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/lesv/.m2/repository/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by lesv** [comment]
https://github.com/google/protobuf/issues/3781

**Comment by lesv** [comment]
Note the current version of java protobuf appears to be 3.4.1 so com.google.cloud should update

**Comment by lesv** [comment]
Actually it appears that veneer is using 3.3.1

**Comment by vam-google** [comment]
@lesv can you please clarify if this issue is reproducible with 3.3.1 or only with 3.0.0?

**Comment by garrettjonesgoogle** [comment]
Since this is just a warning message, and one that is emitted by a dependency of ours, and they already have a tracking issue, I am going to close out the present issue.

**Comment by ludoch** [comment]
This is not a good reason to close the bug... People are now adopting Java11, and Google libraries should not have warnings worrying folks.

**Comment by sduskis** [comment]
@ludoch, I beg to differ.  it's a great reason to close THIS bug. The right people are looking at the issue.  There's nothing we can do here, and the right people are looking at it.  Please feel free to follow up on protocolbuffers/protobuf#3781.
