### ISSUE TITLE
Add static analysis to find bugs sooner

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/google-cloud-java#2546]
Static analysis tools enable finding and avoiding bugs at compile time, before they become issues at runtime, and become much harder (and hence, costlier) to find and fix.

There are tools that can be run offline, such as SpotBugs (successor to FindBugs) and [ErrorProne](http://errorprone.info/), or via online services such as [Coverity](https://scan.coverity.com/) (free for open-source projects). Wikipedia has a [list static analysis tools for Java](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#Java).

FWIW, we've integrated Coverity scans into JanusGraph builds, though ended up not using the Travis CI integration with Coverity; here is how it was done:

* [`.travis.yml`](https://github.com/JanusGraph/janusgraph/blob/master/.travis.yml)
* [analysis script and Dockerfile](https://github.com/JanusGraph/janusgraph/tree/master/analysis) referenced in `.travis.yml` — note that CentOS appears to behave differently from Ubuntu for Coverity

I'm happy to add Coverity support for this repo, if there's interest and support (please vote with 👍 / 👎).

Thoughts?

**Comment by vam-google** [comment]
I think adding static analysis tools will be beneficial for us, but It doesn't look like we have enough resources to add that and fix all the found issues after that right now. If we choose to add them, the same set of tools and rules should be applied to [gax-java](https://github.com/vam-google/gax-java) repo too.

@garrettjonesgoogle what is your opinion about it?

**Comment by garrettjonesgoogle** [comment]
We already use Codacy which reports problems on PRs, so we at least have some coverage already. I think we can wait to add more

**Comment by hzyi-google** [comment]
Move this issue to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
