### ISSUE TITLE
Entities.getVersionProperty API?

### ISSUE THREAD

**Issue by mihania** [GoogleCloudPlatform/google-cloud-java#2551]
In Google App Engine Datastore we had an API to retrieve Entity version, using Entities.getVersionProperty(). Do we have the same API in Google Cloud Datastore or it is missing in current implementation?

**Comment by neozwu** [comment]
To my knowledge, we don't have an API to expose version number. Google Cloud Datastore [documentation](https://cloud.google.com/datastore/docs/concepts/metadataqueries) doesn't mention this, while the AppEngine Datastore [doc](https://cloud.google.com/appengine/docs/standard/java/datastore/metadataqueries) does.

/cc @lesv

**Comment by mihania** [comment]
Thank you, @lesv!

**Comment by lesv** [comment]
@wsh PTAL

**Comment by wsh** [comment]
We do supply this information in the API: https://cloud.google.com/datastore/docs/reference/rest/v1/EntityResult. Our low-level client provides it in the `LookupResponse`, but [DatastoreImpl.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreImpl.java#L288) here in `google-cloud-java` doesn't retain it so far as I can tell.

**Comment by lesv** [comment]
@garrettjonesgoogle FYI

**Comment by garrettjonesgoogle** [comment]
@mihania is this simply a question about what is supported, or do you want to turn this into a request to add the feature?

**Comment by garrettjonesgoogle** [comment]
Closing this out given we have no response. Feel free to re-open if you would like us to take a look again.
