### ISSUE TITLE
BigQuery Java API: Converter for json/avro schema

### ISSUE THREAD

**Issue by lwiddershoven** [GoogleCloudPlatform/google-cloud-java#2553]
When creating a BigQuery schema, it would be really nice to create a BigQuery schema from an avro schema, or json schema. 

The command line tool seems to allow this; and the load command probably loads the schema from the avro file, and having this logic as a support class in the java api would add a lot of value.

Because honestly, I have an industry-standard schema. I don't really want to hand-code that same schema for BigQuery and I most certainly don't want to rely on manual load actions to initialise a schema.

My use case is more of a replication system. BigQuery is just one of the sinks.
I get my messages from Kafka, and can read them as byte[]. I also have the avro.Schema.
Ideally I would just give my bytes and the schema to BigQuery (the BigQuery client lib) and let that do the generic lifting.

**Comment by NicolaSpreafico** [comment]
While the question seems to be unchanged since 27 Oct, I wrote a custom deserializer which allow to deserialize a json schema to` com.google.cloud.bigquery.Schema` object

You can find the source here
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2753

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.

**Comment by dht7** [comment]
I wrote a utility for Avro schema to be converted in BQ schema (although not extensive, but should be helpful 😅)
[https://github.com/dht7/avro-to-bq-schema-converter](https://github.com/dht7/avro-to-bq-schema-converter)
