### ISSUE TITLE
Proposal to minimize Dependency Conflicts

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-java#2555]
Many customers are running into [dependency conflicts](https://stackoverflow.com/questions/33907162/systematic-approach-with-maven-to-deal-with-dependency-hell) using the Java google-cloud (an umbrella package that includes many other artifacts), several of our google-cloud-* artifacts together, and using the google-cloud-* artifacts with other non google-cloud, google artifacts like GoogleCloudPlatform/google-cloud-datastore .  This leads to the [Maven Dependency](https://stackoverflow.com/questions/7175398/maven-dependency-resolution-conflicted) [issues](http://www.eharmony.com/engineering/maven-dependency-wrangling).

The common java solution of creating a [BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies) ([SpringBoot](https://spring.io/blog/2016/04/13/overriding-dependency-versions-with-spring-boot)) ([SpringBoot Gradle](https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle)) and using the [maven-enforcer-plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/) doesn't work when there are artifacts that aren't well behaved (same JAR, but substantially different method signatures and behaviors) like [Netty](https://netty.io/) (See #2398 ) included in the mix.  Our customers are running into situations where they are combining our artifacts with those of slower moving open source projects and things are breaking in very unexpected ways. 

Additionally, customers appear to be confused by google-cloud as it's marked as alpha, even though it brings in some "GA" artifacts.

@ludoch has proposed (and I agree):

1. We have three Uber JAR's that we release GA, BETA, and ALPHA (Beta & Alpha can depend on GA)
2. We [shade](https://maven.apache.org/plugins/maven-shade-plugin/) w/ illegal class names so that IDE's will not auto complete.
3. We then run [ProGuard](https://www.guardsquare.com/en/proguard) to [shrink](https://developer.android.com/studio/build/shrink-code.html) these JAR's.
4. The individual product JAR's should also be done this way.
5. We should still publish non-shaded / non-ProGuarded artifacts for those who need them.

### Drawbacks
1. Larger JAR's
Better reliability will more than offset the issues with additional size.
2. Singleton's are no longer pure. (ie some resources might not be properly guarded)
We should be able to figure this out for libraries.
3. Debugging becomes harder
(We should publish enough info to figure this out)

### Benefits
1. We will only expose our public Classes and Methods.  Our dependencies stay out of the mix.
2. Less customer confusion.

Of course, all we are doing is trying to solve a problem that Java 9 modules also attempts to solve, but our JAR's can't wait for our customers to all get to Java 9.

**Comment by lesv** [comment]
@ludoch @jabubake FYI

**Comment by janedegtiareva** [comment]
Do we know how much larger the JARs will become? Also it would be good to have more details about the extra debugging complexity. Thank you!

**Comment by lesv** [comment]
The total size would be less than you current use (that's one of the gifts of Proguard), but if your app includes the same jar, it will be there twice.  This is only for an additional kind of jar that we publish, so you would still be able to use the current jar's.

For debugging, this will be similar to what users do on [android](https://developer.android.com/studio/build/shrink-code.html) [debugging](https://stackoverflow.com/questions/3913338/how-to-debug-with-obfuscated-with-proguard-applications-on-android).

**Comment by hzyi-google** [comment]
Move this issue to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can still be used for discussion.

**Comment by garrettjonesgoogle** [comment]
There is a potential for this creating new problems, and maybe even more problems than it solves. If a user somehow includes a package from anywhere that pulls in one of the jars from the non-uber-jarred version, there will be version problems, similar to the guava vs guava_jdk5 nightmare we have right now. Types from the following packages (at a minimum) are exposed on the surface of google-cloud-java and can't be hidden away:

- api-common-java
- proto-cloud-*
- grpc-cloud-*
- gax-java
- google-cloud-core*
