### ISSUE TITLE
FireStore Realtime functionality

### ISSUE THREAD

**Issue by Klabauterman** [GoogleCloudPlatform/google-cloud-java#2577]
I would like to know if there is FireStore realtime functionality like in the android SDK is planned. The old firebase admin SDK had it.

Thanks in advance.

**Comment by Mistic92** [comment]
Firestore is not realtime database. You can still use realtime database and firestore.

**Comment by Klabauterman** [comment]
But the Firestore client-SDKs for web, android and ios support data listeners: https://firebase.google.com/docs/firestore/query-data/listen

**Comment by anthmgoogle** [comment]
We will confirm with the Firestore product team. Taking this until I find the right contact.

**Comment by schmidt-sebastian** [comment]
This is on the roadmap for the rest of the Server SDKs. It's already available in Node. Stay tuned!

**Comment by Klabauterman** [comment]
Cool, thanks 👍

**Comment by mataide** [comment]
Hey guys, probably not the best place to ask, but I am also trying to implement listen in a Java Project. I am trying to set this up with REST API. Does anyone knows a valid object for it?

I just tried:

```
{
 "addTarget": {
  "targetId": "alovelace",
  "once": false,
  "documents": {
   "documents": [
    "room"
   ]
  },
  "query": {
   "structuredQuery": {
    "from": [
     {
      "collectionId": "room"
     }
    ]
   }
  }
 }
}
```
Whenever I try, always get:

```
{
 "0": {
  "error": {
   "code": 400,
   "message": "Invalid value (Object), ",
   "status": "INVALID_ARGUMENT",
   "details": [
    {
     "@type": "type.googleapis.com/google.rpc.BadRequest",
     "fieldViolations": [
      {
       "description": "Invalid value (Object), "
      }
     ]
    }
   ]
  }
 }
}
```

**Comment by schmidt-sebastian** [comment]
Please take a look at the Node API and turn on logging to see a dump of the request trace:

```
Firestore.setLogFunction(console.log)
```

That might help you.

**Comment by mataide** [comment]
The documentation still not yet updated. https://firebase.google.com/docs/firestore/query-data/listen
Have anyone tried how to implement this?
