### ISSUE TITLE
google-cloud-firestore Extension point to serialize pojo to map

### ISSUE THREAD

**Issue by kamaz** [GoogleCloudPlatform/google-cloud-java#2579]
Converting custom types like BigDecimal fail with error:

`Cannot convert 12.0099999999999997868371792719699442386627197265625 to Firestore Value`

Looking through the code couldn't find a way how I could add a custom converter that would allow anyone to do conversion before serialization without creating additional layer that is specific to firestore.

It would be great if one of following could be provided to add ability to apply custom coversions:

- inject a whole new class mapper (instead of using ***CustomClassMapper***) - but that could potentially be a big ask 
- have a converter annotation similar to `@Exclude`, `@PropertyName` that would enable to add converter to ***CustomClassMapper***
- alternatives?

**Comment by anthmgoogle** [comment]
We will first confirm whether there is an existing way to do this so making it a question. If there is no current way to do this, we will convert to feature request.

**Comment by schmidt-sebastian** [comment]
This is currently not possible. We will bring this up for discussion internally.

**Comment by schmidt-sebastian** [comment]
As per our internal discussion, we are not treating this as high priority item for now and suggest that you implement your own serialization at the POJO level. If you give us a Map that has BigDecimals already serialized to a String, you will be able to store these objects in Firestore.

**Comment by hienle-hps** [comment]
Sorry to resurrect an old thread, the [POJO to Map recommendation](https://github.com/googleapis/google-cloud-java/issues/2579#issuecomment-344772745) seems reasonable but leaves questions around de-serialization.

@schmidt-sebastian can you share any details from the internal discussions? Specifically regarding `CustomClassMapper` whose `BeanMapper` and `mapper` registry already seem suitable for user-extension.  Were there concerns about bloating the main Firestore library with a complex ORM API?
