### ISSUE TITLE
Add Automatic-Module-Name to JAR MANIFEST.MF

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2586]
Configure JAR plugin to add Automatic-Module-Name for our JAR distributions. Each artifact should have its own module name.

**Comment by anthmgoogle** [comment]
This seems like a repo-wide infrastructure question. @saturnism @lesv @garrettjonesgoogle can you determine feasibility of this suggestion, and if feasible we can turn this into a feature request or cleanup item.

**Comment by lesv** [comment]
This is a Java 9 FR.  It's a common request: grpc/grpc-java#3523, grpc/grpc-java#3522, square/ok-http#3655

It should be trivial to do, see https://github.com/google/guava/commit/f2be0be06ef49dee7c5dfcb3a0231c5ecaf5b621#diff-e407b6f223ee6c04116a91ead9f5e100R42 for an example.

**Comment by hzyi-google** [comment]
Move this issue to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can still be used for discussion.
