### ISSUE TITLE
Include stack trace in logged text

### ISSUE THREAD

**Issue by HunterSherms** [GoogleCloudPlatform/google-cloud-java#2587]
I would like to include the stack trace from ERROR level logs in my logs sent back to StackDriver. How would I implement this?

**Comment by anthmgoogle** [comment]
@lesv @saicheems can you answer whether there is a way to do this currently. If new functionality is required, please convert to type: feature request.

**Comment by lesv** [comment]
It should do this now if you are using one of our adapters.  @jabubake Should be able to elaborate as I'm OoO til Dec.

**Comment by int08h** [comment]
See also #2735

**Comment by pongad** [comment]
I believe this is duplicate of #2735 like @int08h said. IIUC, the "standard" google-cloud-logging does not have this issue. I'll close as duplicate, but please reopen if I misunderstand.
