### ISSUE TITLE
com.google.cloud.firestore.FieldPath is not public

### ISSUE THREAD

**Issue by BlueRiverInteractive** [GoogleCloudPlatform/google-cloud-java#2594]
The FieldPath class is used in many methods of the Firestore API especially in Query, however the class is not public. I assume this is a bug because essentially all these methods requiring a FieldPath cannot be used outside of the com.google.cloud.firestore package.

**Comment by anthmgoogle** [comment]
Thank you. We will evaluate this in our next round of feature planning.
