### ISSUE TITLE
TraceServiceSettings.Builder not very idiomatic

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#2610]
I'm having to do this weird cast, which should be avoidable:

```
TraceServiceClient.create(
	((TraceServiceSettings.Builder) TraceServiceSettings.newBuilder()
	.setCredentialsProvider(
		StackdriverTraceAutoConfiguration.this.finalCredentialsProvider)
	.setExecutorProvider(executorProvider))
	.build())
```

Notice the `(TraceServiceSettings.Builder)` cast, because `setExecutorProvider()` is inherited from the abstract `ClientSettings` and should probably be overwritten to return a `TraceServiceSettings.Builder`.

**Comment by garrettjonesgoogle** [comment]
What version of Java are you using?

**Comment by joaoandremartins** [comment]
Was using jdk1.8.0_121, though seeing the same thing with jdk1.8.0_151.

**Comment by garrettjonesgoogle** [comment]
Also what version of gax are you using?

**Comment by joaoandremartins** [comment]
Apologies, user error. `gax` version was being set to 1.8.1 where it shouldn't.
