### ISSUE TITLE
Add Storage.create() method which takes a restartable input stream

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2620]
In https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2359 , retries had to be turned off for `Blob create(BlobInfo blobInfo, InputStream content, BlobWriteOption... options)` because the `InputStream` can only be consumed once.

We should create a new abstraction named `RetryableInputStream` which can produce a new input stream on the original content, and add a new create method which accepts it, so that it is easier for users to create blobs without loading the entire content into memory.

**Comment by hzyi-google** [comment]
Move to backlog.
