### ISSUE TITLE
Update docs to  0.28.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#2623]
At least some of the javadocs are still on 0.26.0. e.g.

https://googlecloudplatform.github.io/google-cloud-java/0.26.0/apidocs/?com/google/cloud/resourcemanager/package-summary.html

**Comment by michaelbausor** [comment]
There is also a 0.29.0 version of this doc: [https://googlecloudplatform.github.io/google-cloud-java/0.26.0/apidocs/?com/google/cloud/resourcemanager/package-summary.html](https://googlecloudplatform.github.io/google-cloud-java/0.29.0/apidocs/?com/google/cloud/resourcemanager/package-summary.html)

Are we linking to outdated docs from somewhere? https://googlecloudplatform.github.io/google-cloud-java redirects to the correct https://googlecloudplatform.github.io/google-cloud-java/0.29.0/index.html

**Comment by elharo** [comment]
I certainly landed in them somehow. Let me see if I can reproduce exactly how.

**Comment by michaelbausor** [comment]
@elharo I am going to close this for now - please reopen if you find how you landed on the outdated docs. Thanks!
