### ISSUE TITLE
Implement auto tuning of writeSessionFraction in Cloud Spanner Client

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-java#2624]
Currently in `SessionPoolOptions` users can specify what proportion of sessions they want to be pre warmed for read write transactions. It defaults to 0.2 which causes #2540  where the client does not have permissions to write to the database thus causing all the pre warming rpcs to fail.
Also it might not be obvious to users that they can tune this parameter to achieve better performance and default of 0.2 might not be best for everyone. 
To solve this, we should implement auto tuning of this parameter in the client. We can keep track of what proportions of transactions were read write transactions over some window and use that to tune this parameter. We can continuously update this as the usage pattern changes over the lifetime of a client.
We can expose a new option to turn this feature on/off.
cc @tomayles

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. @vkedia I'm not sure if you are working on this but if you are feel free to reopen.
