### ISSUE TITLE
build failed  after adding google cloud dependency 

### ISSUE THREAD

**Issue by rahuldevanavar91** [GoogleCloudPlatform/google-cloud-java#2654]
Hi 
 I am added google cloud  dependency by
```
 implementation ('com.google.cloud:google-cloud-storage:1.12.0'){
        exclude group: 'com.google.guava'
    }
```

but my build is failed with the following error 

Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - auto-value-1.2.jar (com.google.auto.value:auto-value:1.2)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  

> tried by disabling annotation processor

```
packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/project.properties'
    }

.................
.........

javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath false
            }
        }
........................
```

I am getting following error
 More than one file was found with OS independent path 'project.properties'

**Comment by andreamlin** [comment]
Hi rahuldevanavar91,

Which dependency management system is this? Why is guava being excluded from the google-cloud-storage dependency?

**Comment by rahuldevanavar91** [comment]
I am using google  dependency management .
I excluded guava because I am not using it.

**Comment by andreamlin** [comment]
Would you mind posting your BUILD file, pom.xml, .gradle, or whichever config file that lists your dependencies?

**Comment by pongad** [comment]
I'll close this since it has not been updated for a while. Please reopen if required.
