### ISSUE TITLE
Missing method AIRequest.setcontexts in version 2

### ISSUE THREAD

**Issue by avallfox** [GoogleCloudPlatform/google-cloud-java#2655]
Actually, i am using the V1 Dialogflow Client Java SDK.
<dependency>
    <groupId>ai.api</groupId>
    <artifactId>libai</artifactId>
    <version>1.6.12</version>
</dependency>

In the current stable version (1.6.12) we have the possibility to set the Contexts before the query is sent to the server, using the method:

**AIRequest setContexts(List\<AIContext\> contexts)**

This is usefull because we can set (prepare) the status of the dialogflow (chatbot).
How can i do the same with the new V2 DialogFlow Beta version?
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-dialogflow</artifactId>
    <version>0.29.0-alpha</version>
</dependency>

The samples for the new version are here https://github.com/dialogflow/dialogflow-java-client-v2 but i dont find the way to do that using the new library java version (2).

Is in the roadmap ?

**Comment by pongad** [comment]
@wsh Can you help?

**Comment by wsh** [comment]
No? What does this have to do with Datastore?

**Comment by pongad** [comment]
@wsh Sorry for the noise. I must have had too much coffee.

@avallfox I believe the contexts have been moved under "query parameters".  For example, [`DetectQueryIntent`](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2beta1#google.cloud.dialogflow.v2beta1.DetectIntentRequest) has [`QueryParameters`](https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2beta1#google.cloud.dialogflow.v2beta1.QueryParameters) which has `Context`s. Does this help you at all? 

The v1-v2 comparison [page](https://dialogflow.com/docs/reference/v2-comparison) might also help

**Comment by pongad** [comment]
Due to age, I'll close this for now. But please reopen if you still have questions.
