### ISSUE TITLE
CSS Issue on github.io page header element

### ISSUE THREAD

**Issue by HighNoonSolutions** [GoogleCloudPlatform/google-cloud-java#2663]
![screen shot 2017-11-26 at 6 20 01 pm](https://user-images.githubusercontent.com/5672035/33247948-b44db024-d2d6-11e7-89eb-db4c3f79a582.png)

The QuickStart code on the right pushes the content further than the other runtime languages.

Can be fixed with the following css rule change.

`@media only screen and (min-width: 60em)
site.css:1148
.col {
    width: 48%;
}`

**Comment by pongad** [comment]
@jabubake I don't see this behavior on my side. Was this issue already fixed?

**Comment by jabubake** [comment]
I am seeing this, it looks like the page is loading an un-safe script as per Chrome. It renders correctly once enabled

**Comment by vchudnov-g** [comment]
@lesv could you fix this CSS or route to the appropriate person? Thanks!

**Comment by lesv** [comment]
I fixed the css, will look for the script.
