### ISSUE TITLE
Provide Storage.BlobListOption.defaultInstance() method for idiomatically listing every item in a GCS bucket

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#2667]
I want to list every object in a bucket and add it to a list.

I want to use code similar to this:

```
		Storage.BlobListOption blobListOption = null;

		do {
			page = this.gcs.list(path, blobListOption);
			for (BlobInfo blob : page.getValues()) {
				blobs.add(blob);
			}
			blobListOption = Storage.BlobListOption.pageToken(page.getNextPageToken());
		} while (page.hasNextPage());
```

This code blows up with an NPE as expected. In order to make it work, I either need to duplicate the logic inside the while loop to get the first page with a `this.gcs.list(path)` call, or add a bogus `Storage.BlobListOption`, like `Storage.BlobListOption.pageSize(50)` instead of `null` at the beginning.

To support cases like this, there should be a `Storage.BlobListOption` factory for an empty `Storage.BlobListOption`.

Unless I'm missing anything?

**Comment by hzyi-google** [comment]
@joaoandremartins There is an example in `Storage.java` regarding listing all the blobs in a bucket using `Iterator`:
```
String bucketName = "my_unique_bucket";
Page<Blob> blobs = storage.list(bucketName); // Optional options can be passed in as well
Iterator<Blob> blobIterator = blobs.iterateAll();
while (blobIterator.hasNext()) {
    Blob blob = blobIterator.next();
    // do something with the blob
}
```
Please feel free to reply if this does not work for you.

**Comment by hzyi-google** [comment]
Close it for name. Feel free to reopen.

**Comment by joaoandremartins** [comment]
Thanks a lot for the response.

Yes, that should work for us, although I think we should also support `do ... while` semantics to page through all the results with the default `BlobListOption`.

Also, `Page<T>` implementing an `iterateAll()` method that iterates over elements that aren't in that page sounds like a counter-pattern and isn't very intuitive...

**Comment by pongad** [comment]
@joaoandremartins The `iterateAll` method exists kind of as a concession to practicality. Many times we don't care that the results are in multiple pages.

Note that you can also use Guava: `Lists.newArrayList(blobs.iterateAll())`

I'm not sure what problem you're trying to solve that the current surface isn't providing. If you really want to control the paging, it's also possible to
```java
Page<Blob> page = foo();
while (page != null) {
  doThingsWith(page.getValues());
  page = page.getNextPage();
}
```
`getNextPage` returns null if there's no more items to iterate over.
