### ISSUE TITLE
Pub/Sub: synchronous pull "Received data on closed stream"

### ISSUE THREAD

**Issue by dhoard-papajohns** [GoogleCloudPlatform/google-cloud-java#2668]
I'm using the solution for Issue https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1661 to pull a batch of messages to process asynchronously.

I cannot use the recommended class `Subscriber` due to the fact that I need to process / ack messages asynchronously (producer / consumer scenario ... consumer processes, then acks the messages.)

Using `GrpcSubscriberStub` I get random batches of the following logging `INFO` messages ...

```2017-11-30 05:43:51,513 [grpc-default-worker-ELG-2-2] INFO  i.g.internal.AbstractClientStream - Received data on closed stream
2017-11-30 05:43:51,545 [grpc-default-worker-ELG-2-2] INFO  i.g.internal.AbstractClientStream - Received data on closed stream
2017-11-30 05:43:51,557 [grpc-default-worker-ELG-2-2] INFO  i.g.internal.AbstractClientStream - Received data on closed stream
2017-11-30 05:43:51,573 [grpc-default-worker-ELG-2-2] INFO  i.g.internal.AbstractClientStream - Received data on closed stream
2017-11-30 05:43:51,593 [grpc-default-worker-ELG-2-2] INFO  i.g.internal.AbstractClientStream - Received data on closed stream```

**Comment by vchudnov-g** [comment]
We will look into this and get back to you, @dhoard-papajohns

**Comment by pongad** [comment]
I believe this is almost certainly a problem with gRPC, not the client. I see you have already created https://github.com/grpc/grpc-java/issues/3810. I've pinged gRPC asking them to take a look.

In case this is actually a client problem, let's keep this open a little while longer.

**Comment by pongad** [comment]
Due to both age and the fact that this is almost definitely a GRPC problem, I'll close this for now. Please reopen if required.

**Comment by techodepot** [comment]
@pongad Can we reopen this. We are consistently experiencing this issue.

```io.grpc.internal.AbstractClientStream : Received data on closed stream```

We are trying to pull at a rate of 50 messages per second and we process all messages in approximately 20ms. We are seeing a pile up of undelivered messages and our stackdriver pull rate is only showing 0.015 per second

**Comment by ajaaym** [comment]
@techodepot can you please create new issue with full repro?

**Comment by Liron24** [comment]
What is the status of this? I'm experiencing the same exact issue described above
