### ISSUE TITLE
Google Cloud Container Library

### ISSUE THREAD

**Issue by fkorotkov** [GoogleCloudPlatform/google-cloud-java#2670]
It will be nice to have a google cloud library to work with GKE APIs e.g. `google-cloud-container`.

My use case is to write some custom automation for managing clusters. Methods like [get-credentials](https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials) and others can be handy.

**Comment by andreamlin** [comment]
Hi,

A google-cloud-container library is indeed in the works, perhaps to be released by the end of this quarter. Please standby! :D

**Comment by fkorotkov** [comment]
Awesome news!

For future researchers: old `com.google.apis:google-api-services-container` but still supported library can be used in the meantime.

**Comment by garrettjonesgoogle** [comment]
This has been created: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-container
