### ISSUE TITLE
Make Storage.update() rename an object

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#2672]
I expected the following call to rename an object. Unfortunately, its behaviour is not the expected, and it's very different from other similar calls like `setMetadata()`.

```
Storage gcs = ...;

gcs.update(BlobInfo.newBuilder("existingBucket", "existingObject")
				.setBlobId(BlobId.of("existingBucket", "newObject"))
				.build());
```

AFAICT, this tries to make a dummy update to `gs://existingBucket/newObject`, which fails because the URI doesn't exist.
Logically, the behaviour of this call should be to rename the object, which is what I want to do, and appears to be impossible as per [this](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/mv.py#L101): `gsutil mv` copies and removes, which ideally we would avoid doing.

Is there any way to rename a file that doesn't involve copying and removing?
If not, then I'd like to request one.

**Comment by hzyi-google** [comment]
@joaoandremartins Please refer to this code snippet from the `Storage` interface to update metadata of a blob:
```
String bucketName = "my_unique_bucket";
String blobName = "my_blob_name";
String newBlobName = "new_blob_name";
Blob blob = storage.get(bucketName, blobName);
BlobInfo updatedInfo = blob.toBuilder()
    .setBlobId(BlobId.of(bucketName, newBlobName))
    .build();
storage.update(updatedInfo);
```
Feel free to repost if that does not solve your problem.

**Comment by joaoandremartins** [comment]
@hzyi-google thanks for the help.

Unfortunately, that didn't work. I'm still getting a `Not found` error.

As I mentioned in my report,`setBlobId()` isn't having the desired effect. This should be looked into.

**Comment by hzyi-google** [comment]
@joaoandremartins Thanks for the feedback. I'll take a further look.

**Comment by hzyi-google** [comment]
It seems that Object#update is only used to update the metadata per [here](https://cloud.google.com/storage/docs/json_api/v1/objects/update). Therefore additional changes have to be made outside the client library for this request. Can you tell a look as well @neozwu ?

**Comment by pongad** [comment]
IIUC, Storage objects cannot be "renamed". To rename, you must copy to the new place and delete the original. This [doc](https://cloud.google.com/storage/docs/renaming-copying-moving-objects) provides some code samples.

**Comment by joaoandremartins** [comment]
I understand that renaming is currently impossible.
This issue is a feature request to have it implemented eventually -- why are you closing it?

**Comment by joaoandremartins** [comment]
Thanks a lot for the explanation @hzyi-google 

If it's impossible to rename things by design in GCS, then feel free to do however you like with this issue. Having to pay for operations just to rename an object doesn't feel right, though.

**Comment by pongad** [comment]
@joaoandremartins I'm sorry I didn't communicate clearly. The Storage API itself provides no way to rename objects. @hzyi-google Thank you for adding this to feature backlog.
