### ISSUE TITLE
Resolving project-id when not specified is very slow

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/google-cloud-java#2683]
After recently updating gcloud from 0.26 to 0.30 (cloud storage 1.8.0 to 1.12.0), I found that it became much slower when starting up. Looking at logs, I noticed that this URL fetch of the current project-id (when using `getDefaultInstance()` to initialize a service) is very slow, taking ~5-10 seconds

http://metadata.google.internal/computeMetadata/v1/project/project-id

I'm not sure if 0.26 did not make this call or not, but I don't think it had the performance issue.

Explicitly setting project id isn't so bad and eliminates this slowness completely, so it's not a huge issue, but I was surprised to see the significant slow-down when upgrading versions and wonder if this is intended. For context, this is not used in a server but rather in a build task (gradle build cache plugin), so this slow request happens at the start of every build, making them take several seconds longer.

**Comment by pongad** [comment]
@anuraaga Out of curiosity, how did you detect that it was the call that takes a long time?

I started up a test GCE instance and ran
```
$ time curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/project/project-id
pongad-testing
real    0m0.015s
user    0m0.004s
sys     0m0.000s
```
I think it's unlikely that the call itself is the problem.

@anuraaga Can you confirm that you're running on AppEngine, Compute Engine, or Container Engine? The endpoint is only available to them, so if your application is retrying to access that URL from your own machine, it might take it a little longer to fail.

**Comment by anuraaga** [comment]
Hi @pongad I should have clarified better that indeed, these are not running on GCP machines - the client is running on developer machines on a normal office internet connection in Japan.

After trying to use the client recently, and finding that commands that used to run instantly were taking several seconds to initialize, I looked at the INFO logs and noticed it was always hanging on that call. Explicitly setting project-id removed that from the logs and removed the slowdown completely too.

I noticed the slowdown for a couple of days - it could have coincidentally been timed with when I updated our dependency version though and be transient, I will get back with trying to revert to the old version and see if it's still slow.

**Comment by hzyi-google** [comment]
@anuraaga Thanks for the investigations. Since your project is not on any GCP machines, can you also take a look where you specified the project-id per [here]
 (https://github.com/GoogleCloudPlatform/google-cloud-java#specifying-a-project-id) before you explicitly set the project-id? Thanks.

**Comment by anuraaga** [comment]
The project ID is set using the gcloud sdk. I guess the client first polls that url to see if it's on compute engine and if that fails it checks the others. When the metadata endpoint is slow it affects the client during this check.

I tried reverting and found that it is not slow right now. I think I must have saw a transitive issue in the performance of the endpoint outside GCP and it might not be a problem to solve here. That being said, if the compute engine metadata endpoint has poor SLAs for latency outside of GCP, which is understandable, it might be a bad first check for the sdk.

**Comment by pongad** [comment]
@anuraaga I think the current implementation actually checks that endpoint last, but #2705 should remove this concern altogether.
