### ISSUE TITLE
Small inconsistency in Compute interface

### ISSUE THREAD

**Issue by ardias** [GoogleCloudPlatform/google-cloud-java#2686]
Hi there,

Just noticed what i think is a small inconsistency in Compute Interface:
Compute.getNetwork() accepts a **string** (network name) and Compute.getSubnetwork() accepts a **SubnetworkId**

Most, if not all, other **get** methods accept a ResourceId object

**Comment by vchudnov-g** [comment]
Thanks, @ardias. We'll look into this.

@garrettjonesgoogle Is this a library or API issue?

**Comment by garrettjonesgoogle** [comment]
Without checking, probably a library issue.

Anyway, the current Compute surface is going to be deprecated soon and be replaced with a completely difference surface. Accordingly, I am going to close out this issue.
