### ISSUE TITLE
Datastore driver should support ID reservation

### ISSUE THREAD

**Issue by wsh** [GoogleCloudPlatform/google-cloud-java#2693]
This is supported in the low-level client as of version 1.5, which this library [already depends on](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/96fd92b45a1782bfd2304fcf2f2df7e985a4ce4f/google-cloud-bom/pom.xml#L263). #2589 would obviate this.

**Comment by vchudnov-g** [comment]
Thanks! I categorized this issue so we can track it and address it.

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
