### ISSUE TITLE
google cloud storage signed url with custom meta header

### ISSUE THREAD

**Issue by aks0020** [GoogleCloudPlatform/google-cloud-java#2698]
I don't see any option to generate signed url with headers other than 'Content-Type'
I want to generate signed url with `x-goog-meta-*` header how to achieve that with this client library.

**Comment by andreamlin** [comment]
To be fixed with https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2517.

**Comment by garrettjonesgoogle** [comment]
@andreamlin can you verify if this is done now? (#2517 is closed)

**Comment by andreamlin** [comment]
This is done. See `StorageImplTest.testSignUrlWithExtHeaders()` for an example of signing headers.
