### ISSUE TITLE
Google Cloud Datastore - consider renaming delete to remove (for collection consistency)

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#27]

**Comment by aozarov** [comment]
Though I created this issue, I am not sure I favor it. it was more left for discussion, so I suggest not taking actions without more opinions.

**Comment by mziccard** [comment]
My opinion here is that we should stick to delete. Although less consistent with the "collection world", delete sounds more consistent with the API itself and other modules.

**Comment by garrettjonesgoogle** [comment]
This seems stale, closing out.
