### ISSUE TITLE
Feature Request: Signed URLs for Google Cloud Storage Blobs and Buckets 

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-java#2702]
Would it be possible to add functionality to Blob and Bucket to provide signed URLs?

We were discussing this topic (spring-cloud/spring-cloud-gcp#251) and it looks like the existing instructions on the dev site has users construct that URL themselves.

**Comment by hzyi-google** [comment]
Hi @ChengyuanZhao  -

The client library now supports signed URLs for Blobs, here is a sample code for your reference:
```
Storage storage = StorageOptions.getDefaultInstance().getService();
String bucketName = "[BUCKET_NAME]";
String blobName = "[BLOB_NAME]";
String keyPath = "[PATH_TO_KEY]";
URL signedUrl = storage.signUrl(BlobInfo.newBuilder(bucketName, blobName).build(), 
        14, TimeUnit.DAYS, SignUrlOption.signWith(ServiceAccountCredentials.fromStream(
        new FileInputStream(keyPath))));
```
Signed Url for Blobs is in the works along with #2629. Please stand by.

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.

**Comment by minherz** [comment]
client library does not [support it][1] for all platforms. For example, `StorageClient` class for .NET does not have method `SignUrl`.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2702#issuecomment-351551565
