### ISSUE TITLE
Please add a README to google-cloud-bom

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2708]
google-cloud-java/google-cloud-bom/pom.xml

so it is clear to users what is the latest release version to include and how to include that in a `dependencyManagement` section

**Comment by garrettjonesgoogle** [comment]
We do already have some documentation at https://github.com/GoogleCloudPlatform/google-cloud-java#version-management , but we probably want to copy the dependencymanagement sample into a google-cloud-bom README also.
