### ISSUE TITLE
Pub/Sub publisher retrySettings: runtime errors that should be compile time

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#2721]
Publisher built with these retry settings fails at runtime, with generic "illegal argument exception."
The error does point to specific failed pre-conditions, which have to do with minTotalTimeout -- which I had not set here. 

<pre>
        RetrySettings retrySetting = RetrySettings.newBuilder()
                .setInitialRpcTimeout(Duration.ofMillis(500))
                .setMaxAttempts(10)
                .setJittered(Boolean.TRUE)
                .setMaxRpcTimeout(Duration.ofMillis(500))
                .build();
</pre>

**Comment by pongad** [comment]
I don't think it's possible to turn this into compile time error, but the linked PR should help.

**Comment by kir-titievsky** [comment]
Compile time errors was indeed a silly request, but I think we could do much better by changing the set of parameters users actually set like so:

Given this clause: 
 ```java
Preconditions.checkArgument( his.retrySettings.getTotalTimeout().compareTo(MIN_TOTAL_TIMEOUT) >= 0);
```
I propose we deprecate ```setTotalTimeout``` and replace it with ```setTotalTimeoutPadding``` which sets the private total timeout to MIN_TOTAL_TIMEOUT + PAD. 

Similarly, given 
``` Preconditions.checkArgument(
 +        this.retrySettings.getInitialRpcTimeout().compareTo(MIN_RPC_TIMEOUT) >= 0);
```
we replace setInitialRpcTimeout with setInitialRpcTimeoutPad.  

I think we should do the same for all settings objects with preconditions: batch settings, for example.

What do you think?

**Comment by pongad** [comment]
@kir-titievsky I think the problem is that `RetrySettings` isn't specific to pubsub, it is shared with many other  clients where the pad might not make sense. So while I think your proposal make things less error prone, the API might not work.

It also doesn't help with the case where you forget to set a value. In the linked PR, a new method makes it so you can't forget.

**Comment by pongad** [comment]
Moved to feature wiki.
