### ISSUE TITLE
Make google-cloud-logging work with cloud-trace-java

### ISSUE THREAD

**Issue by danialfaridsada** [GoogleCloudPlatform/google-cloud-java#2727]
I want both stackdriver tracing and logging in my project and seems like there is no way to make both of them work on the same project. 

https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-logging
https://github.com/GoogleCloudPlatform/cloud-trace-java

The issue is the library conflict for `com.google.api:gax-grpc` (and possibly others):

The latest `com.google.cloud:google-cloud-logging:1.14.0` depends on `om.google.api:gax-grpc:1.15.0` but 
the latest `com.google.cloud.trace:trace-grpc-api-service:0.5.0` depends on ` com.google.cloud.trace.v1:grpc-consumer:0.5.0` -> `com.google.cloud:google-cloud-trace:0.24.0-alpha` -> `com.google.cloud:google-cloud-core-grpc:1.6.0` -> `com.google.api:gax-grpc:0.25.1`.

So the logging depends on `gax-grpc:1.15.0` but the tracing depends on `gax-grpc:0.25.1` and they are not backward compatible (some classes are removed/renamed).

Is there any way to have a set of versions for these two libraries to work together?

**Comment by garrettjonesgoogle** [comment]
google-cloud-java is at the root of both; cloud-trace-java needs to update its dependency to a more recent version of google-cloud-trace. I would recommend filing an issue with them.

**Comment by danialfaridsada** [comment]
Alright I did that.
Is there a version of `google-cloud-logging` that works with `gax-grpc:0.25.1`?

**Comment by danialfaridsada** [comment]
Also these two projects should be more coordinated and probably be part of the same repo since people would usually use both features of stackdriver in their products.

**Comment by garrettjonesgoogle** [comment]
`1.7.0` - see https://github.com/GoogleCloudPlatform/google-cloud-java#version-management for reference.

**Comment by danialfaridsada** [comment]
Is there a change log I could find out what has changed between the java versions of `com.google.cloud:google-cloud-logging`

**Comment by garrettjonesgoogle** [comment]
1. Determine the google-cloud-logging versions you are interested in
2. Determine the alpha versions in https://github.com/GoogleCloudPlatform/google-cloud-java#version-management that correspond to those versions of google-cloud-logging
3. Read over the release notes for those versions at https://github.com/GoogleCloudPlatform/google-cloud-java/releases

Alternatively, look at the commit history at https://github.com/GoogleCloudPlatform/google-cloud-java/commits/master/google-cloud-logging .

**Comment by pongad** [comment]
Issue seems to already been resolved.
