### ISSUE TITLE
Pub/Sub client should allow connecting to different backends without changes in code

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#2731]
Current Pub/Sub client can be made to use an emulator service instead of pubsub.googleapis.com as the API service. The way this is implemented, however,  appears to require the users to both set an environment variable AND change the client code.  It seems to me this makes hermetic testing difficult.   I think, as an application developer, I would be much happier if I could test my code against an emulator or an alternate backend without touching the code itself.  So the feature request here is that:

The code required to use the emulator currently looks kind of like this:
```bash 
$export PUBSUB_EMULATOR_HOST=10.0.0.200:1234
```
```java
 String hostport = System.getenv("PUBSUB_EMULATOR_HOST");
    ManagedChannel channel = ManagedChannelBuilder.forTarget(hostport).usePlaintext(true).build();
    try {
      TransportChannelProvider channelProvider =
          FixedTransportChannelProvider.create(GrpcTransportChannel.create(channel));
      CredentialsProvider credentialsProvider = NoCredentialsProvider.create();

      TopicName topicName = TopicName.of("my-project-id", "my-topic-id");
      // Set the channel and credentials provider when creating a `Publisher`.
      // Similarly for Subscriber
      Publisher publisher =
          Publisher.newBuilder(topicName)
              .setChannelProvider(channelProvider)
              .setCredentialsProvider(credentialsProvider)
              .build();
```
Might we make it look identical to "normal production code" used to accomplish the same thing? That is:
```java
      TopicName topicName = TopicName.of("my-project-id", "my-topic-id");
      // Create a publisher instance with default settings bound to the topic
      publisher = Publisher.newBuilder(topicName).build();
```
and all the channel building would happen automatically? I presume all but the hostport line are already part of the client library code base.

**Comment by andreencarnacao-focusbc** [comment]
The problem seems to be that when google client library tries to instantiate the default channel does not take into account if the environment variable PUBSUB_EMULATOR_HOST is setted. I am going to do a pull request, but further development on top of it might be needed

**Comment by pongad** [comment]
Some history: we thought it was somewhat dangerous to do this. For example, a small mistake like `PUBSUB_EMULATOR_HOTS=1.2.3.4 delete-all-topics` might delete a bunch of your production topics. It's a judgement call whether the benefits outweighs the risk, but I sympathize with the view that auto-detecting the env var is a bit of a foot-gun.

I think we should go with @jba's suggestion: we'll add a `detectEmulator` method. The method will look up the env var and use the emulator is the var is set. If the var is not set, we'll connect to production host. Users who are OK with the aforementioned risk can simply call the method unconditionally. In this way, the proverbial gun would at least have safety on.

@kir-titievsky @garrettjonesgoogle Are you OK with this?

**Comment by kir-titievsky** [comment]
I think that would work, with couple questions:
1. Could we name the variable something more generic than "emulator": e.g. detectServiceHost?
2. Is there any special machinery required to make this work with both IP addresses and hosnames?  For example, if a user might want to set the emulator to point to pubsub.googleapis.com explicitly, using the environment variable when testing multiple scenarios.

**Comment by garrettjonesgoogle** [comment]
I second @kir-titievsky 's suggestion of a more general approach.

**Comment by pongad** [comment]
@kir-titievsky I'll answer in reverse:

This is a little difficult. The emulator "speaks" plain text and doesn't do SSL encryption. So, either the method automatically sets plain text, assuming that the host in an emulator, or we'll need more than one method.

I have a few designs in my head:

1.
```java
Publisher.newBuilder(topicName).detectEmulator().build();
```
where `detectEmulator` reads the env var. If the env var isn't empty, we turn off encryption and set the host.

2.
```java
Publisher.newBuilder(topicName)
  .detectEmulator(System.getenv("PUBSUB_EMULATOR_HOST"))
  .build();
```
Similar to (1) but we don't hard code what the variable is. If the string isn't empty, turn off encryption and set the host.

3.
```java
String var = System.getenv("PUBSUB_EMULATOR_HOST");
Publisher.newBuilder(topicName)
  .setHost(var)
  .setPlainText(var != null && !var.isEmpty())
  .build();
```
Seems a little weird. `setHost` is a general-looking method it should error if var is empty or null.

4.
```java
String var = System.getenv("PUBSUB_EMULATOR_HOST");
Publisher.Builder builder = Publisher.newBuilder(topicName);
if (var != null && !var.isEmpty()) {
  builder.setHost(var).setPlaintext(true);
}
builder.build();
```
This works, but it's only marginally better than what we have right now.
Adding convenience methods like this is a bit of a feature duplication, and too much duplication leads to confusion. So, the method has to be convenient enough to justify the cost.

My opinion is still that (3) and (4) don't add enough value to justify the duplication. (1) and (2) might; they add more convenience and specific enough to not add much confusion.

**Comment by kir-titievsky** [comment]
Fix post GA.

**Comment by pongad** [comment]
This feature request is already in the feature backlog wiki. I'll close this for now.

**Comment by oande** [comment]
Sorry for resurrecting this issue @pongad @kir-titievsky , but I couldn't find any news regarding this "foot-gun". 🙂I think it'd save a bit of boilerplate code.
>we thought it was somewhat dangerous to do this. For example, a small mistake like PUBSUB_EMULATOR_HOTS=1.2.3.4 delete-all-topics might delete a bunch of your production topics.

If I understand this correctly, the perceived risk essentially boils down to developers who might use the emulator env var with production credentials at the same time? Perhaps the `detectEmulator` method could be documented with a warning about that
