### ISSUE TITLE
BigQuery Data Transfer: ListDataSourcesRequest not documented / not linked to

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-java#2736]
See: https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.html#listDataSources-com.google.cloud.bigquery.datatransfer.v1.ListDataSourcesRequest-

I would expect `com.google.cloud.bigquery.datatransfer.v1.ListDataSourcesRequest` to be a hyperlink to the ListDataSourcesRequest class, but it is not. A search within that page for ListDataSourcesRequest does not show any documentation for that class.

**Comment by tswast** [comment]
Many other classes are also undocumented. `com.google.cloud.bigquery.datatransfer.v1.DataSource` is another example of a class that is referenced but not documented.

Possibly these are all the underlying Protocol Buffer resource classes?

**Comment by neozwu** [comment]
@pongad could you take a look at this? Thanks.

**Comment by pongad** [comment]
The primary problem is that when we generated the docs for the clients, we didn't generate the docs for the protobuf types. I generated the docs for protobuf types, but they don't properly link anything either.

See also: https://github.com/googleapis/api-client-staging/pull/505

**Comment by pongad** [comment]
Root cause should have been fixed by #2862 and take effect the next release. I'll resolve this for now.
