### ISSUE TITLE
Add option to clear traceId thread-local in TraceLoggingEnhancer

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-java#2746]
When the `traceId` thread-local needs to be removed, calling `setCurrentTraceId(null)` is not appropriate because it still leaves a thread-local entry. Instead, and indirect call to `ThreadLocal.remove()` should be exposed. One option is to provide a method called `removeCurrentTraceId`. Another alternative, is to detect the `null` argument to `setCurrentTraceId` and call `remove()` instead of `set(null)` in that case.

**Comment by neozwu** [comment]
Thank you for your feedback. assigned to @pongad to take a look into this.

**Comment by pongad** [comment]
@meltsufin This might be a stupid question, but is there actually a difference?

At the implementation level, IIUC, after you call `threadLocal.remove()`, the next call to `threadLocal.get()` will return whatever `threadLocal.initialValue()` returns. In this case, `initialValue` returns `null`. So I don't think you can tell the difference between `set(null)` and `remove()`, can you?

**Comment by meltsufin** [comment]
@pongad It's not a stupid question, but yes, there is a slight difference. The `remove()` deletes the whole thread-local map entry, whereas `set(null)` leaves the entry hanging with a `null`, "polluting" the thread in a way.
This is relevant in scenarios where threads get reused from a pool, and we need to clean up the threads before returning to the pool.
Indeed, the next call to `get()` will create a `null` entry, but we can't guarantee that the next user of the thread will ever even call `get()`.
This is not a super high priority thing. It's more of a matter of following the best practice of cleaning up thread-locals.

**Comment by pongad** [comment]
I see. So the difference is memory consumption. I'll make this change.
