### ISSUE TITLE
Firestore: DocumentReference#getCollections() should be async

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/google-cloud-java#2771]
Most of the Firestore operations return `ApiFuture<T>`.  The method `DocumentReference#getCollections()` returns an `Iterable<CollectionReference>` but it should probably return `ApiFuture<Iterable<CollectionReference>>` since it calls over the network.

**Comment by samtstern** [comment]
cc @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
The ApiIterable class opens a network connection only when you first ask for data and not when the method executes. This behavior is similar to calling .get() on an ApiFuture.

**Comment by samtstern** [comment]
Should we explicitly return `ApiIterable` to indicate that?  Or is that not the normal style?

**Comment by schmidt-sebastian** [comment]
The Iterable is extracted from the `UnaryCallable` that the generated layer returns. It's signature is ` UnaryCallable<ListCollectionIdsRequest, ListCollectionIdsPagedResponse>`, which is not something I would like to impose on our users.

In the first pass of the review for this client, the method did in fact return an `ApiFuture<Iterable>`, but we changed it to just return an Iterable after initial comments (which I unsuccessfully tried to dig up).

**Comment by schmidt-sebastian** [comment]
This works as intended. Closing.
