### ISSUE TITLE
Integration tests stall when installing locally

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#2778]
I followed the instructions in https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/CONTRIBUTING.md, but all the integration tests got stuck indefinitely, some throwing error messages and either resuming or staying stalled.

I eventually had to use the -DskipTests flag to install.

**Comment by garrettjonesgoogle** [comment]
I personally use -DskipITs when I install.

**Comment by garrettjonesgoogle** [comment]
We should adjust the instructions.
