### ISSUE TITLE
Don't set versions of external dependencies in BOM

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#2781]
For example, in https://github.com/GoogleCloudPlatform/google-cloud-java/blob/184c219c7a7d38bd8146e3a4d35f0972a1d24a10/google-cloud-bom/pom.xml#L136 we're setting the version of `netty-tcnative-boringssl-static`. This conflicts with the version we're using in [spring-cloud-gcp](https://github.com/spring-cloud/spring-cloud-gcp).

If users build their application, they get

```
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.OpenSslEngine
	at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:49)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:378)
	at io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded(ProtocolNegotiators.java:306)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	... 19 common frames omitted
```

Ideally, BOMs only export the versions of the modules the project implements. The dependencies used by the project should go in another pom, e.g., https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/pom.xml

Can we remove the versions of the dependencies of `google-cloud-java` from the BOM?

**Comment by garrettjonesgoogle** [comment]
One of the biggest benefits people get from the google cloud BOM is gettings the correct tcnative dependency. If it conflicts with what you're using, then it probably conflicts with google-cloud-java at large (well, through grpc). 

Now you say that BOMs should only export the versions of the modules the project implements, but doesn't spring-cloud-gcp export a bunch of dependencies not in spring-cloud-gcp?

**Comment by joaoandremartins** [comment]
Who is causing the tcnative issue -- google-cloud-java or netty? If the former, I understand google-cloud-java must add it until the issue is fixed on their side. If netty, then you should probably only recommend the usage of a specific version of tcnative and not put anything on the bom.

We're facing a similar question on our end -- you are providing tcnative's version that is incompatible with Spring Boot 2 and we're having to override it on our side so that SB2 users don't see any (hard to debug) errors.

By providing 2.0.6 on your side, you're breaking all SB2 users.

`spring-cloud-gcp`'s bom doesn't provide dependencies, unless we really need a specific version (like tcnative in this case).
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml

Then for internal use,
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/pom.xml#L60

https://github.com/spring-cloud/spring-cloud-gcp/pull/273

**Comment by pongad** [comment]
@garrettjonesgoogle Is there any action item required to resolve the problem other than moving to `netty-grpc-shaded`? If not, I think we should resolve this as dup of #2813.

**Comment by garrettjonesgoogle** [comment]
There are a bunch of other external packages that we set versions for also.

**Comment by pongad** [comment]
@saturnism Do you have any recommendations here?

**Comment by saturnism** [comment]
Per discussion from email:

1. Move non google-client libraries (i.e., 3rd party dependencies, like netty, guava, protobuf, org.json, any test-related libraries) to parent dependency management section, so that it's not exported via the BOM, but is still a direct dependency of the sub modules.
1. Advise the use of Enforcer plugin to detect conflicting versions in user's POM. In the user's POM, enforcer won't be able to detect version conflicts if the version was managed by the BOM.  Thus #1 is can be a good thing.
1. Move pluginManagement and pluginRepository section from BOM to parent. There is no reason to export those via a BOM.

**Comment by garrettjonesgoogle** [comment]
We have moved the dependencies not managed by our project to the parent pom, so closing this out now.
