### ISSUE TITLE
LocalDatastoreHelper uses org.threeten.bp.Duration instead of the jdk version

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/google-cloud-java#2793]
Could you please use java.time.Duration? Any reason for why to use the backport?

**Comment by garrettjonesgoogle** [comment]
We are still Java 7 compatible - java.time.Duration was added in Java 8.

**Comment by pongad** [comment]
Since we need Java 7 compatibility, I'll close this as infeasible. We'll migrate to `java.time.*` when we're able to drop Java 7 support.

**Comment by garrettjonesgoogle** [comment]
We shouldn't necessarily promise that we'll migrate to `java.time.*` - that's a breaking change, which we want to minimize.

**Comment by pongad** [comment]
Edited
