### ISSUE TITLE
Error with spring boot in app engine java 8 standard 

### ISSUE THREAD

**Issue by santhh** [GoogleCloudPlatform/google-cloud-java#2794]
Hello: I was trying to configure my first spring boot project in app engine.  As soon as I add the dependancy, I get this error below. Any idea what may be causing this?

Suppressed: 
[INFO] GCLOUD: 	|java.lang.RuntimeException: Error scanning entry autovalue/shaded/com/google$/common/collect/$Maps$FilteredEntrySortedMap$SortedKeySet.class from jar file:///Users/masudhasan/Documents/workspace-sts-3.8.4.RELEASE/demo/target/appengine-staging/WEB-INF/lib/auto-value-1.2.jar
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD: 	|	at java.lang.Thread.run(Thread.java:745)
[INFO] GCLOUD: 	|Caused by: 
[INFO] GCLOUD: 	|java.util.zip.ZipException: invalid LOC header (bad signature)
[INFO] GCLOUD: 	|	at java.util.zip.ZipFile.read(Native Method)
[INFO] GCLOUD: 	|	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
[INFO] GCLOUD: 	|	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
[INFO] GCLOUD: 	|	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
[INFO] GCLOUD: 	|	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[INFO] GCLOUD: 	|	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[INFO] GCLOUD: 	|	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[INFO] GCLOUD: 	|	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:480)
[INFO] GCLOUD: 	|	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:443)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:977)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD: 	|	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD: 	|	at java.lang.Thread.run(Thread.java:745)

**Comment by pongad** [comment]
I believe the main problem is a corrupted JAR file. Could you delete the offending file and try again.

I think this is happening during compilation, not when running your program right? If the problem persists, would it be possible for you to share your dependency manifest (pom.xml, build.gradle, etc)? Then we can see if we can repro this.

**Comment by santhh** [comment]
thanks for looking at this. Yes I resolved it already. Please close.
