### ISSUE TITLE
Avoid exporting multiple versions of the same dependency.

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/google-cloud-java#2803]
This is a good practice to do in general, opencensus tried to enable Maven Enforcer's dependencyConvergence and we found some issues (same issues apply for the trace library as well), see the bolded targets as an example:

+--- com.google.cloud:google-cloud-monitoring:0.33.0-beta
|    +--- io.netty:netty-tcnative-boringssl-static:2.0.7.Final
|    +--- com.google.cloud:google-cloud-core:1.15.0
|    |    +--- joda-time:joda-time:2.9.2
|    |    +--- com.google.http-client:google-http-client:1.23.0
|    |    |    +--- **com.google.code.findbugs:jsr305:1.3.9 -> 3.0.1**
|    |    |    \--- org.apache.httpcomponents:httpclient:4.0.1
|    |    |         +--- org.apache.httpcomponents:httpcore:4.0.1
|    |    |         +--- commons-logging:commons-logging:1.1.1
|    |    |         \--- commons-codec:commons-codec:1.3
|    |    +--- **com.google.code.findbugs:jsr305:3.0.1**
|    |    +--- com.google.api:api-common:1.2.0
|    |    |    \--- **com.google.code.findbugs:jsr305:3.0.0 -> 3.0.1**
|    |    +--- com.google.api:gax:1.16.0
|    |    |    +--- com.google.auto.value:auto-value:1.2
|    |    |    +--- com.google.code.findbugs:jsr305:3.0.0 -> 3.0.1
|    |    |    +--- org.threeten:threetenbp:1.3.3
|    |    |    +--- com.google.auth:google-auth-library-oauth2-http:0.9.0
|    |    |    |    +--- com.google.auth:google-auth-library-credentials:0.9.0
|    |    |    |    +--- com.google.http-client:google-http-client:1.19.0 -> 1.23.0 (*)
|    |    |    |    \--- com.google.http-client:google-http-client-jackson2:1.19.0
|    |    |    |         +--- com.google.http-client:google-http-client:1.19.0 -> 1.23.0 (*)
|    |    |    |         \--- com.fasterxml.jackson.core:jackson-core:2.1.3
|    |    |    \--- com.google.api:api-common:1.2.0 (*)
|    |    +--- com.google.protobuf:protobuf-java-util:3.5.1
|    |    |    +--- **com.google.protobuf:protobuf-java:3.5.1**
|    |    |    \--- com.google.code.gson:gson:2.7
|    |    +--- com.google.api.grpc:proto-google-common-protos:1.0.4
|    |    |    \--- **com.google.protobuf:protobuf-java:3.4.0 -> 3.5.1**
|    |    \--- com.google.api.grpc:proto-google-iam-v1:0.1.28
|    |         +--- com.google.api.grpc:proto-google-common-protos:1.0.4 (*)
|    |         +--- **com.google.protobuf:protobuf-java:3.4.0 -> 3.5.1**
|    |         \--- com.google.api:api-common:1.2.0 (*)
|    +--- com.google.cloud:google-cloud-core-grpc:1.15.0
|    |    +--- io.netty:netty-tcnative-boringssl-static:2.0.7.Final
|    |    +--- com.google.auth:google-auth-library-credentials:0.9.0
|    |    +--- com.google.cloud:google-cloud-core:1.15.0 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.5.1
|    |    +--- com.google.protobuf:protobuf-java-util:3.5.1 (*)
|    |    +--- io.grpc:grpc-protobuf:1.9.0
|    |    |    +--- io.grpc:grpc-core:1.9.0
|    |    |    |    +--- io.grpc:grpc-context:1.9.0
|    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.1.2 -> 2.2.0
|    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.0 -> 3.0.1
|    |    |    |    +--- com.google.instrumentation:instrumentation-api:0.4.3
|    |    |    |    |    \--- com.google.code.findbugs:jsr305:3.0.0 -> 3.0.1
|    |    |    |    \--- io.opencensus:opencensus-contrib-grpc-metrics:0.10.0
|    |    |    |         \--- com.google.errorprone:error_prone_annotations:2.1.2 -> 2.2.0
|    |    |    +--- com.google.protobuf:protobuf-java:3.5.1
|    |    |    +--- com.google.protobuf:protobuf-java-util:3.5.1 (*)
|    |    |    +--- com.google.api.grpc:proto-google-common-protos:1.0.0 -> 1.0.4 (*)
|    |    |    \--- io.grpc:grpc-protobuf-lite:1.9.0
|    |    |         \--- io.grpc:grpc-core:1.9.0 (*)
|    |    +--- **io.grpc:grpc-context:1.9.0**
|    |    +--- **io.grpc:grpc-netty:1.9.0**
|    |    |    +--- io.grpc:grpc-core:[1.9.0] -> 1.9.0 (*)
|    |    |    +--- io.netty:netty-codec-http2:[4.1.17.Final] -> 4.1.17.Final
|    |    |    |    +--- io.netty:netty-codec-http:4.1.17.Final
|    |    |    |    |    \--- io.netty:netty-codec:4.1.17.Final
|    |    |    |    |         \--- io.netty:netty-transport:4.1.17.Final
|    |    |    |    |              +--- io.netty:netty-buffer:4.1.17.Final
|    |    |    |    |              |    \--- io.netty:netty-common:4.1.17.Final
|    |    |    |    |              \--- io.netty:netty-resolver:4.1.17.Final
|    |    |    |    |                   \--- io.netty:netty-common:4.1.17.Final
|    |    |    |    \--- io.netty:netty-handler:4.1.17.Final
|    |    |    |         +--- io.netty:netty-buffer:4.1.17.Final (*)
|    |    |    |         +--- io.netty:netty-transport:4.1.17.Final (*)
|    |    |    |         \--- io.netty:netty-codec:4.1.17.Final (*)
|    |    |    \--- io.netty:netty-handler-proxy:4.1.17.Final
|    |    |         +--- io.netty:netty-transport:4.1.17.Final (*)
|    |    |         +--- io.netty:netty-codec-socks:4.1.17.Final
|    |    |         |    \--- io.netty:netty-codec:4.1.17.Final (*)
|    |    |         \--- io.netty:netty-codec-http:4.1.17.Final (*)
|    |    +--- **io.grpc:grpc-stub:1.9.0**
|    |    |    \--- io.grpc:grpc-core:1.9.0 (*)
|    |    +--- **io.grpc:grpc-auth:1.9.0**
|    |    |    +--- io.grpc:grpc-core:[1.9.0] -> 1.9.0 (*)
|    |    |    \--- com.google.auth:google-auth-library-credentials:0.9.0
|    |    \--- com.google.api:gax-grpc:1.16.0
|    |         +--- com.google.auto.value:auto-value:1.2
|    |         +--- com.google.code.findbugs:jsr305:3.0.0 -> 3.0.1
|    |         +--- com.google.api:gax:1.16.0 (*)
|    |         +--- **io.grpc:grpc-netty:1.7.0 -> 1.9.0 (*)**
|    |         +--- **io.grpc:grpc-stub:1.7.0 -> 1.9.0 (*)**
|    |         +--- **io.grpc:grpc-auth:1.7.0 -> 1.9.0 (*)**
|    |         +--- **io.grpc:grpc-protobuf:1.7.0 -> 1.9.0 (*)**
|    |         +--- org.threeten:threetenbp:1.3.3
|    |         +--- com.google.auth:google-auth-library-oauth2-http:0.9.0 (*)
|    |         +--- com.google.auth:google-auth-library-credentials:0.9.0
|    |         +--- com.google.api.grpc:proto-google-common-protos:1.0.0 -> 1.0.4 (*)
|    |         \--- com.google.api:api-common:1.2.0 (*)
|    +--- com.google.api.grpc:proto-google-cloud-monitoring-v3:0.1.28
|    |    +--- com.google.api.grpc:proto-google-common-protos:1.0.4 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.4.0 -> 3.5.1
|    |    \--- com.google.api:api-common:1.2.0 (*)
|    +--- io.grpc:grpc-netty:1.9.0 (*)
|    +--- io.grpc:grpc-stub:1.9.0 (*)

**Comment by garrettjonesgoogle** [comment]
This is not a problem with google-cloud-java. google-cloud-java imports newer versions of certain things (e.g. grpc, protobuf) than its dependencies do (google-http-client, gax, proto-google-common-protos). Dependencies converge within google-cloud-java itself (we have dependency convergence enforcement on); we have no control over the fact that there is not convergence at a level above us.

**Comment by ejona86** [comment]
@bogdandrutu, I don't see anything wrong with google-cloud java with your output there. It seems like google-cloud-monitoring problem. For convergence you get to exclude transitive dependencies that you update.

**Comment by ejona86** [comment]
As an example, consider these lines from that output:
```
| +--- com.google.cloud:google-cloud-core:1.15.0
...
| | +--- com.google.http-client:google-http-client:1.23.0
| | | +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.1
```

Taking a [look at google-cloud-core's POM](http://search.maven.org/remotecontent?filepath=com/google/cloud/google-cloud-core/1.15.0/google-cloud-core-1.15.0.pom) shows the jsr305 dependency is already excluded, so this shouldn't trigger convergence issues:
```
    <dependency>
      <groupId>com.google.http-client</groupId>
      <artifactId>google-http-client</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.google.code.findbugs</groupId>
          <artifactId>jsr305</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by bogdandrutu** [comment]
@ejona86 thanks for the answer and clarification.

@garrettjonesgoogle I think the problem is in google-cloud-monitoring which 

My error was this:
```
   > A conflict was found between the following modules:
      - com.google.protobuf:protobuf-java:3.5.1
      - com.google.protobuf:protobuf-java:3.4.0
```

**Comment by bogdandrutu** [comment]
We were able to fix this issue on our side. I think this can be closed.
