### ISSUE TITLE
PlatformInformation.isOnGAEStandard7 returns erroneous false positive

### ISSUE THREAD

**Issue by wsh** [GoogleCloudPlatform/google-cloud-java#2805]
Seen from a Java 8 app in Flex. (Discovered because it's trying to construct a URLFetch transport for API clients.) Can provide further details, of course, but tbh I think there are better ways to detect this information than what that class does right now.

**Comment by wsh** [comment]
For Googlers: b/64313434 has better information for us to use in detecting GAE and runtime details.

For other users who might encounter this before we fix it: my temporary workaround was to explicitly specify:

```yaml
env_variables:
   JETTY_PROPERTIES: -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog
```

in my app.yaml. (Other values would work, too, the important part is that the property is non-null so that [this line](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/b7b3f21b784a3524f7830f34148abfd3e39677d4/google-cloud-core/src/main/java/com/google/cloud/PlatformInformation.java#L44) returns false.

**Comment by pongad** [comment]
@wsh @neozwu IIUC, it should be sufficient to say `System.getenv("GAE_RUNTIME").equals("java7")` right?

I must admit I don't understand the runtime very well.

**Comment by neozwu** [comment]
@pongad I'm not exactly sure since some env vars and sys props could have been changed/added/removed since I wrote the original method. IIRC, at the time, we decided to use jetty logger env var to identify a GAE 7 app deployed on J8 dev server.  @lesv can comment more on this.

**Comment by wsh** [comment]
@pongad that should be correct for any currently deployed GAE Java 7 app.

**Comment by lesv** [comment]
We have a bunch of issues around this in other repo's as well:
google/google-api-java-client#1089
google/google-auth-library as well  -- probably a few others

**Comment by lesv** [comment]
google-cloud-java can be made to support Java7 grpc, it doesn't now, but why?
Most users should be on Java8 if they are using this library.

**Comment by wsh** [comment]
@lesv where does gRPC come into this?

**Comment by lesv** [comment]
@wsh Many of the GA'd services google-cloud-java services are gRPC only.  Datastore is one that isn't currently.

**Comment by wsh** [comment]
[Cloud Storage](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-storage) appears to use HTTP, as does [Cloud Translate](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-translate). Both of those are GA, too. Isn't that orthogonal to this, though? When the App Engine Standard Java 7 runtime is decommissioned, we don't have to worry about these checks, but at least right now we do.

**Comment by lesv** [comment]
@jonparrott FYI

@wsh You may be right - Jon now owns this, so I'll let him weigh in.

**Comment by jonparrott** [comment]
Sounds reasonable?
