### ISSUE TITLE
1st party - Composite GCS Uploads

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/google-cloud-java#2812]
It'd be great to have first party support for GCS composit uploads of large files / streams. While technically possible the SDK now, its not nearly as easy as using gsutil:
`gsutil -o GSUtil:parallel_composite_upload_threshold=150M cp bigfile gs://your-bucket`

Thinking something like this would be great:
```
storage = ....
blobInfo = ...
storage.parallelCompositUpload(readChannel, blobInfo);

```

**Comment by hzyi-google** [comment]
Move this issue to feature request [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog) and close it here. This place can continue to be used for discussion.
