### ISSUE TITLE
can not set fieldDelimiter and encoding at load job configuration java client

### ISSUE THREAD

**Issue by MSimsekYildirim** [GoogleCloudPlatform/google-cloud-java#2820]
Hi, 

I want to load tab separated file from bucket to BiqQuery table. 
Unfortunately, there is no option to set delimiter type and encoding at LoadJobConfiguration at Java client.

**Comment by pongad** [comment]
@MSimsekYildirim The option exists but a little hidden. You can use [`setFormatOptions`](https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/bigquery/LoadJobConfiguration.Builder.html#setFormatOptions-com.google.cloud.bigquery.FormatOptions-) to set [`CsvOptions`](https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/bigquery/CsvOptions.html). There you can set delimiter and encoding.

**Comment by MSimsekYildirim** [comment]
Thanks for the quick response!
