### ISSUE TITLE
Consider using partial builds for PRs

### ISSUE THREAD

**Issue by igorbernstein2** [GoogleCloudPlatform/google-cloud-java#2853]
It would be nice to narrow PR builds to just the clients/modules that that PR affects while it's open. And a run the full test suite less frequently: either on merge, daily or when cutting a release.

To limit the affect modules, something like https://github.com/lesfurets/partial-build-plugin can be used.

**Comment by hzyi-google** [comment]
Move this issue to feature [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). This place can continue to be used for discussion.
