### ISSUE TITLE
ServiceOptions.getDefaultProjectId() in Cloud Shell picks up "no-project-id" from metadata server

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2855]
In Cloud Shell, where a project ID is properly configured in gcloud:
`gcloud config list --format 'value(core.project)'` shows the project ID, and
`echo $CLOUDSDK_CONFIG` shows the configuration directory.

Run a Java application that uses `ServiceOptions.getProjectId()` in cloud shell. It picks up `no-project-id` from the metadata server.

**Comment by hzyi-google** [comment]
Hi @saturnism, can I confirm with you about the environment of the project? Is it running on GAE, GCE or anywhere else?

**Comment by wsh** [comment]
@hzyi-google It sounds like @saturnism is running this code in [Cloud Shell](https://cloud.google.com/shell/). I don't think that the metadata service is supported there.

@saturnism do you have [application-default credentials](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/) set up? [ServiceOptions](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/b7b3f21b784a3524f7830f34148abfd3e39677d4/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L326) tries a number of things before it hits the metadata service.

**Comment by saturnism** [comment]
@wsh this is in cloud shell, which sets up the credentials automatically.  It's still retrieving project ID from metadata server even after explicitly setting up app default credentials.

In Cloud Shell, you can retrieve Project ID from metadata server, which is always `no-project-id`. It's clear that the logic in `ServiceOptions.getProjectId()` is would simply return that rather than continuing to try.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.33.0/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L332

**Comment by saturnism** [comment]
This is causing trouble practically for all of our Java code labs that runs in Cloud Shell. Can the priority be raised?

**Comment by wsh** [comment]
As you can see, it first looks to the environmental variables, in particular `GOOGLE_CLOUD_PROJECT`. I'm surprised that Cloud Shell doesn't set that. What would you suggest the fix is here: trying to check the Cloud SDK credentials first? Or is this a question of making the metadata service work for Cloud Shell?

**Comment by pongad** [comment]
Alternatively, can we just `if ("no-project-id".equals(result)) return null;`? For these methods, null means "don't know; go ask the next person".

That way we treat "no-project-id" as a sentinel error, much like how we treat `String.indexOf` returning -1.

**Comment by wsh** [comment]
Sure. (The risk, of course, is that the sentinel value changes.) I wonder if the response code is non-200 for this case? That would be less brittle.

**Comment by hzyi-google** [comment]
The response code is 200/OK when I run a `curl -i http://metadata.google.internal/computeMetadata/v1/project/project-id` from cloud shell.

**Comment by wsh** [comment]
This is being addressed with `GOOGLE_CLOUD_PROJECT`. @saturnism, I've CC'd you on the internal bug (73092008).

**Comment by pongad** [comment]
Internal bug is fixed but not rolled out yet. I'll leave this open until then.

**Comment by pongad** [comment]
Env var `GOOGLE_CLOUD_PROJECT` is set in cloud shell. We should be good now. I'll close this; please reopen if the problem persists.

**Comment by saturnism** [comment]
Thanks. Just caught up. However, the current logic will always ping metadata server first rather than checking gcloud SDK credentials first, right? This is contrary to the doc, and can be inefficient. Is there a way to restore the behavior of using metadata server as the last resort?
