### ISSUE TITLE
BigQuery table info is missing Labels

### ISSUE THREAD

**Issue by LukeDefeo** [GoogleCloudPlatform/google-cloud-java#2865]
The big query table info is missing the labels map

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/b7b3f21b784a3524f7830f34148abfd3e39677d4/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableInfo.java

It is present on the dataset and on the underlying model object so it seems to just have been missed out on the mapping

**Comment by pongad** [comment]
Dataset doesn't handle labels properly. This is a bug now.
