### ISSUE TITLE
Google cloud java package summary is unreachable.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/google-cloud-java#2869]
This URL is unreachable?
https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/compute/package-summary.html

This is breaking tests that depend on it (not sure if it affects customers), for example: https://travis-ci.org/GoogleCloudPlatform/appengine-plugins-core/builds/338186738#L1512

Has this page moved? Or is it just down?

**Comment by garrettjonesgoogle** [comment]
It's at https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/compute/deprecated/package-summary.html now. It is because of https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2819 .
