### ISSUE TITLE
Expose a true asynchronous DatabaseClient

### ISSUE THREAD

**Issue by rschildmeijer** [GoogleCloudPlatform/google-cloud-java#2875]
Deep inside (google.cloud.spanner.SpannerImpl) the client library grpc is used. Grpc enables non-blocking/asynchronous paradigms.
So it should be possible to expose a real asynchronous api. With real I mean a true event-driven approach and not just wrap the current blocking DatabaseClientImpl using a thread pool.

**Comment by hzyi-google** [comment]
Move this issue to [feature backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). Discussions and comments are still welcome here. Please feel free to reopen if there has been work in progress.
