### ISSUE TITLE
Use setProjection in DefaultStorageRpc.compose

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#289]
This depends on b/20659000. The projection parameter is not supported by compose API. As soon as this is fixed we should add `setProjection` to `DefaultStorageRpc.compose`.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
