### ISSUE TITLE
WriteChannel.capture surprisingly may do I/O

### ISSUE THREAD

**Issue by anuraaga** [GoogleCloudPlatform/google-cloud-java#2896]
`WriteChannel.capture` as implemented by `BaseWriteChannel` flushes the buffer before capturing. While this seems reasonable to reduce the size of the captured state, it is surprising since the javadoc doesn't mention this at all - intuitively, it does not seem like a method that just captures `RestorableState` would do blocking I/O, so the javadoc should be extended to clarify this point or the flushing should be removed.

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core/src/main/java/com/google/cloud/WriteChannel.java#L40

**Comment by pongad** [comment]
I actually find it unreasonable. It is far too surprising that `capture` might throw an exception.
