### ISSUE TITLE
Why is Compute going away in favor of Compute Engine Client Libraries? 

### ISSUE THREAD

**Issue by ardias** [GoogleCloudPlatform/google-cloud-java#2897]
Compute Engine Client Libraries are in maintenance mode and not receiving any updates as stated in its github project page (https://github.com/google/google-api-java-client), so why is the Compute library going away in favour of that? 
What are the plans for Compute support? Is it going away completely at some point? Is it going to be replaced with something else?

Thanks in advance

**Comment by pongad** [comment]
@ardias We are working to auto-generate a Compute client that's more idiomatic than the one in google-api-java-client. Once in place, it will be the recommended client to use. The auto-generation will also mean it'll be easily updated when new Compute features release.

I'll close the issue for now, but please reopen if you have further questions.
