### ISSUE TITLE
Vision API creating Annotator client

### ISSUE THREAD

**Issue by redserpent7** [GoogleCloudPlatform/google-cloud-java#2921]
Hi,

I am trying to find a documentation for how to create an annotator client with a credentials file. I do not want to use goolge default credentials. When using the translate API, I load my credentials file like so:

 ```
Credentials creds = ServiceAccountCredentials.fromStream(new FileInputStream("/path/to/credential/file"));
return TranslateOptions.newBuilder().setCredentials(creds).build().getService();
```

What is the equivalent way in Vision?

**Comment by pongad** [comment]
@redserpent7 The way to load credentials is a little different. There is an example [here](https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/vision/v1/ImageAnnotatorClient.html). Search for "To customize credentials".

I'll close this for now, but please reopen if you still need help.
