### ISSUE TITLE
Document gRPC and common classpath conflicts troubleshooting

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/google-cloud-java#2928]
For ALPN error, refer to [gRPC troubleshooting guide](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting).

Add additional documentation for Guava and Protobuf related errors, and examples to shade.

**Comment by pongad** [comment]
The ALPN error should hopefully not be a problem anymore, since we're using shaded netty now.

I'm not super familiar with shading. Is this something users can do themselves. I thought shading is something library maintainer has to do.

**Comment by saturnism** [comment]
@pongad it won't be a problem until the shaded netty between different gRPC versions become a problem.

This request is to document the potential issues users run into and ways to resolve them.

**Comment by saturnism** [comment]
After #2977, @saturnism to add more details on example exceptions as well as maven configurations.

**Comment by pongad** [comment]
Assigning @saturnism since the PR is merged.

**Comment by pongad** [comment]
@saturnism Can this be closed now?

**Comment by saturnism** [comment]
yes pls! thnx.
