### ISSUE TITLE
Google Cloud Java Libraries for 32 bit

### ISSUE THREAD

**Issue by DhanduS** [GoogleCloudPlatform/google-cloud-java#2946]
The GIT links state that X86_64 Bit is supported. Does it mean that 32 bit OS versions are not supported.

**Comment by pongad** [comment]
That's correct. 32 bit versions are not supported because [netty-tcnative](http://netty.io/wiki/forked-tomcat-native.html) does not support them. You *might* be able to build the package yourself though, if you need it.

Please let us know if you have more questions.
