### ISSUE TITLE
Firestore IT broken

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#2961]
The Firestore integration tests timed out with the latest commit which included Firestore changes:

https://circleci.com/gh/GoogleCloudPlatform/google-cloud-java/1742

We need to do a release today - the Firestore changes probably should be rolled back.

**Comment by garrettjonesgoogle** [comment]
cc @andreamlin @vkedia

**Comment by garrettjonesgoogle** [comment]
cc @snehashah16

**Comment by schmidt-sebastian** [comment]
Hm, the tests are timing out with no messages:

-------------------------------------------------------
Running com.google.cloud.firestore.it.ITSystemTest
Too long with no output (exceeded 10m0s)

I will look at this later. For now, I will revert the commits.

**Comment by schmidt-sebastian** [comment]
Reverts:
https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2964
https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2965

**Comment by garrettjonesgoogle** [comment]
Thanks!

**Comment by garrettjonesgoogle** [comment]
Resolving this because the problem was fixed with a rollback.
