### ISSUE TITLE
Remove dependency on Datastore's client

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#300]

**Comment by garrettjonesgoogle** [comment]
@ajkannan What does this issue mean?

**Comment by ajkannan** [comment]
Cloud Datastore provides a client library that we use instead of the proto-generated code.  For example, see here in the [spi folder](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore/src/main/java/com/google/cloud/datastore/spi/DefaultDatastoreRpc.java#L41).  The client strips out some functionality that would be accessible if we used the proto-generated code directly (e.g. see the mention of #300 in #308).

**Comment by mziccard** [comment]
I would be careful with adopting grpc for the datastore API while grpc is not supported in AE. Some AE users migrated to google-cloud (instead of using the AE client) to be able to reuse their code across platforms. Just some random thougths :)

**Comment by garrettjonesgoogle** [comment]
@mziccard that seems very relevant and not random :-P

**Comment by lesv** [comment]
gRPC should now work on GAE Standard J7 & J8, but isn't yet super performant (neither is REST).

**Comment by garrettjonesgoogle** [comment]
Correction to @lesv 's note - gRPC works on GAE Standard J8, but not J7.

**Comment by garrettjonesgoogle** [comment]
This is redundant with https://github.com/GoogleCloudPlatform/google-cloud-java/issues/493 , which we have added to https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . Closing this issue out.
