### ISSUE TITLE
Re-declare BigQuery as GA

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#3012]
We tried to bump BigQuery to GA in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2982 , but it got erased in the version bump of the release at https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3004/files#diff-9fa081a8634fe9e631cd85762bb9ceb9 . The thing we need to do differently is to change the `released-version` version in the versions.txt file for bigquery instead of only `current-version`, since the version bump script bases the bump on `released-version`. Like last time, we shouldn't update the README files until release.

**Comment by pongad** [comment]
Does this boil down to changing `versions.txt` file but not running the update script (yet)? When we release, the version should get bumped properly then propagated?

**Comment by garrettjonesgoogle** [comment]
Hmm yes, that's what we should do.
