### ISSUE TITLE
UnresolvedAddressException when using GRPC_PROXY_EXP

### ISSUE THREAD

**Issue by aakash-fk** [GoogleCloudPlatform/google-cloud-java#3030]
I am using google-cloud-vision and google-cloud-language.

I need to use the `GRPC_PROXY_EXP` environment variable. However due to a bug in grpc 1.9.0, the proxy variable causes an UnresolvedAddressException. This is documented at https://github.com/grpc/grpc-java/pull/4027.

The problem is fixed in 1.10.0. When will google-cloud-vision/language be updated to use grpc 1.10.0?

Alternatively, is there any other way for me to use a forward proxy with these two libraries?

**Comment by JHiggins26** [comment]
I am also experiencing this issue. Any workarounds?

**Comment by aakash-fk** [comment]
@JHiggins26 What worked for me: manually go through all dependencies of the google cloud library, and for every io.grpc:*:1.9.0 package that you find, add a dependency on version 1.9.1 of that package to your project.

**Comment by HendPro12** [comment]
@JHiggins26 @aakash-fk This workaround of adding dependencies for io.grpc:*1.9.1 did not work for me.

**Comment by hzyi-google** [comment]
gRPC has been [updated](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-api-grpc/pom.xml#L102) in the latest version of google-cloud-java. Please bump the version of google-cloud-java and see if it helps.

**Comment by hzyi-google** [comment]
Hi all,

grpc version has been bumped to 1.12.0. I'll close it here. Please feel free to ask for reopening if you still see a problem.
