### ISSUE TITLE
Pub sub does not seem to work with Java 7 because of gRPC/netty stuff

### ISSUE THREAD

**Issue by j256** [GoogleCloudPlatform/google-cloud-java#3048]
Although the docs state that Java 8 is required, this invalidates its use in my corporate code base which is back on Java 7.   I do see that the class files are Java 7 compliant however.  Is it possible to run under Java 7?  Are there versions of the API that work under 7?

**Comment by garrettjonesgoogle** [comment]
Java 8 is only really required when running under App Engine; otherwise Java 7 is the minimum version ( see https://github.com/GoogleCloudPlatform/google-cloud-java#java-versions ).

**Comment by j256** [comment]
Sigh.  Sorry about that.  Not sure where I got Java 8 from.  Thanks for the quick response.

**Comment by j256** [comment]
Although it runs, I can't get the following test program to run under 0.36, 37, or 38.  It runs under Java 8 however so I suspect that maybe a dependency has a requirement? 

With Java 7 I'm getting the `java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN` class not found error which implies that it is in a different classloader.

Test program:

```
public class TestMain {
	public static void main(String[] args) throws Exception {
		Class.forName("org.eclipse.jetty.alpn.ALPN", true, TestMain.class.getClassLoader());
		String projectId = "my-project";
		String topicId = "test-topic";
		String subscriberId = "test-main";
		ProjectSubscriptionName subsciptionName = ProjectSubscriptionName.of(projectId, subscriberId);
		// SubscriptionName subsciptionName = SubscriptionName.of(projectId, subscriberId);
		Builder builder = Subscriber.newBuilder(subsciptionName, new OurReceiver());
		GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream("/tmp/creds.json"));
		builder.setCredentialsProvider(FixedCredentialsProvider.create(credentials));
		Subscriber subscriber = builder.build();
		subscriber.startAsync().awaitRunning();
		subscriber.awaitTerminated(10000000, TimeUnit.MILLISECONDS);
	}
	private static class OurReceiver implements MessageReceiver {
		@Override
		public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
			System.out.println("received message: " + message.getMessageId());
			consumer.ack();
		}
	}
}
```

My pom is just:

```
	<dependencies>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-pubsub</artifactId>
			<version>0.38.0-beta</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by j256** [comment]
This looks like a problem with the netty gprc 1.9.0.  What a mess.

**Comment by j256** [comment]
I'm going to close this because it is an overlap with https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3044
