### ISSUE TITLE
Update READMEs for BigQuery

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#3051]
- Main README: move to GA section
- BigQuery README: remove warning about being work-in-progress

and update anything else that is amiss...

**Comment by marcin-kolda** [comment]
Please also update version on https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-install-java as it's confusing.

**Comment by pongad** [comment]
@jabubake Could you tell me how to update the site? Feel free to assign it back to me if you want.

**Comment by jabubake** [comment]
@pongad Ack, submitted request internally to update version (cc-ed you on it). It would be good to have a standing instruction on updating the docs every time a release is cut for the library.

**Comment by pongad** [comment]
Everything is up to date now.
