### ISSUE TITLE
We should set ServiceOptions.applicationName as the user-agent in Datastore requests.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#308]
PR #307 provides a way to get a string in the following format "gcloud-java/xxxx" (xxxx stands for the version) from the service options. We should set it for every service.

The typical way to set it for apiary clients is via `setApplicationName` on the apiary service builder.

When #300 is fixed that should be simple as we will have access directly to the apiary (or gRPC) client
though it would be nice a way to specify it even before that.

For more info see #278

**Comment by mziccard** [comment]
This was fixed in #1282
