### ISSUE TITLE
Need to flush the Google Pub/Sub batch so that it delivers immediately?

### ISSUE THREAD

**Issue by j256** [GoogleCloudPlatform/google-cloud-java#3081]
I am using the batch system in Pub/Sub to increase throughput but our system also takes a check-point every so often when all of the messages should be pushed out.

Right now the `Publisher.publishAllOutstanding()` method is `private`.  Please consider making it public or otherwise providing some mechanism to flush the batch buffers.

Thanks.

**Comment by pongad** [comment]
Resolved by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3093
