### ISSUE TITLE
[Firestore] Need unit testing guidelines

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/google-cloud-java#3098]
In the `google-cloud-firestore` package, many of the public API classes are `final`.  In the Android SDK we explicitly made these classes non-final to enable unit testing, with a big warning saying that general purpose subclassing is not supported.

For server-side Java we should do one of:

1. Un-`final` the classes
2. Recommend users to try Mockito 2.0 or PowerMock
3. Adopt some other method ... maybe see what other Cloud SDKs do for testability

cc @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
Fixed with #3176
