### ISSUE TITLE
What would be the correct import? com.google.cloud.speech.v1 or com.google.cloud.speech.v1beta1

### ISSUE THREAD

**Issue by ravindu** [GoogleCloudPlatform/google-cloud-java#3119]
Hi All,
I'm having doubt that what would be the correct import to be used in google-clould-java streaming because i found some examples which have used both **com.google.cloud.speech.v1** and **com.google.cloud.speech.v1beta1** imports. Looking forward for  to hear your valuable suggestions.

Thanks in advance

**Comment by pongad** [comment]
@ravindu I'd use `v1`. We created `v1beta1` when the API was not yet stabilized. Now that it has, I think we should use v1 for production.

**Comment by wathsala-w** [comment]
@pongad if we are to get latest bug fixes (RC version), is it good enough to experiment with com.google.cloud.speech.v1p1beta1.* ? Below example also use that package, with last update 8 days back.

https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/Recognize.java

**Comment by pongad** [comment]
All the speech clients are generated with the same mechanism, so using `v1p1beta1` probably won't fix any bugs client-side. That said, if the RC version have a feature you want to experiment with, I think using it is the right choice.

**Comment by wathsala-w** [comment]
Thanks @pongad. Where can i find the release notes on SDK release versions?

**Comment by pongad** [comment]
Does [this](https://github.com/GoogleCloudPlatform/google-cloud-java/releases) have what yo need?

**Comment by wathsala-w** [comment]
@pongad oh ok, it's for the suite. Thanks.
