### ISSUE TITLE
Publish javadocs to maven central

### ISSUE THREAD

**Issue by jontejj** [GoogleCloudPlatform/google-cloud-java#3133]
Javadocs are published to [http://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/](http://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/) but not to
[http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.appengine%22%20AND%20a%3A%22appengine-api-1.0-sdk%22](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.appengine%22%20AND%20a%3A%22appengine-api-1.0-sdk%22). Why is that? This can easily be configured by
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>2.7</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
</plugin>
```
Which it is by default if you use
```xml
	<parent>
		<groupId>org.sonatype.oss</groupId>
		<artifactId>oss-parent</artifactId>
		<version>9</version>
	</parent>
``` 
in the root pom. I can see that you have a "release" profile that should enable this. Was that profile not used during the release?

**Comment by hzyi-google** [comment]
@garrettjonesgoogle Do you think this is what we should do?

**Comment by garrettjonesgoogle** [comment]
We do already push artifact-specific docs to maven, e.g. http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.cloud%22%20AND%20a%3A%22google-cloud-spanner%22

We just don't have a top-level target that makes a jar with all javadocs under google-cloud-java. I think we're doing the right thing from a bundling perspective.

**Comment by jontejj** [comment]
So I'm not supposed to use
```
<dependency>
  <groupId>com.google.appengine</groupId>
  <artifactId>appengine-api-1.0-sdk</artifactId>
  <version>1.9.65</version>
</dependency>
```

as a dependency? Would be convenient to have the sources for the artefact that is used, so that IDEs can download it automatically.

**Comment by garrettjonesgoogle** [comment]
appengine-api-1.0-sdk doesn't come from this repository...

**Comment by jontejj** [comment]
Whereabouts would that be coming from then? :)

**Comment by garrettjonesgoogle** [comment]
It is built from internal source code. In order to file an issue to the App Engine team, find the relevant link in https://cloud.google.com/support/docs/issue-trackers .

**Comment by jontejj** [comment]
Nah, that's too cumbersome for me. It's not that important for me
