### ISSUE TITLE
Allow adding google credentials through logback appender code or xml configuration

### ISSUE THREAD

**Issue by moshevi** [GoogleCloudPlatform/google-cloud-java#3137]
Any reason why the only option to inject credentials to google-cloud-logging-logback is through the GOOGLE_APPLICATION_CREDENTIALS environment variable?
Any option to add it to the appender configuration file or code?
Thanks.

**Comment by andreamlin** [comment]
Closing this issue because it is similar to https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3215. Please continue discussion there.
