### ISSUE TITLE
Bigtable: Admin should have proto utility methods

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-java#3141]
There are some complex protobuf objects.  Here are some possibilities where utilities might come in handy:

- any message with "oneof" gets confusjng, since users set multiple values (`AppProfile`, `DropRowRangeRequest`, `ModifyColumnFamiliesRequest`)
- `Instance` messages are complex
- `PartialUpdateInstanceRequest` use `google.protobuf.FieldMask` which is quite confusing
- `CheckConsistency` is used for for polling, so it's ideal having a utility for this kind of functionality
- "TableExists" type functionality should use ListTables instead of GetTable, since it's less expensive.  Users should have a clear API that produces the most efficient calls.

**Comment by hzyi-google** [comment]
I'm not sure about priority. Feel free to bump if necessary.

**Comment by igorbernstein2** [comment]
I'm still in the process of cleaning things up, but the wrappers have landed.
