### ISSUE TITLE
Pub/Sub: Mitigate message duplication to due stuck stream-close signal

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-java#3146]
As documented offline, Pub/Sub streamingPull may result in a high duplicate rate because the server terminates a streamingPull connection by sending a signal down the stream. This signal is delivered to the client after the messages already in the stream buffer are processed. As a result, the client may send acks and modifyAckDeadline's up a stream that has already been broken, leading to their loss.

To close this bug:
- Agree on a mitigation strategy. Currently, it is to send acks and modifyAckDeadline's as separate requests (synchronous or streaming?)
- Implement in Java.
- Validate that the implementation does not lead to performance degradation or extreme delays in ack and modAck delivery to the server, which would again lead to high rate of duplication.
- Reproduce in other clients. 

This is GA launch blocking.

**Comment by pongad** [comment]
The reference implementation in Java is already completed in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3123

**Comment by pongad** [comment]
From meeting today, this was closed by #3123
