### ISSUE TITLE
Pub/Sub: When returnImmediatly is set to false in a PullRequest it sometimes ignores messages

### ISSUE THREAD

**Issue by idoshamun** [GoogleCloudPlatform/google-cloud-java#3168]
I use this snippet for implementing sync pulling:
https://cloud.google.com/pubsub/docs/pull#synchronous-pull

Sometimes when there is a few minutes gap between messages, this snippet doesn't return `PullResponse` and hangs on the request call.

I ended up doing something like this in the meantime which works perfectly but I don't like the implementation (scala):
```scala
Future {
        val pullRequest = PullRequest.newBuilder().setMaxMessages(1).setReturnImmediately(true)
          .setSubscription(subscription.toString).build()
        val pullResponse = subscriber.pullCallable().call(pullRequest)
        pullResponse.getReceivedMessagesList.asScala
      }.flatMap { list =>
        if (list.isEmpty) {
          Thread.sleep(10)
          pull()
        } else {
          Future.successful(list.foreach(callback.invoke))
        }
      }
``

**Comment by pongad** [comment]
@mdietz94 I think this might be a server issue?

**Comment by mdietz94** [comment]
It's WAI. When return immediately is false we may hang up until the max rpc deadline so that we get as many messages as possible. Lowering max messages or reducing the RPC deadline will change the behavior.

**Comment by idoshamun** [comment]
I see, thanks. I thought it should not hang up until messages arive
