### ISSUE TITLE
BigQuery: Cannot list jobs when there has been an invalid job request

### ISSUE THREAD

**Issue by alixhami** [GoogleCloudPlatform/google-cloud-java#3178]
I recently ran an invalid job outside of the Java BigQuery client library, and when I try to list jobs when running the BigQuery samples tests with the Java client library, I get an error:

```
Running com.google.cloud.examples.bigquery.snippets.ITBigQuerySnippets
Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 162.203 sec <<< FAILURE! - in com.google.cloud.examples.bigquery.snippets.ITBigQuerySnippets
testJob(com.google.cloud.examples.bigquery.snippets.ITBigQuerySnippets)  Time elapsed: 1.602 sec  <<< ERROR!
java.lang.IllegalArgumentException: value must be set if and only if the type is not ARRAY
	at com.google.cloud.examples.bigquery.snippets.ITBigQuerySnippets.testJob(ITBigQuerySnippets.java:273)
```

This error comes from from the Java BigQuery client library when it attempts to build an invalid job ([error defined here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/b7b3f21b784a3524f7830f34148abfd3e39677d4/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/QueryParameterValue.java#L116))

This issue is similar to one we fixed in [Python](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4246). The solution we used was to not validate Job objects as they are created from the API, which allowed invalid jobs from the API to be constructed into Job objects.

**Comment by alixhami** [comment]
cc @tswast

**Comment by tswast** [comment]
Presumably Java will need a slightly different solution, as it is statically typed and can't really delay when it attempts to parse the various properties from the API response (or maybe I'm wrong about that?).

The Job resource provides a [status.errors[]](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#status.errors) list (exposed in Java as [JobStatus.getExecutionErrors()](https://googlecloudplatform.github.io/google-cloud-java/0.45.0/apidocs/com/google/cloud/bigquery/JobStatus.html#getExecutionErrors--)), so maybe we could parse to a default value in the case of errors with the expectation that they can check this property when listing / getting a failed job.
