### ISSUE TITLE
How to pass Audio from Microphone to Google Speech To Text?

### ISSUE THREAD

**Issue by goxr3plus** [GoogleCloudPlatform/google-cloud-java#3188]
I can't find any example for this functionality on the repository : 

https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-speech

Is it supported at all ?

**Comment by hzyi-google** [comment]
Hi @goxr3plus ,
Can you provide more context? What is the major difference here between audio from microphone and audio produced otherwise?
If you are looking for a streaming call, Speech can take `StreamingRecognizeRequest`. More information about streaming calls can be found [here](https://cloud.google.com/speech-to-text/docs/basics#streaming-requests).

**Comment by goxr3plus** [comment]
Thanks for replying :) . I need to stream audio from computer microphones . I am doing it with another library which supports only Google Cloud Speech Private , though i can't find out how to with your official library in Java .

https://github.com/goxr3plus/java-google-speech-api

**Comment by hzyi-google** [comment]
I am not aware of the private repo for speech as you mentioned, would you mind sharing it? Although I do believe under most circumstances features in a private repo are usually under development and should become public in the future.

**Comment by goxr3plus** [comment]
@hzyi-google What i need is plug-in the microphone to the computer and 10 lines of Java code to get the audio from Microphone and do Speech Recognition with google-cloud-java library ?

How can i do that in Java Code ? I know how to capture audio from the Microphone . 

How can i call StreamingRecognizeRequest with your current Java Library , can we have an example please ?? :)

**Comment by goxr3plus** [comment]
This is the repository i am talking about : https://github.com/goxr3plus/java-google-speech-api

**Comment by goxr3plus** [comment]
I don't need to recognize audio from .flac files etc .... just raw data from Microphone  how i can do it ? 

``` JAVA
 try (SpeechClient speechClient = SpeechClient.create()) {
   RecognitionConfig.AudioEncoding encoding = RecognitionConfig.AudioEncoding.FLAC;
   int sampleRateHertz = 44100;
   String languageCode = "en-US";
   RecognitionConfig config = RecognitionConfig.newBuilder()
     .setEncoding(encoding)
     .setSampleRateHertz(sampleRateHertz)
     .setLanguageCode(languageCode)
     .build();
   String uri = "gs://bucket_name/file_name.flac";
   RecognitionAudio audio = RecognitionAudio.newBuilder()
     .setUri(uri)
     .build();
   RecognizeResponse response = speechClient.recognize(config, audio);
 }
```

**Comment by hzyi-google** [comment]
If your question is how to capture audio from outside the computer using java, [this](https://docs.oracle.com/javase/tutorial/sound/capturing.html) might be what you want to refer to.

**Comment by goxr3plus** [comment]
Thank you, but my question is let's say i capture the audio from the
Microphone, how to pass the Audio to the Google Text To Speech Library so
it returns text,  in real time.

I need to do Real Time Speech Recognitom from 🎤 microphone using your
library how i can do it?

**Comment by goxr3plus** [comment]
@hzyi-google  My dear friend i am waiting an answer on this , it is very important :) .

**Comment by hzyi-google** [comment]
Here comes the answer my dear friend :-) Sorry I was quite busy in the past few days.

Suppose your microphone has an interface similar to `Iterable`:
```java
interface Microphone {
	
  boolean hasNext();
  Audio next();

}
```

Then you could use `splitCall` in [`BidiStreamingCallable`](https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/rpc/BidiStreamingCallable.java) this way:

```java

try (SpeechClient client = SpeechClient.create()) {

  ResponseObserver<StreamingRecognizeResponse> responseObserver =
      new ResponseObserver<StreamingRecognizeResponse>() {
    
    public void onStart(StreamController controller) {
      // do nothing
    }

    public void onResponse(StreamingRecognizeResponse response) {
      // do something with the response
    }

    public void onComplete() {
      // do something to close up
    }

    public void onError() {
      // do something to handle errors
    }
  }

  ClientStream<StreamingRecognizeRequest, StreamingRecognizeResponse> clientStream =
	    speechClient.streamingRecognizeCallable().splitCall(responseObserver);
  
  StreamingRecognitionConfig config = StreamingRecognitionConfig.newBuilder()
    ... // set up config
    .build();

  StreamingRecognizeRequest configRequest = StreamingRecognizeRequest.newBuilder()
    .setStreamingConfig(configRequest)
    .build();  // The first request in a streaming call has to be a config

  clientStream.send(configRequest);
  
  while (microphone.hasNext()) {
    StreamingRecognizeRequest request = 
        createRecognizeRequestFromMicrophone(microphone.next()); // create streaming requests
    clientStream.send(request);
  }
}
```

Is this what you want?

**Comment by goxr3plus** [comment]
The code produces no errors except the credentials .

```JAVA
java.io.IOException: The Application Default Credentials are not available. They
 are available if running in Google Compute Engine. Otherwise, the environment v
ariable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defini
ng the credentials. See https://developers.google.com/accounts/docs/application-
default-credentials for more information.
```

Is there any tutorial on how to provide the credentials , i have already setup projects on Google Cloud Engine , i have Client ID and Secret Key , Access Tokens etc for Google Speech Recognition , how though i can provide them from the Java code :)

Thank you very much for helping me , all these will become tutorials on youtube by me for other people .

**Comment by goxr3plus** [comment]
@hzyi-google In attempts of improvements i tried to modify the code to use .FLAC encoding because it is better , so added this on pom.xml

```XML
<dependency>                                  
	<groupId>com.github.axet</groupId>        
	<artifactId>java-flac-encoder</artifactId>
	<version>0.3.8</version>                  
</dependency>                                 
```

`.setEncoding(RecognitionConfig.AudioEncoding.FLAC)`

But getting the below error : 

```java
com.google.api.gax.rpc.CancelledException: io.grpc.StatusRuntimeException: CANCE
LLED: Failed to read message.
Jul 02, 2018 3:06:09 AM io.grpc.netty.shaded.io.netty.handler.codec.http2.Defaul
tHttp2ConnectionDecoder$FrameReadListener shouldIgnoreHeadersOrDataFrame
INFO: [id: 0x7eac131d, L:/192.168.1.5:5048 - R:speech.googleapis.com/172.217.23.
138:443] ignoring HEADERS frame for stream RST_STREAM sent. {}

```

**Comment by hzyi-google** [comment]
`OutOfRangeException`: speech currently [limit the streaming request to 1 minute](https://cloud.google.com/speech-to-text/quotas). Probably you could follow the discussions [here](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/807) and see if you could work around it in java.

`CancelledException`: You wouldn't need another artifact just to `setEncoding(RecognitionConfig.AudioEncoding.FLAC)`. If you were to encode the audio from your microphone using the artifact above before sending them to speech api, it's likely you did not encode the audio correct. Please verify it if that's the case (probably play it?), and if you still have this issue please let me know.

**Comment by goxr3plus** [comment]
I see from description that  , LINEAR16 is at least double size of FLAC and that affects the speed of sending audio to Google Servers and getting back response : 

```XML
[`FLAC`](https://xiph.org/flac/documentation.html) (Free Lossless Audio
 Codec) is the recommended encoding because it is
 lossless--therefore recognition is not compromised--and
 requires only about half the bandwidth of `LINEAR16`. `FLAC` stream
 encoding supports 16-bit and 24-bit samples, however, not all fields in
 `STREAMINFO` are supported.
```

Have you any way in mind that i can support FLAC Encoding :) ?

**Comment by hzyi-google** [comment]
This is beyond the code in google-cloud-java and beyond the scope of my knowledge, sorry. You could probably share your question in their repo. I would still be happy to help you with questions related to speech api.

**Comment by hzyi-google** [comment]
I'm going to close it here but feel free to ask for reopen if you still have problems with speech api.

**Comment by absin1** [comment]
I tried this code. But the 
`public void onResponse(StreamingRecognizeResponse response) {
		System.err.println("REAL Time Response >>" + response);
}` takes a long time to respond. It's not realtime at all. I know streaming speech to text should be near realtime, it works on all android devices and on web ([here](https://www.google.com/intl/en/chrome/demos/speech.html)). 
What can be the issue. My byte stream is coming near real time. I know this because I print the byte stream as soon as I mute my microphone the array goes all 0s. Can you help?

**Comment by goxr3plus** [comment]
Also a good think is to send FLAC audio to the server,that's why i asked it
before :)

**Comment by absin1** [comment]
As it happens, I am accurately aware of the exact nature of my stream. It's coming from a VoIP call. The bitrrate is 16, 8000 frames per second and mono channeled raw pcm. It comes encoded in u law, but that is taken care of before forwarding it to google asr. Every byte array I add to the client stream is 320 in length. Should I accumulate it before sending it to google? Is it too small to be sent?

**Comment by absin1** [comment]
"Can you change the 10 above to probably 1000 or larger to see if that solves your problem?" Thanks a lot for responding promptly. I am actually using a sip client. I have redirected the stream meant for speakers to the clientstream object. At a time 320 sized byte array.

**Comment by hzyi-google** [comment]
In that case can you share how you redirected the stream? And can you estimate how long the delay is?

**Comment by absin1** [comment]
Hi I was AFK over the weekend. I am using an SIP client called peers. I get the incoming audio as a byte array. For brevity take a look [here](https://github.com/absin1/peersNew/blob/master/peers-demo/src/main/java/net/sourceforge/peers/demo/StreamSoundManager1.java). The `init()` method gets called when the java VOIP client receives the call. Here I inititalize the stream etc. The `writeData(byte[] buffer, int offset, int length)` receives the data (at real time, I checked this already) from the other person on the VOIP. I just add this to `clientStream`. Please suggest.
