### ISSUE TITLE
Merge without code review allowed

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#3206]
See https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3193 for example.

"Review has been requested on this pull request. It is not required to merge."

I suspect the repo should be configured to require review before merge.

**Comment by pongad** [comment]
This sounds like a good idea. I don't have the powers to do this, but I'll assign @garrettjonesgoogle .

**Comment by hzyi-google** [comment]
Seems like this is done. Please reopen if it's not.
