### ISSUE TITLE
ThreadManager not available on Google Cloud Java

### ISSUE THREAD

**Issue by bhagyas** [GoogleCloudPlatform/google-cloud-java#3213]
It is available in AppEngine SDK, but not on Google Cloud Java. This limits applications from being ported over to the new SDK.

**Comment by elharo** [comment]
Not sure this is a google-cloud-java issue. Google Cloud Java is not a replacement for the App Engine Java SDK. Can you elaborate? Did you mean the Cloud SDK?

**Comment by bhagyas** [comment]
T
hank you.
This was resolved by adding Google AppEngine API as a dependency.
