### ISSUE TITLE
Logging to root handler doesn't work

### ISSUE THREAD

**Issue by papudesi** [GoogleCloudPlatform/google-cloud-java#3220]
We use [tomcat-runtime](https://github.com/GoogleCloudPlatform/tomcat-runtime), and our logging.properties looks like this:

```
handlers = com.google.cloud.logging.LoggingHandler
.level = INFO

com.google.cloud.logging.LoggingHandler.level = INFO
com.google.cloud.logging.LoggingHandler.log = gae_app.log
com.google.cloud.logging.LoggingHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = %3$s: %5$s%6$s

.handlers = com.google.cloud.logging.LoggingHandler
```

Adding something like `org.apache.handlers` works, just not for the root handler.

**Comment by pongad** [comment]
I'm unable to reproduce this. Could you try doing this at startup?
```java
for (Handler handler : Logger.getLogger("").getHandlers()) {
    System.err.println(handler);
}
```
On my machine, this properly prints `com.google.cloud.logging.LoggingHandler@6b0d80ed` signifying that the handler is registered. (The `6b0d80ed` is irrelevant here.)

**Comment by papudesi** [comment]
@pongad verified there are no root loggers:
```
    Logger rootLogger = Logger.getLogger("");
    System.err.println("# Root handlers = " + rootLogger.getHandlers().length);
    for (Handler handler : rootLogger.getHandlers()) {
      System.err.println(handler);
    }
```
And from the logs:
```
# Root handlers = 0
```

**Comment by meltsufin** [comment]
Just to make sure, are you both running the same version of the `google-cloud-logging` library?

**Comment by pongad** [comment]
@meltsufin Thank you for taking a look. I am running `1.28.0`. I'm confused how this is happening though, since IIUC the logic to read and logging configuration file isn't in `google-cloud-logging`. My current suspicion is that the tomcat runtime is doing something funny, but I'm completely willing to be told I'm wrong.

**Comment by meltsufin** [comment]
@pongad The logging configuration is loaded by Tomcat itself. The runtime is not really doing anything with it. We do have a [sample app](https://github.com/GoogleCloudPlatform/tomcat-runtime/blob/master/tests/test-war-integration/src/main/resources/logging.properties) that actually registers a root handler that may aid with debugging.

**Comment by papudesi** [comment]
@meltsufin @pongad I'm using `1.14.0` (on account of #3219) :)

**Comment by papudesi** [comment]
@meltsufin @pongad seeing the same thing with `1.28.0` as well.

**Comment by pongad** [comment]
@papudesi From investigating this, I don't think the problem is with the client lib. Does this problem occur in any other runtime? (Tomcat was never GA and now deprecated; the runtime team encourages you to move to Jetty runtime.)

**Comment by hzyi-google** [comment]
It seems the issue has been resolved here. Please ask for reopen if not.
