### ISSUE TITLE
Requester Pays on NIO

### ISSUE THREAD

**Issue by Horneth** [GoogleCloudPlatform/google-cloud-java#3221]
There is an option on `BlobSourceOption` and `BlobWriteOption` to specify the billing project to use when accessing a requester pays bucket, but there doesn't seem to be a way to wire that through NIO.
Am I missing it ? And if not is this something that could be considered ?

**Comment by Horneth** [comment]
A more specific suggestion would be to add the relevant options for `userProject`: [`BlobSourceOption`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/92a07265ed884a7f772146739684fc12d7e2ff56/google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L640), [`BlobGetOption`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/92a07265ed884a7f772146739684fc12d7e2ff56/google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L730), [`BlobWriteOption`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/92a07265ed884a7f772146739684fc12d7e2ff56/google-cloud-clients/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L546)
to all calls to the Storage object such that the billing project is always explicitly set. Would there be any objection to that ? I'm happy to make a PR.
I'm thinking [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/92a07265ed884a7f772146739684fc12d7e2ff56/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java#L191), and where necessary in `CloudStorageFileSystemProvider`.

This is problematic for us because it prevents using of any requester pays enabled buckets through NIO.

@jean-philippe-martin any thoughts ? :)

**Comment by jean-philippe-martin** [comment]
That's a good idea, I would welcome a PR yes. Make sure to mention me in it so I can find it easily!

**Comment by droazen** [comment]
@Horneth Do you have a PR for this feature ready to go, or could you easily make one?

**Comment by jean-philippe-martin** [comment]
Code is now in, the feature should be available. Let me know how it goes, and mention me in a new bug if you run into any difficulty!

**Comment by jean-philippe-martin** [comment]
@hzyi-google, would you mind please closing this issue? I am not able to do it myself.

**Comment by hzyi-google** [comment]
Sure. Thanks for contributing!

**Comment by jean-philippe-martin** [comment]
Thank you, @hzyi-google !

**Comment by hzyi-google** [comment]
@jean-philippe-martin There are integration tests failing. Can you double check?

**Comment by jean-philippe-martin** [comment]
Yes I can look into it @hzyi-google . Do you have something a bit more specific? Do you mean the `ITStorageTest` test suite?

**Comment by hzyi-google** [comment]
From my side, `testCantCreateWithoutUserProject`, `testCantReadWithoutUserProject`, `testCantCopyWithoutUserProject` and `testFileExistsRequesterPaysNoUserProject` are failing (the last one is an error).

**Comment by hzyi-google** [comment]
@jean-philippe-martin Yes you are right. Our testing project do have the permission to the method in resourcemanager api. And the test with errors is for the same reason. I'll create a separate github issue for this and ignore the tests for now. Thanks for the clarification :)

**Comment by jean-philippe-martin** [comment]
@hzyi-google great, I'm glad the mystery is solved! 

Hopefully there is some way you can use a project without these permissions, so you can restore the tests on your side. Or split the integration tests into two parts, one with that permission and one without.
