### ISSUE TITLE
unable do junit testing of TableResult outside of package

### ISSUE THREAD

**Issue by ymcjava** [GoogleCloudPlatform/google-cloud-java#3228]
I am using table to result to get the result from query job and then using a FieldValueList to iterate the list of row and is working fine, However when I do the junit testing for this code , I tried the TableResultTest and getting error that TableResult() not available publicly. Is there any way I can populate the FiledValueList in TableResult and do the unit test on different package

 TableResult result = queryJob.getQueryResults();

for (FieldValueList row : result.iterateAll()) {
}

**Comment by jackbarantee** [comment]
Thanks a lot a for fixing this issue

**Comment by ymcjava** [comment]
Thanks for fixing this issue
