### ISSUE TITLE
import com.google.pubsub.v1.ProjectTopicName cannot be resolved

### ISSUE THREAD

**Issue by LiviuArln** [GoogleCloudPlatform/google-cloud-java#3230]
So I am using Gradle to build the project and implicitly get your library. If you have some other dependencies with the same packages names inside, the dependency is not grabbed by Gradle. Otherwise the class is missing even from your sources here. 

I see "mvn compile " fails for pubsub ... Not expecting this kind of issues here ...

Please advise

**Comment by pongad** [comment]
@LiviuArln I think we need more details or reproduction step. If I create a new Gradle project and add
```
dependencies {
	compile 'com.google.cloud:google-cloud-pubsub:0.47.0-beta'
}
```
everything works fine. Perhaps you're not pulling dependencies pubsub library neds?

**Comment by hzyi-google** [comment]
The issue seems to have been resolved here. Please ask for reopen if not.
