### ISSUE TITLE
SessionPool logging is using wrong object string to replace

### ISSUE THREAD

**Issue by carlzogheib** [GoogleCloudPlatform/google-cloud-java#3235]
Class: `com.google.cloud.spanner.SessionPool`
Function: `PoolMaintainer.closeIdleSessions(Instant currTime)`

`logger.log(Level.FINE, "Closing session %s", sess.getName());`
Should instead be
`logger.log(Level.FINE, "Closing session {0}", sess.getName());`
to replace `{0}` with `sess.getName()`, otherwise all it's logging is `Closing session %s`

**Comment by pongad** [comment]
Closed by https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3224

**Comment by pongad** [comment]
Sorry closed wrong issue :cry:
