### ISSUE TITLE
Google DLP broken with 0.46.0-beta: Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found

### ISSUE THREAD

**Issue by henrik-io** [GoogleCloudPlatform/google-cloud-java#3236]
Ever since the Google DLP service went from V2Beta to GA, my production code is broken. I'm getting an exception with a message like this: 

`Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found`

I'm stepping through the execution in the debugger, and I can see what looks like a URL referencing the old service:
`google.privacy.dlp.v2beta1.DlpService/RedactContent`. See attached screen shot for details. My production service that uses DLP is not functional, and it's a big deal to re-deploy without DLP. What do I need to do to get this to work again? 

<img width="676" alt="screen shot 2018-05-07 at 9 53 11 am" src="https://user-images.githubusercontent.com/32073685/39713721-a1c0fc2e-51dc-11e8-8a75-764de29f2fd0.png">

**Comment by pongad** [comment]
Hi @henrik-io . I don't think this is an issue with the client lib. According to the DLP team, the beta endpoint has just been turned down. Could you migrate to `com.google.cloud.dlp.v2` package instead?

**Comment by henrik-io** [comment]
Hi @pongad and thanks for your response. It never struck me to check the imports as I didn't realize there were package paths with specific Beta versions. Maybe I missed something or didn't get the memo, but I don't recall reading about package path changes for the GA migration. If the Beta API has been retired, I'd suggest removing those packages altogether from the jar files going forward. I'd rather take a compilation error than a runtime surprise.

**Comment by pongad** [comment]
I can completely understand the confusion. We're actually planning to remove the beta package this week.

**Comment by henrik-io** [comment]
Awesome. Did the V2Beta types RedactContentRequest/RedactContentResponse disappear? What's the V2 equivalents? Thanks.

**Comment by henrik-io** [comment]
@pongad it seems like quite a bit has changed between the V2Beta1 and GA versions. Is there a migration guide? I looked in the examples section, but it seems like `https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/dlp/src/main/java/com/example/dlp/Redact.java` only deals with redacting images. It would be very helpful with a real example for redacting text and maybe a migration guide. Thanks.

**Comment by pongad** [comment]
I also cannot seem to find a migration guide, but [this](https://cloud.google.com/dlp/docs/deidentify-sensitive-data) might help you. I believe text redaction functionality has been moved to `deidentifyContent`.
