### ISSUE TITLE
Not able to run this sample project 

### ISSUE THREAD

**Issue by Mahawbc** [GoogleCloudPlatform/google-cloud-java#3244]
I have created new json with new google console project but its not working. when i going to run project its giving error like "Failed to obtain access toke com.fasterxml.jackson.core.JsonParseException:Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')" and 
"java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.google.auth.oauth2.AccessToken.getExpirationTime()' on a null object reference"
 here i have attached my json file also. Give solution for this issue

**Comment by andreamlin** [comment]
Hello! What does this json file describe? Is the json file the service account credentials file? Otherwise, if it isn't sensitive info, can you attach the json file?

**Comment by hzyi-google** [comment]
Closing it due to not hearing back from customer. Please ask for reopen if the issue still exists.
