### ISSUE TITLE
Batched Requests don't honor the host setting

### ISSUE THREAD

**Issue by albertzaharovits** [GoogleCloudPlatform/google-cloud-java#3254]
Batch endpoint always hits `www.googleapis.com` irrespective of the `host` setting on the `StorageOptions` that built the storage client.
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/52b727aef88ae76984aa3c02b4d7067e198d34b7/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L191

**Comment by hzyi-google** [comment]
Hi @albertzaharovits ,
IIRC batch requests of all google apis have to hit "https://www.googleapis.com/batch/[api_name]/[endpoint]". Is there a reason you want to change the batch URL?

**Comment by pongad** [comment]
@hzyi-google I think we should fix this. For example, the user could be pointing the client to a test instance when integration testing. Right now, everything will hit the test instance, but batches will get to the real one, which is probably really confusing.

**Comment by albertzaharovits** [comment]
Hi @hzyi-google ,

I was expecting that `StorageOptionsBuilder.setHost` be consistent across APIs. It is impractical if only certain APIs follow this setting.

As @pongad hinted, our usecase is in the scope of integration testing. Specifically the GCS repository plugin for elasticsearch. The mock integ server is here: https://github.com/elastic/elasticsearch/blob/master/plugins/repository-gcs/qa/google-cloud-storage/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageTestServer.java

We have skirted around it by using this hack: https://github.com/elastic/elasticsearch/blob/c351b51ac4f322ec5453806a8a0af027a71d5802/plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageService.java#L121

**Comment by hzyi-google** [comment]
@pongad @albertzaharovits Thanks for pointing this out. I'll work on this.
