### ISSUE TITLE
All README links to specific products (i.e. Datastore, Dialgoflow, etc.) are broken

### ISSUE THREAD

**Issue by matthewayne** [GoogleCloudPlatform/google-cloud-java#3260]
All README links that point to a specific product i.e. Datastore, Dialogflow, etc. are broken

Example: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore

**Comment by Mistic92** [comment]
I see everything was moved to https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients
