### ISSUE TITLE
Unit test firestore: Mocking DocumentReference and CollectionReference

### ISSUE THREAD

**Issue by einevea** [GoogleCloudPlatform/google-cloud-java#3263]
We are trying to test classes with dependencies on firestore and we found we cannot mock these classes because their constructors are internal. Is it possible if the following methods return interfaces instead of classes: 

val collectionReference:CollectionReference = db.collection(collectionName)
val document: DocumentReference = collectionReference.document(docId)

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over. I filed an internal issue and will update you as we make progress.

**Comment by mustafaakin** [comment]
We need them too for unit testing purposes

**Comment by AbhishekChugh** [comment]
Looks like the constructor of CollectionReference was missed in the fix

**Comment by schmidt-sebastian** [comment]
Follow up PR: https://github.com/googleapis/google-cloud-java/pull/6054
