### ISSUE TITLE
TraceLoggingEnhancer sets trace ID in the wrong field

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-java#3280]
The trace ID of a log entry is being set [in the wrong field](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/TraceLoggingEnhancer.java#L61) (label).

In order for the log entries to be linked to the trace, the `TraceLoggingEnhancer` needs to look something like [this](https://github.com/spring-cloud/spring-cloud-gcp/pull/683/files#diff-808bd3f7c7330cf558cdec7c5f754906).
1) Use `setTrace()`, not `setLabel()`
2) Use a `project/myProjectId/traces/myTraceId` format.

**Comment by andreamlin** [comment]
Pull request: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/3301
