### ISSUE TITLE
[BigQuery] TableId.setProjectId ignored if non-null value exists

### ISSUE THREAD

**Issue by MMMarcy** [GoogleCloudPlatform/google-cloud-java#3283]
As per the title, calling [setProjectId](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableId.java#L113) to an existing tableId instance is ignored if the existing projectId is not null.

Suggested changing this to:
```java
  TableId setProjectId(String projectId) {
    Preconditions.checkArgument(!Strings.isNullOrEmpty(projectId), "ErrorMSG");
    return TableId.of(projectId, getDataset(), getTable());
  }
```

**Comment by andreamlin** [comment]
Hi MMMarcy, would you like to submit a Pull Request for this?
