### ISSUE TITLE
Google Cloud Javadoc reference page doesn't work anymore

### ISSUE THREAD

**Issue by zenfenan** [GoogleCloudPlatform/google-cloud-java#3289]
The API reference (Javadoc) site for Google Cloud doesn't work anymore. I have seen it working yesterday. And the link to access the site is http://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/index.html

**Comment by hzyi-google** [comment]
Thanks for pointing this out. We are working on it right now. 
This is a dup of #3292, I'll close it here and please follow up in the other issue.
