### ISSUE TITLE
redirect JavaDocs

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-java#3292]
Not very old javadoc links such as https://googlecloudplatform.github.io/google-cloud-java/latest/apidocs/com/google/cloud/bigquery/package-summary.html are now 404.

https://googlecloudplatform.github.io/google-cloud-java/latest should redirect to https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients

ObReference: https://www.w3.org/Provider/Style/URI

**Comment by hzyi-google** [comment]
This is a known issue and we are working on it. Thanks for pointing that out.
