### ISSUE TITLE
Only the first of several US phone numbers in the same input gets de-identified

### ISSUE THREAD

**Issue by henrik-io** [GoogleCloudPlatform/google-cloud-java#3302]
I'm sending an input string with several phone numbers to the DLP service, and it seems like only the first occurrence gets de-identified. My input looks like this: `"My phone number is 408.867.5309 or 650.867.5309"`. My config is:

- Using all available InfoTypes. PHONE_NUMBER is definitely in there.
- The string gets set as one single Row in a Table which is added to a ContentItem.

The request code looks like this:

```
                DeidentifyContentRequest request =
                        DeidentifyContentRequest.newBuilder()
                                .setParent(ProjectName.of(projectId).toString())
                                .setDeidentifyConfig(deidentifyConfig)
                                .setInspectConfig(inspectConfig)
                                .setItem(contentItem)
                                .build();
```

Only the first occurrence of the phone number in the input string above gets de-identified.

**Comment by andreamlin** [comment]
Calling the redaction method with a raw REST call 
```
{
  "inspectConfig": {
    "infoTypes": [
      {
        "name": "PHONE_NUMBER"
      }
    ]
  },
  "deidentifyConfig": {
    "infoTypeTransformations": {
      "transformations": [
        {
          "infoTypes": [
            {
              "name": "PHONE_NUMBER"
            }
          ],
          "primitiveTransformation": {
            "redactConfig": {}
          }
        }
      ]
    }
  },
  "item": {
    "table": {
      "rows": [
        {
          "values": [
            {
              "stringValue": "My phone number is 408.867.5309 or 650.867.5309"
            }
          ]
        }
      ],
      "headers": [
        {
          "name": "sample"
        }
      ]
    }
  }
}
```
also fails, so this error is likely an API error rather than the Java client library error.

An internal bug will be filed for this issue.

Thanks for bringing it to our attention!

**Comment by andreamlin** [comment]
If you call `setMinLikelihood(VERY_UNLIKELY)` on the `inspectConfig`, the result will be `"My phone number is  or "`

The heuristic for phone numbers just didn't conclude, with a high enough confidence, that the second phone number was a phone number.

Hope that solves the problem!

**Comment by andreamlin** [comment]
Closing the issue for now. Feel free to reopen or recomment if there are further related problems.

**Comment by andreamlin** [comment]
Just a follow up, the DLP team responded to the bug saying that they are looking to adjust their heuristics to have higher confidence on that second phone number in the example you provided.

**Comment by henrik-io** [comment]
Awesome! Meanwhile, I followed the suggestion in the previous response and set the min likelihood to VERY_UNLIKELY and it seemed to get me past my issue.
