### ISSUE TITLE
google-cloud-logging LogEntry is missing a "spanId" field.

### ISSUE THREAD

**Issue by sebright** [GoogleCloudPlatform/google-cloud-java#3325]
I'm writing a LoggingEnhancer for OpenCensus (https://github.com/census-instrumentation/opencensus-java/pull/1212).  I noticed that the Stackdriver LogEntry has a "spanId" field in https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry, but the google-cloud-logging LogEntry class does not ([LogEntry.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java)).  Should both LogEntry data structures have a "spanId"?  If so, I can make a pull request to add the field.

/cc @g-easy

**Comment by hzyi-google** [comment]
That sounds quite reasonable to me. Please feel free to send over pull requests.
(I don't know a lot about logging so @garrettjonesgoogle @pongad please share your inputs if you see a problem here)

**Comment by sebright** [comment]
Thanks!  I made a PR: #3332
