### ISSUE TITLE
Logging - no public API to create SourceLocation.Builder

### ISSUE THREAD

**Issue by solatis** [GoogleCloudPlatform/google-cloud-java#3331]
It appears there is no public API to create a new `com.google.cloud.logging.SourceLocation.Builder` object, thus I am unable to append this metadata to the log entries. 

Expected API would be to have a public `com.google.cloud.logging.SourceLocation.newBuilder()` function, but this is not there.

**Comment by hzyi-google** [comment]
Sounds reasonable.
(While before the method is added, you should be able to use `new SourceLocation.Builder()` to create a builder. It is not optimized but should work, as is used in [tests](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/89436180eb6dabd90bbc38c5600d00f5b262cc36/google-cloud-clients/google-cloud-logging/src/test/java/com/google/cloud/logging/LogEntryTest.java#L53))

**Comment by solatis** [comment]
The problem is that the `SourceLocation.Builder` constructor is also private. This works from the tests because they share the same namespace, but doesn't work others.

**Comment by solatis** [comment]
The problem is that the SourceLocation.Builder constructor is also private, as seen here:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/89436180eb6dabd90bbc38c5600d00f5b262cc36/google-cloud-clients/google-cloud-logging/src/main/java/com/google/cloud/logging/SourceLocation.java#L45

The reason this works in the tests is that they share the same package/namespace, but it doesn't work for others.

**Comment by hzyi-google** [comment]
Oh sorry I missed that. Working on that soon.
