### ISSUE TITLE
Pubsub exception refers to faulty URL

### ISSUE THREAD

**Issue by DylanMeeus** [GoogleCloudPlatform/google-cloud-java#3333]
When I try to use ApiFutures.allAsList(messageIDFutures).get() it raises an exception when the resource name is wrong:

```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid resource name given (name=testresource). Refer to https://cloud.google.com/pubsub/overview#names for more information.
```

However, the URL: https://cloud.google.com/pubsub/overview#names is of no help, as it just points to: https://cloud.google.com/pubsub/docs/overview#names which has no "Overview#names" and thus is of little help in resolving this issue.

**Comment by hzyi-google** [comment]
The error message seems to come from server side. @pongad do you have any ideas who we can talk to?

**Comment by andreamlin** [comment]
@DylanMeeus would https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1 be more helpful? If so, we can change the server side error message to return that URL instead.

**Comment by andreamlin** [comment]
Submitted an internal bug and bug fix.

**Comment by andreamlin** [comment]
The error message will now point to https://cloud.google.com/pubsub/docs/admin#resource_names.
The fix has been submitted internally. I do not know when PubSub releases to production, but I think at the latest it will release in a week. Closing this issue for now.

**Comment by DylanMeeus** [comment]
@andreamlin That is a much more useful page to point to, thank you!
