### ISSUE TITLE
Dependency issues with PubSub and beam-sdks-java-io-google-cloud-platform

### ISSUE THREAD

**Issue by talonx** [GoogleCloudPlatform/google-cloud-java#3363]
I have just introduced Beam libraries along with the GCP I/O (for the PubsubIO unbounded source) jar into my existing project which has Bigtable and PubSub.

My pom dependencies look like this 

```
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>0.34.0-beta</version>
    </dependency>

    <dependency>
      <groupId>com.google.cloud.bigtable</groupId>
      <artifactId>bigtable-hbase-1.x</artifactId>
      <version>1.0.0-pre3</version>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-runners-flink_2.11</artifactId>
      <version>2.4.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-core</artifactId>
      <version>2.4.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.beam</groupId>
      <artifactId>beam-sdks-java-io-google-cloud-platform</artifactId>
      <version>2.4.0</version>
    </dependency>

```
The beam-sdks-java-io-google-cloud-platform dependencies seem to cause a conflict, and maven does not even resolve the dependencies correctly due to conflicting versions. The error message is

```
Could not resolve version conflict among [com.google.cloud:google-cloud-pubsub:jar:0.34.0-beta -> com.google.cloud:google-cloud-core-grpc:jar:1.16.0 -> io.grpc:grpc-protobuf:jar:1.9.0 -> io.grpc:grpc-core:jar:1.9.0,
 com.google.cloud:google-cloud-pubsub:jar:0.34.0-beta -> io.grpc:grpc-netty:jar:1.9.0 -> io.grpc:grpc-core:jar:[1.9.0,
1.9.0],
 com.google.cloud:google-cloud-pubsub:jar:0.34.0-beta -> io.grpc:grpc-stub:jar:1.9.0 -> io.grpc:grpc-core:jar:1.9.0,
 com.google.cloud:google-cloud-pubsub:jar:0.34.0-beta -> io.grpc:grpc-auth:jar:1.9.0 -> io.grpc:grpc-core:jar:[1.9.0,
1.9.0],
 com.google.cloud.bigtable:bigtable-hbase-1.x:jar:1.0.0-pre3 -> com.google.cloud.bigtable:bigtable-hbase:jar:1.0.0-pre3 -> io.grpc:grpc-core:jar:1.5.0,
 org.apache.beam:beam-runners-flink_2.11:jar:2.4.0 -> org.apache.beam:beam-runners-core-java:jar:2.4.0 -> org.apache.beam:beam-model-fn-execution:jar:2.4.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-runners-flink_2.11:jar:2.4.0 -> org.apache.beam:beam-runners-core-construction-java:jar:2.4.0 -> org.apache.beam:beam-model-job-management:jar:2.4.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-runners-flink_2.11:jar:2.4.0 -> org.apache.beam:beam-runners-core-construction-java:jar:2.4.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> io.grpc:grpc-all:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,
1.2.0],
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> io.grpc:grpc-all:jar:1.2.0 -> io.grpc:grpc-okhttp:jar:1.2.0 -> io.grpc:grpc-core:jar:[1.2.0,
1.2.0],
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> io.grpc:grpc-all:jar:1.2.0 -> io.grpc:grpc-protobuf-lite:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> io.grpc:grpc-all:jar:1.2.0 -> io.grpc:grpc-protobuf-nano:jar:1.2.0 -> io.grpc:grpc-core:jar:1.2.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> com.google.cloud.bigtable:bigtable-protos:jar:1.0.0-pre3 -> io.grpc:grpc-core:jar:1.5.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> com.google.cloud.bigtable:bigtable-client-core:jar:1.0.0 -> io.grpc:grpc-core:jar:1.7.0,
 org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.4.0 -> com.google.cloud.bigtable:bigtable-client-core:jar:1.0.0 -> io.opencensus:opencensus-contrib-grpc-util:jar:0.7.0 -> io.grpc:grpc-core:jar:1.6.1]
```
I have tried juggling around with lower/other versions of the PubSub/Bigtable libraries, but that just leads to more, different errors. Is there any way to resolve this? 

I have looked at shading with relocation for the "beam-sdks-java-io-google-cloud-platform" jar but without success. There are related tickets like https://github.com/apache/beam/pull/4727 and the umbrella #2555 , but the latter has been moved to the backlog. Any solutions?

**Comment by talonx** [comment]
Should I raise this against Beam? They have an ongoing discussion about managing dependencies better in their dev mailing list, but this is a blocker for me until they upgrade their dependencies.

**Comment by sduskis** [comment]
Please upgrade Bigtable to 1.4.0.  We started pegging Cloud Bigtable's grpc version to what ever is in google-cloud-java.

**Comment by sduskis** [comment]
@talonx, there's a long standing Beam issue to upgrade grpc.

In the short term,  can remove the explicit `google-cloud-pubsub` dependency and use what ever version `beam-sdks-java-io-google-cloud-platform` uses for `googl-cloud-pubsub` instead?

**Comment by talonx** [comment]
@sduskis - I'll try using whatever pubsub version the Beam library uses, however that might cause other conflicts with Bigtable.

In the meantime, I've gotten around this problem temporarily by building Beam 2.4.0 from scratch using the newer libraries.

**Comment by talonx** [comment]
Also, using bigtable-hbase-beam is not possible for me as that library is Beam-oriented, meaning I need to use the pipeline APIs, which is not my requirement for reading from Bigtable.

**Comment by sduskis** [comment]
Got it.  I'm Cloud Bigtable developer, so my guidance will be geared more towards Bigtable.  Please consider using `bigtable-hbase-1.x-shaded` which does package renaming on critical dependencies like the grpc dependencies.

**Comment by talonx** [comment]
Thanks for the `bigtable-hbase-1.x-shaded` suggestion - that worked for me when I ran the job on Dataflow - it was failing with `bigtable-hbase-1.x`.

**Comment by hzyi-google** [comment]
@sduskis Thanks for answering this issue!
