### ISSUE TITLE
`IntentsClient.listIntents(...)` in the google-cloud-dialogflow library does not retrieve the training phases of an Intent

### ISSUE THREAD

**Issue by mrietveld** [GoogleCloudPlatform/google-cloud-java#3368]
When using the following method: 
`com.google.cloud.dialogflow.v2.IntentsClient#listIntents(com.google.cloud.dialogflow.v2.ProjectAgentName)`, the training phrases are not being returned to the client. 

Locally tested with 0.51.0-alpha

**Comment by hzyi-google** [comment]
Hi @mrietveld,
I wasn't able to repro what you described. Can you provide more context like, how you set up the agent, what's your sample code and what's your result? Thanks!

**Comment by hzyi-google** [comment]
Close it due to inactivity. Please feel free to ask for reopen if the issue still exists.
