### ISSUE TITLE
Upgrade to latest grpc

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#3373]
We currently depend on 1.10.1, but 1.12.0 is available now.

**Comment by hzyi-google** [comment]
@garrettjonesgoogle Can I just bump it manually or should this be done by codegen?

**Comment by garrettjonesgoogle** [comment]
Bump it manually, and run integration tests locally to make sure they pass (since CI doesn't run integration tests on PRs)
