### ISSUE TITLE
Update README for Compute

### ISSUE THREAD

**Issue by andreamlin** [GoogleCloudPlatform/google-cloud-java#3377]
Fix links on https://cloud.google.com/compute/docs/api/libraries#google_apis_java_client_library.

Update google-cloud-compute/README.rst with correct links.

Regenerate the gh_pages branch, and ensure that https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/compute/v1/package-summary.html returns a 200.

**Comment by garrettjonesgoogle** [comment]
gh_pages is generated now, the link works.

**Comment by JustinBeckwith** [comment]
We also need to call out that this library is un-deprecated :) .

**Comment by JustinBeckwith** [comment]
Thank you for the quick turn around!
