### ISSUE TITLE
How to use google application credentials json file with 12factor app on heroku or elsewhere?

### ISSUE THREAD

**Issue by dfuentes77** [GoogleCloudPlatform/google-cloud-java#3385]
We like to stick to the [12factor best practices](https://12factor.net/config) of using environment variables for any credentials.   Using Heroku, we don't want to commit this file to our repo, but we can't include the whole file as an env variable.  

Is there an option using this SDK that allows us to authenticate with only the necessary values from the provided json file, set only as environment variables?

**Comment by hzyi-google** [comment]
Hi @dfuentes77,

[ServiceAccountCredentials.newBuilder()](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L561) might be helpful. With this you should be able to build a `ServiceAccountCredentials` after setting all the entries in the json files pointed by `GOOGLE_APPLICATION_CREDENTIALS` to envrionment variables and then pass that to a `ServiceOptions` or a `Client`:

```
ServiceAccountCredentials credentials = ServiceAccountCredentials.newBuilder()...;
ServiceOptions options = ServiceOptions.newBuilder()
      .setCredentials(credentials)
      .setProjectId("[project-id]")
      .build();
```
Let me know if that helps.

**Comment by ttfreeman** [comment]
> ServiceAccountCredentials.newBuilder()

How do we actually use this in our code? Is there a Node.js example?

**Comment by hzyi-google** [comment]
Hi @ttfreeman, this repo is about Java. For Node.js please check out [google-cloud-node](https://github.com/googleapis/google-cloud-node/issues).
