### ISSUE TITLE
`ServiceOptions.java`: Extract projectId from credentials when provided via .setCredentials`

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#3386]
Handwritten clients that use `ServiceOptions`:

when `.setCredentials` is used, the project id is not extracted from the service account.
This behavior is different when  service account credentials are supplied via `GOOGLE_APPLICATION_CREDENTIALS` env var (project id is extracted)

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L465

Similar issue for BigQuery:
https://github.com/GoogleCloudPlatform/java-docs-samples/issues/936

**Comment by jabubake** [comment]
@hostirosti FYI

**Comment by hostirosti** [comment]
Example:

```
GoogleCredentials creds;
try {
   InputStream is = MyClass.class.getClassLoader().getResourceAsStream("service_account.json");
   creds = GoogleCredentials.fromStream(is);
} catch (IOException e) {
   e.printStackTrace();
   return;
}

ServiceOptions.newBuilder().setCredentials(creds)...
```

**Comment by hzyi-google** [comment]
`ServiceOptions` sets `projectId` and `credentials` separately. It would first look for `projectId` in [this](https://github.com/GoogleCloudPlatform/google-cloud-java#specifying-a-project-id) sequence, and then look for `credentials` in [this](https://github.com/GoogleCloudPlatform/google-cloud-java#authentication) sequence. The reason you have the same `projectId` when you set the credentials through `GOOGLE_APPLICATION_CREDENTIALS` is that this json file is the first place `ServiceOptions` looks for both `projectId` and `credentials` if neither of them is set explicitly. 

Though there has been discussions over whether we should extract the `projectId` from a `ServiceAccountCredentials` when the `credentials` is explicitly passed to the `ServiceOptions`, we generally consider the current behavior intended. Besides, it is possible that users might want the `projectId` to be different from what is provided in the `ServiceAccountCredentials` json file.

We encourage people to use `GOOGLE_APPLICATION_CREDENTIALS` environment variable over other authentication approaches whenever possible. If you have to manually create and set a `credentials`, please also set the `projectId`:
```
ServiceOptions options = ServiceOptions.newBuilder()
    .setCredentials(credentials)
    .setProjectId("[project-id]")
    .build();
```
