### ISSUE TITLE
Java docs for Google Cloud Java clients for older versions are not accessible

### ISSUE THREAD

**Issue by zenfenan** [GoogleCloudPlatform/google-cloud-java#3390]
Recently, changes were done to migrate the Java doc page for Google Cloud client libraries. The latest version of the client libraries' API details can be found at https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html However earlier we could just play with the version on the URL and get the API reference for a particular version like https://googlecloudplatform.github.io/google-cloud-java/0.46.0/apidocs/index.html but now we can't do that anymore. Whatever version we give, it is redirecting to the latest version's page. I think developers should still be able to view the API reference material for the older versions as well.

**Comment by garrettjonesgoogle** [comment]
The space taken up by storing all versions was too high and it wasn't scalable to keep every prior version. 

Note that we generate a javadocs jar for every build and that is available on maven; for example, you can get the javadocs for every previous version of spanner by doing a search on search.maven.org:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.cloud%22%20AND%20a%3A%22google-cloud-spanner%22
