### ISSUE TITLE
can't import the com.google.api.services.bigquery.Bigquery

### ISSUE THREAD

**Issue by Louisepower** [GoogleCloudPlatform/google-cloud-java#3393]
when I ready to export data from BQ  to GCS, there always have errors that 
can't import the com.google.api.services.bigquery.Bigquery;
com.google.api.services.bigquery.model.Job;

**Comment by hzyi-google** [comment]
Hi @Louisepower ,

are the errors about importing the java packages? If you are using the Bigquery library in this repo, I believe you should do:

```java
import com.google.cloud.bigquery.BigQuery;
import com.google.cloud.bigquery.Job;
```

**Comment by hzyi-google** [comment]
Close the issue due to inactivity. Please ask for reopen if the issue still exists.

**Comment by sonia1997** [comment]
Cannot import 
import com.google.api.services.bigquery.Bigquery;
in Java. I am getting an error while writing this code in my Java file.
