### ISSUE TITLE
Unknow topic of "_deleted-topic_" in the list

### ISSUE THREAD

**Issue by weiganglin** [GoogleCloudPlatform/google-cloud-java#3396]
when listing all the topics, the topic of "_deleted-topic_" is returned on the list, which is  not created by user, and cause issue to parsing the topic
`com.google.api.pathtemplate.ValidationException: ProjectTopicName.parse: formattedString not in valid format: Parameter "_deleted-topic_" must be in the form "projects/{project=*}/topics/{topic=*}"
	at com.google.api.pathtemplate.PathTemplate.validatedMatch(PathTemplate.java:454)
	at com.google.pubsub.v1.ProjectTopicName.parse(ProjectTopicName.java:78)`

**Comment by hzyi-google** [comment]
Hi @weiganglin ,

Can you give us a repro sample?

**Comment by weiganglin** [comment]
```ProjectName projectName = ProjectName.of(project);
ListSubscriptionsPagedResponse response = client.listSubscriptions(projectName);
        for (Subscription sub :response.iterateAll())
        {
            try
            {
                String subName = ProjectSubscriptionName.parse(sub.getName()).getSubscription();
                String topic = ProjectTopicName.parse(sub.getTopic()).getTopic();
                subscriptions.put(subName, topic);
            }
            catch (com.google.api.pathtemplate.ValidationException e) 
            {
                LOGGER.warn("Fail to add subscription with topic to map.", e);
            }
        }```

**Comment by hzyi-google** [comment]
Thanks for the response.
`subscription.getTopic()` would return `_deleted-topic_` if the topic has been deleted according to [here](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#subscription). If that's the case for you, I believe it would be OK to just deleted the subscription.

**Comment by weiganglin** [comment]
@hzyi-google Thanks for you reply,  if I create a top "test_topic", and create a subscription "test_sub" listen to the "test_topic", if I delete the "test_topic", and recreate a new "test_topic", if the old "test_sub" will listen to the new created "test_topic"? I thought delete a topic will remove all the subscriptions that listen to that topic.

**Comment by hzyi-google** [comment]
@weiganlin This is intended behavior as listed in [here](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Publisher)(under `DeleteTopic`).
