### ISSUE TITLE
Bigquery list projects

### ISSUE THREAD

**Issue by weiganglin** [GoogleCloudPlatform/google-cloud-java#3397]
I would like have new feature of listing projects. 
The old bigquery library support to list projects, any reason the new library does not support that?

**Comment by shollyman** [comment]
I'd recommend against this, actually.  bigquery.projects.list is an old API method that was created before project metadata was made available directly to users.

These days, resource manager gives you the same information, but with more functionality.  See https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-resourcemanager#listing-all-projects for basic project enumeration, but take a look at the other capabilities there if you're interested in project metadata.

**Comment by hzyi-google** [comment]
Using google-cloud-resourcemanager would be the recommended way to manage projects.

**Comment by weiganglin** [comment]
Thanks, that would be useful
