### ISSUE TITLE
[google-cloud-java][Text-to-Speech][Android] want to use api key

### ISSUE THREAD

**Issue by changemyminds** [GoogleCloudPlatform/google-cloud-java#3400]
I use the [Text-to-Speech Java Library](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-texttospeech) on my Android app. 
I want to use google cloud api-key to use the Text-to-Speech Java Library.

On my android. If I did the following code, it got the error message.
```
try (TextToSpeechClient textToSpeechClient = TextToSpeechClient.create()) { 
}

/* 
error message
java.io.IOException: The Application Default Credentials are not available. 
They are available if running in Google Compute Engine. 
Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials.
See https://developers.google.com/accounts/docs/application-default-credentials for more information.
*/
```
So I read the [Authentication API Keys document](https://cloud.google.com/docs/authentication/api-keys) and found API-Key not support Text-to-Speech, so I can't use api-key to Text-to-Speech Java Library.

If I want to use Text-to-Speech by API-Key or Text-to-Speech Java Library on Android. How can I do it ?

The following code is my command line and execute on mac and It work fine and can get the "audioContent". I think I can use http method by java. Is there any other way ?
```
Curl -H "X-Goog-Api-Key: API_KEY" \
  -H "Content-Type: application/json; charset=utf-8" \
  --data "{
    'input':{
      'text':'Hello I am david, Nice to meet you'
    },
    'voice':{
      'languageCode':'en-gb',
      'name':'en-GB-Standard-A',
      'ssmlGender':'FEMALE'
    },
    'audioConfig':{
      'audioEncoding':'MP3'
    }
  }" "https://texttospeech.googleapis.com/v1beta1/text:synthesize"
```

**Comment by changemyminds** [comment]
I use http method to use the API_KEY on Android and it work fine for me.

The example is [here](https://github.com/changemyminds/GCP_TTS_APIKEY_Android).

If the [Text-to-Speech Java Library](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-texttospeech) can support the API_KEY, please let me know. Thanks.

**Comment by hzyi-google** [comment]
Thanks for the information. Currently there probably won't be a better way, but we are working on an authentication approach for android right now. Please stand by.

**Comment by yankarinRG** [comment]
> Thanks for the information. Currently there probably won't be a better way, but we are working on an authentication approach for android right now. Please stand by.

Hello @hzyi-google, since your reply is one year old, were there any updates on a dedicated Android library for Google Cloud Text-to-Speech?

Thank you.

**Comment by IrfanJam33L** [comment]
heyy can you provide full code? I want to use this API in my app but there is no proper documentation for using it in Android

**Comment by nikste** [comment]
Any update on this?
