### ISSUE TITLE
Drop support for Java 7

### ISSUE THREAD

**Issue by andreamlin** [GoogleCloudPlatform/google-cloud-java#3426]
Clients won't be able to fetch dependencies from Maven due to Java 7 not supporting TLS 1.2 by default 
[Sample failed CI build](https://ci.appveyor.com/project/googlejavacloud/google-cloud-java-v0gf7/build/3082), note the "Received fatal alert: protocol_version" message:
```
[ERROR] Failed to execute goal on project proto-google-cloud-bigquerydatatransfer-v1:
 Could not resolve dependencies for project com.google.api.grpc:proto-google-cloud-bigquerydatatransfer-v1:jar:0.18.1-SNAPSHOT:
 Failed to collect dependencies at com.google.api.grpc:proto-google-common-protos:jar:1.12.0:
 Failed to read artifact descriptor for com.google.api.grpc:proto-google-common-protos:jar:1.12.0:
 Could not transfer artifact com.google.api.grpc:proto-google-common-protos:pom:1.12.0 from/to central (https://repo.maven.apache.org/maven2):
 Received fatal alert: protocol_version -> [Help 1]
```

This will continue to break any CI builds that use Java 7, e.g. in google-cloud-java.

This can be mitigated by https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3427, which will solve the dependency fetch issue, but still leaves open concerns that we are supported an outdated, potentially insecure version of Java.

Java 7 doesn't have public security updates any more, and it has been deprecated by Oracle.

**Comment by garrettjonesgoogle** [comment]
But what about https://tonyyan.wordpress.com/2015/07/17/enabled-tls-1-2-and-tls-1-1-on-java-7/ ?

**Comment by andreamlin** [comment]
I've spent a couple days trying to apply fixes to enable TLS 1.2 on Java 7 without any luck, but if someone else can do it that would be great!

**Comment by andreamlin** [comment]
Also even if we enable TLS 1.2 on Java 7, users would have to do the same thing.

**Comment by andreamlin** [comment]
We should get sign-off from the DPE, LOL, and Java gRPC teams.

**Comment by andreamlin** [comment]
Apiary libraries have yet to turn down Java 5 support, so this issue won't be resolved for a long time. Closing for now.
