### ISSUE TITLE
Add support to Dataproc workflows

### ISSUE THREAD

**Issue by davidrabinowitz** [GoogleCloudPlatform/google-cloud-java#3436]
Dataproc has a new workflow implementation (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1beta2#google.cloud.dataproc.v1beta2.WorkflowTemplateService). Is it possible to add a Java client for it?

**Comment by andreamlin** [comment]
Hello, 

The Java clients are refreshed weekly, and the newest client may be out by the end of the week.

**Comment by davidrabinowitz** [comment]
Notice that workflows are ay the v1beta2 api, is it generated as well?

**Comment by hzyi-google** [comment]
@danoscarmike Can you verify whether dataproc v1beta2 is ready to be generated?

**Comment by danoscarmike** [comment]
@hzyi-google as discussed offline - I have added this version to the batch whitelist so it may be included in this week's release.

**Comment by hzyi-google** [comment]
v1beta2 is now in master.
