### ISSUE TITLE
FirestoreOptions .setCredentials() seems to be ignored

### ISSUE THREAD

**Issue by andrewparmet** [GoogleCloudPlatform/google-cloud-java#3458]
I recently upgraded Firestore from version 0.51.0-beta to 0.52.0-beta, which allows overriding of various options. My instantiation broke and now throws this exception:
`
com.google.cloud.firestore.FirestoreException: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
`

 My previous service instantiation code looked like this:
```java
GoogleCredentials creds = getServiceAccountCredentialsFromFile();
Firestore firestore = new DefaultFirestoreFactory()
    .create(
        FirestoreOptions.newBuilder()
            .setCredentials(creds)
            .setProjectId(projectId)
            .build());
```

After upgrading this config no longer works; I have to do something like this:
```java
Firestore firestore = new DefaultFirestoreFactory()
    .create(
        FirestoreOptions.newBuilder()
            .setCredentialsProvider(FixedCredentialsProvider.create(creds))
            .setProjectId(projectId)
            .build());
```

I have also tried this:
```java
Firestore firestore = new DefaultFirestoreFactory()
    .create(
        FirestoreOptions.newBuilder()
            .setCredentials(creds)
            .setProjectId(config.getString("firestore.projectId"))
            .setCredentialsProvider(FirestoreOptions.getDefaultCredentialsProviderBuilder().build())
            .build());
```

but this also did not work.

Is it expected that `setCredentials()` is effectively ignored?

**Comment by hzyi-google** [comment]
@chingor13 Jeff, this seems to be related to the changes you made to `ServiceOptions`. Would you mind taking a look?

**Comment by andrewparmet** [comment]
From my investigation this was caused by a change in GrpcFirestoreRpc; I've opened a PR #3460  that does "the minimal thing" to get correct overriding behavior if that's the direction y'all want to go.

**Comment by hzyi-google** [comment]
cc/ @schmidt-sebastian
