### ISSUE TITLE
Setting userProject from NIO FileSystemProvider

### ISSUE THREAD

**Issue by ryan-williams** [GoogleCloudPlatform/google-cloud-java#3475]
I'm happy to see that [requester-pays support was just added](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3221)!

afaict, I can't set the `userProject` in a `CloudStorageFileSystemProvider` that gets instantiated via the Java NIO `FileSystemProvider` machinery, which uses `Class.newInstance()` to invoke the nullary constructor:

```java
import java.net.URI;
import java.nio.file.Paths;
import java.nio.file.Files;
Files.newDirectoryStream(Paths.get(new URI("gs://<bucket>")))
```

throws:
```
com.google.cloud.storage.StorageException: Bucket is requester pays bucket but no user project provided.
  at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
  at com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:347)
  at com.google.cloud.storage.StorageImpl$8.call(StorageImpl.java:299)
  …
```

Is there a way to set the user-project, other than as a ctor param?
- an environment variable would seem easiest
  - afaict there's no standard mechanism for doing that across GCS libraries in various languages
  - perhaps it's still ok to add one here
- a setter would help a bit
  - I'll be mainly using it from [hammerlab/path-utils](https://github.com/hammerlab/path-utils), where I (unfortunately) have code to [reach into the `installedProviders` and modify the providers for a given URI scheme](https://github.com/hammerlab/path-utils/blob/1.5.0/src/main/scala/org/hammerlab/paths/FileSystems.scala#L128-L145)
  - a setter would at least save me from a second reflection hack to reach

**Comment by hzyi-google** [comment]
You could set the `userProject` in `CloudStorageConfiguration` as is in the [tests](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/ab575d0eaf987cbc04f715310b4f23277bd84b9c/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java#L639). Please let us know if that's not what you want.

**Comment by ryan-williams** [comment]
Thanks for that pointer @hzyi-google; that helped, but I still needed #3504.

`CloudStorageFileSystemProvider` [checks its instance var `userProject`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/f7ed77f677db6de8e5d7805170673eed4cd57fac/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L667) to determine whether to set that parameter when calling `storage.get`, but that was never being set from [the config passed to `setDefaultCloudStorageConfiguration`].

**Comment by hzyi-google** [comment]
Thanks for the clarification and contribution! I added a few comments in the pull request, can you take a look please?

**Comment by ryan-williams** [comment]
jfyi: I published a fork of the `google-cloud-nio` module with this merged at [`org.lasersonlab:google-cloud-nio:0.55.2-alpha`](https://oss.sonatype.org/content/repositories/releases/org/lasersonlab/google-cloud-nio/0.55.2-alpha/); I think the PR is awaiting review, but no rush on my end 😄
