### ISSUE TITLE
Could not initialize class com.google.cloud.bigquery.datatransfer.v1.stub.GrpcDataTransferServiceStub

### ISSUE THREAD

**Issue by deepakstriim** [GoogleCloudPlatform/google-cloud-java#3492]
I'm trying to use BQ Data transfer client just to list supported data sources as an example but I'm seeing this error:
"java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.bigquery.datatransfer.v1.stub.GrpcDataTransferServiceStub"
This is my pom:
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquerydatatransfer</artifactId>
            <version>0.55.1-beta</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.1.0</version>
        </dependency>

This is the sample code:
```java
        Credentials credentials = GoogleCredentials
                .fromStream(new FileInputStream(credsFile));
//        googleCloudStorage = StorageOptions.newBuilder().setCredentials(credentials)
//                .setProjectId(projectId).build().getService();

        DataTransferServiceSettings transferServiceSettings = DataTransferServiceSettings.newBuilder()
                .setCredentialsProvider(FixedCredentialsProvider.create(credentials))
                .build();
        // Instantiate a client. If you don't specify credentials when constructing a client, the
        // client library will look for credentials in the environment, such as the
        // GOOGLE_APPLICATION_CREDENTIALS environment variable.
        try (DataTransferServiceClient client = DataTransferServiceClient.create(transferServiceSettings)) {
            // Request the list of available data sources.
            String parent = String.format("projects/%s", projectId);
            ListDataSourcesRequest request =
                    ListDataSourcesRequest.newBuilder()
                            .setParent(parent)
                            .build();
            ListDataSourcesPagedResponse response = client.listDataSources(request);
```
It throws error at the line where dts client is initialized: 
DataTransferServiceClient.create(transferServiceSettings)

**Comment by hzyi-google** [comment]
`DataTransferServiceClient.create(transferServiceSettings)` throws an `IOException`. You would need to either catch or propagate the exception.

**Comment by deepakstriim** [comment]
my main method propogates Exception:
    public static void main(String[] args) throws Exception {

**Comment by hzyi-google** [comment]
Can you share your entire file? I have a repro program the same as your code and my main method throws IOException, but I can't the the issue you have.

**Comment by hzyi-google** [comment]
Close the issue due to inactivity. Feel free to ask for reopen if you are still seeing the issue.
