### ISSUE TITLE
Make Objectify work with google-cloud-datastore

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#350]
[Objectify](https://github.com/objectify/objectify) is a popular data access API for Google Cloud Datastore.

It would be great if we are able to make it work with gcloud-java-datastore.

/cc @stickfigure

**Comment by lnealan** [comment]
Would love to see this!

**Comment by firstthumb** [comment]
Is there any progress on this?

**Comment by mziccard** [comment]
I am sad to say there's no progress on this and no ETA. We would love this to be reality but for the time being it's not a priority.

**Comment by prebenl** [comment]
This, together with a public endpoint for the Search API, would be the final piece to give us flexibility to freely move on and off the App Engine.

**Comment by lesv** [comment]
* Async Datastore
* TaskQueues
* Memcache

**Comment by sai-pullabhotla** [comment]
For those of you who are still looking for a high level API like Objectify, check out [Catatumbo](https://github.com/sai-pullabhotla/catatumbo) - A JPA like framework for the Cloud Datastore. 

https://github.com/sai-pullabhotla/catatumbo 

Disclosure - I'm the author of this open source (Apache 2.0 license) API.

**Comment by sekys** [comment]
+1 please support Objectify

**Comment by meltsufin** [comment]
+1 this is a very high priority for customers of Datastore

**Comment by erugeri** [comment]
+1, really needed to migrate to Flex from MVM.

**Comment by NicoKanitz** [comment]
+1 this is a very high priority for customers of Datastore

**Comment by arouzrokh** [comment]
Team, I'm the Java PM here from GCP. Thank you for all the feedback on Objectify. I am working on this and will update you soon with a more clear status report and roadmap very soon. Thank you for your patience.

**Comment by trunganh39** [comment]
Is there a status on this?

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by wsh** [comment]
This is coming with the next version of Objectify (v6). cc @stickfigure

**Comment by stickfigure** [comment]
It's in alpha right now. For people asking - please try out objectify-6.0a1. Feedback will help accelerate the release process! Thanks.
