### ISSUE TITLE
Can't find the library for the Pubsub class

### ISSUE THREAD

**Issue by deepakstriim** [GoogleCloudPlatform/google-cloud-java#3508]
Hi, I'm trying to replicate the functionality in java similar to the google-dts repo here (which is written in python): https://github.com/mtai/bq-dts-partner-sdk  to be able to listen to pub-sub messages from DTS and send a response. However I can't find the code required in  <artifactId>google-cloud-bigquerydatatransfer</artifactId> library. Searching a little bit I found this library: https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/pubsub/v1/package-summary.html, however couldn't find the pom to download it. Please let me know what am I missing.

**Comment by andreamlin** [comment]
Hi, the latest google-cloud-pubsub pom is hosted at  https://repo.maven.apache.org/maven2/com/google/cloud/google-cloud-pubsub/1.37.0/google-cloud-pubsub-1.37.0.pom, and you can find it in this repo at https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/pom.xml.

**Comment by deepakstriim** [comment]
Thanks @andreamlin 
This is what I gathered from the pom:
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-pubsub</artifactId>
      <version>1.37.2-SNAPSHOT</version>
    </dependency>
but it didn't download any dependency for me. Let me know if it looks incorrect.

**Comment by hzyi-google** [comment]
Can you trying changing the version to 1.37.0?

**Comment by deepakstriim** [comment]
that works. Thanks !
