### ISSUE TITLE
Project build error: Non-resolvable import POM: Could not find artifact com.google.cloud:google-cloud-bom:pom:0.59.0-alpha in central (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by NewProgUser** [GoogleCloudPlatform/google-cloud-java#3601]
I am beginner to JAVA and Maven. I want to use google speech to text and some other google APIs for my project in eclipse IDE and i have been trying to add a dependency in pom.xml file as follows

`<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bom</artifactId>
        <version>0.59.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>`

But, the IDE is flashing error in pom.xml file as "Project build error: Non-resolvable import POM: Could not find artifact com.google.cloud:google-cloud-bom:pom:0.59.0-alpha in central (https://repo.maven.apache.org/maven2)"

I am following the instructions posted on this page : https://github.com/GoogleCloudPlatform/google-cloud-java

I have no idea how to fix this dependency error, any help would be appreciated

**Comment by garrettjonesgoogle** [comment]
We are in the middle of a release, and 0.59.0 isn't actually out yet - try 0.58.0 for now.

**Comment by NewProgUser** [comment]
Thanks Garrett, it worked.
