### ISSUE TITLE
DNS system test is failing

### ISSUE THREAD

**Issue by andreamlin** [GoogleCloudPlatform/google-cloud-java#3618]
See https://circleci.com/gh/GoogleCloudPlatform/google-cloud-java/11146 for sample failure log

**Comment by hzyi-google** [comment]
The failure seems transient. I couldn't repro the issue on my machine and later circleci builds are successful.

**Comment by JustinBeckwith** [comment]
Can we close this and re-open if it happens again?

**Comment by hzyi-google** [comment]
Sure.
