### ISSUE TITLE
Creating ML versions fails while using a correct SCIKIT trained model

### ISSUE THREAD

**Issue by subrataashe** [GoogleCloudPlatform/google-cloud-java#3621]
I created a trained  scikit trained model and it works fine locally. However, when I create a new version in my model, it throws the below error:
In google console:-
Command:
gcloud ml-engine versions create $VERSION_NAME       --model $MODEL_NAME --origin $MODEL_DIR       --runtime-version=1.9 --framework $FRAMEWORK 
      --python-version=3.5

ERROR:
Creating version (this might take a few minutes)......failed.
ERROR: (gcloud.ml-engine.versions.create) Bad model detected with error:  "Failed to load model: Invalid model type detected: builtins.int. Please make sure the model file is an exported sklearn model or pipeline. (Error code: 0)"

**Comment by hzyi-google** [comment]
According to ml-engine [documentation](https://cloud.google.com/sdk/gcloud/reference/ml-engine/versions/create) $MODEL_DIR here should be output by https://www.tensorflow.org/versions/r0.12/api_docs/python/state_ops.html#Saver. 

Also cloud ml-engine is not a java api in this repo so I'm gonna close it here. You could contact [cloudml-samples](https://github.com/GoogleCloudPlatform/cloudml-samples).
