### ISSUE TITLE
Error adding google-cloud-storage to new project

### ISSUE THREAD

**Issue by varumora-everywoah** [GoogleCloudPlatform/google-cloud-java#3627]
Adding 
`implementation 'com.google.cloud:google-cloud-storage:1.42.0'`

to an empty Android Studio project compiles ok, but when pressing play I get the next error:

> More than one file was found with OS independent path 'META-INF/DEPENDENCIES'

I'm I missing anything here?

**Comment by andreamlin** [comment]
@jbolinger Are you familiar with android project setup?

**Comment by jbolinger** [comment]
Have you looked at [Firebase Cloud Storage](https://firebase.google.com/docs/storage/android/start)? If not, you may want to take a look at that first and see if it would be a better fit for your project since it's designed for mobile devices.

This library isn't officially supported for Android, but you can probably make it work if you really need to. Try adding something like this to your app's `build.gradle` to resolve the conflict:

```
android {
    // ...
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
}
```

**Comment by varumora-everywoah** [comment]
@jbolinger Thanks for answering. I just tried your solution but it didn't work

**Comment by jbolinger** [comment]
@varumora-everywoah did you get the same error message or a different one?

I was able to successfully run an app with this dependency, but there was one other file that needed to be excluded:

```
packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/INDEX.LIST'
}
```

**Comment by varumora-everywoah** [comment]
That was it! thank you!

**Comment by jbolinger** [comment]
No problem, let us know if you run into any more issues.

**Comment by GuptaRaghav** [comment]
> No problem, let us know if you run into any more issues.

Hey jbolinger after excluding this file i ran into other issue now it s saying "app\build\intermediates\merged_java_res\debug\out.jar: The process cannot access the file because it is being used by another process."

**Comment by jbolinger** [comment]
That error doesn't sound related. Do a clean and/or invalidate the cache/restart if you're using Intellij or Android Studio. If that doesn't do the trick feel free to open a new issue and include more details about what you're trying to do and any errors.
