### ISSUE TITLE
PubSub subscriber closes connection but remains running when messages are not acked/nacked

### ISSUE THREAD

**Issue by gil-naamani** [GoogleCloudPlatform/google-cloud-java#3646]
I have a suscriber which receives messages and uses the data to call an api. I had an issue with my api which left the connection hanging, and as such the subscription never acked/nacked the message. At this point, after a couple of minutes, the subscriber eventually closes its connection and the backlog begins to climb - when I patched the api to resolve the issue, the subscriber didn't process any old or new messages; however, when I restarted the application and create a new subscriber than the entire backlog is processed. 

I can solve the issue in my api, and add some timeout logic to my receiver to stop this from occurring in the first place - but I am more interested in figuring out how to fail gracefully in an event like this where the subscriber is hanging. I have some logic in my application which periodically polls the subscriber to check that it is in a running state and restarts (stopAsync() + create a new subscription) if not. I can easily recreate this locally by adding a long delay to my API, and when I do so I notice again that the subscriber stops receiving any messages (I also checked the netstats and saw that there were no open connections to pubsub) - yet it still claims to be in a running state. Ideally my program would be able to identify that its not running and create a new subscriber (perhaps with some backoff), such that if I remove the delay in the api it would be automatically resolved without requiring me to manually restart the application.

Is there some way to detect that the subscriber is hanging? Is that the intended behavior for a subscriber when acks/nacks are delayed?

**Comment by hzyi-google** [comment]
Michael, can you take a look @pongad ?

**Comment by pongad** [comment]
@gil-naamani Can you provide any more detail about how long this problem take to happen? The `Subscriber` will keep extending the message deadline for one hour. At that point it will assume that the message is lost and give up.

There was a bug where the `Subscriber` didn't release resource properly when giving up, preventing it from pulling more messages. #3633 fixes this.

If the problem occur on the horizon of an hour or more, you might just need to wait a couple days for us to cut a new release.

**Comment by pongad** [comment]
Version `1.43.0` is released. It should contain the bug fix. I'll close this for the time being, but please let us know if you still run into the problem.
