### ISSUE TITLE
Can I use this library to access firestore as a firebase auth user? 

### ISSUE THREAD

**Issue by nbransby** [GoogleCloudPlatform/google-cloud-java#3682]
It appears google-auth-library-java supports 3LO so what is the blocker that prevents google-cloud-java being used in user environments (desktop, not mobile)?

**Comment by schmidt-sebastian** [comment]
We currently don't support Firebase Auth or Rules integration with the Server SDKs, so you can only access them through Service Accounts. If you need third-party access in a Server Environment, you can use the Mobile Node SDK (https://www.npmjs.com/package/firebase).

**Comment by nbransby** [comment]
Actually what I need is a desktop java Firebase client and this is the closest thing you have.

As the only alternative i have is to write my own client against the API, I was hoping instead that you could give me some guidance on the changes required to make this sdk to work with user auth

**Comment by schmidt-sebastian** [comment]
There is quite a bit of backend work required to make this happen. While it is on our roadmap, it will likely take us a while. For what it's worth, we just open sourced our Java-based Android client and if you want to experiment, it might be less work to make the Android client work on desktop. See https://github.com/firebase/firebase-android-sdk

**Comment by nbransby** [comment]
Yeah not according to the maintainers there, please see https://github.com/firebase/firebase-android-sdk/issues/14#issuecomment-420719963

What is the backend work required? Surely if the client libraries are using the same APIs the backend must already support it? @samtstern appears to be under a similar impression: https://github.com/firebase/firebase-admin-java/issues/206#issuecomment-421175871

**Comment by nbransby** [comment]
@schmidt-sebastian I’m trying to get a picture of the work required as I’m going to have to figure this out somehow

**Comment by schmidt-sebastian** [comment]
Hi! Sorry for being slow here. We don't have good guidance at this point. I fear that you will hit some roadblocks that make this hard or impossible to implement. I'll see if we can get a rough scope of what this work entails, and will let you know if this change is possible as a client-side only update.

**Comment by nbransby** [comment]
Thanks, I eagerly await your response

**Comment by schmidt-sebastian** [comment]
We believe that the client side work for this will actually be pretty minimal, and that most of the work required here has to be done by one of our backend engineers. I will see what resources we have to prioritize this, but if you are blocked by this, then I would consider finding a workaround for the time being. Sorry about that!

**Comment by nbransby** [comment]
Out of interest what is the backend work required? Is the android client
using a different API to this library then?

**Comment by schmidt-sebastian** [comment]
The Android client is using third-party auth. What we eventually want to implement for the Server SDKs is service account auth with the option to "impersonate" a third party. So you would authenticate with the Service Account's private key and a token from a Firebase user. This will be similar to what we offer for the Realtime Database: https://firebase.google.com/docs/database/admin/start#authenticate-with-limited-privileges

By the way, someone over on the .Net repo just described how they are using the .Net client with a Firebase Auth user. This might be helpful for you: https://github.com/googleapis/google-cloud-dotnet/issues/2536#issuecomment-424991308

**Comment by nbransby** [comment]
Ah I see, well I don't think that will fit my use case anyway as I'm
developing a desktop client and presumedly that would still require
including the private key in the client.

Thanks for the link to the .net client thread

**Comment by samtstern** [comment]
Thanks @schmidt-sebastian 

@nbransby I really apologize for what has turned out to be a wild goose chase!  What Sebastian showed on the C# client was exactly what I had in mind from the start by sending you here: obtain a Firebase Auth *user* credential from the REST API and then figure out how to add it to all the requests to the backend.  As mentioned in that thread, you now are in the business of refreshing the token yourself every hour and I don't quite know how to make that play nice with real-time listeners.

**Comment by nbransby** [comment]
@samtstern thanks, how do you make that play nice with real-time listeners on android?

**Comment by samtstern** [comment]
@nbransby I wasn't involved with the development of the Android client lib so no idea, but that sounds like the kind of thing you could find out by digging into the source!  Although I imagine on Android the Firebase Auth SDK does most of the work for us.

**Comment by nbransby** [comment]
@samtstern thanks I think I will start with attempting to port the android sdk in its entirety

**Comment by gabber235** [comment]
Is this already out or is this still being worked on? If so, what is the current road map?

@nbransby have you ported it or not? If so, is there a way that others might use it?

**Comment by schmidt-sebastian** [comment]
We haven't made progress on this front yet.
