### ISSUE TITLE
PubSub creating lots of thread

### ISSUE THREAD

**Issue by kakadiyahardik** [GoogleCloudPlatform/google-cloud-java#3720]
I am using PubSub with java

### Actual behabiour
When i start application (it contains subscriber code) It creates a lot of thread, so after start within few times server will closed

### My code for subscriber
ProjectSubscriptionName subName = ProjectSubscriptionName.of(CommonUtils.GCLOUD_PROJECT_ID,
SUBSCRIPTION_ID);

		MessageReceiver receiver = new MessageReceiver() {
			@Override
			public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
				String messageString = message.getData().toStringUtf8();
				System.out.println("message received : " + message.getMessageId());
				consumer.ack();

			}
		};

		Subscriber subscriber = null;
		try {
			ExecutorProvider executorProvider = InstantiatingExecutorProvider.newBuilder().setExecutorThreadCount(1)
					.build();
			subscriber = Subscriber.newBuilder(subName, receiver)
					.setCredentialsProvider(FixedCredentialsProvider.create(credentials))
					.setExecutorProvider(executorProvider).build();

			subscriber.startAsync();
		} catch (Exception e) {
			errorLog.push(e);
		}

**Comment by pongad** [comment]
@kakadiyahardik How many threads are you seeing? We create a shared "system executor" to help manage timing-related operations, since we have seen problems where user code is too busy working on messages that "house keeping" operations cannot be scheduled. Does it help if you add `.setSystemExecutorProvider(executorProvider)`?

**Comment by kakadiyahardik** [comment]
Thank you for your reply, and sorry because there is a mistake in my code so it was created the lots of thread.

**Comment by pongad** [comment]
Looks like the issue is resolved :)
