### ISSUE TITLE
Update service address for pubsub

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#381]
The service address for pubsub is currently set to pubsub-experimental.googleapis.com, but needs to be updated to pubsub.googleapis.com when pubsub has gRPC support in GA.

**Comment by omarkj** [comment]
Has Pubsub gRPC moved to GA?

We are getting errors now from the `pubsub-experimental.googleapis.com` which informs us to enable the API - but, according to the API Manager the experimental API does not exist.

This seemed to have started today, as this [Stackoverflow issue](http://stackoverflow.com/questions/38860888/gloud-java-permission-denied-google-cloud-pub-sub-api-experimental) (from someone other than me).

Thanks!
Ómar

**Comment by mziccard** [comment]
@omarkj we are aware of this. I just prepared a PR that switches our default endpoint from `pubsub-experimental.googleapis.com` to `pubsub.googleapis.com`. This should be fixed in the next release (that should be out by end of the week).

**Comment by mziccard** [comment]
This was fixed with #1149
