### ISSUE TITLE
Update the release process to support releases of individual modules

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#406]
Having the option to have a separate version (and release) for each module would be very nice.
This would allow a particular service client to get updated independently (though we should probably
also update the gcloud-java "all" module).

/cc @mziccard

**Comment by mziccard** [comment]
I did a bit of research on this and it seems to be doable. Basically this relies un bumping only the version of selected projects keeping in mind:
- When any module's version increases the aggregator module's version has to increase
- When any module's version increases all dependent modules versions must increase

We should be able to release only the modules that changed by using maven's `-pl` option:
> Comma-delimited list of specified reactor projects to build instead of all projects. A project can be specified by [groupId]:artifactId or by its relative path.

My concerns are:
1. Which version should the aggregator have? Probably the lower version amongst sub-modules, or a totally different version?
2. Tagging: with which version should we tag the repo? The most reasonable approach is tagging with the aggregator's version but this causes my third concern
3. Tracking an artifact back to code in the repo becomes harder. A user using gcloud-java-storage v1.0.0 will not find any v1.0.0 tag in the repo. He would probably have to check the release notes and see that gcloud-java-storage v1.0.0 has been shipped with gcloud-java v0.42.0 and look for the v0.42.0 tag.
4. "Intuitivity": I imagine that a user familiar with gcloud-java-datastore v0.X.0 might try to add gcloud-java-storage v0.X.0 to his project which might not be the latest version and not even exist

Side notes: AWS java SDK is a multimodule project where all modules share the same version.

**Comment by garrettjonesgoogle** [comment]
We are currently using three "version tracks" - GA clients, Beta clients, and Alpha clients. We updated our release scripts a while back to support this. We don't currently have any plans for completely independent versions. 

There isn't anything additional in this issue that we intend to support, so I'm going to close it out.
