### ISSUE TITLE
Add to LocalGcdHelper an option to dump the generated indexes

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#409]
We should explore to option to configure `LocalGcdHelper` to run with a `datastore-indexes.xml` that is configured with `autoGenerate="true"` and then provide an option to save the generated indexes in a desired place.

For more info see [this](https://cloud.google.com/datastore/docs/tools/indexconfig).

**Comment by garrettjonesgoogle** [comment]
This seems more appropriate for the Google Cloud SDK. Closing out.
