### ISSUE TITLE
Consider using AutoValue for immutable value types.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#418]
We should evaluate if using `AutoValue` is a good fit for us.

This will help to eliminate boilerplate code (though IDE's today typically help in the initial part and some
even in the maintenance part).

We should consider IDE support/behavior when the referred auto generated class is missing, 
flexibility in copying set values (e.g. passed collection to immutable collection), replacing `null` with api-client `Data.nullOf`,..).

Also, it introduce the dependency of "@Nullable" annotation and I think once users see that in the code they expect it in other places (so, we should go and change the code to use it consistently when applicable).

**Comment by garrettjonesgoogle** [comment]
This is something we can consider opportunistically - we already use it a bit in gax-java. I don't think it's worth retaining an issue for it, though.
