### ISSUE TITLE
Support parent in Project

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#419]
When public documentation is ready for ResourceId and a Project's parent, we should add support for parents.

**Comment by ajkannan** [comment]
To address when this issue is resolved: parent isn't currently returned in a list response, whether or not the field is specified explicitly.

Parent is returned in a `get` request.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
