### ISSUE TITLE
Support UserCredentials

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#431]
The `google-auth-library-java` library has a type of credentials called `UserCredentials` which we should wrap in `gcloud-java-core`.  However, this requires [this issue](https://github.com/google/google-auth-library-java/issues/52) to be fixed.

**Comment by ajkannan** [comment]
Supporting UserCredentials also depends on giving the users a nice way to generate User Credentials JSON files (tracked by [this issue](https://github.com/google/google-auth-library-java/issues/54)).

**Comment by ajkannan** [comment]
Once this issue is resolved, we should add documentation, especially for services like Resource Manager that need User Credentials.

**Comment by ajkannan** [comment]
Removed the "blocked" label.  While waiting for the issue (linked in the original post) would make the user's experience nicer, we don't want to prolong blockage of ITs for resource manager.

**Comment by mziccard** [comment]
Update on this: the `google-auth-library-java` issue has been fixed and the latest version contains the fix.

**Comment by lesv** [comment]
It appears this has been fixed

**Comment by garrettjonesgoogle** [comment]
Well, the work in google-auth-library-java is done, but I don't think the work on ITs for resource manager has been done.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
