### ISSUE TITLE
Figure out if using URLFetch if running on AppEngine is necessary

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#449]
If we can always use NetHttpTransport, we can remove the logic in `DefaultHttpTransportFactory.create` (in [`ServiceOptions`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-core/src/main/java/com/google/gcloud/ServiceOptions.java)) to check if we're running on App Engine.

**Comment by aozarov** [comment]
I think it should be safe to remove it.

**Comment by mziccard** [comment]
I run a quick storage example and requests seem to work fine in AppEngine with `NetHttpTransport`. However from [here](https://google.github.io/google-http-java-client/releases/1.21.0/javadoc/index.html?overview-summary.html) I read:

> `com.google.api.client.javanet.NetHttpTransport` is discouraged due to a bug in the App Engine SDK itself in how it parses HTTP headers in the response

Is this a known problem in AE? Or has it been already fixed?

**Comment by aozarov** [comment]
> Is this a known problem in AE? Or has it been already fixed?

Yes, we saw that before (and we should have mentioned that in the issue).
This was actually the reason we didn't do anything about it yet.
I am %99.9 confident that this should be fine however I could not trace the source of this comment or anyone that knows more about it. We did test it and it seems to be working fine.

**Comment by garrettjonesgoogle** [comment]
This has become irrelevant with recent developments. We are not going to ensure google-cloud-java is compatible with Java 7 on App Engine; Java 8 on App Engine doesn't have the same restrictions with network fetching. Java 8 support on App Engine is quite close, and is being tracked in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1918 . Closing out this issue.
