### ISSUE TITLE
Dataset.delete, Table.delete and Job.cancel ignore the if-non-match header

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#468]
It seems to me that the following apis
- [Dataset.delete](https://cloud.google.com/bigquery/docs/reference/v2/datasets/delete)
- [Table.delete](https://cloud.google.com/bigquery/docs/reference/v2/tables/delete)
- [Job.cancel](https://cloud.google.com/bigquery/docs/reference/v2/datasets/delete)

Ignore the HTTP `if-none-match` header (they fail as expected if `if-match` header does not match).

**Comment by garrettjonesgoogle** [comment]
Closing because https://github.com/GoogleCloudPlatform/google-cloud-java/issues/469 is being tracked on the backlog instead of in an open issue.
