### ISSUE TITLE
Add support for etag checks

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#469]
BigQuery supports setting the `if-match` and `if-none-match` headers (see [here](https://cloud.google.com/bigquery/docs/data)) to check for etag match or mismatch when requesting some resource.

We should add support for `etagMatch` and `etagNotMatch` options. This support can be provided once the following issues are closed:
- [ ] #340 
- [ ] #466
- [ ] #468

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion .

Special note: even if the listed issues are "closed", that doesn't mean that they got implemented, so they would need to be individually checked.
