### ISSUE TITLE
writeLogEntries: what happens if no logName is provided?

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#475]

**Comment by lesv** [comment]
@jabubake Can you try this and tell us the results.

**Comment by jabubake** [comment]
Logs are not written out when no filename is specified, it gets blocked but no exception is thrown.
We require a `Preconditions.checkNotNull` and  a `<default-log-name>`

**Comment by michaelbausor** [comment]
@jabubake I am not finding the same issue - what can I do to reproduce?

I am finding that if the log name is set to null in `LoggingHandler` then the default value of "java.log" is used. There is an error case if the user sets the log name to an empty string, which is guaranteed to fail.

And if you use the generated `LoggingClient` directly, we get an exception back from the service, which is what we expect.

**Comment by jabubake** [comment]
@michaelbausor  : retested, looks like this is fine. I am seeing the exception, I think my test was incorrect earlier.
With the generated LoggingClient, I am seeing : Exception in thread "main" com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT
Code used to test : https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/logging/cloud-client/src/main/java/com/example/logging/QuickstartSample.java
