### ISSUE TITLE
Consider writing names in {@code} block

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#476]
A way to do this is to reformat everything in form `foobar` to {@code foobar}

**Comment by mziccard** [comment]
This also applies to `pubsub`

**Comment by garrettjonesgoogle** [comment]
Provisionally marking as blocking GA (docs quality).

**Comment by garrettjonesgoogle** [comment]
Related issue that applies to all languages: https://github.com/googleapis/toolkit/issues/331

**Comment by pongad** [comment]
@garrettjonesgoogle Do you object to closing this as dup?

**Comment by garrettjonesgoogle** [comment]
Hmm I think it might make sense to keep this open, because it is likely for someone else to file a new issue against google-cloud-java not knowing there is a cross-language issue filed in toolkit.

**Comment by garrettjonesgoogle** [comment]
I have changed my mind. I am going to close this out and let it be tracked on the all-language issue ( oogleapis/toolkit#331 ).
