### ISSUE TITLE
Multiple instances of "all X goes through this method"

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-java#481]
This is a protodoc issue.
See writeLogEntries for an example.

**Comment by garrettjonesgoogle** [comment]
Still appears to be an issue - reference link: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/LoggingServiceV2Client.java#L292

**Comment by garrettjonesgoogle** [comment]
Provisionally marking 'blocking GA'.

**Comment by lesv** [comment]
ProtoDoc needs an update to fix.
