### ISSUE TITLE
Remove check for "Unnamed" name in ProjectInfo.fromPb()

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#484]
Currently, when using `ListProjects`, projects without a name are given the name "Unnamed" when returned by `ListProjects`.  As a result, we explicitly set the name to null if a project's name is "Unnamed" in `ProjectInfo.fromPb` When this is fixed, we can stop this behavior.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
