### ISSUE TITLE
Missing configuration for dryRun jobs causes NPE

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#525]
A query job created with `dryRun = true` has no `configuration` field. The following is the response I get from [Jobs: insert](https://cloud.google.com/bigquery/docs/reference/v2/jobs/insert).

``` json
{
 "kind": "bigquery#job",
 "etag": "\"Bop49sEVg6UBKwr7tLdL8AavHaw/LRPbO11E3VlTAE5UxM2F_Mfu01M\"",
 "jobReference": {
  "projectId": "gcloud-devel"
 },
 "status": {
  "state": "DONE"
 },
 "statistics": {
  "creationTime": "1452067884640",
  "totalBytesProcessed": "26",
  "query": {
   "totalBytesProcessed": "26",
   "totalBytesBilled": "0",
   "cacheHit": false
  }
 }
}
```

While if I create the same job with `dryRun = false` the configuration is present instead:

``` json
{
 "kind": "bigquery#job",
 "etag": "\"Bop49sEVg6UBKwr7tLdL8AavHaw/OI0lGTx2GlKc0VoAAYS-fIXHWok\"",
 "id": "gcloud-devel:job_nixqXTMu-mS9U26Ixnxr9KZxCyc",
 "selfLink": "https://www.googleapis.com/bigquery/v2/projects/gcloud-devel/jobs/job_nixqXTMu-mS9U26Ixnxr9KZxCyc",
 "jobReference": {
  "projectId": "gcloud-devel",
  "jobId": "job_nixqXTMu-mS9U26Ixnxr9KZxCyc"
 },
 "configuration": {
  "query": {
   "query": "select StringField from gcloud_test_dataset_temp_6c127c49_9574_4e17_ad2b_8e85071997aa.testing_table",
   "destinationTable": {
    "projectId": "gcloud-devel",
    "datasetId": "_6bb2fc157573f6bd0fed98f3b039c1e71f26d7d1",
    "tableId": "anon5f489e91b602aaed3dc62a46d51ba3c070e5d03f"
   },
   "createDisposition": "CREATE_IF_NEEDED",
   "writeDisposition": "WRITE_TRUNCATE"
  },
  "dryRun": false
 },
 "status": {
  "state": "RUNNING"
 },
 "statistics": {
  "creationTime": "1452070358348",
  "startTime": "1452070358585"
 },
 "user_email": "..."
}
```

While this does not affect the functionality itself I was wondering whether configuration should be returned also for dry-run jobs for consistency? /cc @jcondit @jtigani

For what concerns `gcloud-java` the absence of a configuration causes a NPE to be thrown at [JobInfo:297](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-bigquery/src/main/java/com/google/gcloud/bigquery/JobInfo.java#L297).

**Comment by jcondit** [comment]
Yeah, looks like a bug on our end. Thanks for the report!

**Comment by polleyg** [comment]
Is there any ETA on a roll-out for this fix? I've just hit this bug.

http://stackoverflow.com/questions/41604995/bigquery-client-library-throwing-npe-when-setting-dryrun-to-true

**Comment by jcondit** [comment]
I've pinged our internal bug to see if we can get the API behavior straightened out.

In the meantime, perhaps we can fix the NPE in the client library independently? @tswast

**Comment by jcondit** [comment]
We've submitted a fix for this issue on the backend. It'll take a week or two to roll out.

**Comment by tswast** [comment]
Marking as blocking GA, just to make sure we double check that this is working and close this out. Sorry I didn't have time to make a quick fix.

**Comment by garrettjonesgoogle** [comment]
@jcondit where is the backend fix now?

**Comment by jcondit** [comment]
Deployed to prod.

**Comment by garrettjonesgoogle** [comment]
@jcondit Thanks!

Next we just need to verify that the client library code works ok in the formerly-problematic scenario.

**Comment by garrettjonesgoogle** [comment]
I have verified it by writing a new integration test in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2328 .

Closing this issue now.
