### ISSUE TITLE
Provide builder for ProjectListOption.filter()

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#531]
Then the user doesn't have to enter large strings that combine multiple filters themselves.

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
