### ISSUE TITLE
Provide a way to create AuthCredentials given an AccessToken

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#608]
`GoogleCredentials` supports creating an instance using a temporary [`AccessToken`](https://github.com/google/google-auth-library-java/blob/281d485e679545ed06f46e6090fc5d47f4a140e8/oauth2_http/java/com/google/auth/oauth2/AccessToken.java).

It would be nice to support it.

We could do that by getting the token string and expiration time and adding ourselves as `AuthCredentials.CredentialsChangedListener` to capture token updates.

**Comment by garrettjonesgoogle** [comment]
Some analysis would need to be done to see if this is still relevant.

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
