### ISSUE TITLE
Include getProjectNumber and getProjectId in Service

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/google-cloud-java#612]
They should be available in ServiceOptions.

**Comment by mziccard** [comment]
We already have a `projectId()` getter in `ServiceOptions`. `projectNumber` is an information we don't have and never used, is there any reason to have a getter for project number?

**Comment by mziccard** [comment]
This remained open for a while. If you have more details or you feel strongly about it, please feel free to reopen.
