### ISSUE TITLE
Add Page implementation for testing

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/google-cloud-java#613]
Add Page a simple `PageImpl` under https://github.com/GoogleCloudPlatform/gcloud-java/tree/master/gcloud-java-core/src/main/java/com/google/gcloud/testing that gets one or more list of values.

**Comment by garrettjonesgoogle** [comment]
It's not clear what the need is. This seems like something that can just be done when it's actually needed. Closing this out.
