### ISSUE TITLE
Support signed android api keys

### ISSUE THREAD

**Issue by jerjou** [GoogleCloudPlatform/google-cloud-java#660]
If you create an android api key in the cloud console, and restrict its usage using your package and sha1 cert, then all calls to google apis using that key need to be signed. It'd be great if gcloud-java could support signing the requests in android, so that it can be used with restricted android api keys.

**Comment by mziccard** [comment]
Dear @jerjou, thanks for your interest. Could you please provide us with some more details?
> then all calls to google apis using that key need to be signed

What do you mean that all calls to google apis need to be "signed"?

How are you doing this now? Could you share with us a piece of code so that we (or maybe only me as the others might have already understood :) can better understand? 

Thank you:)

**Comment by jerjou** [comment]
Sorry - I assumed that api requests were signed based on the errors I was getting, but after some more investigation, that appears to not be the case.

What I mean is - if you create an android api key in the cloud console and provide it with your package and sha1 cert, then api calls to cloud apis using that key - from an android device - return 403s, saying that the `client app <empty>` is blocked. I suspect this is because the api call isn't providing critical auth information (such as what the client app is - thus `<empty>`) in the request; and I suspect that the [android-specific client lib](https://developers.google.com/android/guides/api-client) does provide this information.

Does that make sense?

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
