### ISSUE TITLE
Figure out Compute possible error codes

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#662]
I couldn't manage to find a page with all errors codes that the Compute service can return. Possible error codes should be known, in particular we need to identify retryable ones.

**Comment by mziccard** [comment]
The creation of an error-codes page is being tracked internally (b/28086880)

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
