### ISSUE TITLE
Add support for Storage transfer

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#667]
see: https://cloud.google.com/storage/transfer/

**Comment by lesv** [comment]
Why wasn't this required for GA?

**Comment by garrettjonesgoogle** [comment]
This is a distinct service from Storage.

Someone filed an issue much more recently for this: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2222

New client requests are being tracked internally now. I'm going to close this out.
