### ISSUE TITLE
Support TransactionOptions in v1beta3

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#677]
See discussion in #637 for more context.

This is blocked on transaction options being supported in a subsequent release of v1beta3.

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
