### ISSUE TITLE
Understand possible DiskType.validDiskSize formats

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#683]
[DiskType.validDiskSize](https://cloud.google.com/compute/docs/reference/latest/diskTypes#validDiskSize) is documented as:

> An optional textual description of the valid disk size, such as "10GB-10TB".

We should understand the format this field can have so that we can split it into two numbers (e.g. `minSize` and `maxSize`).

**Comment by danoscarmike** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog. This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
