### ISSUE TITLE
Provide an in-memory or local-disk emulator of the storage APIs for testing

### ISSUE THREAD

**Issue by dimo414** [GoogleCloudPlatform/google-cloud-java#684]
Easy to describe, hard to do :) Presently the only way I can verify my `gcloud-java` code is to run it against a real GCS bucket, which costs money and requires being authenticated.

**Comment by aozarov** [comment]
@dimo414 I completely agree!

It is fairly simple to write something to support basic functionality (get/set/listing without options) but not so if we care about being a 100% (or close to it) compatible. 

It is on our road-map and in fact as part of the efforts to add nio.Files facade to GCS in gcloud-java-contrib (currently at the [gcs-nio](https://github.com/GoogleCloudPlatform/gcloud-java/tree/gcs-nio) branch) we also plan to provide a **basic** local gcs implementation. Any contribution to make it better (and closer to the real service) are welcome!

A different and complete local implementation that will be included in the cloud SDK will come at some point (but probably not any time soon).

/cc @mziccard @jart @jean-philippe-martin

**Comment by dimo414** [comment]
Thanks @aozarov, an nio.Files facade will be excellent.

**Comment by jean-philippe-martin** [comment]
I believe this issue is related to #1993, which was just closed. We now expose a "LocalStorageHelper" that offers an in-memory emulator of (the core parts of) the storage API.

**Comment by garrettjonesgoogle** [comment]
This is done, so closing out the issue.
