### ISSUE TITLE
Get baseUrl for Compute's identities

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#693]
For resource identities we use the following base url in `ResourceId`:

``` java
 private static final String BASE_URL = "https://www.googleapis.com/compute/v1/projects/";
```

As noticed by @aozarov this could be derived from service  (e.g. [com.google.api.services.compute.Compute]() has a `getBaseUrl` method).

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
