### ISSUE TITLE
Compute's DiskType.id field is never set

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#695]
[DiskType.id](https://cloud.google.com/compute/docs/reference/latest/diskTypes#id) is documented but never returned by the service. See for instance the result of a GET:

``` json
{
 "kind": "compute#diskType",
 "creationTimestamp": "2014-10-17T16:09:45.266-07:00",
 "name": "local-ssd",
 "description": "Local SSD",
 "validDiskSize": "375GB-375GB",
 "zone": "https://content.googleapis.com/compute/v1/projects/gcloud-devel/zones/us-central1-a",
 "selfLink": "https://content.googleapis.com/compute/v1/projects/gcloud-devel/zones/us-central1-a/diskTypes/local-ssd",
 "defaultDiskSizeGb": "375"
}
```

**Comment by mziccard** [comment]
This is being tracked internally (b/28041512)

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
