### ISSUE TITLE
Enhance docs with possible values of Compute operation's .error.errors[].code

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#751]
We should figure out possible values that can be assumed by [error.errors[].code](https://cloud.google.com/compute/docs/reference/latest/globalOperations#error.errors.code).
The field is only documented as:

> The error type identifier for this error.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
