### ISSUE TITLE
LocalLoggingHelper uses 8080 as default port.

### ISSUE THREAD

**Issue by shinfan** [GoogleCloudPlatform/google-cloud-java#769]
The test could fail if the port is occupied. LocalLoggingHelper should be able to search for available ports.

**Comment by aozarov** [comment]
@shinfan also can you provide a reference to the related gax issue (I assume that the delegate test helper in gax would need to be modified as well?).

**Comment by shinfan** [comment]
Currently this localLoggingHelper does not use the test helper in gax. The test helper in gax has already implemented the port searching functionality.

**Comment by mziccard** [comment]
This was fixed with #1377
