### ISSUE TITLE
Make Operation.targetId of ResourceId type

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#792]
Compute's operations have a `targetId` field that right now is of type `String`.
As soon as we mapped all possible resource URLs to identity classes we should change `targetId` to `ResourceId` type. Operation class should become:

``` java
public class Operation<T extends ResourceId> {
  // ...
  T targetId();
  // ...
}
```

This way all methods in `Compute` will return the corresponding operation, eg:

``` java
Operation<SnapshotId> createSnapshot(SnapshotInfo snapshot, OperationOption... options);
```

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
