### ISSUE TITLE
NIO: Close channels on FS close

### ISSUE THREAD

**Issue by jart** [GoogleCloudPlatform/google-cloud-java#809]
CloudStorageFileSystem#close() should synchronously close all active channels associated with the file system instance, per NIO documentation.

**Comment by garrettjonesgoogle** [comment]
@jean-philippe-martin this issue is more than a year old, can you comment on the need to address it?

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.

**Comment by jean-philippe-martin** [comment]
close() is still a no-op, in violation of the NIO documentation. It hasn't been an issue but would be nice to have. I would argue we should keep this issue open.
