### ISSUE TITLE
NIO: Further research error code translation

### ISSUE THREAD

**Issue by jart** [GoogleCloudPlatform/google-cloud-java#810]
See `CloudStorageFileSystemProvider#asIOException` method.

**Comment by garrettjonesgoogle** [comment]
@jean-philippe-martin this issue is more than a year old, can you comment on the need to address it?

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.
