### ISSUE TITLE
NIO: Support string file attributes

### ISSUE THREAD

**Issue by jart** [GoogleCloudPlatform/google-cloud-java#811]
Implement these method:

``` java
  public Map<String, Object> readAttributes(Path path, String attributes, LinkOption... options) {
    // Java 7 NIO defines at least eleven string attributes we'd want to support
    // (eg. BasicFileAttributeView and PosixFileAttributeView), so rather than a partial
    // implementation we rely on the other overload for now.
    throw new UnsupportedOperationException();
  }

  /**
   * Throws {@link UnsupportedOperationException} because Cloud Storage objects are immutable.
   */
  @Override
  public void setAttribute(Path path, String attribute, Object value, LinkOption... options) {
    throw new CloudStorageObjectImmutableException();
  }
```

This hasn't been a priority so far, because a type-safe version of this API exists that offers the exact same functionality. We consider that API better. Bet we need to support this too.

**Comment by garrettjonesgoogle** [comment]
cc @jean-philippe-martin

**Comment by garrettjonesgoogle** [comment]
@jean-philippe-martin this issue is more than a year old, can you comment on the need to address it?

**Comment by danoscarmike** [comment]
This issue may no longer be relevant due to its age.  If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this it with enough information to help us reproduce it.

**Comment by jean-philippe-martin** [comment]
ReadAttributes is still unimplemented to this day. It's not critical, but certainly would be nice to have.
