### ISSUE TITLE
Ability to inline JSON into GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by jart** [GoogleCloudPlatform/google-cloud-java#828]
Some CI systems don't really give you the option to have files. Since we're not sure yet if it would be a good idea to allow the user to configure the default instance of `CloudStorageFileSystemProvider` with a `Storage` object that has custom authentication, it would be really nice if the environment variable provided greater flexibility.

I propose that, if the `GOOGLE_APPLICATION_CREDENTIALS` environment has a value that:

1. Starts with `^\s*\{`
2. Is valid JSON

Then it will be treated as though it's the contents of the key file, rather than a filename.

@aozarov @jean-philippe-martin

**Comment by jean-philippe-martin** [comment]
It sounds nice. One potential caveat is that we're not the [only people](https://developers.google.com/identity/protocols/application-default-credentials) accepting this variable. Users might be confused and start using our method with other languages or in other libraries and get errors.
Instead, we could leave the [createApplicationDefaults()](https://github.com/GoogleCloudPlatform/gcloud-java/blob/353d2db0962c6a3bd3823cf24c83d0b128fd41d5/gcloud-java-core/src/main/java/com/google/gcloud/AuthCredentials.java#L322) call (or moral equivalent) unchanged and instead allow our users to find their way to the [createForJson(InputStream jsonCredentialStream)](https://github.com/GoogleCloudPlatform/gcloud-java/blob/353d2db0962c6a3bd3823cf24c83d0b128fd41d5/gcloud-java-core/src/main/java/com/google/gcloud/AuthCredentials.java#L363) method.

**Comment by jart** [comment]
In that case, how do we escalate this bug so it applies to all projects that use `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by mziccard** [comment]
I agree this is a much needed feature. However `GOOGLE_APPLICATION_CREDENTIALS` are used and [documented](https://developers.google.com/identity/protocols/application-default-credentials#howtheywork) also elsewhere. I fear that changing this convention in the "sole" `gcloud-*` world might be confusing. \cc @jgeewax @aozarov

**Comment by mziccard** [comment]
This has been open for a while but as per my previous comment this is not something we can change.

**Comment by mgoddard-pivotal** [comment]
I am looking into using the Cloud Natural Language API for some applications which will be run in Cloud Foundry.  Google has built a service broker, so I can "bind" my app to an "instance" of the GCP NLP API and, from that, I can get the JSON string which could be contained within a file which I see referenced by GOOGLE_APPLICATION_CREDENTIALS.  The example I'm looking to use is here:

  https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/language

Based on this example, if I can set GOOGLE_APPLICATION_CREDENTIALS to the path to this JSON file, all is well.  If, however, all I have is the string containing the JSON, it's not apparent how I proceed as there is no such example within the repo I mention here.  Could anyone here offer an alternative?

Thanks!

  Mike
