### ISSUE TITLE
Fix null pointer test in CloudStorageFileSystemProviderTest

### ISSUE THREAD

**Issue by jart** [GoogleCloudPlatform/google-cloud-java#830]
A null pointer is triggered from `testNullness` and therefore is disabled.

**Comment by mziccard** [comment]
@jart is this still an issue?

**Comment by jart** [comment]
Correct this is still an issue: https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-contrib/gcloud-java-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java#L632

**Comment by lesv** [comment]
Updated Link https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java

**Comment by lesv** [comment]
This relates to Storage, so I've marked it so.  I don't think this blocks GA, but we should investigate and fix.
