### ISSUE TITLE
Write integration tests for Datastore

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#840]
Datastore already has a beefed-up local emulator, so these integration tests don't need to be very detailed.  The main point is that they can interact with the actual service (i.e. the request endpoint is correct, errors are being translated properly, etc)

**Comment by garrettjonesgoogle** [comment]
An integration test as since been created: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-datastore/src/test/java/com/google/cloud/datastore/it/ITDatastoreTest.java . Closing out this issue now.
