### ISSUE TITLE
Include LocalStorageService in the testing documentation.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/google-cloud-java#859]
Currently LocalStorageService is being implemented in the gcs-nio branch.
Once that branch is merged and `LocalStorageService` is ready for use we should make sure
it has its own `package-info.java` and update the [TESTING](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/TESTING.md) instructions to include it.

/cc @jart @jean-philippe-martin

**Comment by garrettjonesgoogle** [comment]
It doesn't appear that this ever reached master - closing out the issue.

**Comment by jean-philippe-martin** [comment]
LocalStorage was renamed to [LocalStorageHelper](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/LocalStorageHelper.java) but it's still very much around and super useful for tests. It is still the case that it would be nice to expose it to a broader audience once we feel it's ready, as we've had informal inquiries from others who also would like a fake storage option to test their own storage-using code.

**Comment by garrettjonesgoogle** [comment]
Ahh ok, thanks for letting me know its new location :-)

**Comment by lesv** [comment]
We have all the others, we should have this as well.

**Comment by jean-philippe-martin** [comment]
Excellent, thank you for doing this!

May I also kindly ask someone to review my LocalStorageService bugfix that's been waiting for review for about a week? It's #1935.
