### ISSUE TITLE
Create base class for local test helpers

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/google-cloud-java#879]
There is some functionality, such as finding free ports to bind and listen to, that are useful across local test helpers.

**Comment by mziccard** [comment]
To add to this: `LocalStorageHelper`(currently named `LocalGcsHelper`) that is being developed in `gcs-nio` uses an in-memory emulator and will have no method for finding free ports.

**Comment by mziccard** [comment]
This was fixed in #1377
