### ISSUE TITLE
Consider moving Compute's ServiceAccount to core

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#958]
Compute instances contain a list of service accounts, each of each has an `email` and `scope` fields. We should consider moving this information to `gcloud-java-core` as soon as it might be needed elsewhere.

**Comment by garrettjonesgoogle** [comment]
This has been added to our feature backlog: https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog . This issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.
