### ISSUE TITLE
Separate API classes into separate modules from implementations

### ISSUE THREAD

**Issue by jboynes** [GoogleCloudPlatform/google-cloud-java#96]
When using injection, application code would generally not need to interact with the implementation classes. For example, it would receive a `Datastore` or `Storage` instance directly and never need to interact with any of the factory or `ServiceOptions` classes e.g.

``` java
class MyApp {
  @Resource Datastore dataset;
  @Inject Bucket data;
  void doSomething() {
    // just use dataset and data fields ...
  }
}
```

By separating the API classes that it would use into a separate jar, the user can avoid having a dependency on the implementation itself and on any of the libraries that the implementation happens to use.

**Comment by garrettjonesgoogle** [comment]
Since this issue hasn't been touched in a year and a half and the current design is stable, I'm going to closed out the issue.
