### ISSUE TITLE
PubSub Emulator: subscriptions to deleted topics preserve old topic

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#988]
As documented in [projects.topics/delete](https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/delete) when a topic is deleted existing subscriptions to this topic are not deleted, but their `topic` field is set to `_deleted-topic_`.

When testing agains the Pub/Sub emulator subscriptions to a deleted topic have their `topic` field still set to the deleted topic's name.

**Comment by mziccard** [comment]
See also https://github.com/GoogleCloudPlatform/gcloud-common/issues/129

**Comment by garrettjonesgoogle** [comment]
It looks like the topic field name is fixed - any appropriate changes in `google-cloud-java` can now be made.

**Comment by garrettjonesgoogle** [comment]
@pongad can you triage?

**Comment by pongad** [comment]
Pubsub no longer uses emulator for testing. I think we're safe to close this.
