### ISSUE TITLE
PubSub Emulator: Subscription.ackDeadlineSeconds is defaulted to 60

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/google-cloud-java#989]
According to the [docs](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L286), if `ackDeadlineSeconds` is not provided it should be defaulted to 10. In the emulator it is set to 60 instead.

See also GoogleCloudPlatform/gcloud-common#129

**Comment by garrettjonesgoogle** [comment]
This is already being tracked at the source so I'm going to close out this issue.
